{"metadata":{"title":"activity","symbolKind":"property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation(py)activity","navigatorTitle":[{"text":"activity","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"activity","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"Activity"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","kind":"typeIdentifier","text":"Activity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity"},{"text":"?","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversation\/activity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversation\/activity"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A most recent "},{"type":"codeVoice","code":"Activity"},{"type":"text","text":" for the "},{"type":"codeVoice","code":"Conversation"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversation\/activity"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"Conversation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Activity"}],"type":"topic","title":"Activity","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/activity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Activity"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversation/activity":{"navigatorTitle":[{"text":"activity","kind":"identifier"}],"abstract":[{"text":"A most recent ","type":"text"},{"code":"Activity","type":"codeVoice"},{"type":"text","text":" for the "},{"code":"Conversation","type":"codeVoice"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversation\/activity","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Activity","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity"},{"kind":"text","text":"?"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversation\/activity","title":"activity"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"activity","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"activity","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"ZDKActivity","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"activity"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"ZDKConversation","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments","value":[{"kind":"identifier","text":"ZDKConversation"}],"op":"replace"},{"value":"ZDKActivity","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/fragments","value":[{"kind":"identifier","text":"ZDKActivity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversation~1activity\/title","value":"activity"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversation~1activity\/fragments","op":"replace","value":[{"text":"activity","kind":"identifier"}]}]}]}