{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"text":"FieldType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"type"}],"symbolKind":"property","title":"type","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKEmailFormField(py)type","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}]},"abstract":[{"text":"The field type.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkemailformfield\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkemailformfield\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKEmailFormField\/type"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","text":"FieldType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/EmailFormField"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKEmailFormField/type":{"url":"\/documentation\/zendesksdkconversationkit\/zdkemailformfield\/type","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKEmailFormField\/type","kind":"symbol","title":"type","abstract":[{"text":"The field type.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FieldType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/EmailFormField":{"url":"\/documentation\/zendesksdkconversationkit\/emailformfield","kind":"symbol","role":"symbol","abstract":[{"text":"Form Field used for email input","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EmailFormField","kind":"identifier"}],"navigatorTitle":[{"text":"EmailFormField","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/EmailFormField","title":"EmailFormField","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FieldType":{"role":"symbol","title":"FieldType","navigatorTitle":[{"kind":"identifier","text":"FieldType"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","url":"\/documentation\/zendesksdkconversationkit\/fieldtype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FieldType"}],"type":"topic","abstract":[{"text":"Form field type. ","type":"text"},{"code":"text","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"email"},{"type":"text","text":", "},{"code":"select","type":"codeVoice"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"type"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","text":"ZDKFieldType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"type","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKEmailFormField~1type\/title"},{"op":"replace","value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKEmailFormField~1type\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1EmailFormField\/title","value":"ZDKEmailFormField","op":"replace"},{"value":[{"text":"ZDKEmailFormField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1EmailFormField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/title","value":"ZDKFieldType"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKFieldType"}]}]}]}