{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdklocationrequestaction\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdklocationrequestaction\/type"]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLocationRequestAction\/type","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","text":"ActionType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType","text":"ActionType","kind":"typeIdentifier"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKLocationRequestAction(py)type","role":"symbol","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LocationRequestAction"]]},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ActionType"},{"type":"text","text":" of this action."}],"kind":"symbol","sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType":{"role":"symbol","title":"ActionType","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ActionType"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","url":"\/documentation\/zendesksdkconversationkit\/actiontype"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/LocationRequestAction":{"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/locationrequestaction","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LocationRequestAction","kind":"symbol","navigatorTitle":[{"text":"LocationRequestAction","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationRequestAction","kind":"identifier"}],"title":"LocationRequestAction","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKLocationRequestAction/type":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLocationRequestAction\/type","kind":"symbol","title":"type","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType","text":"ActionType"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ActionType"},{"type":"text","text":" of this action."}],"url":"\/documentation\/zendesksdkconversationkit\/zdklocationrequestaction\/type","role":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKActionType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/title","op":"replace","value":"ZDKActionType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/fragments","value":[{"text":"ZDKActionType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LocationRequestAction\/title","value":"ZDKLocationRequestAction"},{"op":"replace","value":[{"text":"ZDKLocationRequestAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LocationRequestAction\/fragments"},{"value":"type","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLocationRequestAction~1type\/title"},{"value":[{"text":"type","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLocationRequestAction~1type\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}