{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkcarouselmessagecontent\/messageitems"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkcarouselmessagecontent\/messageitems"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKCarouselMessageContent\/messageItems"},"abstract":[{"text":"The action items of the ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent"]]},"metadata":{"title":"messageItems","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"messageItems","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKCarouselMessageContent(py)messageItems","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageItems","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessageActionItem","text":"MessageActionItem"},{"kind":"text","text":"]"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageItems","kind":"identifier"},{"kind":"text","text":": ["},{"text":"MessageActionItem","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessageActionItem","kind":"typeIdentifier"},{"kind":"text","text":"]"}]}],"kind":"declarations"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKCarouselMessageContent/messageItems":{"abstract":[{"type":"text","text":"The action items of the "},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"messageItems","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkcarouselmessagecontent\/messageitems","kind":"symbol","type":"topic","title":"messageItems","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageActionItem","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessageActionItem"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKCarouselMessageContent\/messageItems","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/CarouselMessageContent":{"url":"\/documentation\/zendesksdkconversationkit\/carouselmessagecontent","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CarouselMessageContent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent","title":"CarouselMessageContent","abstract":[],"navigatorTitle":[{"text":"CarouselMessageContent","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionItem":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageActionItem","kind":"identifier"}],"title":"MessageActionItem","type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageActionItem","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionitem","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","abstract":[{"text":"An item in a list type message, such as list or carousel.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"messageItems"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"messageItems","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<ZDKMessageActionItem *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"messageItems"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKCarouselMessageContent~1messageItems\/title","op":"replace","value":"messageItems"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKCarouselMessageContent~1messageItems\/fragments","value":[{"kind":"identifier","text":"messageItems"}]},{"value":"ZDKCarouselMessageContent","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1CarouselMessageContent\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1CarouselMessageContent\/fragments","op":"replace","value":[{"text":"ZDKCarouselMessageContent","kind":"identifier"}]},{"value":"ZDKMessageActionItem","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/fragments","value":[{"kind":"identifier","text":"ZDKMessageActionItem"}]}]}]}