{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType\/image"},"abstract":[{"text":"An image in a ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"case","navigatorTitle":[{"text":"ZDKMessageTypeImage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"}],"role":"symbol","title":"MessageType.image","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType@ZDKMessageTypeImage","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/messagetype\/image"]},{"paths":["\/documentation\/zendesksdkconversationkit\/messagetype\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType/image":{"abstract":[{"type":"text","text":"An image in a "},{"type":"codeVoice","code":"Conversation"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType\/image","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ZDKMessageTypeImage","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messagetype\/image","title":"MessageType.image","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType":{"abstract":[{"text":"Represents the different ","type":"text"},{"type":"codeVoice","code":"Message"},{"text":" types in a ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageType"}],"title":"MessageType","navigatorTitle":[{"kind":"identifier","text":"MessageType"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","url":"\/documentation\/zendesksdkconversationkit\/messagetype"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKMessageTypeImage"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKMessageTypeImage","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"ZDKMessageTypeImage","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType~1image\/title","value":"ZDKMessageTypeImage","op":"replace"},{"value":[{"text":"ZDKMessageTypeImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType~1image\/fragments"},{"value":"ZDKMessageType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/title"},{"value":[{"text":"ZDKMessageType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}