{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/defaultconversationkitbuilder\/build(config:featureflagmanager:callbackqueue:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/defaultconversationkitbuilder\/build(config:featureflagmanager:callbackqueue:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig","text":"Config"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureFlagManager"},{"kind":"text","text":": "},{"text":"FeatureFlagManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager"},{"text":", ","kind":"text"},{"text":"callbackQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationKitObjC","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit"}],"title":"build(config:featureFlagManager:callbackQueue:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"buildWithConfig:featureFlagManager:callbackQueue:"}],"platforms":[],"externalID":"c:@CM@ZendeskSDKConversationKit@objc(cs)ZDKDefaultConversationKitBuilder(im)buildWithConfig:featureFlagManager:callbackQueue:","modules":[{"name":"ZendeskSDKConversationKit"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"build","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Config","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig"},{"kind":"text","text":", "},{"text":"featureFlagManager","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FeatureFlagManager","preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callbackQueue"},{"kind":"text","text":": "},{"text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier"},{"text":" = .main) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","text":"ConversationKitObjC","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder\/build(config:featureFlagManager:callbackQueue:)"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/DefaultConversationKitBuilder/build(config:featureFlagManager:callbackQueue:)":{"title":"build(config:featureFlagManager:callbackQueue:)","navigatorTitle":[{"text":"buildWithConfig:featureFlagManager:callbackQueue:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig","text":"Config"},{"text":", ","kind":"text"},{"text":"featureFlagManager","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager","text":"FeatureFlagManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callbackQueue"},{"kind":"text","text":": "},{"text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit","text":"ConversationKitObjC","kind":"typeIdentifier"}],"url":"\/documentation\/zendesksdkconversationkit\/defaultconversationkitbuilder\/build(config:featureflagmanager:callbackqueue:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder\/build(config:featureFlagManager:callbackQueue:)","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/DefaultConversationKitBuilder":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DefaultConversationKitBuilder","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/defaultconversationkitbuilder","navigatorTitle":[{"text":"DefaultConversationKitBuilder","kind":"identifier"}],"title":"DefaultConversationKitBuilder","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","abstract":[{"code":"ConversationKitObjC","type":"codeVoice"},{"type":"text","text":" needs to be configured  with a "},{"code":"Config","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"that includes the necessary "},{"type":"codeVoice","code":"integrationId"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"integrationId","type":"codeVoice"},{"type":"text","text":" can be retrieved from the Native Messaging dashboard."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationKitObjC","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","navigatorTitle":[{"text":"ConversationKitObjC","kind":"identifier"}],"title":"ConversationKitObjC","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Config"}],"url":"\/documentation\/zendesksdkconversationkit\/config","navigatorTitle":[{"text":"Config","kind":"identifier"}],"title":"Config","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"buildWithConfig:featureFlagManager:callbackQueue:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"buildWithConfig:featureFlagManager:callbackQueue:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Qo@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit","text":"id<ZDKConversationKit>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"buildWithConfig:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","text":"ZDKConfig","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureFlagManager:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKFeatureFlagManager","kind":"typeIdentifier","text":"ZDKFeatureFlagManager"},{"text":" *) ","kind":"text"},{"text":"featureFlagManager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"callbackQueue:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject<OS_dispatch_queue>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"callbackQueue"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder~1build(config:featureFlagManager:callbackQueue:)\/title","op":"replace","value":"buildWithConfig:featureFlagManager:callbackQueue:"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder~1build(config:featureFlagManager:callbackQueue:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"buildWithConfig:featureFlagManager:callbackQueue:","kind":"identifier"}],"op":"replace"},{"value":"ZDKDefaultConversationKitBuilder","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder\/title"},{"value":[{"text":"ZDKDefaultConversationKitBuilder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder\/fragments"},{"value":"ZDKConversationKit","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title"},{"value":[{"kind":"identifier","text":"ZDKConversationKit"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/title","op":"replace","value":"ZDKConfig"},{"value":[{"text":"ZDKConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/fragments"}]}]}