{"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheFirstTenMostRecentConversationsInMemory","kind":"identifier"},{"text":"([","kind":"text"},{"text":"Conversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)cacheFirstTenMostRecentConversationsInMemory:","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"cacheFirstTenMostRecentConversationsInMemory(_:)","roleHeading":"Instance Method","required":true,"navigatorTitle":[{"text":"cacheFirstTenMostRecentConversationsInMemory:","kind":"identifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/cachefirsttenmostrecentconversationsinmemory(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/cachefirsttenmostrecentconversationsinmemory(_:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/cacheFirstTenMostRecentConversationsInMemory(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cacheFirstTenMostRecentConversationsInMemory","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"conversations","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","kind":"typeIdentifier","text":"Conversation"},{"kind":"text","text":"])"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A list of "},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":" objects to add to memory."}],"type":"paragraph"}],"name":"conversations"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"abstract":[{"type":"text","text":"Caches the most recent ten conversations in memory for quick access."}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Conversation","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation","type":"topic","title":"Conversation","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/cacheFirstTenMostRecentConversationsInMemory(_:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/cacheFirstTenMostRecentConversationsInMemory(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheFirstTenMostRecentConversationsInMemory","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/cachefirsttenmostrecentconversationsinmemory(_:)","kind":"symbol","title":"cacheFirstTenMostRecentConversationsInMemory(_:)","abstract":[{"type":"text","text":"Caches the most recent ten conversations in memory for quick access."}],"type":"topic","navigatorTitle":[{"text":"cacheFirstTenMostRecentConversationsInMemory:","kind":"identifier"}],"required":true},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"abstract":[],"navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","role":"symbol","title":"ConversationKitShared","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitShared"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"cacheFirstTenMostRecentConversationsInMemory:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cacheFirstTenMostRecentConversationsInMemory:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"cacheFirstTenMostRecentConversationsInMemory:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<ZDKConversation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversations"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","value":"ZDKConversation"},{"value":[{"text":"ZDKConversation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1cacheFirstTenMostRecentConversationsInMemory(_:)\/title","value":"cacheFirstTenMostRecentConversationsInMemory:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cacheFirstTenMostRecentConversationsInMemory:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1cacheFirstTenMostRecentConversationsInMemory(_:)\/fragments"},{"value":"ConversationKitShared","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","value":[{"text":"ConversationKitShared","kind":"identifier"}],"op":"replace"}]}]}