{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationTags()-5791u","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)clearConversationTags","roleHeading":"Instance Method","title":"clearConversationTags()","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearConversationTags"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"clearConversationTags","kind":"identifier"}],"required":true},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationtags()-5791u"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationtags()-5791u"]}],"kind":"symbol","defaultImplementationsSections":[{"title":"ConversationKit Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/clearConversationTags()-4u2i3"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Clears all tags from storage."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearConversationTags","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/clearConversationTags()-4u2i3":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/clearconversationtags()-4u2i3","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/clearConversationTags()-4u2i3","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearConversationTags","kind":"identifier"},{"text":"()","kind":"text"}],"title":"clearConversationTags()"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"abstract":[],"navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","role":"symbol","title":"ConversationKitShared","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitShared"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearConversationTags()-5791u":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"clearConversationTags","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"clearConversationTags","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationTags()-5791u","defaultImplementations":1,"role":"symbol","title":"clearConversationTags()","abstract":[{"type":"text","text":"Clears all tags from storage."}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationtags()-5791u","kind":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clearConversationTags"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearConversationTags"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearConversationTags"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","value":[{"text":"ConversationKitShared","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearConversationTags()-5791u\/title","value":"clearConversationTags"},{"value":[{"kind":"text","text":"- "},{"text":"clearConversationTags","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearConversationTags()-5791u\/fragments","op":"replace"}]}]}