{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"featureFlagManager","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FeatureFlagManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/featureflagmanager"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/featureflagmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/featureFlagManager","interfaceLanguage":"swift"},"metadata":{"title":"featureFlagManager","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ZendeskSDKConversationKit"}],"required":true,"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(py)featureFlagManager","navigatorTitle":[{"kind":"identifier","text":"featureFlagManager"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"featureFlagManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager","text":"FeatureFlagManager"}],"role":"symbol"},"abstract":[{"text":"Current ","type":"text"},{"code":"FeatureFlagManager","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"abstract":[],"navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","role":"symbol","title":"ConversationKitShared","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitShared"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/featureFlagManager":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/featureflagmanager","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"featureFlagManager"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/featureFlagManager","required":true,"abstract":[{"type":"text","text":"Current "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"featureFlagManager","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FeatureFlagManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager"}],"title":"featureFlagManager"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"featureFlagManager","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"featureFlagManager","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ZDKFeatureFlagManager","preciseIdentifier":"c:objc(cs)ZDKFeatureFlagManager"},{"kind":"text","text":" * "},{"kind":"identifier","text":"featureFlagManager"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","op":"replace","value":"ConversationKitShared"},{"value":[{"text":"ConversationKitShared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1featureFlagManager\/title","op":"replace","value":"featureFlagManager"},{"value":[{"text":"featureFlagManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1featureFlagManager\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}