{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationFields(_:)-4sbmy"},"sections":[],"defaultImplementationsSections":[{"title":"ConversationKit Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/setConversationFields(_:)-9c9as"]}],"abstract":[{"type":"text","text":"Provide a dictionary of custom fields."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationfields(_:)-4sbmy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationfields(_:)-4sbmy"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setConversationFields","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"fields","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"fields","content":[{"inlineContent":[{"text":"The dictionary of custom fields to be provided.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Strings, numbers and booleans are the only supported value types that can be passed."}],"type":"paragraph"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setConversationFields:"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)setConversationFields:","required":true,"title":"setConversationFields(_:)","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setConversationFields","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":"])","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/setConversationFields(_:)-4sbmy":{"required":true,"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationFields(_:)-4sbmy","role":"symbol","title":"setConversationFields(_:)","type":"topic","abstract":[{"type":"text","text":"Provide a dictionary of custom fields."}],"navigatorTitle":[{"kind":"identifier","text":"setConversationFields:"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationfields(_:)-4sbmy","defaultImplementations":1,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setConversationFields","kind":"identifier"},{"kind":"text","text":"(["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":"])","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"abstract":[],"navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","role":"symbol","title":"ConversationKitShared","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitShared"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/setConversationFields(_:)-9c9as":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/setConversationFields(_:)-9c9as","role":"symbol","type":"topic","title":"setConversationFields(_:)","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/setconversationfields(_:)-9c9as","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConversationFields","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"setConversationFields:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConversationFields:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setConversationFields:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSObject *>"},{"kind":"text","text":" *) "},{"text":"fields","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationFields(_:)-4sbmy\/title","value":"setConversationFields:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationFields(_:)-4sbmy\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setConversationFields:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared","op":"replace"},{"value":[{"kind":"identifier","text":"ConversationKitShared"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}