{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/clearConversationTags()"],["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationTags()-5791u"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearConversationTags","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"s:25ZendeskSDKConversationKit012ConversationC0PAAE05clearD4TagsyyF","title":"clearConversationTags()","role":"symbol","roleHeading":"Instance Method","extendedModule":"ZendeskSDKConversationKit","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearConversationTags","kind":"identifier"},{"kind":"text","text":"()"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationtags()-4u2i3"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationTags()-4u2i3"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"title":"ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"code":"SettingsParameters","type":"codeVoice"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"ConversationKitSettings"},{"text":", ","type":"text"},{"code":"Config","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"text":" ","type":"text"},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"code":"AccessLevel","type":"codeVoice"},{"type":"text","text":" and will check for a persisted user."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationKit"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationKit","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","url":"\/documentation\/zendesksdkconversationkit\/conversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearConversationTags()-5791u":{"title":"clearConversationTags()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearConversationTags"},{"text":"()","kind":"text"}],"defaultImplementations":1,"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationtags()-5791u","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationTags()-5791u","required":true,"navigatorTitle":[{"text":"clearConversationTags","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Clears all tags from storage.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearConversationTags()-4u2i3":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationtags()-4u2i3","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationTags()-4u2i3","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearConversationTags"},{"text":"()","kind":"text"}],"title":"clearConversationTags()","abstract":[],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/clearConversationTags()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearConversationTags","kind":"identifier"},{"text":"()","kind":"text"}],"defaultImplementations":1,"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/clearconversationtags()","required":true,"abstract":[{"type":"text","text":"Clear all tags from storage."}],"kind":"symbol","type":"topic","title":"clearConversationTags()","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/clearConversationTags()"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationKitShared","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","navigatorTitle":[{"kind":"identifier","text":"ConversationKitShared"}],"abstract":[],"title":"ConversationKitShared"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"clearConversationTags","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearConversationTags()-5791u\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearConversationTags"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearConversationTags()-5791u\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","value":[{"kind":"identifier","text":"ConversationKitShared"}]}]}]}