{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setConversationTags"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tags"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)-6c0gj","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/setConversationTags(_:)"],["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)-4nfxc"]]},"sections":[],"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"method","roleHeading":"Instance Method","extendedModule":"ZendeskSDKConversationKit","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConversationTags"},{"text":"([","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"role":"symbol","title":"setConversationTags(_:)","externalID":"s:25ZendeskSDKConversationKit012ConversationC0PAAE03setD4TagsyySaySSGF"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)-6c0gj"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/setConversationTags(_:)-4nfxc":{"title":"setConversationTags(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setConversationTags"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"defaultImplementations":1,"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)-4nfxc","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)-4nfxc","required":true,"navigatorTitle":[{"kind":"identifier","text":"setConversationTags:"}],"role":"symbol","abstract":[{"text":"Provide an array of custom fields.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/setConversationTags(_:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/setConversationTags(_:)","defaultImplementations":1,"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/setconversationtags(_:)","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setConversationTags","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}],"title":"setConversationTags(_:)","abstract":[{"text":"Provide an array of tags.","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/setConversationTags(_:)-6c0gj":{"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)-6c0gj","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConversationTags"},{"text":"([","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"kind":"symbol","title":"setConversationTags(_:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)-6c0gj"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"title":"ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"code":"SettingsParameters","type":"codeVoice"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"ConversationKitSettings"},{"text":", ","type":"text"},{"code":"Config","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"text":" ","type":"text"},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"code":"AccessLevel","type":"codeVoice"},{"type":"text","text":" and will check for a persisted user."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationKit"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationKit","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","url":"\/documentation\/zendesksdkconversationkit\/conversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationKitShared","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","navigatorTitle":[{"kind":"identifier","text":"ConversationKitShared"}],"abstract":[],"title":"ConversationKitShared"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"setConversationTags:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationTags(_:)-4nfxc\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConversationTags:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationTags(_:)-4nfxc\/fragments"},{"op":"replace","value":"ConversationKitShared","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ConversationKitShared"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments"}]}]}