{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH","doc:\/\/com.zendesk.ConversationKit\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ActivityType"}],"symbolKind":"enum","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityType"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType","title":"ActivityType","roleHeading":"Enumeration"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/activitytype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/activitytype"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKActivityType) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivityType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRead","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/typingStart","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/typingStop"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/stringValue"],"title":"Instance Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/Equatable-Implementations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/RawRepresentable-Implementations"]}],"references":{"doc://com.zendesk.ConversationKit/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/zendesksdkconversationkit\/activitytype\/rawrepresentable-implementations"},"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/conversationRead":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRead","kind":"symbol","title":"ActivityType.conversationRead","type":"topic","abstract":[{"type":"text","text":"A conversationRead activity"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationRead"}],"url":"\/documentation\/zendesksdkconversationkit\/activitytype\/conversationread","navigatorTitle":[{"text":"ZDKActivityTypeConversationRead","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/typingStop":{"abstract":[{"type":"text","text":"A stop typing activity"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/typingStop","url":"\/documentation\/zendesksdkconversationkit\/activitytype\/typingstop","kind":"symbol","type":"topic","title":"ActivityType.typingStop","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"typingStop"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKActivityTypeTypingStop"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","url":"\/documentation\/zendesksdkconversationkit\/activitytype","kind":"symbol","type":"topic","title":"ActivityType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ActivityType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ActivityType","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/init(rawValue:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/init(rawValue:)","kind":"symbol","title":"init(rawValue:)","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/activitytype\/init(rawvalue:)"},"doc://com.zendesk.ConversationKit/Se":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","title":"Swift.Decodable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/Equatable-Implementations":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/zendesksdkconversationkit\/activitytype\/equatable-implementations"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/typingStart":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/typingStart","kind":"symbol","title":"ActivityType.typingStart","type":"topic","abstract":[{"type":"text","text":"A start typing activity"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"typingStart","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/activitytype\/typingstart","navigatorTitle":[{"kind":"identifier","text":"ZDKActivityTypeTypingStart"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/stringValue":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/stringValue","kind":"symbol","title":"stringValue","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"stringValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/zendesksdkconversationkit\/activitytype\/stringvalue"},"doc://com.zendesk.ConversationKit/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SY","title":"Swift.RawRepresentable"},"doc://com.zendesk.ConversationKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ZDKActivityType"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKActivityType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKActivityType"}],"op":"replace"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRead","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/typingStart","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/typingStop"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKActivityType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1conversationRead\/title","value":"ZDKActivityTypeConversationRead","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1conversationRead\/fragments","value":[{"kind":"identifier","text":"ZDKActivityTypeConversationRead"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1typingStop\/title","value":"ZDKActivityTypeTypingStop"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1typingStop\/fragments","op":"replace","value":[{"text":"ZDKActivityTypeTypingStop","kind":"identifier"}]},{"value":"ZDKActivityType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title"},{"op":"replace","value":[{"text":"ZDKActivityType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1typingStart\/title","value":"ZDKActivityTypeTypingStart","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1typingStart\/fragments","value":[{"text":"ZDKActivityTypeTypingStart","kind":"identifier"}]}]}]}