{"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationlist"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationlist"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationList","title":"ConversationList","symbolKind":"class","navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationList","kind":"identifier"}]},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList\/init(conversations:hasMore:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationList\/conversations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationList\/hasMore"]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKConversationList) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationList"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationList/hasMore":{"type":"topic","kind":"symbol","title":"hasMore","navigatorTitle":[{"text":"hasMore","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationList\/hasMore","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationlist\/hasmore","abstract":[{"type":"text","text":"Whether there are more conversations available than the ones returned"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasMore","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationList":{"type":"topic","kind":"symbol","title":"ConversationList","navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList","url":"\/documentation\/zendesksdkconversationkit\/conversationlist","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationList","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/SQ":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationList/conversations":{"type":"topic","kind":"symbol","title":"conversations","navigatorTitle":[{"text":"conversations","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationList\/conversations","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationlist\/conversations","abstract":[{"text":"A list of ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversations","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation"},{"text":"]","kind":"text"}]},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.ConversationKit/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE"},"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationList/init(conversations:hasMore:)":{"type":"topic","kind":"symbol","title":"init(conversations:hasMore:)","navigatorTitle":[{"text":"initWithConversations:hasMore:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList\/init(conversations:hasMore:)","url":"\/documentation\/zendesksdkconversationkit\/conversationlist\/init(conversations:hasmore:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversations","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","kind":"typeIdentifier","text":"Conversation"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"hasMore"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationList/init(from:)":{"type":"topic","kind":"symbol","title":"init(from:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList\/init(from:)","url":"\/documentation\/zendesksdkconversationkit\/conversationlist\/init(from:)","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://com.zendesk.ConversationKit/Se":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","title":"Swift.Decodable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"ZDKConversationList","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKConversationList","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ZDKConversationList"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationList\/conversations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationList\/hasMore"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList\/init(conversations:hasMore:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationList","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"hasMore","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationList~1hasMore\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationList~1hasMore\/fragments","op":"replace","value":[{"text":"hasMore","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/title","value":"ZDKConversationList"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKConversationList"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/fragments"},{"value":"conversations","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationList~1conversations\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationList~1conversations\/fragments","value":[{"kind":"identifier","text":"conversations"}],"op":"replace"},{"value":"initWithConversations:hasMore:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList~1init(conversations:hasMore:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList~1init(conversations:hasMore:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConversations:hasMore:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}