{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField"},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field","doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKTextFormField) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextFormField","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/init(from:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/init(id:text:name:label:placeholder:minSize:maxSize:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/id","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/label","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/maxSize","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/maxSizeObjc","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/minSize","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/minSizeObjc","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/name","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/placeholder","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/text","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/type","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/value"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/isEqual(_:)"]}],"abstract":[{"type":"text","text":"Form Field that takes in generic user input"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/textformfield"]},{"paths":["\/documentation\/zendesksdkconversationkit\/textformfield"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"metadata":{"title":"TextFormField","symbolKind":"class","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Class","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKTextFormField","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextFormField"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextFormField","kind":"identifier"}]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/minSize":{"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"title":"minSize","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/minSize","kind":"symbol","abstract":[{"type":"text","text":"The minimum allowed length for the response for a field of type text."}],"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/minsize"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField":{"type":"topic","abstract":[{"type":"text","text":"Form Field that takes in generic user input"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextFormField","kind":"identifier"}],"navigatorTitle":[{"text":"TextFormField","kind":"identifier"}],"title":"TextFormField","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/textformfield","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/placeholder":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/placeholder","kind":"symbol","abstract":[{"text":"Placeholder text for the field.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"placeholder"}],"title":"placeholder","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/textformfield\/placeholder"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/init(from:)":{"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/init(from:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(from:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/init(from:)","kind":"symbol","abstract":[],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/minSizeObjc":{"abstract":[{"type":"text","text":"The minimum allowed length for the response for a field of type text."}],"type":"topic","title":"minSizeObjc","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/minSizeObjc","url":"\/documentation\/zendesksdkconversationkit\/textformfield\/minsizeobjc","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minSizeObjc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"minSizeObjc","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/SH":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/type":{"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/type","navigatorTitle":[{"kind":"identifier","text":"type"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The field type."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"text":"FieldType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType"}],"type":"topic","title":"type"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/hash":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/hash","kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/hash"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Field":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Field","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Field"}],"role":"symbol","type":"topic","title":"Field","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field","url":"\/documentation\/zendesksdkconversationkit\/field","abstract":[{"type":"text","text":"Objective-C representation of the fields in a "},{"code":"Form","type":"codeVoice"},{"type":"text","text":" message"}]},"doc://com.zendesk.ConversationKit/SQ":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/value":{"abstract":[{"type":"text","text":"The value of the field. Same as "},{"type":"codeVoice","code":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/value","url":"\/documentation\/zendesksdkconversationkit\/textformfield\/value","kind":"symbol","title":"value","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/label":{"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/label","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"label"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"label","navigatorTitle":[{"kind":"identifier","text":"label"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/label","kind":"symbol","abstract":[{"type":"text","text":"The label of the field. Must be unique per "},{"type":"codeVoice","code":"form"},{"type":"text","text":" or "},{"type":"codeVoice","code":"formResponse"},{"text":".","type":"text"}],"type":"topic"},"doc://com.zendesk.ConversationKit/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/id":{"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/id","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"id","navigatorTitle":[{"kind":"identifier","text":"id"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/id","kind":"symbol","abstract":[{"text":"The id of the ","type":"text"},{"type":"codeVoice","code":"Field"},{"type":"text","text":"."}],"type":"topic"},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP"},"doc://com.zendesk.ConversationKit/Se":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","title":"Swift.Decodable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/text":{"type":"topic","abstract":[{"type":"text","text":"The text value of the "},{"type":"codeVoice","code":"Field"},{"type":"text","text":"."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"text"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"text"}],"title":"text","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/textformfield\/text","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/text"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/maxSize":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxSize"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"maxSize","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/maxSize","kind":"symbol","abstract":[{"type":"text","text":"The maximum allowed length for the response for a field of type text."}],"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/maxsize"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/name":{"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"name","navigatorTitle":[{"text":"name","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/name","kind":"symbol","abstract":[{"type":"text","text":"The name of the field. Must be unique per "},{"type":"codeVoice","code":"form"},{"text":" or ","type":"text"},{"code":"formResponse","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/name"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/maxSizeObjc":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxSizeObjc"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"maxSizeObjc","navigatorTitle":[{"text":"maxSizeObjc","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/maxSizeObjc","kind":"symbol","abstract":[{"text":"The maximum allowed length for the response for a field of type text.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/maxsizeobjc"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/description":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/description","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/description","title":"description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/isEqual(_:)":{"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/isequal(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/isEqual(_:)","kind":"symbol","abstract":[{"text":"Returns a Boolean value that indicates whether the receiver and a given object are equal.","type":"text"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/init(id:text:name:label:placeholder:minSize:maxSize:)":{"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"placeholder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"minSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"maxSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}],"title":"init(id:text:name:label:placeholder:minSize:maxSize:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/init(id:text:name:label:placeholder:minSize:maxSize:)","kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/textformfield\/init(id:text:name:label:placeholder:minsize:maxsize:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKTextFormField"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKTextFormField","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKTextFormField","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/id","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/label","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/maxSizeObjc","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/minSizeObjc","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/name","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/placeholder","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/text","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/type","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/value"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/isEqual(_:)"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field"],"type":"conformsTo","kind":"relationships"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKTextFormField","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKTextFormField","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField\/fragments","value":[{"kind":"identifier","text":"ZDKTextFormField"}]},{"value":"placeholder","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1placeholder\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1placeholder\/fragments","value":[{"kind":"identifier","text":"placeholder"}]},{"op":"replace","value":"minSizeObjc","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1minSizeObjc\/title"},{"value":[{"text":"minSizeObjc","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1minSizeObjc\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1type\/title","value":"type","op":"replace"},{"value":[{"kind":"identifier","text":"type"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1type\/fragments"},{"value":"hash","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1hash\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKField","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field\/fragments","value":[{"text":"ZDKField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1value\/title","value":"value"},{"value":[{"text":"value","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1value\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1label\/title","value":"label","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1label\/fragments","op":"replace","value":[{"text":"label","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1id\/title","value":"id","op":"replace"},{"value":[{"text":"id","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1id\/fragments","op":"replace"},{"value":"text","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1text\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1text\/fragments","value":[{"kind":"identifier","text":"text"}]},{"op":"replace","value":"name","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1name\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1name\/fragments","value":[{"kind":"identifier","text":"name"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1maxSizeObjc\/title","value":"maxSizeObjc"},{"op":"replace","value":[{"kind":"identifier","text":"maxSizeObjc"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1maxSizeObjc\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1isEqual(_:)\/title","value":"isEqual:"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1isEqual(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}