{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/connectionStatusChanged","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationAdded","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationRemoved","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationUpdated","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/loginResult","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/logoutResult","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/messageUpdated","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/newActivity","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/newMessage","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/persistedUserRetrieved","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/proactiveMessageStatusChanged","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/pushTokenPrepared","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/pushTokenUpdateResult","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/userAccessRevoked","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/userUpdated"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/Equatable-Implementations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/RawRepresentable-Implementations"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH","doc:\/\/com.zendesk.ConversationKit\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"kind":"symbol","abstract":[{"text":"List of events that covers all events that could come from ","type":"text"},{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":"."}],"sections":[],"metadata":{"symbolKind":"enum","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent","title":"ZDKConversationKitEvent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Enumeration","role":"symbol"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/conversationRemoved":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationRemoved","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Current user has lost access to "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" with identifier."}],"title":"ZDKConversationKitEvent.conversationRemoved","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/conversationremoved","navigatorTitle":[{"text":"ZDKConversationKitEventConversationRemoved","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationRemoved"},"doc://com.zendesk.ConversationKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/newMessage":{"title":"ZDKConversationKitEvent.newMessage","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/newmessage","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/newMessage","abstract":[{"text":"New ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":" received for ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":" with identifier."}],"navigatorTitle":[{"text":"ZDKConversationKitEventNewMessage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"newMessage","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/conversationAdded":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationAdded"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventConversationAdded"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationAdded","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/conversationadded","kind":"symbol","title":"ZDKConversationKitEvent.conversationAdded","abstract":[{"text":"Current user has gained access to ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":"."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/RawRepresentable-Implementations":{"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/persistedUserRetrieved":{"kind":"symbol","title":"ZDKConversationKitEvent.persistedUserRetrieved","navigatorTitle":[{"text":"ZDKConversationKitEventPersistedUserRetrieved","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/persisteduserretrieved","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"persistedUserRetrieved","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"User"},{"type":"text","text":" has been retrieved from storage."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/persistedUserRetrieved"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/pushTokenUpdateResult":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushTokenUpdateResult"}],"type":"topic","abstract":[{"text":"The result of the call to update the push token ","type":"text"},{"code":"String","type":"codeVoice"},{"type":"text","text":" with possible "},{"code":"Error","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/pushtokenupdateresult","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/pushTokenUpdateResult","title":"ZDKConversationKitEvent.pushTokenUpdateResult","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ZDKConversationKitEventPushTokenUpdateResult","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/proactiveMessageStatusChanged":{"role":"symbol","title":"ZDKConversationKitEvent.proactiveMessageStatusChanged","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/proactivemessagestatuschanged","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":" event has occurred."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"proactiveMessageStatusChanged","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventProactiveMessageStatusChanged"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/proactiveMessageStatusChanged"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"abstract":[{"text":"List of events that covers all events that could come from ","type":"text"},{"type":"codeVoice","code":"ConversationKit"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEvent"}],"role":"symbol","title":"ZDKConversationKitEvent","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/init(rawValue:)":{"title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/init(rawValue:)","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/init(rawvalue:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/messageUpdated":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/messageUpdated","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageUpdated"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/messageupdated","type":"topic","abstract":[{"text":"Existing ","type":"text"},{"type":"codeVoice","code":"Message"},{"type":"text","text":" updated for "},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":" with identifier."}],"title":"ZDKConversationKitEvent.messageUpdated","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventMessageUpdated"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/connectionStatusChanged":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/connectionStatusChanged","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/connectionstatuschanged","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventConnectionStatusChanged"}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connectionStatusChanged","kind":"identifier"}],"abstract":[{"type":"text","text":"A connection status change event can come from Reachability or Realtime connection."}],"kind":"symbol","title":"ZDKConversationKitEvent.connectionStatusChanged"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/loginResult":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loginResult","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/loginresult","kind":"symbol","abstract":[{"text":"The result of the login call with possible ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventLoginResult"}],"title":"ZDKConversationKitEvent.loginResult","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/loginResult"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/newActivity":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ZDKConversationKitEventNewActivity","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/newActivity","abstract":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"Activity"},{"type":"text","text":" received for "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" with identifier."}],"title":"ZDKConversationKitEvent.newActivity","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/newactivity","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"newActivity"}],"type":"topic"},"doc://com.zendesk.ConversationKit/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SY","title":"Swift.RawRepresentable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/logoutResult":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logoutResult"}],"abstract":[{"type":"text","text":"The result of the logout call with possible "},{"code":"Error","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"ZDKConversationKitEventLogoutResult","kind":"identifier"}],"role":"symbol","title":"ZDKConversationKitEvent.logoutResult","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/logoutresult","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/logoutResult"},"doc://com.zendesk.ConversationKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/conversationUpdated":{"role":"symbol","title":"ZDKConversationKitEvent.conversationUpdated","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationUpdated","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationUpdated"}],"navigatorTitle":[{"text":"ZDKConversationKitEventConversationUpdated","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"code":"Conversation","type":"codeVoice"},{"type":"text","text":" has been updated."}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/conversationupdated"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/userUpdated":{"title":"ZDKConversationKitEvent.userUpdated","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/userUpdated","type":"topic","abstract":[{"type":"text","text":"The "},{"code":"User","type":"codeVoice"},{"type":"text","text":" has been updated."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userUpdated"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/userupdated","navigatorTitle":[{"text":"ZDKConversationKitEventUserUpdated","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/Equatable-Implementations":{"type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/equatable-implementations"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/userAccessRevoked":{"role":"symbol","title":"ZDKConversationKitEvent.userAccessRevoked","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/userAccessRevoked","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"userAccessRevoked","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventUserAccessRevoked"}],"kind":"symbol","type":"topic","abstract":[{"type":"codeVoice","code":"UserAccess"},{"text":" has been revoked.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/useraccessrevoked"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/pushTokenPrepared":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pushTokenPrepared","kind":"identifier"}],"type":"topic","title":"ZDKConversationKitEvent.pushTokenPrepared","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/pushTokenPrepared","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/pushtokenprepared","abstract":[{"text":"The push token ‘String’ was stored.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventPushTokenPrepared"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKConversationKitEvent","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/connectionStatusChanged","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationAdded","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationRemoved","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationUpdated","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/loginResult","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/logoutResult","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/messageUpdated","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/newActivity","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/newMessage","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/persistedUserRetrieved","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/proactiveMessageStatusChanged","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/pushTokenPrepared","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/pushTokenUpdateResult","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/userAccessRevoked","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/userUpdated"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKConversationKitEvent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1conversationRemoved\/title","value":"ZDKConversationKitEventConversationRemoved"},{"value":[{"kind":"identifier","text":"ZDKConversationKitEventConversationRemoved"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1conversationRemoved\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1newMessage\/title","value":"ZDKConversationKitEventNewMessage"},{"op":"replace","value":[{"text":"ZDKConversationKitEventNewMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1newMessage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1conversationAdded\/title","value":"ZDKConversationKitEventConversationAdded"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1conversationAdded\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitEventConversationAdded"}]},{"value":"ZDKConversationKitEventPersistedUserRetrieved","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1persistedUserRetrieved\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1persistedUserRetrieved\/fragments","value":[{"text":"ZDKConversationKitEventPersistedUserRetrieved","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1pushTokenUpdateResult\/title","value":"ZDKConversationKitEventPushTokenUpdateResult","op":"replace"},{"value":[{"text":"ZDKConversationKitEventPushTokenUpdateResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1pushTokenUpdateResult\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1proactiveMessageStatusChanged\/title","value":"ZDKConversationKitEventProactiveMessageStatusChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1proactiveMessageStatusChanged\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitEventProactiveMessageStatusChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","value":"ZDKConversationKitEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitEvent"}]},{"value":"ZDKConversationKitEventMessageUpdated","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1messageUpdated\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1messageUpdated\/fragments","value":[{"text":"ZDKConversationKitEventMessageUpdated","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1connectionStatusChanged\/title","value":"ZDKConversationKitEventConnectionStatusChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1connectionStatusChanged\/fragments","value":[{"text":"ZDKConversationKitEventConnectionStatusChanged","kind":"identifier"}]},{"value":"ZDKConversationKitEventLoginResult","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1loginResult\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1loginResult\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitEventLoginResult"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1newActivity\/title","op":"replace","value":"ZDKConversationKitEventNewActivity"},{"value":[{"text":"ZDKConversationKitEventNewActivity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1newActivity\/fragments","op":"replace"},{"value":"ZDKConversationKitEventLogoutResult","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1logoutResult\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1logoutResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationKitEventLogoutResult"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1conversationUpdated\/title","op":"replace","value":"ZDKConversationKitEventConversationUpdated"},{"value":[{"kind":"identifier","text":"ZDKConversationKitEventConversationUpdated"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1conversationUpdated\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1userUpdated\/title","op":"replace","value":"ZDKConversationKitEventUserUpdated"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1userUpdated\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitEventUserUpdated"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1userAccessRevoked\/title","value":"ZDKConversationKitEventUserAccessRevoked"},{"value":[{"kind":"identifier","text":"ZDKConversationKitEventUserAccessRevoked"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1userAccessRevoked\/fragments","op":"replace"},{"value":"ZDKConversationKitEventPushTokenPrepared","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1pushTokenPrepared\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1pushTokenPrepared\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitEventPushTokenPrepared"}],"op":"replace"}]}]}