{"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/init(from:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/init(text:altText:mediaURL:attachmentId:mediaType:mediaSize:metadata:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/altText","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/attachmentId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/mediaSize","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/mediaType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/mediaURL","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/metadata","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/text","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/isEqual(_:)"]}],"sections":[],"metadata":{"roleHeading":"Class","modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"text":"FileMessageContent","kind":"identifier"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FileMessageContent","kind":"identifier"}],"title":"FileMessageContent","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKFileMessageContent","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKFileMessageContent) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileMessageContent"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/filemessagecontent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/filemessagecontent"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/init(from:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/init(from:)","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/init(from:)","title":"init(from:)","type":"topic","kind":"symbol","role":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/mediaURL":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/mediaURL","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/mediaurl","kind":"symbol","title":"mediaURL","abstract":[{"type":"text","text":"The media URL of the "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"mediaURL"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Content":{"title":"Content","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Content"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","navigatorTitle":[{"kind":"identifier","text":"Content"}],"url":"\/documentation\/zendesksdkconversationkit\/content","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/metadata":{"url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/metadata","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"metadata"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/metadata","abstract":[{"type":"text","text":"The metadata of the "},{"type":"codeVoice","code":"Message"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"metadata","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"title":"metadata"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/description":{"url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/description","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/description","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"description"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/attachmentId":{"title":"attachmentId","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/attachmentId","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/attachmentid","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The attachment identifier of the "},{"type":"codeVoice","code":"Message"},{"text":".","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"attachmentId","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/mediaSize":{"abstract":[{"type":"text","text":"Media size of the "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"title":"mediaSize","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/mediasize","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/mediaSize","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mediaSize"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"mediaSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/hash":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/hash","abstract":[],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/hash","type":"topic","title":"hash","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent":{"url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"FileMessageContent","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FileMessageContent","kind":"identifier"}],"title":"FileMessageContent"},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/text":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/text","abstract":[{"text":"The text of the ","type":"text"},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/text","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"text","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"text","kind":"identifier"}],"title":"text"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/type":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType"}],"title":"type","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The type of the ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/type","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/altText":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/altText","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"altText","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"The alternate text displayed for the "},{"code":"Message","type":"codeVoice"},{"type":"text","text":", used for accessibility."}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/alttext","title":"altText","role":"symbol","navigatorTitle":[{"text":"altText","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/mediaType":{"navigatorTitle":[{"text":"mediaType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/mediaType","abstract":[{"type":"text","text":"Media type of the "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/mediatype","type":"topic","title":"mediaType","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"mediaType","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/isEqual(_:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/isequal(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isEqual(_:)"},"doc://com.zendesk.ConversationKit/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/Se"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/init(text:altText:mediaURL:attachmentId:mediaType:mediaSize:metadata:)":{"url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/init(text:alttext:mediaurl:attachmentid:mediatype:mediasize:metadata:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/init(text:altText:mediaURL:attachmentId:mediaType:mediaSize:metadata:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"altText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"mediaURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attachmentId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mediaSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":"]?)"}],"title":"init(text:altText:mediaURL:attachmentId:mediaType:mediaSize:metadata:)"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ConversationKit/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKFileMessageContent"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKFileMessageContent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKFileMessageContent"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/altText","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/attachmentId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/mediaSize","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/mediaType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/mediaURL","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/metadata","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/text","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/type"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/isEqual(_:)"]}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content"],"type":"conformsTo","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKFileMessageContent","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1mediaURL\/title","value":"mediaURL","op":"replace"},{"value":[{"text":"mediaURL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1mediaURL\/fragments","op":"replace"},{"op":"replace","value":"ZDKMessageContent","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Content\/title"},{"value":[{"text":"ZDKMessageContent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Content\/fragments","op":"replace"},{"value":"metadata","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1metadata\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1metadata\/fragments","value":[{"text":"metadata","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1description\/title","value":"description","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"value":"attachmentId","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1attachmentId\/title","op":"replace"},{"value":[{"text":"attachmentId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1attachmentId\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1mediaSize\/title","value":"mediaSize","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1mediaSize\/fragments","value":[{"text":"mediaSize","kind":"identifier"}]},{"value":"hash","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1hash\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1hash\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent\/title","op":"replace","value":"ZDKFileMessageContent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent\/fragments","value":[{"text":"ZDKFileMessageContent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1text\/title","value":"text","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1text\/fragments","value":[{"kind":"identifier","text":"text"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1type\/title","value":"type"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1type\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1altText\/title","value":"altText"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1altText\/fragments","value":[{"kind":"identifier","text":"altText"}],"op":"replace"},{"op":"replace","value":"mediaType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1mediaType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1mediaType\/fragments","value":[{"text":"mediaType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}]}]}]}