{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationRoutingAssigned","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/activitytype\/conversationroutingassigned"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/activitytype\/conversationroutingassigned"]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRoutingAssigned","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates that the conversation has been assigned."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"conversationRoutingAssigned","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Case","navigatorTitle":[{"text":"ZDKActivityTypeConversationRoutingAssigned","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"ActivityType.conversationRoutingAssigned","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType@ZDKActivityTypeConversationRoutingAssigned"},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/conversationRoutingAssigned":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRoutingAssigned","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationRoutingAssigned"}],"abstract":[{"text":"Indicates that the conversation has been assigned.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKActivityTypeConversationRoutingAssigned"}],"url":"\/documentation\/zendesksdkconversationkit\/activitytype\/conversationroutingassigned","kind":"symbol","title":"ActivityType.conversationRoutingAssigned","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","kind":"symbol","role":"collection","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivityType"}],"title":"ActivityType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ActivityType"}],"url":"\/documentation\/zendesksdkconversationkit\/activitytype","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKActivityTypeConversationRoutingAssigned","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"ZDKActivityTypeConversationRoutingAssigned","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ZDKActivityTypeConversationRoutingAssigned"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1conversationRoutingAssigned\/title","op":"replace","value":"ZDKActivityTypeConversationRoutingAssigned"},{"op":"replace","value":[{"text":"ZDKActivityTypeConversationRoutingAssigned","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1conversationRoutingAssigned\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title","value":"ZDKActivityType","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKActivityType"}]}]}]}