{"variants":[{"paths":["\/documentation\/zendesksdkconversationkit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit"]}],"hierarchy":{"paths":[[]]},"kind":"symbol","metadata":{"externalID":"ZendeskSDKConversationKit","role":"collection","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Framework","symbolKind":"module","title":"ZendeskSDKConversationKit"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Authentication","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Author","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/BuyAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/EmailFormField","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ImageMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LinkAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LocationRequestAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Option","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/PostbackAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RealtimeSettings","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ReplyAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ShareAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/UnsupportedMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageEvent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKPushTokenEvent"]},{"title":"Protocols","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilder","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SettingsParameters"],"title":"Structures"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitVersionNumber","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitVersionString"],"title":"Variables"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionTitle","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/PostbackActionID"],"title":"Type Aliases"},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthorType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitEvent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormField","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionBuyState","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionModel","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Subrole","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/VisitType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField":{"url":"\/documentation\/zendesksdkconversationkit\/textformfield","abstract":[{"type":"text","text":"Form Field that takes in generic user input"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField","title":"TextFormField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextFormField","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"TextFormField","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/PostbackAction":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/PostbackAction","url":"\/documentation\/zendesksdkconversationkit\/postbackaction","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PostbackAction"}],"role":"symbol","navigatorTitle":[{"text":"PostbackAction","kind":"identifier"}],"kind":"symbol","title":"PostbackAction","abstract":[],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize":{"url":"\/documentation\/zendesksdkconversationkit\/actionitemsize","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The display size of "},{"type":"codeVoice","code":"MessageActionItem"},{"type":"text","text":"."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionItemSize","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize","navigatorTitle":[{"text":"ActionItemSize","kind":"identifier"}],"title":"ActionItemSize"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/AuthenticationType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationType"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/authenticationtype","navigatorTitle":[{"kind":"identifier","text":"AuthenticationType"}],"title":"AuthenticationType","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ReplyAction":{"title":"ReplyAction","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ReplyAction","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReplyAction"}],"navigatorTitle":[{"text":"ReplyAction","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/replyaction","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"code":"SettingsParameters","type":"codeVoice"},{"text":" (that contains ","type":"text"},{"type":"codeVoice","code":"ConversationKitSettings"},{"text":", ","type":"text"},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"code":"DefaultConversationKit","type":"codeVoice"},{"text":"’s initializer will create the App ","type":"text"},{"type":"codeVoice","code":"AccessLevel"},{"type":"text","text":" and will check for a persisted user."}],"type":"topic","title":"ConversationKit","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConversationKit","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationKit","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent":{"abstract":[{"text":"Text related ","type":"text"},{"code":"MessageContent","type":"codeVoice"}],"role":"symbol","type":"topic","title":"TextMessageContent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextMessageContent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextMessageContent"}],"url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageAction":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageAction"}],"title":"MessageAction","url":"\/documentation\/zendesksdkconversationkit\/messageaction","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageAction"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ShareAction":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ShareAction"}],"role":"symbol","title":"ShareAction","url":"\/documentation\/zendesksdkconversationkit\/shareaction","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ShareAction","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ShareAction","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionBuyState":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageActionBuyState"}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionbuystate","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionBuyState","role":"symbol","title":"MessageActionBuyState","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageActionBuyState"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config":{"abstract":[],"type":"topic","title":"Config","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/config","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Config","kind":"identifier"}],"navigatorTitle":[{"text":"Config","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKMessageEvent":{"title":"ZDKMessageEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKMessageEvent"}],"abstract":[{"type":"text","text":"Wrapper object for Obj-C to return the associated types of the "},{"type":"codeVoice","code":"newMessage"},{"text":" and ","type":"text"},{"code":"messageUpdated","type":"codeVoice"},{"type":"text","text":" events."}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkmessageevent","type":"topic","navigatorTitle":[{"text":"ZDKMessageEvent","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageEvent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType":{"title":"ActionType","abstract":[],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/actiontype","navigatorTitle":[{"text":"ActionType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionType"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageContent":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageContent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageContent"}],"title":"MessageContent","role":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/messagecontent","kind":"symbol","abstract":[{"type":"text","text":"Enum that encapsulates all the different message types and their content"}],"navigatorTitle":[{"text":"MessageContent","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Field":{"kind":"symbol","title":"Field","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Field"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Field"}],"url":"\/documentation\/zendesksdkconversationkit\/field","abstract":[{"text":"Objective-C representation of the fields in a ","type":"text"},{"code":"Form","type":"codeVoice"},{"type":"text","text":" message"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitBuilderObjC":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC","title":"ConversationKitBuilderObjC","navigatorTitle":[{"kind":"identifier","text":"ConversationKitBuilderObjC"}],"role":"symbol","abstract":[{"text":"Type conforming to ","type":"text"},{"type":"codeVoice","code":"ConversationKitBuilderObjC"},{"type":"text","text":" provide methods which vend concrete types of "},{"type":"codeVoice","code":"ConversationKitObjC"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationKitBuilderObjC","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitbuilderobjc"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKRegion":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkregion","role":"symbol","fragments":[{"kind":"identifier","text":"ZDKRegion"}],"abstract":[{"text":"The region used to connect to the server.","type":"text"}],"type":"topic","title":"ZDKRegion","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKRegion"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Activity","kind":"identifier"}],"navigatorTitle":[{"text":"Activity","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/activity","title":"Activity"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ImageMessageContent":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ImageMessageContent","kind":"symbol","type":"topic","title":"ImageMessageContent","navigatorTitle":[{"text":"ImageMessageContent","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageMessageContent"}],"url":"\/documentation\/zendesksdkconversationkit\/imagemessagecontent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/BuyAction":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/BuyAction","navigatorTitle":[{"kind":"identifier","text":"BuyAction"}],"title":"BuyAction","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BuyAction","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/buyaction","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"title":"ConversationKitObjC","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitObjC"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","abstract":[{"code":"ConversationKitObjC","type":"codeVoice"},{"text":" needs to be configured  with a ","type":"text"},{"code":"ConversationKitSettings","type":"codeVoice"},{"type":"text","text":" "},{"text":"that includes the necessary ","type":"text"},{"code":"integrationId","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"integrationId"},{"type":"text","text":" can be retrieved from the Native Messaging dashboard."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ConversationKitObjC","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/PostbackActionID":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PostbackActionID"}],"title":"PostbackActionID","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PostbackActionID"}],"url":"\/documentation\/zendesksdkconversationkit\/postbackactionid","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/PostbackActionID","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/EmailFormField":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/EmailFormField","navigatorTitle":[{"text":"EmailFormField","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"EmailFormField","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EmailFormField","kind":"identifier"}],"abstract":[{"text":"Form Field used for email input","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/emailformfield"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormMessageContent":{"kind":"symbol","navigatorTitle":[{"text":"FormMessageContent","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/formmessagecontent","type":"topic","abstract":[{"code":"Form","type":"codeVoice"},{"text":" related ","type":"text"},{"code":"MessageContent","type":"codeVoice"},{"type":"text","text":". Used to display an unsubmitted form."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormMessageContent","title":"FormMessageContent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FormMessageContent","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Option":{"kind":"symbol","title":"Option","url":"\/documentation\/zendesksdkconversationkit\/option","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Option","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Option"}],"role":"symbol","abstract":[{"type":"codeVoice","code":"Option"},{"text":" model used for","type":"text"},{"code":"Form","type":"codeVoice"},{"text":" ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":" types, when the input "},{"type":"codeVoice","code":"type"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"select"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Option"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Participant":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Participant"}],"abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/participant","title":"Participant","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","type":"topic","navigatorTitle":[{"text":"Participant","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Author":{"url":"\/documentation\/zendesksdkconversationkit\/author","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Author"}],"kind":"symbol","type":"topic","title":"Author","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Author","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Author"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FieldType":{"type":"topic","title":"FieldType","url":"\/documentation\/zendesksdkconversationkit\/fieldtype","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FieldType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FieldType","kind":"identifier"}],"abstract":[{"type":"text","text":"Form field type. "},{"type":"codeVoice","code":"text"},{"type":"text","text":", "},{"type":"codeVoice","code":"email"},{"type":"text","text":", "},{"type":"codeVoice","code":"select"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"navigatorTitle":[{"kind":"identifier","text":"ActivityType"}],"url":"\/documentation\/zendesksdkconversationkit\/activitytype","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","title":"ActivityType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ActivityType","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitVersionString":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitversionstring","role":"symbol","navigatorTitle":[{"text":"ConversationKitVersionString","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitVersionString"},{"kind":"text","text":": <<error type>>"}],"abstract":[{"type":"text","text":"Project version string for ConversationKit."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitVersionString","type":"topic","title":"ConversationKitVersionString"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionModel":{"navigatorTitle":[{"kind":"identifier","text":"MessageActionModel"}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionmodel","kind":"symbol","abstract":[],"role":"symbol","title":"MessageActionModel","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionModel","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageActionModel","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SelectFormField":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField","kind":"symbol","abstract":[{"text":"Form Field that takes in generic user input","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SelectFormField"}],"url":"\/documentation\/zendesksdkconversationkit\/selectformfield","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelectFormField"}],"role":"symbol","title":"SelectFormField"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKLoginResult":{"abstract":[],"role":"symbol","title":"ZDKLoginResult","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ZDKLoginResult","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkloginresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKLoginResult","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent":{"url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FormResponseMessageContent","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormResponseMessageContent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent","kind":"symbol","abstract":[{"code":"FormResponse","type":"codeVoice"},{"text":" related ","type":"text"},{"type":"codeVoice","code":"MessageContent"},{"text":". Used to display a submitted form.","type":"text"}],"title":"FormResponseMessageContent","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Message","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","title":"Message","url":"\/documentation\/zendesksdkconversationkit\/message","role":"symbol","abstract":[],"navigatorTitle":[{"text":"Message","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"abstract":[{"type":"text","text":"List of events that covers all events that could come from "},{"code":"ConversationKit","type":"codeVoice"},{"text":".","type":"text"}],"title":"ZDKConversationKitEvent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessage":{"url":"\/documentation\/zendesksdkconversationkit\/proactivemessage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProactiveMessage"}],"abstract":[],"kind":"symbol","type":"topic","title":"ProactiveMessage","navigatorTitle":[{"text":"ProactiveMessage","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitVersionNumber":{"abstract":[{"type":"text","text":"Project version number for ConversationKit."}],"type":"topic","title":"ConversationKitVersionNumber","navigatorTitle":[{"kind":"identifier","text":"ConversationKitVersionNumber"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitversionnumber","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitVersionNumber","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationKitVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"User","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"User"}],"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/user","title":"User"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SettingsParameters":{"type":"topic","navigatorTitle":[{"text":"SettingsParameters","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SettingsParameters","kind":"identifier"}],"abstract":[{"text":"Groups together a set of parameters","type":"text"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/settingsparameters","title":"SettingsParameters","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SettingsParameters"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitEvent":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitEvent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitEvent","navigatorTitle":[{"kind":"identifier","text":"ConversationKitEvent"}],"type":"topic","role":"symbol","title":"ConversationKitEvent","url":"\/documentation\/zendesksdkconversationkit\/conversationkitevent","abstract":[{"text":"List of events that covers all events that could come from ","type":"text"},{"type":"codeVoice","code":"ConversationKit"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitError":{"kind":"symbol","title":"ConversationKitError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationKitError"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitError","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkiterror","abstract":[{"type":"text","text":"Errors that could be returned from "},{"code":"ConversationKit","type":"codeVoice"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Authentication":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Authentication","kind":"identifier"}],"navigatorTitle":[{"text":"Authentication","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/authentication","abstract":[],"title":"Authentication","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Authentication"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messagetype","title":"MessageType","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageType"}],"abstract":[{"type":"text","text":"Represents the different "},{"type":"codeVoice","code":"Message"},{"text":" types in a ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageType"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitSettings":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitSettings"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationKitSettings"}],"type":"topic","abstract":[],"title":"ConversationKitSettings","url":"\/documentation\/zendesksdkconversationkit\/conversationkitsettings"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"kind":"symbol","title":"Conversation","role":"symbol","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/CarouselMessageContent":{"url":"\/documentation\/zendesksdkconversationkit\/carouselmessagecontent","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CarouselMessageContent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent","title":"CarouselMessageContent","abstract":[],"navigatorTitle":[{"text":"CarouselMessageContent","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent":{"url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent","navigatorTitle":[{"kind":"identifier","text":"FileMessageContent"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileMessageContent"}],"title":"FileMessageContent","abstract":[],"role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageStatus"}],"abstract":[{"type":"text","text":"Represents the status of the "},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageStatus"}],"title":"MessageStatus","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messagestatus"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/LocationRequestAction":{"title":"LocationRequestAction","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/locationrequestaction","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LocationRequestAction","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"LocationRequestAction","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LocationRequestAction","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType":{"navigatorTitle":[{"text":"ConversationType","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationtype","abstract":[{"type":"text","text":"Represents the possible types of a "},{"type":"codeVoice","code":"Conversation"},{"text":".","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","title":"ConversationType","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus":{"title":"ProactiveMessageStatus","kind":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessageStatus","kind":"identifier"}],"navigatorTitle":[{"text":"ProactiveMessageStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Status that compliments a "},{"code":"ProactiveMessageStatusChanged","type":"codeVoice"},{"text":" event in ","type":"text"},{"code":"ConversationKitEvent","type":"codeVoice"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKActivityEvent":{"title":"ZDKActivityEvent","navigatorTitle":[{"text":"ZDKActivityEvent","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/zdkactivityevent","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKActivityEvent","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Wrapper object for Obj-C to return the associated types of the ","type":"text"},{"code":"newActivity","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"activityReceived"},{"type":"text","text":" events."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKPushTokenEvent":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKPushTokenEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKPushTokenEvent"}],"title":"ZDKPushTokenEvent","kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/zdkpushtokenevent","navigatorTitle":[{"text":"ZDKPushTokenEvent","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/RealtimeSettings":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"RealtimeSettings"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RealtimeSettings","url":"\/documentation\/zendesksdkconversationkit\/realtimesettings","kind":"symbol","role":"symbol","title":"RealtimeSettings","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RealtimeSettings"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationList":{"kind":"symbol","title":"ConversationList","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationList"}],"navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationlist","type":"topic","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/VisitType":{"url":"\/documentation\/zendesksdkconversationkit\/visittype","title":"VisitType","type":"topic","abstract":[{"type":"text","text":"Represents the possible visit types for the SDK."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/VisitType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisitType","kind":"identifier"}],"navigatorTitle":[{"text":"VisitType","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/UnsupportedMessageContent":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/unsupportedmessagecontent","title":"UnsupportedMessageContent","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnsupportedMessageContent"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UnsupportedMessageContent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/UnsupportedMessageContent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"WebViewAction"}],"title":"WebViewAction","url":"\/documentation\/zendesksdkconversationkit\/webviewaction","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WebViewAction"}],"type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKProactiveMessageStatusChanged":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}],"type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":" event has occurred"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged","navigatorTitle":[{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}],"title":"ZDKProactiveMessageStatusChanged","role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"abstract":[],"title":"ConversationKitShared","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitShared"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationKitShared"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionTitle":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionTitle","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messageactiontitle","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageActionTitle"}],"navigatorTitle":[{"kind":"identifier","text":"MessageActionTitle"}],"title":"MessageActionTitle"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitBuilder":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitBuilder","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilder","abstract":[{"text":"Type conforming to ","type":"text"},{"type":"codeVoice","code":"ConversationKitBuilder"},{"text":" provide methods which vend concrete types of ","type":"text"},{"type":"codeVoice","code":"ConversationKit"}],"role":"symbol","navigatorTitle":[{"text":"ConversationKitBuilder","kind":"identifier"}],"type":"topic","title":"ConversationKitBuilder","url":"\/documentation\/zendesksdkconversationkit\/conversationkitbuilder"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormField":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormField","navigatorTitle":[{"text":"FormField","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormField"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Enum representing the Field"}],"url":"\/documentation\/zendesksdkconversationkit\/formfield","title":"FormField"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Subrole":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Subrole"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Subrole","title":"Subrole","url":"\/documentation\/zendesksdkconversationkit\/subrole","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Subrole","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConnectionStatus":{"role":"symbol","title":"ConnectionStatus","navigatorTitle":[{"text":"ConnectionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus","url":"\/documentation\/zendesksdkconversationkit\/connectionstatus","type":"topic","abstract":[{"text":"Represents the current connection state of the client.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionStatus"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Content":{"url":"\/documentation\/zendesksdkconversationkit\/content","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Content","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","title":"Content","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Content"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/LinkAction":{"title":"LinkAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LinkAction"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LinkAction","url":"\/documentation\/zendesksdkconversationkit\/linkaction","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"LinkAction"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationStatus":{"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationstatus","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus","title":"ConversationStatus","role":"symbol","kind":"symbol","abstract":[{"text":"Represents the status of the ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationStatus"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/AuthorType":{"role":"symbol","title":"AuthorType","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthorType","kind":"symbol","abstract":[{"type":"text","text":"Represents the role of the user on the "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"AuthorType","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/authortype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthorType","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionItem":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageActionItem","kind":"identifier"}],"title":"MessageActionItem","type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageActionItem","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionitem","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","abstract":[{"text":"An item in a list type message, such as list or carousel.","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/DefaultConversationKitBuilder":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultConversationKitBuilder"}],"navigatorTitle":[{"text":"DefaultConversationKitBuilder","kind":"identifier"}],"abstract":[],"title":"DefaultConversationKitBuilder","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/defaultconversationkitbuilder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Authentication","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Author","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/BuyAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/EmailFormField","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ImageMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LinkAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LocationRequestAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Option","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/PostbackAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RealtimeSettings","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ReplyAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ShareAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/UnsupportedMessageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageEvent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKPushTokenEvent"],"title":"Classes"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitVersionNumber","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthorType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionBuyState","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/VisitType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKRegion"]}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":"ZDKTextFormField","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField\/fragments","op":"replace","value":[{"text":"ZDKTextFormField","kind":"identifier"}]},{"op":"replace","value":"ZDKPostbackAction","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1PostbackAction\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1PostbackAction\/fragments","value":[{"kind":"identifier","text":"ZDKPostbackAction"}]},{"op":"replace","value":"ZDKMessageItemSize","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/title"},{"value":[{"text":"ZDKMessageItemSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/title","op":"replace","value":"ZDKAuthenticationType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/fragments","value":[{"text":"ZDKAuthenticationType","kind":"identifier"}]},{"value":"ZDKReplyAction","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ReplyAction\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ReplyAction\/fragments","value":[{"kind":"identifier","text":"ZDKReplyAction"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/title","value":"ZDKTextMessageContent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/fragments","value":[{"kind":"identifier","text":"ZDKTextMessageContent"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/title","op":"replace","value":"ZDKMessageAction"},{"value":[{"kind":"identifier","text":"ZDKMessageAction"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ShareAction\/title","value":"ZDKShareAction","op":"replace"},{"value":[{"text":"ZDKShareAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ShareAction\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionBuyState\/title","value":"ZDKMessageActionBuyState"},{"value":[{"kind":"identifier","text":"ZDKMessageActionBuyState"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionBuyState\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/title","op":"replace","value":"ZDKConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/fragments","value":[{"text":"ZDKConfig","kind":"identifier"}]},{"value":"ZDKMessageEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessageEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessageEvent\/fragments","value":[{"kind":"identifier","text":"ZDKMessageEvent"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/title","op":"replace","value":"ZDKActionType"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/fragments","value":[{"text":"ZDKActionType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field\/title","value":"ZDKField"},{"value":[{"kind":"identifier","text":"ZDKField"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC\/title","op":"replace","value":"ZDKConversationKitBuilder"},{"op":"replace","value":[{"text":"ZDKConversationKitBuilder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC\/fragments"},{"op":"replace","value":"ZDKActivity","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKActivity"}]},{"op":"replace","value":"ZDKImageMessageContent","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ImageMessageContent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ImageMessageContent\/fragments","value":[{"kind":"identifier","text":"ZDKImageMessageContent"}]},{"value":"ZDKBuyAction","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1BuyAction\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKBuyAction"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1BuyAction\/fragments"},{"value":"ZDKConversationKit","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments","value":[{"text":"ZDKConversationKit","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1EmailFormField\/title","op":"replace","value":"ZDKEmailFormField"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1EmailFormField\/fragments","value":[{"kind":"identifier","text":"ZDKEmailFormField"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormMessageContent\/title","value":"ZDKFormMessageContent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormMessageContent\/fragments","value":[{"kind":"identifier","text":"ZDKFormMessageContent"}]},{"value":"ZDKOption","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Option\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Option\/fragments","value":[{"kind":"identifier","text":"ZDKOption"}]},{"value":"ZDKParticipant","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/fragments","op":"replace","value":[{"text":"ZDKParticipant","kind":"identifier"}]},{"op":"replace","value":"ZDKAuthor","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Author\/title"},{"op":"replace","value":[{"text":"ZDKAuthor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Author\/fragments"},{"value":"ZDKFieldType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/title"},{"op":"replace","value":[{"text":"ZDKFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title","value":"ZDKActivityType"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKActivityType"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments"},{"op":"replace","value":"ConversationKitVersionString","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitVersionString\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitVersionString\/fragments","value":[{"kind":"identifier","text":"ConversationKitVersionString"}],"op":"replace"},{"value":"ZDKSelectFormField","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/fragments","op":"replace","value":[{"text":"ZDKSelectFormField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult\/title","value":"ZDKLoginResult","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKLoginResult"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/title","value":"ZDKFormResponseMessageContent"},{"value":[{"kind":"identifier","text":"ZDKFormResponseMessageContent"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title","value":"ZDKMessage"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","op":"replace","value":[{"text":"ZDKMessage","kind":"identifier"}]},{"value":"ZDKConversationKitEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title"},{"value":[{"kind":"identifier","text":"ZDKConversationKitEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/title","op":"replace","value":"ZDKProactiveMessage"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessage"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/fragments"},{"op":"replace","value":"ConversationKitVersionNumber","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitVersionNumber\/title"},{"value":[{"text":"ConversationKitVersionNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitVersionNumber\/fragments"},{"value":"ZDKUser","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/fragments","value":[{"kind":"identifier","text":"ZDKUser"}],"op":"replace"},{"op":"replace","value":"ZDKAuthentication","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Authentication\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Authentication\/fragments","value":[{"kind":"identifier","text":"ZDKAuthentication"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/title","op":"replace","value":"ZDKMessageType"},{"value":[{"kind":"identifier","text":"ZDKMessageType"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/fragments"},{"value":"ZDKConversationKitSettings","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitSettings\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitSettings\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitSettings"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","value":"ZDKConversation","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments","value":[{"kind":"identifier","text":"ZDKConversation"}],"op":"replace"},{"value":"ZDKCarouselMessageContent","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1CarouselMessageContent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKCarouselMessageContent"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1CarouselMessageContent\/fragments","op":"replace"},{"value":"ZDKFileMessageContent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent\/fragments","value":[{"text":"ZDKFileMessageContent","kind":"identifier"}],"op":"replace"},{"value":"ZDKMessageStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus\/title"},{"value":[{"kind":"identifier","text":"ZDKMessageStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LocationRequestAction\/title","value":"ZDKLocationRequestAction"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LocationRequestAction\/fragments","op":"replace","value":[{"text":"ZDKLocationRequestAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType\/title","value":"ZDKConversationType"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType\/fragments","value":[{"text":"ZDKConversationType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/title","value":"ZDKProactiveMessageStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatus"}]},{"value":"ZDKActivityEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent\/fragments","value":[{"text":"ZDKActivityEvent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKPushTokenEvent\/title","value":"ZDKPushTokenEvent","op":"replace"},{"value":[{"text":"ZDKPushTokenEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKPushTokenEvent\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1RealtimeSettings\/title","value":"ZDKRealtimeSettings","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRealtimeSettings"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1RealtimeSettings\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/title","value":"ZDKConversationList"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/fragments","value":[{"kind":"identifier","text":"ZDKConversationList"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1VisitType\/title","value":"ZDKVisitType","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1VisitType\/fragments","value":[{"kind":"identifier","text":"ZDKVisitType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1UnsupportedMessageContent\/title","op":"replace","value":"ZDKUnsupportedMessageContent"},{"value":[{"text":"ZDKUnsupportedMessageContent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1UnsupportedMessageContent\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction\/title","value":"ZDKWebViewAction"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction\/fragments","value":[{"text":"ZDKWebViewAction","kind":"identifier"}]},{"op":"replace","value":"ZDKProactiveMessageStatusChanged","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged\/fragments","value":[{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}],"op":"replace"},{"value":"ConversationKitShared","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","value":[{"text":"ConversationKitShared","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus\/title","value":"ZDKConnectionStatus"},{"value":[{"text":"ZDKConnectionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus\/fragments"},{"value":"ZDKMessageContent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Content\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Content\/fragments","value":[{"text":"ZDKMessageContent","kind":"identifier"}]},{"value":"ZDKLinkAction","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LinkAction\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LinkAction\/fragments","value":[{"kind":"identifier","text":"ZDKLinkAction"}]},{"value":"ZDKConversationStatus","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus\/fragments","value":[{"text":"ZDKConversationStatus","kind":"identifier"}],"op":"replace"},{"value":"ZDKAuthorType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthorType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKAuthorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/title","value":"ZDKMessageActionItem"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/fragments","value":[{"kind":"identifier","text":"ZDKMessageActionItem"}]},{"value":"ZDKDefaultConversationKitBuilder","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder\/title","op":"replace"},{"value":[{"text":"ZDKDefaultConversationKitBuilder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder\/fragments"}]}]}