{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent\/init(messageItems:metadata:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","externalID":"s:25ZendeskSDKConversationKit22CarouselMessageContentC12messageItems8metadataACSayAA0E10ActionItemCG_SDySSs11AnyHashableVGSgtcfc","title":"init(messageItems:metadata:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messageItems"},{"text":": [","kind":"text"},{"text":"MessageActionItem","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessageActionItem","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":"]?)"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messageItems"},{"kind":"text","text":": ["},{"text":"MessageActionItem","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessageActionItem"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":"]? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/carouselmessagecontent\/init(messageitems:metadata:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/CarouselMessageContent":{"kind":"symbol","role":"symbol","title":"CarouselMessageContent","url":"\/documentation\/zendesksdkconversationkit\/carouselmessagecontent","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarouselMessageContent"}],"navigatorTitle":[{"kind":"identifier","text":"CarouselMessageContent"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/CarouselMessageContent/init(messageItems:metadata:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent\/init(messageItems:metadata:)","url":"\/documentation\/zendesksdkconversationkit\/carouselmessagecontent\/init(messageitems:metadata:)","kind":"symbol","role":"symbol","type":"topic","title":"init(messageItems:metadata:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageItems"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessageActionItem","kind":"typeIdentifier","text":"MessageActionItem"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":"]?)"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionItem":{"type":"topic","title":"MessageActionItem","url":"\/documentation\/zendesksdkconversationkit\/messageactionitem","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MessageActionItem","kind":"identifier"}],"abstract":[{"text":"An item in a list type message, such as list or carousel.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageActionItem","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1CarouselMessageContent\/title","value":"ZDKCarouselMessageContent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1CarouselMessageContent\/fragments","value":[{"kind":"identifier","text":"ZDKCarouselMessageContent"}]},{"value":"ZDKMessageActionItem","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/title"},{"op":"replace","value":[{"text":"ZDKMessageActionItem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}