{"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/notificationhasbeenclicked"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/notificationhasbeenclicked"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notificationHasBeenClicked","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus"]]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationHasBeenClicked","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invoked when a proactive message has been clicked on."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"title":"ProactiveMessageStatus.notificationHasBeenClicked","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus@ZDKProactiveMessageStatusNotificationHasBeenClicked","navigatorTitle":[{"text":"ZDKProactiveMessageStatusNotificationHasBeenClicked","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notificationHasBeenClicked","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus/notificationHasBeenClicked":{"title":"ProactiveMessageStatus.notificationHasBeenClicked","role":"symbol","abstract":[{"type":"text","text":"Invoked when a proactive message has been clicked on."}],"url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/notificationhasbeenclicked","type":"topic","navigatorTitle":[{"text":"ZDKProactiveMessageStatusNotificationHasBeenClicked","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationHasBeenClicked","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notificationHasBeenClicked","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProactiveMessageStatus"}],"abstract":[{"type":"text","text":"Status that compliments a "},{"type":"codeVoice","code":"ProactiveMessageStatusChanged"},{"type":"text","text":" event in "},{"type":"codeVoice","code":"ConversationKitEvent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProactiveMessageStatus"}],"title":"ProactiveMessageStatus","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ZDKProactiveMessageStatusNotificationHasBeenClicked","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKProactiveMessageStatusNotificationHasBeenClicked","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKProactiveMessageStatusNotificationHasBeenClicked","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1notificationHasBeenClicked\/title","value":"ZDKProactiveMessageStatusNotificationHasBeenClicked","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1notificationHasBeenClicked\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatusNotificationHasBeenClicked"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/title","value":"ZDKProactiveMessageStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/navigatorTitle","value":[{"text":"ZDKProactiveMessageStatus","kind":"identifier"}],"op":"replace"}]}]}