{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageActionItem\/mediaType"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem"]]},"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessageActionItem(py)mediaType","title":"mediaType","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaType"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"mediaType","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkmessageactionitem\/mediatype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkmessageactionitem\/mediatype"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The type of the media referenced by the [mediaUrl], e.g. “image\/jpeg”."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionItem":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageActionItem","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messageactionitem","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","title":"MessageActionItem","type":"topic","abstract":[{"type":"text","text":"An item in a list type message, such as list or carousel."}],"navigatorTitle":[{"text":"MessageActionItem","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKMessageActionItem/mediaType":{"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkmessageactionitem\/mediatype","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageActionItem\/mediaType","role":"symbol","title":"mediaType","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mediaType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"mediaType"}],"abstract":[{"type":"text","text":"The type of the media referenced by the [mediaUrl], e.g. “image\/jpeg”."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"mediaType"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"mediaType","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"mediaType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"ZDKMessageActionItem","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/fragments","value":[{"kind":"identifier","text":"ZDKMessageActionItem"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessageActionItem~1mediaType\/title","op":"replace","value":"mediaType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessageActionItem~1mediaType\/fragments","value":[{"kind":"identifier","text":"mediaType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}