{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/full"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"full","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKWebViewActionSize@ZDKWebViewActionSizeFull","navigatorTitle":[{"kind":"identifier","text":"ZDKWebViewActionSizeFull"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"full","kind":"identifier"}],"role":"symbol","symbolKind":"case","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Case","title":"WebViewActionSize.full"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/webviewactionsize\/full"]},{"paths":["\/documentation\/zendesksdkconversationkit\/webviewactionsize\/full"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize/full":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/full","title":"WebViewActionSize.full","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKWebViewActionSizeFull"}],"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize\/full","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WebViewActionSize"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"WebViewActionSize"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize","role":"symbol","title":"WebViewActionSize","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKWebViewActionSizeFull","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"ZDKWebViewActionSizeFull"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKWebViewActionSizeFull"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKWebViewActionSizeFull","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize~1full\/title"},{"op":"replace","value":[{"text":"ZDKWebViewActionSizeFull","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize~1full\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize\/title","value":"ZDKWebViewActionSize"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize\/fragments","value":[{"text":"ZDKWebViewActionSize","kind":"identifier"}]}]}]}