{"abstract":[{"text":"The action text to display.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKBuyAction\/text","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkbuyaction\/text"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkbuyaction\/text"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/BuyAction"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"text","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKBuyAction(py)text","navigatorTitle":[{"text":"text","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKBuyAction/text":{"abstract":[{"text":"The action text to display.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkbuyaction\/text","type":"topic","kind":"symbol","title":"text","navigatorTitle":[{"text":"text","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKBuyAction\/text","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/BuyAction":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BuyAction","kind":"identifier"}],"title":"BuyAction","navigatorTitle":[{"kind":"identifier","text":"BuyAction"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/buyaction","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/BuyAction","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"text"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"text"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"text","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKBuyAction~1text\/title","value":"text"},{"value":[{"text":"text","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKBuyAction~1text\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1BuyAction\/title","op":"replace","value":"ZDKBuyAction"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1BuyAction\/fragments","value":[{"kind":"identifier","text":"ZDKBuyAction"}]}]}]}