{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newMessage","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/newmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/newmessage"]}],"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"newMessage"}],"navigatorTitle":[{"text":"ZDKConversationKitEventNewMessage","kind":"identifier"}],"roleHeading":"Case","title":"ZDKConversationKitEvent.newMessage","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventNewMessage","symbolKind":"case"},"abstract":[{"type":"text","text":"New "},{"type":"codeVoice","code":"Message"},{"type":"text","text":" received for "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" with identifier."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/newMessage","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","role":"symbol","navigatorTitle":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","title":"ZDKConversationKitEvent","abstract":[{"text":"List of events that covers all events that could come from ","type":"text"},{"type":"codeVoice","code":"ConversationKit"},{"text":".","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/newMessage":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"newMessage"}],"navigatorTitle":[{"text":"ZDKConversationKitEventNewMessage","kind":"identifier"}],"type":"topic","abstract":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"Message"},{"text":" received for ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" with identifier."}],"title":"ZDKConversationKitEvent.newMessage","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/newmessage","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/newMessage"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKConversationKitEventNewMessage"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKConversationKitEventNewMessage","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"ZDKConversationKitEventNewMessage","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","value":"ZDKConversationKitEvent"},{"value":[{"kind":"identifier","text":"ZDKConversationKitEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments"},{"value":"ZDKConversationKitEventNewMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1newMessage\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1newMessage\/fragments","op":"replace","value":[{"text":"ZDKConversationKitEventNewMessage","kind":"identifier"}]}]}]}