{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/pushtokenupdateresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/pushtokenupdateresult"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pushTokenUpdateResult","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"abstract":[{"type":"text","text":"The result of the call to update the push token "},{"type":"codeVoice","code":"String"},{"text":" with possible ","type":"text"},{"type":"codeVoice","code":"Error"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/pushTokenUpdateResult"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","title":"ZDKConversationKitEvent.pushTokenUpdateResult","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventPushTokenUpdateResult"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pushTokenUpdateResult","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventPushTokenUpdateResult"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/pushTokenUpdateResult":{"title":"ZDKConversationKitEvent.pushTokenUpdateResult","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushTokenUpdateResult"}],"kind":"symbol","abstract":[{"text":"The result of the call to update the push token ","type":"text"},{"code":"String","type":"codeVoice"},{"text":" with possible ","type":"text"},{"code":"Error","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"ZDKConversationKitEventPushTokenUpdateResult","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/pushtokenupdateresult","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/pushTokenUpdateResult","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","role":"symbol","navigatorTitle":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","title":"ZDKConversationKitEvent","abstract":[{"text":"List of events that covers all events that could come from ","type":"text"},{"type":"codeVoice","code":"ConversationKit"},{"text":".","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKConversationKitEventPushTokenUpdateResult","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKConversationKitEventPushTokenUpdateResult","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKConversationKitEventPushTokenUpdateResult","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1pushTokenUpdateResult\/title","value":"ZDKConversationKitEventPushTokenUpdateResult","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1pushTokenUpdateResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationKitEventPushTokenUpdateResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","value":"ZDKConversationKitEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments","value":[{"text":"ZDKConversationKitEvent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}