{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC"]]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getMessages(before:conversationId:completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/getmessages(before:conversationid:completion:)"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/getmessages(before:conversationid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Call to fetch a list of messages before a given record ","type":"text"},{"code":"timestamp","type":"codeVoice"},{"text":" for a given ","type":"text"},{"code":"conversation","type":"codeVoice"},{"text":". This call will trigger a network request.","type":"text"}],"metadata":{"title":"getMessages(before:conversationId:completion:)","navigatorTitle":[{"text":"getMessagesBefore:conversationId:completion:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit(im)getMessagesBefore:conversationId:completion:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessages"},{"text":"(","kind":"text"},{"text":"before","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"required":true,"modules":[{"name":"ZendeskSDKConversationKit"}],"platforms":[]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getMessages","kind":"identifier"},{"kind":"text","text":"("},{"text":"before","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","text":"Conversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"timestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The timestamp of the record before which a list of up to 100 messages wil be retrieved"}]}]},{"name":"conversationId","content":[{"inlineContent":[{"type":"text","text":"The identifier of the "},{"type":"codeVoice","code":"Conversation"},{"text":" containing the messages","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The updated ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"text":" with the loaded messages if successful, ","type":"text"},{"code":"ConversationKitError","type":"codeVoice"},{"text":" if not.","type":"text"}],"type":"paragraph"}],"name":"completion"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"Conversation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/getMessages(before:conversationId:completion:)":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/getmessages(before:conversationid:completion:)","title":"getMessages(before:conversationId:completion:)","kind":"symbol","required":true,"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMessagesBefore:conversationId:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getMessages","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"before"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation"},{"kind":"text","text":"?, "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getMessages(before:conversationId:completion:)","abstract":[{"text":"Call to fetch a list of messages before a given record ","type":"text"},{"type":"codeVoice","code":"timestamp"},{"type":"text","text":" for a given "},{"code":"conversation","type":"codeVoice"},{"text":". This call will trigger a network request.","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"kind":"symbol","title":"ConversationKitObjC","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitObjC"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","abstract":[{"code":"ConversationKitObjC","type":"codeVoice"},{"type":"text","text":" needs to be configured  with a "},{"type":"codeVoice","code":"ConversationKitSettings"},{"type":"text","text":" "},{"type":"text","text":"that includes the necessary "},{"type":"codeVoice","code":"integrationId"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"integrationId","type":"codeVoice"},{"text":" can be retrieved from the Native Messaging dashboard.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationKitObjC"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"getMessagesBefore:conversationId:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"getMessagesBefore:conversationId:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"getMessagesBefore:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *) "},{"text":"timestamp","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"conversationId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","text":"ZDKConversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"ZDKConversation","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments","value":[{"text":"ZDKConversation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getMessages(before:conversationId:completion:)\/title","value":"getMessagesBefore:conversationId:completion:"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getMessages(before:conversationId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getMessagesBefore:conversationId:completion:"}],"op":"replace"},{"value":"ZDKConversationKit","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title"},{"op":"replace","value":[{"text":"ZDKConversationKit","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments"}]}]}