{"kind":"symbol","abstract":[{"code":"UserAccess","type":"codeVoice"},{"text":" has been revoked.","type":"text"}],"sections":[],"metadata":{"title":"ZDKConversationKitEvent.userAccessRevoked","role":"symbol","roleHeading":"Case","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventUserAccessRevoked","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"userAccessRevoked","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventUserAccessRevoked"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"userAccessRevoked","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/useraccessrevoked"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/useraccessrevoked"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/userAccessRevoked"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"abstract":[{"type":"text","text":"List of events that covers all events that could come from "},{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEvent"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKConversationKitEvent"}],"title":"ZDKConversationKitEvent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/userAccessRevoked":{"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/useraccessrevoked","title":"ZDKConversationKitEvent.userAccessRevoked","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventUserAccessRevoked"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/userAccessRevoked","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userAccessRevoked","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"UserAccess"},{"text":" has been revoked.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ZDKConversationKitEventUserAccessRevoked"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitEventUserAccessRevoked"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKConversationKitEventUserAccessRevoked","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","value":"ZDKConversationKitEvent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1userAccessRevoked\/title","value":"ZDKConversationKitEventUserAccessRevoked"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1userAccessRevoked\/fragments","value":[{"text":"ZDKConversationKitEventUserAccessRevoked","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}