{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"abstract":[{"type":"text","text":"The type of the "},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/filemessagecontent\/type"]},{"paths":["\/documentation\/zendesksdkconversationkit\/filemessagecontent\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/type"},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType"}],"title":"type","modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKFileMessageContent(py)type","navigatorTitle":[{"kind":"identifier","text":"type"}]},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType":{"abstract":[{"text":"Represents the different ","type":"text"},{"type":"codeVoice","code":"Message"},{"text":" types in a ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageType"}],"title":"MessageType","navigatorTitle":[{"kind":"identifier","text":"MessageType"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","url":"\/documentation\/zendesksdkconversationkit\/messagetype"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent":{"title":"FileMessageContent","role":"symbol","navigatorTitle":[{"text":"FileMessageContent","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileMessageContent","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent/type":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent\/type","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent\/type","title":"type","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","kind":"typeIdentifier","text":"MessageType"}],"role":"symbol","abstract":[{"type":"text","text":"The type of the "},{"type":"codeVoice","code":"Message"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"type","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"type","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ZDKMessageType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/title","op":"replace","value":"ZDKMessageType"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/fragments","value":[{"text":"ZDKMessageType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent\/title","value":"ZDKFileMessageContent"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKFileMessageContent"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1type\/title","value":"type","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent~1type\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"}]}]}