{"abstract":[{"type":"text","text":"Fetches the current wait time for a specific conversation."},{"type":"text","text":" "},{"type":"text","text":"If polling is enabled, this call will initiate polling for updates to wait time."},{"type":"text","text":" "},{"type":"text","text":"Results received from polling or polling retries will be received on the publisher and also will be emitted as "},{"type":"codeVoice","code":"ConversationKitEvent"},{"type":"text","text":"s."}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/fetchwaittimeforconversation(conversationid:)-8u02m"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0"}],"symbolKind":"method","title":"fetchWaitTimeForConversation(conversationId:)","externalID":"s:25ZendeskSDKConversationKit012ConversationC0PAAE016fetchWaitTimeForD014conversationId7Combine12AnyPublisherVyAA0fG4DataCAA0dC5ErrorOGSS_tF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchWaitTimeForConversation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"WaitTimeData","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ConversationKitError","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"kind":"text","text":">"}],"roleHeading":"Instance Method","extendedModule":"ZendeskSDKConversationKit","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchWaitTimeForConversation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"WaitTimeData","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ConversationKitError","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"conversationId","content":[{"type":"paragraph","inlineContent":[{"text":"The Id of the conversation to fetch the wait time for.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"An ","type":"text"},{"code":"AnyPublisher","type":"codeVoice"},{"text":" that passes through ","type":"text"},{"code":"WaitTimeData","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"ConversationKitError","type":"codeVoice"},{"text":" ","type":"text"},{"text":"containing the wait time data associated with the conversation if successful, ","type":"text"},{"code":"ConversationKitError","type":"codeVoice"},{"text":" if not.","type":"text"}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/fetchWaitTimeForConversation(conversationId:)-8u02m"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/fetchWaitTimeForConversation(conversationId:)-8u02m":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/fetchwaittimeforconversation(conversationid:)-8u02m","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchWaitTimeForConversation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier","text":"AnyPublisher"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData","kind":"typeIdentifier","text":"WaitTimeData"},{"kind":"text","text":", "},{"preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","kind":"typeIdentifier","text":"ConversationKitError"},{"kind":"text","text":">"}],"title":"fetchWaitTimeForConversation(conversationId:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/fetchWaitTimeForConversation(conversationId:)-8u02m","type":"topic","role":"symbol","abstract":[{"text":"Fetches the current wait time for a specific conversation.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If polling is enabled, this call will initiate polling for updates to wait time."},{"type":"text","text":" "},{"type":"text","text":"Results received from polling or polling retries will be received on the publisher and also will be emitted as "},{"code":"ConversationKitEvent","type":"codeVoice"},{"type":"text","text":"s."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitError":{"navigatorTitle":[{"text":"ConversationKitError","kind":"identifier"}],"abstract":[{"text":"Errors that could be returned from ","type":"text"},{"code":"ConversationKit","type":"codeVoice"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","title":"ConversationKitError","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitError","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkiterror"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/waittimedata","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WaitTimeData"}],"abstract":[],"title":"WaitTimeData","navigatorTitle":[{"kind":"identifier","text":"WaitTimeData"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKit","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ConversationKit"},{"text":" needs to be configured  with ","type":"text"},{"type":"codeVoice","code":"SettingsParameters"},{"text":" (that contains ","type":"text"},{"type":"codeVoice","code":"Config"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"FeatureFlagManager"},{"text":")","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"type":"codeVoice","code":"DispatchQueue"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"DefaultConversationKit"},{"text":"’s initializer will create the App ","type":"text"},{"type":"codeVoice","code":"AccessLevel"},{"text":" and will check for a persisted user.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ConversationKit","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","title":"ConversationKit","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/title","value":"ZDKWaitTimeData"},{"value":[{"kind":"identifier","text":"ZDKWaitTimeData"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/fragments"},{"value":[{"kind":"identifier","text":"ZDKWaitTimeData"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}