{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getConversations(offset:result:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Call to fetch the user’s list of conversations. This call will fetch the conversations list from storage,","type":"text"},{"text":" ","type":"text"},{"text":"and will trigger a network request if no conversation has been previously persisted.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"ConversationList","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationList","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ConversationKitError","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"offset","content":[{"inlineContent":[{"type":"text","text":"The number of items to skip before starting to collect the result set."}],"type":"paragraph"}]},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"text":"A list of ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"text":" if successful, ","type":"text"},{"code":"ConversationKitError","type":"codeVoice"},{"text":" if not.","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"defaultImplementationsSections":[{"title":"ConversationKit Implementations","anchor":"ConversationKit-Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getConversations(offset:result:)-2a38g"]}],"sections":[],"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"ConversationList","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationList"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","externalID":"s:25ZendeskSDKConversationKit012ConversationC0P16getConversations6offset6resultySi_ys6ResultOyAA0D4ListCAA0dC5ErrorOGcSgtF","required":true,"roleHeading":"Instance Method","title":"getConversations(offset:result:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/getconversations(offset:result:)"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/getConversations(offset:result:)":{"kind":"symbol","title":"getConversations(offset:result:)","role":"symbol","abstract":[{"type":"text","text":"Call to fetch the user’s list of conversations. This call will fetch the conversations list from storage,"},{"type":"text","text":" "},{"type":"text","text":"and will trigger a network request if no conversation has been previously persisted."}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/getconversations(offset:result:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getConversations(offset:result:)","defaultImplementations":1,"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationList","text":"ConversationList"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","text":"ConversationKitError"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/getConversations(offset:result:)-2a38g":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"ConversationList","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationList"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"title":"getConversations(offset:result:)","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/getconversations(offset:result:)-2a38g","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getConversations(offset:result:)-2a38g","abstract":[{"text":"Call to fetch the user’s list of conversations. This call will fetch the conversations list from storage,","type":"text"},{"text":" ","type":"text"},{"text":"and will trigger a network request if no conversation has been previously persisted.","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKit","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ConversationKit"},{"text":" needs to be configured  with ","type":"text"},{"type":"codeVoice","code":"SettingsParameters"},{"text":" (that contains ","type":"text"},{"type":"codeVoice","code":"Config"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"FeatureFlagManager"},{"text":")","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"type":"codeVoice","code":"DispatchQueue"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"DefaultConversationKit"},{"text":"’s initializer will create the App ","type":"text"},{"type":"codeVoice","code":"AccessLevel"},{"text":" and will check for a persisted user.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ConversationKit","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","title":"ConversationKit","role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitError":{"navigatorTitle":[{"text":"ConversationKitError","kind":"identifier"}],"abstract":[{"text":"Errors that could be returned from ","type":"text"},{"code":"ConversationKit","type":"codeVoice"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","title":"ConversationKitError","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitError","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkiterror"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationList":{"type":"topic","navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationList","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationlist","role":"symbol","abstract":[],"title":"ConversationList","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/title","value":"ZDKConversationList"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/fragments","value":[{"kind":"identifier","text":"ZDKConversationList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConversationList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}