{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loginUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"jwt","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"User","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"User"},{"text":"’s ","type":"text"},{"type":"codeVoice","code":"jwt"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"jwt"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"User"},{"text":" if successful, ","type":"text"},{"type":"codeVoice","code":"ConversationKitError"},{"text":" if not.","type":"text"}]}],"name":"result"}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/loginuser(with:result:)-7ziwl"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"extendedModule":"ZendeskSDKConversationKit","symbolKind":"method","externalID":"s:25ZendeskSDKConversationKit012ConversationC0PAAE9loginUser4with6resultySS_ys6ResultOyAA0F0CAA0dC5ErrorOGcSgtF","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loginUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","text":"User"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","text":"ConversationKitError"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"title":"loginUser(with:result:)"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"Call to authenticate a new user, or re-authenticate an existing user during a conversation.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/loginUser(with:result:)-7ziwl","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/loginUser(with:result:)-7ziwl":{"type":"topic","role":"symbol","title":"loginUser(with:result:)","abstract":[{"type":"text","text":"Call to authenticate a new user, or re-authenticate an existing user during a conversation."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loginUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","text":"User","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","text":"ConversationKitError","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/loginUser(with:result:)-7ziwl","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/loginuser(with:result:)-7ziwl"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitError":{"navigatorTitle":[{"text":"ConversationKitError","kind":"identifier"}],"abstract":[{"text":"Errors that could be returned from ","type":"text"},{"code":"ConversationKit","type":"codeVoice"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","title":"ConversationKitError","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitError","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkiterror"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/user","kind":"symbol","title":"User","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"User","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"User","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKit","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ConversationKit"},{"text":" needs to be configured  with ","type":"text"},{"type":"codeVoice","code":"SettingsParameters"},{"text":" (that contains ","type":"text"},{"type":"codeVoice","code":"Config"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"FeatureFlagManager"},{"text":")","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"type":"codeVoice","code":"DispatchQueue"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"DefaultConversationKit"},{"text":"’s initializer will create the App ","type":"text"},{"type":"codeVoice","code":"AccessLevel"},{"text":" and will check for a persisted user.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ConversationKit","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","title":"ConversationKit","role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]}},"variantOverrides":[{"patch":[{"value":"ZDKUser","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/title"},{"value":[{"kind":"identifier","text":"ZDKUser"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/fragments"},{"value":[{"text":"ZDKUser","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}