{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendConversationActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"activity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ActivityType","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ActivityType"},{"type":"text","text":" that is to be sent"}],"type":"paragraph"}],"name":"activity"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":"that the "},{"type":"codeVoice","code":"Activity"},{"type":"text","text":" will be sent"}]}],"name":"conversationId"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Available Activity Types are:"}]},{"items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"conversationRead"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"typingStart"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"typingStop"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Call to send an activity "},{"code":"ActivityType","type":"codeVoice"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"defaultImplementationsSections":[{"anchor":"ConversationKit-Implementations","title":"ConversationKit Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendConversationActivity(activity:conversationId:result:)-94aw0"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/sendconversationactivity(activity:conversationid:result:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendConversationActivity(activity:conversationId:result:)"},"metadata":{"externalID":"s:25ZendeskSDKConversationKit012ConversationC0P04sendD8Activity8activity14conversationId6resultyAA0F4TypeO_SSys6ResultOyytAA0dC5ErrorOGcSgtF","required":true,"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendConversationActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"activity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType","text":"ActivityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","text":"ConversationKitError"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"sendConversationActivity(activity:conversationId:result:)","roleHeading":"Instance Method","role":"symbol"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/sendConversationActivity(activity:conversationId:result:)-94aw0":{"kind":"symbol","title":"sendConversationActivity(activity:conversationId:result:)","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/sendconversationactivity(activity:conversationid:result:)-94aw0","abstract":[{"type":"text","text":"Call to send an activity "},{"type":"codeVoice","code":"ActivityType"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendConversationActivity(activity:conversationId:result:)-94aw0","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendConversationActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"activity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ActivityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/sendConversationActivity(activity:conversationId:result:)":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/sendconversationactivity(activity:conversationid:result:)","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendConversationActivity(activity:conversationId:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendConversationActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"activity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType","text":"ActivityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","text":"ConversationKitError"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"required":true,"defaultImplementations":1,"role":"symbol","abstract":[{"type":"text","text":"Call to send an activity "},{"type":"codeVoice","code":"ActivityType"}],"title":"sendConversationActivity(activity:conversationId:result:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"url":"\/documentation\/zendesksdkconversationkit\/activitytype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivityType","kind":"identifier"}],"kind":"symbol","type":"topic","title":"ActivityType","abstract":[],"navigatorTitle":[{"text":"ActivityType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKit","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ConversationKit"},{"text":" needs to be configured  with ","type":"text"},{"type":"codeVoice","code":"SettingsParameters"},{"text":" (that contains ","type":"text"},{"type":"codeVoice","code":"Config"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"FeatureFlagManager"},{"text":")","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"type":"codeVoice","code":"DispatchQueue"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"DefaultConversationKit"},{"text":"’s initializer will create the App ","type":"text"},{"type":"codeVoice","code":"AccessLevel"},{"text":" and will check for a persisted user.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ConversationKit","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","title":"ConversationKit","role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitError":{"navigatorTitle":[{"text":"ConversationKitError","kind":"identifier"}],"abstract":[{"text":"Errors that could be returned from ","type":"text"},{"code":"ConversationKit","type":"codeVoice"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","title":"ConversationKitError","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitError","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkiterror"}},"variantOverrides":[{"patch":[{"value":"ZDKActivityType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title"},{"value":[{"text":"ZDKActivityType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments"},{"value":[{"text":"ZDKActivityType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}