{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","kind":"typeIdentifier","text":"Message"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","kind":"typeIdentifier","text":"Message"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":" that will be sent.","type":"text"}]}],"name":"message"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the "},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":" that the "},{"code":"Message","type":"codeVoice"},{"type":"text","text":" will be appended to."}]}],"name":"conversationId"}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The  sent"},{"type":"codeVoice","code":"Message"},{"type":"text","text":" object."}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","content":[{"inlineContent":[{"text":"This will throw an error of type ","type":"text"},{"code":"ConversationKitError","type":"codeVoice"},{"text":" in case of failure.","type":"text"}],"type":"paragraph"}],"name":"Throws","style":"note"}]}],"defaultImplementationsSections":[{"title":"ConversationKit Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendMessage(message:conversationId:)-63hix"],"anchor":"ConversationKit-Implementations"}],"metadata":{"roleHeading":"Instance Method","externalID":"s:25ZendeskSDKConversationKit012ConversationC0P11sendMessage7message14conversationIdAA0F0CAH_SStYaKF","required":true,"platforms":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.0"}],"title":"sendMessage(message:conversationId:)","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","text":"Message"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","text":"Message"}],"modules":[{"name":"ZendeskSDKConversationKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendMessage(message:conversationId:)"},"sections":[],"abstract":[{"type":"text","text":"Call to send a "},{"type":"codeVoice","code":"Message"},{"type":"text","text":". This call will trigger a network request."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/sendmessage(message:conversationid:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKit","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ConversationKit"},{"text":" needs to be configured  with ","type":"text"},{"type":"codeVoice","code":"SettingsParameters"},{"text":" (that contains ","type":"text"},{"type":"codeVoice","code":"Config"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"FeatureFlagManager"},{"text":")","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"type":"codeVoice","code":"DispatchQueue"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"DefaultConversationKit"},{"text":"’s initializer will create the App ","type":"text"},{"type":"codeVoice","code":"AccessLevel"},{"text":" and will check for a persisted user.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ConversationKit","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","title":"ConversationKit","role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"abstract":[],"title":"Message","navigatorTitle":[{"text":"Message","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","url":"\/documentation\/zendesksdkconversationkit\/message","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Message","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/sendMessage(message:conversationId:)-63hix":{"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/sendmessage(message:conversationid:)-63hix","abstract":[{"type":"text","text":"Call to send a "},{"type":"codeVoice","code":"Message"},{"type":"text","text":". This call will trigger a network request."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendMessage(message:conversationId:)-63hix","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Message","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Message","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","kind":"typeIdentifier"}],"title":"sendMessage(message:conversationId:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/sendMessage(message:conversationId:)":{"abstract":[{"type":"text","text":"Call to send a "},{"type":"codeVoice","code":"Message"},{"type":"text","text":". This call will trigger a network request."}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/sendmessage(message:conversationid:)","required":true,"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendMessage(message:conversationId:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","text":"Message"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","text":"Message"}],"defaultImplementations":1,"type":"topic","title":"sendMessage(message:conversationId:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title","value":"ZDKMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","value":[{"text":"ZDKMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKMessage"}],"op":"replace"}]}]}