{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/connectionStatusChanged","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"metadata":{"navigatorTitle":[{"text":"ZDKConversationKitEventConnectionStatusChanged","kind":"identifier"}],"title":"ZDKConversationKitEvent.connectionStatusChanged","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventConnectionStatusChanged","roleHeading":"Case","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"connectionStatusChanged","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"connectionStatusChanged","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"abstract":[{"text":"A connection status change event can come from Reachability or Realtime connection.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/connectionstatuschanged"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/connectionstatuschanged"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/connectionStatusChanged":{"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/connectionstatuschanged","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"connectionStatusChanged","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ZDKConversationKitEventConnectionStatusChanged","kind":"identifier"}],"title":"ZDKConversationKitEvent.connectionStatusChanged","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/connectionStatusChanged","abstract":[{"type":"text","text":"A connection status change event can come from Reachability or Realtime connection."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","title":"ZDKConversationKitEvent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"List of events that covers all events that could come from "},{"type":"codeVoice","code":"ConversationKit"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"ZDKConversationKitEvent","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKConversationKitEventConnectionStatusChanged","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ZDKConversationKitEventConnectionStatusChanged","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKConversationKitEventConnectionStatusChanged","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1connectionStatusChanged\/title","value":"ZDKConversationKitEventConnectionStatusChanged"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1connectionStatusChanged\/fragments","op":"replace","value":[{"text":"ZDKConversationKitEventConnectionStatusChanged","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","value":"ZDKConversationKitEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments","value":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"op":"replace"}]}]}