{"kind":"symbol","metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit(im)sendConversationReferralWithProactiveMessageId:conversationId:completion:","roleHeading":"Instance Method","role":"symbol","required":true,"title":"sendConversationReferral(proactiveMessageId:conversationId:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sendConversationReferral","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Conversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"sendConversationReferralWithProactiveMessageId:conversationId:completion:","kind":"identifier"}],"symbolKind":"method","platforms":[],"modules":[{"name":"ZendeskSDKConversationKit"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendConversationReferral(proactiveMessageId:conversationId:completion:)"},"abstract":[{"text":"Call to send a conversation referral. This call will fetch the updated conversation with the proactive message added.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendConversationReferral"},{"kind":"text","text":"("},{"kind":"externalParam","text":"proactiveMessageId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"proactiveMessageId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The proactive message id tapped"}]}]},{"name":"conversationId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The existing conversation id"}]}]},{"content":[{"inlineContent":[{"text":"The updated ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"text":" with the proactive message added if successful, ","type":"text"},{"code":"Error","type":"codeVoice"},{"type":"text","text":" if not."}],"type":"paragraph"}],"name":"completion"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendconversationreferral(proactivemessageid:conversationid:completion:)"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendconversationreferral(proactivemessageid:conversationid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/sendConversationReferral(proactiveMessageId:conversationId:completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sendConversationReferral","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"proactiveMessageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"required":true,"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendconversationreferral(proactivemessageid:conversationid:completion:)","navigatorTitle":[{"kind":"identifier","text":"sendConversationReferralWithProactiveMessageId:conversationId:completion:"}],"type":"topic","kind":"symbol","title":"sendConversationReferral(proactiveMessageId:conversationId:completion:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendConversationReferral(proactiveMessageId:conversationId:completion:)","abstract":[{"text":"Call to send a conversation referral. This call will fetch the updated conversation with the proactive message added.","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Conversation","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation","type":"topic","title":"Conversation","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"type":"topic","navigatorTitle":[{"text":"ConversationKitObjC","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","kind":"symbol","title":"ConversationKitObjC","abstract":[{"code":"ConversationKitObjC","type":"codeVoice"},{"type":"text","text":" needs to be configured  with a "},{"code":"Config","type":"codeVoice"},{"text":" ","type":"text"},{"text":"that includes the necessary ","type":"text"},{"code":"integrationId","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"integrationId","type":"codeVoice"},{"type":"text","text":" can be retrieved from the Native Messaging dashboard."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitObjC","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"sendConversationReferralWithProactiveMessageId:conversationId:completion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"sendConversationReferralWithProactiveMessageId:conversationId:completion:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"sendConversationReferralWithProactiveMessageId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"proactiveMessageId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"conversationId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(ZDKConversation *, NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"sendConversationReferralWithProactiveMessageId:conversationId:completion:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendConversationReferral(proactiveMessageId:conversationId:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendConversationReferral(proactiveMessageId:conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendConversationReferralWithProactiveMessageId:conversationId:completion:"}],"op":"replace"},{"value":"ZDKConversation","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","op":"replace"},{"op":"replace","value":[{"text":"ZDKConversation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title","op":"replace","value":"ZDKConversationKit"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}