{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormMessageContent\/isEqual(_:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isEqual(_:)","roleHeading":"Instance Method","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKFormMessageContent(im)isEqual:","symbolKind":"method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormMessageContent"]]},"kind":"symbol","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/formmessagecontent\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/formmessagecontent\/isequal(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"object"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"the object to compare against","type":"text"}]}],"name":"object"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormMessageContent":{"kind":"symbol","navigatorTitle":[{"text":"FormMessageContent","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/formmessagecontent","type":"topic","abstract":[{"code":"Form","type":"codeVoice"},{"text":" related ","type":"text"},{"code":"MessageContent","type":"codeVoice"},{"type":"text","text":". Used to display an unsubmitted form."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormMessageContent","title":"FormMessageContent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FormMessageContent","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormMessageContent/isEqual(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isEqual(_:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormMessageContent\/isEqual(_:)","kind":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/formmessagecontent\/isequal(_:)","abstract":[{"text":"Returns a Boolean value that indicates whether the receiver and a given object are equal.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isEqual:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormMessageContent\/title","value":"ZDKFormMessageContent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormMessageContent\/fragments","value":[{"kind":"identifier","text":"ZDKFormMessageContent"}]},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormMessageContent~1isEqual(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormMessageContent~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}