{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/sendMessageFailed"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"ZDKConversationKitEventSendMessageFailed","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendMessageFailed"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventSendMessageFailed","roleHeading":"Case","modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","title":"ZDKConversationKitEvent.sendMessageFailed","symbolKind":"case"},"abstract":[{"type":"text","text":"The sending "},{"code":"Message","type":"codeVoice"},{"text":" failed with ","type":"text"},{"type":"codeVoice","code":"ConversationKitError"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"sendMessageFailed","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/sendmessagefailed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/sendmessagefailed"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/sendMessageFailed":{"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/sendmessagefailed","abstract":[{"type":"text","text":"The sending "},{"code":"Message","type":"codeVoice"},{"type":"text","text":" failed with "},{"type":"codeVoice","code":"ConversationKitError"},{"text":".","type":"text"}],"role":"symbol","type":"topic","title":"ZDKConversationKitEvent.sendMessageFailed","navigatorTitle":[{"text":"ZDKConversationKitEventSendMessageFailed","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sendMessageFailed","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/sendMessageFailed","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"abstract":[{"text":"List of events that covers all events that could come from ","type":"text"},{"code":"ConversationKit","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"kind":"symbol","title":"ZDKConversationKitEvent","type":"topic","navigatorTitle":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKConversationKitEventSendMessageFailed","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKConversationKitEventSendMessageFailed"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKConversationKitEventSendMessageFailed","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKConversationKitEventSendMessageFailed","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1sendMessageFailed\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1sendMessageFailed\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitEventSendMessageFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","value":"ZDKConversationKitEvent"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments","op":"replace","value":[{"text":"ZDKConversationKitEvent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}