{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/activity\/appuserid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/activity\/appuserid"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/appUserId","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","title":"appUserId","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"appUserId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity(py)appUserId","navigatorTitle":[{"kind":"identifier","text":"appUserId"}]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/appUserId":{"title":"appUserId","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"appUserId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/appUserId","url":"\/documentation\/zendesksdkconversationkit\/activity\/appuserid","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appUserId"}],"abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity":{"title":"Activity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/activity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Activity","kind":"identifier"}],"navigatorTitle":[{"text":"Activity","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","role":"collection","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"appUserId"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"appUserId","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"appUserId"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"appUserId","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1appUserId\/title","op":"replace"},{"value":[{"text":"appUserId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1appUserId\/fragments"},{"op":"replace","value":"ZDKActivity","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/fragments","value":[{"text":"ZDKActivity","kind":"identifier"}],"op":"replace"}]}]}