{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/url"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived\/url"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived\/url"]}],"kind":"symbol","metadata":{"title":"url","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKOpenWebViewMessageReceived(py)url","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"url"}],"role":"symbol","roleHeading":"Instance Property"},"abstract":[{"text":"The url ","type":"text"},{"type":"codeVoice","code":"String"},{"type":"text","text":" of the Conversation Extension that needs to be opened."}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKOpenWebViewMessageReceived/url":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/url","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"url"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived\/url","abstract":[{"type":"text","text":"The url "},{"type":"codeVoice","code":"String"},{"text":" of the Conversation Extension that needs to be opened.","type":"text"}],"title":"url"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKOpenWebViewMessageReceived":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKOpenWebViewMessageReceived","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKOpenWebViewMessageReceived","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived","abstract":[{"text":"A new message with a webview action ","type":"text"},{"type":"codeVoice","code":"openOnReceive"},{"type":"text","text":" has occurred"}],"title":"ZDKOpenWebViewMessageReceived"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"url"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"url"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"url","kind":"identifier"}],"languages":["occ"]}]}},{"value":"url","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived~1url\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived~1url\/fragments","value":[{"text":"url","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived\/title","value":"ZDKOpenWebViewMessageReceived"},{"value":[{"text":"ZDKOpenWebViewMessageReceived","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived\/fragments"}]}]}