{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LocationRequestAction"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LocationRequestAction\/metadata"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/locationrequestaction\/metadata"]},{"paths":["\/documentation\/zendesksdkconversationkit\/locationrequestaction\/metadata"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"metadata","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"abstract":[{"type":"text","text":"The metadata of this action"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKLocationRequestAction(py)metadata","title":"metadata","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"property","navigatorTitle":[{"text":"metadata","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"metadata","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":"]?"}],"roleHeading":"Instance Property","role":"symbol"},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/LocationRequestAction/metadata":{"url":"\/documentation\/zendesksdkconversationkit\/locationrequestaction\/metadata","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LocationRequestAction\/metadata","type":"topic","title":"metadata","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"metadata","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"metadata"}],"abstract":[{"text":"The metadata of this action","type":"text"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/LocationRequestAction":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LocationRequestAction","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocationRequestAction","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/locationrequestaction","navigatorTitle":[{"text":"LocationRequestAction","kind":"identifier"}],"title":"LocationRequestAction","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"metadata"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"metadata"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSDictionary<NSString *,NSObject *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"metadata"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LocationRequestAction~1metadata\/title","value":"metadata","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LocationRequestAction~1metadata\/fragments","value":[{"text":"metadata","kind":"identifier"}]},{"op":"replace","value":"ZDKLocationRequestAction","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LocationRequestAction\/title"},{"value":[{"text":"ZDKLocationRequestAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LocationRequestAction\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}