{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig(py)restRetryPolicy","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"restRetryPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RestRetryPolicy","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKRestRetryPolicy"}],"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"restRetryPolicy"}],"title":"restRetryPolicy","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/restRetryPolicy","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"restRetryPolicy","kind":"identifier"},{"kind":"text","text":": "},{"text":"RestRetryPolicy","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RestRetryPolicy","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKRestRetryPolicy","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"abstract":[{"text":"The ","type":"text"},{"code":"RestRetryPolicy","type":"codeVoice"},{"text":" applied to all requests made to Sunshine Conversations.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/config\/restretrypolicy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/config\/restretrypolicy"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Config"}],"url":"\/documentation\/zendesksdkconversationkit\/config","navigatorTitle":[{"text":"Config","kind":"identifier"}],"title":"Config","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/RestRetryPolicy":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RestRetryPolicy","abstract":[{"text":"The retry policy used when making REST requests.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RestRetryPolicy","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/restretrypolicy","navigatorTitle":[{"text":"RestRetryPolicy","kind":"identifier"}],"title":"RestRetryPolicy","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config/restRetryPolicy":{"url":"\/documentation\/zendesksdkconversationkit\/config\/restretrypolicy","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restRetryPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKRestRetryPolicy","text":"RestRetryPolicy"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/restRetryPolicy","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"RestRetryPolicy"},{"text":" applied to all requests made to Sunshine Conversations.","type":"text"}],"navigatorTitle":[{"text":"restRetryPolicy","kind":"identifier"}],"type":"topic","title":"restRetryPolicy","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"restRetryPolicy"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"restRetryPolicy","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RestRetryPolicy","text":"ZDKRestRetryPolicy","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKRestRetryPolicy"},{"kind":"text","text":" * "},{"text":"restRetryPolicy","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/title","op":"replace","value":"ZDKConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/fragments","value":[{"text":"ZDKConfig","kind":"identifier"}]},{"value":"ZDKRestRetryPolicy","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1RestRetryPolicy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRestRetryPolicy"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1RestRetryPolicy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config~1restRetryPolicy\/title","value":"restRetryPolicy"},{"value":[{"text":"restRetryPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config~1restRetryPolicy\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}