{"metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"size"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKOpenWebViewMessageReceived(py)size","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"size","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKWebViewActionSize","text":"WebViewActionSize"}]},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived\/size"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived\/size"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/size"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"The size of the webview","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKWebViewActionSize","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize","text":"WebViewActionSize","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKOpenWebViewMessageReceived/size":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived\/size","title":"size","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/size","navigatorTitle":[{"text":"size","kind":"identifier"}],"type":"topic","abstract":[{"text":"The size of the webview","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKWebViewActionSize","text":"WebViewActionSize","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKOpenWebViewMessageReceived":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived","title":"ZDKOpenWebViewMessageReceived","navigatorTitle":[{"text":"ZDKOpenWebViewMessageReceived","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A new message with a webview action "},{"type":"codeVoice","code":"openOnReceive"},{"type":"text","text":" has occurred"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKOpenWebViewMessageReceived","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize":{"abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize","navigatorTitle":[{"text":"WebViewActionSize","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"WebViewActionSize","kind":"identifier"}],"title":"WebViewActionSize","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"size"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"size","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKWebViewActionSize","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize","text":"ZDKWebViewActionSize","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived~1size\/fragments","value":[{"text":"size","kind":"identifier"}]},{"value":"ZDKOpenWebViewMessageReceived","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived\/title"},{"value":[{"text":"ZDKOpenWebViewMessageReceived","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived\/fragments","op":"replace"},{"op":"replace","value":"ZDKWebViewActionSize","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize\/fragments","op":"replace","value":[{"text":"ZDKWebViewActionSize","kind":"identifier"}]}]}]}