{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"text":" has been updated.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/userUpdated","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/userupdated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/userupdated"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"userUpdated","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventUserUpdated","title":"ZDKConversationKitEvent.userUpdated","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"userUpdated","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"text":"ZDKConversationKitEventUserUpdated","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/userUpdated":{"title":"ZDKConversationKitEvent.userUpdated","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/userupdated","type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"User","type":"codeVoice"},{"text":" has been updated.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userUpdated"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventUserUpdated"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/userUpdated","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","kind":"symbol","role":"collection","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","title":"ZDKConversationKitEvent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","role":"symbol","type":"topic","abstract":[{"text":"List of events that covers all events that could come from ","type":"text"},{"type":"codeVoice","code":"ConversationKit"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEvent"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKConversationKitEventUserUpdated"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKConversationKitEventUserUpdated","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ZDKConversationKitEventUserUpdated","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"ZDKConversationKitEventUserUpdated","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1userUpdated\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1userUpdated\/fragments","value":[{"text":"ZDKConversationKitEventUserUpdated","kind":"identifier"}],"op":"replace"},{"value":"ZDKConversationKitEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKConversationKitEvent"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments"}]}]}