{"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/fetchwaittimeforconversation(conversationid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/fetchwaittimeforconversation(conversationid:completion:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchWaitTimeForConversation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","text":"WaitTimeData","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The Id of the conversation to fetch the wait time for.","type":"text"}]}],"name":"conversationId"},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Return the wait time data associated with the conversation if successful, "},{"type":"codeVoice","code":"Error"},{"text":" if not.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/fetchWaitTimeForConversation(conversationId:completion:)"},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"fetchWaitTimeForConversationWithConversationId:completion:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit(im)fetchWaitTimeForConversationWithConversationId:completion:","title":"fetchWaitTimeForConversation(conversationId:completion:)","symbolKind":"method","platforms":[],"required":true,"modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchWaitTimeForConversation"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"WaitTimeData","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC"]]},"abstract":[{"type":"text","text":"Fetches the current wait time for a specific conversation"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/fetchWaitTimeForConversation(conversationId:completion:)":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/fetchwaittimeforconversation(conversationid:completion:)","kind":"symbol","required":true,"abstract":[{"text":"Fetches the current wait time for a specific conversation","type":"text"}],"title":"fetchWaitTimeForConversation(conversationId:completion:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/fetchWaitTimeForConversation(conversationId:completion:)","navigatorTitle":[{"kind":"identifier","text":"fetchWaitTimeForConversationWithConversationId:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fetchWaitTimeForConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"WaitTimeData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","kind":"symbol","role":"symbol","abstract":[{"type":"codeVoice","code":"ConversationKitObjC"},{"type":"text","text":" needs to be configured  with a "},{"type":"codeVoice","code":"Config"},{"text":" ","type":"text"},{"text":"that includes the necessary ","type":"text"},{"type":"codeVoice","code":"integrationId"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"integrationId","type":"codeVoice"},{"type":"text","text":" can be retrieved from the Native Messaging dashboard."}],"title":"ConversationKitObjC","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","navigatorTitle":[{"kind":"identifier","text":"ConversationKitObjC"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitObjC"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData":{"kind":"symbol","type":"topic","title":"WaitTimeData","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WaitTimeData"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","navigatorTitle":[{"text":"WaitTimeData","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/waittimedata"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","kind":"symbol","role":"collection","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"fetchWaitTimeForConversationWithConversationId:completion:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"fetchWaitTimeForConversationWithConversationId:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"fetchWaitTimeForConversationWithConversationId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"conversationId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(ZDKWaitTimeData *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData#*$objc(cs)NSError)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1fetchWaitTimeForConversation(conversationId:completion:)\/title","value":"fetchWaitTimeForConversationWithConversationId:completion:"},{"value":[{"kind":"text","text":"- "},{"text":"fetchWaitTimeForConversationWithConversationId:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1fetchWaitTimeForConversation(conversationId:completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title","value":"ZDKConversationKit","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKConversationKit"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/title","value":"ZDKWaitTimeData","op":"replace"},{"value":[{"text":"ZDKWaitTimeData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}