{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"user","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"user"},{"kind":"text","text":": "},{"text":"User","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKLoginResult(py)user","navigatorTitle":[{"text":"user","kind":"identifier"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult\/user","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"user"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","text":"User","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkloginresult\/user"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkloginresult\/user"]}],"abstract":[{"type":"text","text":"The "},{"code":"User","type":"codeVoice"},{"type":"text","text":" object if authentication was successful."}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKLoginResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKLoginResult","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKLoginResult","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"ZDKLoginResult","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult","url":"\/documentation\/zendesksdkconversationkit\/zdkloginresult","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKLoginResult/user":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"user","kind":"identifier"},{"kind":"text","text":": "},{"text":"User","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"user","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"User","type":"codeVoice"},{"text":" object if authentication was successful.","type":"text"}],"title":"user","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult\/user","url":"\/documentation\/zendesksdkconversationkit\/zdkloginresult\/user","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User":{"title":"User","navigatorTitle":[{"text":"User","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"User","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"user"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"user","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","text":"ZDKUser","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"user","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKLoginResult","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult\/title"},{"op":"replace","value":[{"text":"ZDKLoginResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult~1user\/title","op":"replace","value":"user"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult~1user\/fragments","value":[{"kind":"identifier","text":"user"}],"op":"replace"},{"value":"ZDKUser","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/title","op":"replace"},{"value":[{"text":"ZDKUser","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/fragments"}]}]}