{"kind":"symbol","sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType"}],"title":"type","modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKFormResponseMessageContent(py)type"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/type"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The type  of the "},{"type":"codeVoice","code":"Message"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","kind":"typeIdentifier","text":"MessageType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent\/type"]},{"paths":["\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType":{"navigatorTitle":[{"kind":"identifier","text":"MessageType"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","title":"MessageType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageType"}],"abstract":[{"type":"text","text":"Represents the different "},{"type":"codeVoice","code":"Message"},{"text":" types in a ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messagetype"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent/type":{"kind":"symbol","title":"type","navigatorTitle":[{"text":"type","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent\/type","type":"topic","abstract":[{"text":"The type  of the ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","kind":"typeIdentifier","text":"MessageType"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/type","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent":{"navigatorTitle":[{"kind":"identifier","text":"FormResponseMessageContent"}],"url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent","type":"topic","title":"FormResponseMessageContent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseMessageContent","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent","abstract":[{"code":"FormResponse","type":"codeVoice"},{"type":"text","text":" related "},{"type":"codeVoice","code":"MessageContent"},{"type":"text","text":". Used to display a submitted form."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"type","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"type"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"ZDKMessageType"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKMessageType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/title","op":"replace"},{"value":[{"text":"ZDKMessageType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/title","value":"ZDKFormResponseMessageContent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/fragments","op":"replace","value":[{"text":"ZDKFormResponseMessageContent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}