{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"hash","symbolKind":"property","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWebViewAction(py)hash","modules":[{"name":"ZendeskSDKConversationKit"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWebViewAction\/hash","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkwebviewaction\/hash"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkwebviewaction\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction":{"title":"WebViewAction","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WebViewAction"}],"navigatorTitle":[{"kind":"identifier","text":"WebViewAction"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewaction","abstract":[],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKWebViewAction/hash":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWebViewAction\/hash","url":"\/documentation\/zendesksdkconversationkit\/zdkwebviewaction\/hash","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"hash"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hash"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"ZDKWebViewAction","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction\/fragments","value":[{"text":"ZDKWebViewAction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWebViewAction~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWebViewAction~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}