{"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKImageMessageContent(py)type","navigatorTitle":[{"text":"type","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"property","role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ImageMessageContent"]]},"sections":[],"abstract":[{"text":"The type of the ","type":"text"},{"type":"codeVoice","code":"Message"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkimagemessagecontent\/type"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkimagemessagecontent\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKImageMessageContent\/type","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKImageMessageContent/type":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"title":"type","abstract":[{"type":"text","text":"The type of the "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKImageMessageContent\/type","kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkimagemessagecontent\/type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ImageMessageContent":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ImageMessageContent","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageMessageContent"}],"kind":"symbol","abstract":[],"title":"ImageMessageContent","role":"symbol","navigatorTitle":[{"text":"ImageMessageContent","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/imagemessagecontent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType":{"navigatorTitle":[{"kind":"identifier","text":"MessageType"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","title":"MessageType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageType"}],"abstract":[{"type":"text","text":"Represents the different "},{"type":"codeVoice","code":"Message"},{"text":" types in a ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messagetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"type","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","kind":"typeIdentifier","text":"ZDKMessageType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKImageMessageContent~1type\/title","op":"replace","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKImageMessageContent~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ImageMessageContent\/title","value":"ZDKImageMessageContent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ImageMessageContent\/fragments","op":"replace","value":[{"text":"ZDKImageMessageContent","kind":"identifier"}]},{"op":"replace","value":"ZDKMessageType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/fragments","value":[{"kind":"identifier","text":"ZDKMessageType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}