{"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/persisteduserretrieved"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/persisteduserretrieved"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"case","title":"ZDKConversationKitEvent.persistedUserRetrieved","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"persistedUserRetrieved"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventPersistedUserRetrieved","role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventPersistedUserRetrieved"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"persistedUserRetrieved"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/persistedUserRetrieved","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"code":"User","type":"codeVoice"},{"text":" has been retrieved from storage.","type":"text"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"abstract":[{"text":"List of events that covers all events that could come from ","type":"text"},{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","kind":"symbol","navigatorTitle":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"title":"ZDKConversationKitEvent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/persistedUserRetrieved":{"abstract":[{"text":"The ","type":"text"},{"code":"User","type":"codeVoice"},{"type":"text","text":" has been retrieved from storage."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/persistedUserRetrieved","title":"ZDKConversationKitEvent.persistedUserRetrieved","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"persistedUserRetrieved","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ZDKConversationKitEventPersistedUserRetrieved","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/persisteduserretrieved"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKConversationKitEventPersistedUserRetrieved","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"ZDKConversationKitEventPersistedUserRetrieved"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKConversationKitEventPersistedUserRetrieved"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","op":"replace","value":"ZDKConversationKitEvent"},{"value":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments"},{"value":"ZDKConversationKitEventPersistedUserRetrieved","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1persistedUserRetrieved\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1persistedUserRetrieved\/fragments","op":"replace","value":[{"text":"ZDKConversationKitEventPersistedUserRetrieved","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}