{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/locationRequest","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationRequest"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType"]]},"metadata":{"role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType@ZDKActionTypeLocationRequest","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationRequest"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"ActionType.locationRequest","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypeLocationRequest"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"An action to request a location."}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/actiontype\/locationrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/actiontype\/locationrequest"]}],"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/locationRequest":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/locationRequest","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/actiontype\/locationrequest","abstract":[{"text":"An action to request a location.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypeLocationRequest"}],"title":"ActionType.locationRequest","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationRequest","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionType","kind":"identifier"}],"navigatorTitle":[{"text":"ActionType","kind":"identifier"}],"title":"ActionType","url":"\/documentation\/zendesksdkconversationkit\/actiontype"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKActionTypeLocationRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKActionTypeLocationRequest","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"ZDKActionTypeLocationRequest","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1locationRequest\/title","value":"ZDKActionTypeLocationRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1locationRequest\/fragments","value":[{"kind":"identifier","text":"ZDKActionTypeLocationRequest"}],"op":"replace"},{"op":"replace","value":"ZDKActionType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/fragments","value":[{"kind":"identifier","text":"ZDKActionType"}]}]}]}