{"metadata":{"roleHeading":"Instance Method","extendedModule":"ZendeskSDKConversationKit","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearConversationFields","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"s:25ZendeskSDKConversationKit012ConversationC0PAAE05clearD6FieldsyyF","title":"clearConversationFields()"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/clearConversationFields()-5php8"],["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationFields()-xjsp"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearConversationFields"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationfields()-y6gd"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationFields()-y6gd","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/clearConversationFields()-5php8":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/clearConversationFields()-5php8","title":"clearConversationFields()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearConversationFields"},{"text":"()","kind":"text"}],"defaultImplementations":1,"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Clear all custom fields from storage."}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/clearconversationfields()-5php8","required":true,"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"kind":"symbol","type":"topic","title":"ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"text":" needs to be configured  with ","type":"text"},{"type":"codeVoice","code":"SettingsParameters"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"ConversationKitSettings"},{"type":"text","text":", "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"type":"text","text":" "},{"text":"and ","type":"text"},{"code":"DispatchQueue","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"code":"DefaultConversationKit","type":"codeVoice"},{"type":"text","text":"’s initializer will create the App "},{"code":"AccessLevel","type":"codeVoice"},{"text":" and will check for a persisted user.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKit"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkit","role":"symbol","navigatorTitle":[{"text":"ConversationKit","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearConversationFields()-xjsp":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearConversationFields","kind":"identifier"},{"text":"()","kind":"text"}],"required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearConversationFields"}],"kind":"symbol","abstract":[{"type":"text","text":"Clears all fields from storage."}],"defaultImplementations":1,"title":"clearConversationFields()","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationFields()-xjsp","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationfields()-xjsp","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearConversationFields()-y6gd":{"title":"clearConversationFields()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearConversationFields","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationfields()-y6gd","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationFields()-y6gd"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitShared"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationKitShared"}],"type":"topic","title":"ConversationKitShared"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearConversationFields()-xjsp\/title","value":"clearConversationFields","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"clearConversationFields","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearConversationFields()-xjsp\/fragments"},{"op":"replace","value":"ConversationKitShared","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","value":[{"kind":"identifier","text":"ConversationKitShared"}]}]}]}