{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-80ytw"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc"]]},"metadata":{"title":"proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","externalID":"s:25ZendeskSDKConversationKit012ConversationC0PAAE29proactiveMessageStatusChanged_0eF03jwtyAA09ProactivefG0O_AA0jF0CSSSgtF","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"proactiveMessageStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","text":"ProactiveMessageStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"proactiveMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","kind":"typeIdentifier","text":"ProactiveMessage"},{"kind":"text","text":", "},{"text":"jwt","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"extendedModule":"ZendeskSDKConversationKit"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)-80ytw"]}],"abstract":[{"type":"text","text":"Processes a "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":" status change."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageStatusChanged"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"status"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","text":"ProactiveMessageStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"proactiveMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","text":"ProactiveMessage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"jwt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"status","content":[{"inlineContent":[{"type":"text","text":"The current status of a "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"proactiveMessage","content":[{"inlineContent":[{"text":"The current ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"jwt"},{"type":"text","text":" that represents the content of a "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":"."}]}],"name":"jwt"}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-80ytw":{"title":"proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"proactiveMessageStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","kind":"typeIdentifier","text":"ProactiveMessageStatus"},{"text":", ","kind":"text"},{"text":"proactiveMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","kind":"typeIdentifier","text":"ProactiveMessage"},{"text":", ","kind":"text"},{"text":"jwt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Processes a "},{"code":"ProactiveMessage","type":"codeVoice"},{"text":" status change.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-80ytw","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)-80ytw","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageStatusChanged"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","text":"ProactiveMessageStatus","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"proactiveMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ProactiveMessage","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"},{"text":", ","kind":"text"},{"text":"jwt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"required":true,"type":"topic","navigatorTitle":[{"text":"proactiveMessageStatusChanged:proactiveMessage:jwt:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Processes a "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":" status change."}],"defaultImplementations":1,"title":"proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)-4ctcc","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus":{"title":"ProactiveMessageStatus","navigatorTitle":[{"text":"ProactiveMessageStatus","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus","abstract":[{"type":"text","text":"Status that compliments a "},{"code":"ProactiveMessageStatusChanged","type":"codeVoice"},{"text":" event in ","type":"text"},{"code":"ConversationKitEvent","type":"codeVoice"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProactiveMessageStatus"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitShared"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationKitShared"}],"type":"topic","title":"ConversationKitShared"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessage":{"title":"ProactiveMessage","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProactiveMessage"}],"url":"\/documentation\/zendesksdkconversationkit\/proactivemessage","navigatorTitle":[{"kind":"identifier","text":"ProactiveMessage"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"proactiveMessageStatusChanged:proactiveMessage:jwt:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc\/fragments","value":[{"text":"- ","kind":"text"},{"text":"proactiveMessageStatusChanged:proactiveMessage:jwt:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/title","value":"ZDKProactiveMessageStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/fragments","op":"replace","value":[{"text":"ZDKProactiveMessageStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared","op":"replace"},{"value":[{"text":"ConversationKitShared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/title","value":"ZDKProactiveMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/fragments","value":[{"text":"ZDKProactiveMessage","kind":"identifier"}],"op":"replace"}]}]}