{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setConversationTags"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"setConversationTags:"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)setConversationTags:","title":"setConversationTags(_:)","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setConversationTags","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"tags","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"tags","content":[{"inlineContent":[{"type":"text","text":"The dictionary of custom tags to be provided."}],"type":"paragraph"}]}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"content":[{"inlineContent":[{"type":"text","text":"Strings, numbers and booleans are the only supported value types that can be passed."}],"type":"paragraph"}],"type":"aside","style":"note","name":"Note"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)-4nfxc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)-4nfxc"],"traits":[{"interfaceLanguage":"occ"}]}],"defaultImplementationsSections":[{"title":"ConversationKitShared Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)-6c0gj"]}],"kind":"symbol","abstract":[{"type":"text","text":"Provide an array of custom fields."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)-4nfxc","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/setConversationTags(_:)-6c0gj":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)-6c0gj","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)-6c0gj","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConversationTags","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"title":"setConversationTags(_:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitShared"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationKitShared"}],"type":"topic","title":"ConversationKitShared"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/setConversationTags(_:)-4nfxc":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setConversationTags"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}],"required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setConversationTags:"}],"kind":"symbol","abstract":[{"type":"text","text":"Provide an array of custom fields."}],"defaultImplementations":1,"title":"setConversationTags(_:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)-4nfxc","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)-4nfxc","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"setConversationTags:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setConversationTags:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setConversationTags:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tags"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","op":"replace","value":[{"text":"ConversationKitShared","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationTags(_:)-4nfxc\/title","value":"setConversationTags:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationTags(_:)-4nfxc\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setConversationTags:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}