{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageActions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction","text":"MessageAction","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/messageActions"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/textmessagecontent\/messageactions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/textmessagecontent\/messageactions"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageActions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MessageAction","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"messageActions","kind":"identifier"}],"title":"messageActions","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKTextMessageContent(py)messageActions"},"abstract":[{"text":"Any actions associated with the message","type":"text"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent":{"title":"TextMessageContent","url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent","kind":"symbol","abstract":[{"type":"text","text":"Text related "},{"code":"MessageContent","type":"codeVoice"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextMessageContent"}],"navigatorTitle":[{"kind":"identifier","text":"TextMessageContent"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent/messageActions":{"url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent\/messageactions","abstract":[{"type":"text","text":"Any actions associated with the message"}],"kind":"symbol","type":"topic","title":"messageActions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageActions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction","kind":"typeIdentifier","text":"MessageAction"},{"kind":"text","text":"]?"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/messageActions","navigatorTitle":[{"kind":"identifier","text":"messageActions"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageAction":{"url":"\/documentation\/zendesksdkconversationkit\/messageaction","role":"symbol","kind":"symbol","title":"MessageAction","abstract":[],"navigatorTitle":[{"text":"MessageAction","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageAction","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"messageActions"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"messageActions"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<ZDKMessageAction>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"messageActions"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/title","op":"replace","value":"ZDKTextMessageContent"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKTextMessageContent"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/navigatorTitle","op":"replace","value":[{"text":"ZDKTextMessageContent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent~1messageActions\/title","op":"replace","value":"messageActions"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent~1messageActions\/fragments","op":"replace","value":[{"text":"messageActions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/title","op":"replace","value":"ZDKMessageAction"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKMessageAction"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKMessageAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}