{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/isEqual(_:)"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"the object to compare against","type":"text"}]}],"name":"object"}]}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKTextMessageContent(im)isEqual:","symbolKind":"method","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/textmessagecontent\/isequal(_:)"]},{"paths":["\/documentation\/zendesksdkconversationkit\/textmessagecontent\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent/isEqual(_:)":{"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent\/isequal(_:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/isEqual(_:)","title":"isEqual(_:)","role":"symbol","kind":"symbol","abstract":[{"text":"Returns a Boolean value that indicates whether the receiver and a given object are equal.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent":{"abstract":[{"text":"Text related ","type":"text"},{"code":"MessageContent","type":"codeVoice"}],"role":"symbol","type":"topic","title":"TextMessageContent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextMessageContent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextMessageContent"}],"url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"isEqual:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent~1isEqual(_:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent~1isEqual(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/title","value":"ZDKTextMessageContent","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKTextMessageContent"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}