{"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"clearProactiveMessages(proactiveMessageIds:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearProactiveMessages","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)clearProactiveMessagesWithProactiveMessageIds:","navigatorTitle":[{"text":"clearProactiveMessagesWithProactiveMessageIds:","kind":"identifier"}]},"abstract":[{"text":"Call to delete proactive messages data from storage","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearProactiveMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"proactiveMessageIds"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"proactiveMessageIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ids of the proactive message concerned"}]}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)","interfaceLanguage":"swift"},"defaultImplementationsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-63emt"],"anchor":"ConversationKitShared-Implementations","title":"ConversationKitShared Implementations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearProactiveMessages(proactiveMessageIds:)":{"kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)","abstract":[{"text":"Call to delete proactive messages data from storage","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearProactiveMessages","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"clearProactiveMessagesWithProactiveMessageIds:","kind":"identifier"}],"defaultImplementations":1,"title":"clearProactiveMessages(proactiveMessageIds:)","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","title":"ConversationKitShared","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitShared","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearProactiveMessages(proactiveMessageIds:)-63emt":{"type":"topic","abstract":[{"text":"Call to delete proactive messages data from storage","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-63emt","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)-63emt","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearProactiveMessages","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"clearProactiveMessages(proactiveMessageIds:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clearProactiveMessagesWithProactiveMessageIds:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearProactiveMessagesWithProactiveMessageIds:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearProactiveMessagesWithProactiveMessageIds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"proactiveMessageIds"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ids of the proactive message concerned"}]}],"name":"proactiveMessageIds"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearProactiveMessages(proactiveMessageIds:)\/title","value":"clearProactiveMessagesWithProactiveMessageIds:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearProactiveMessages(proactiveMessageIds:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clearProactiveMessagesWithProactiveMessageIds:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","value":[{"kind":"identifier","text":"ConversationKitShared"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationKitShared"}]}]}]}