{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"defaultImplementationsSections":[{"title":"ConversationKitShared Implementations","anchor":"ConversationKitShared-Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-80ytw"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","text":"ProactiveMessageStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"proactiveMessage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","kind":"typeIdentifier","text":"ProactiveMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jwt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"status","content":[{"inlineContent":[{"type":"text","text":"The current status of a "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"proactiveMessage","content":[{"type":"paragraph","inlineContent":[{"text":"The current ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"text":".","type":"text"}]}]},{"name":"jwt","content":[{"inlineContent":[{"text":"","type":"text"},{"code":"jwt","type":"codeVoice"},{"text":" that represents the content of a ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)"},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","text":"ProactiveMessageStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"proactiveMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","text":"ProactiveMessage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"jwt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"proactiveMessageStatusChanged:proactiveMessage:jwt:"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)proactiveMessageStatusChanged:proactiveMessage:jwt:","required":true,"symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Processes a ","type":"text"},{"type":"codeVoice","code":"ProactiveMessage"},{"text":" status change.","type":"text"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessageStatus","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","abstract":[{"text":"Status that compliments a ","type":"text"},{"type":"codeVoice","code":"ProactiveMessageStatusChanged"},{"text":" event in ","type":"text"},{"type":"codeVoice","code":"ConversationKitEvent"}],"url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus","kind":"symbol","type":"topic","title":"ProactiveMessageStatus","role":"symbol","navigatorTitle":[{"text":"ProactiveMessageStatus","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessage":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","url":"\/documentation\/zendesksdkconversationkit\/proactivemessage","abstract":[],"title":"ProactiveMessage","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessage","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ProactiveMessage","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-80ytw":{"role":"symbol","title":"proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","abstract":[{"type":"text","text":"Processes a "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":" status change."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageStatusChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ProactiveMessageStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"proactiveMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProactiveMessage","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jwt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-80ytw","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)-80ytw"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","title":"ConversationKitShared","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitShared","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessageStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ProactiveMessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus"},{"text":", ","kind":"text"},{"text":"proactiveMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ProactiveMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"},{"text":", ","kind":"text"},{"text":"jwt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"defaultImplementations":1,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"proactiveMessageStatusChanged:proactiveMessage:jwt:"}],"abstract":[{"text":"Processes a ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"text":" status change.","type":"text"}],"kind":"symbol","title":"proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","required":true,"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"proactiveMessageStatusChanged:proactiveMessage:jwt:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"proactiveMessageStatusChanged:proactiveMessage:jwt:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"proactiveMessageStatusChanged:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","text":"ZDKProactiveMessageStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKProactiveMessage","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"proactiveMessage"},{"kind":"text","text":" "},{"kind":"identifier","text":"jwt:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"jwt"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"status","content":[{"inlineContent":[{"text":"The current status of a ","type":"text"},{"type":"codeVoice","code":"ProactiveMessage"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"proactiveMessage","content":[{"inlineContent":[{"type":"text","text":"The current "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"jwt","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"jwt","type":"codeVoice"},{"text":" that represents the content of a ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"text":".","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"ZDKProactiveMessageStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/title"},{"value":[{"text":"ZDKProactiveMessageStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/fragments"},{"value":[{"text":"ZDKProactiveMessageStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/navigatorTitle"},{"value":"ZDKProactiveMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/title"},{"value":[{"kind":"identifier","text":"ZDKProactiveMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/fragments"},{"value":[{"text":"ZDKProactiveMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/navigatorTitle"},{"value":"ConversationKitShared","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title"},{"value":[{"text":"ConversationKitShared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments"},{"value":[{"kind":"identifier","text":"ConversationKitShared"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/navigatorTitle"},{"value":"proactiveMessageStatusChanged:proactiveMessage:jwt:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1proactiveMessageStatusChanged(_:proactiveMessage:jwt:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"proactiveMessageStatusChanged:proactiveMessage:jwt:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1proactiveMessageStatusChanged(_:proactiveMessage:jwt:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}