{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConversationTags"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tags"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"tags","content":[{"type":"paragraph","inlineContent":[{"text":"The dictionary of custom tags to be provided.","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Strings, numbers and booleans are the only supported value types that can be passed."}],"type":"paragraph"}]}]}],"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"method","required":true,"navigatorTitle":[{"kind":"identifier","text":"setConversationTags:"}],"title":"setConversationTags(_:)","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)setConversationTags:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConversationTags"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"])"}],"roleHeading":"Instance Method","role":"symbol"},"kind":"symbol","sections":[],"abstract":[{"text":"Provide an array of custom fields.","type":"text"}],"defaultImplementationsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/setConversationTags(_:)-6c0gj"],"title":"ConversationKit Implementations","anchor":"ConversationKit-Implementations"}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/setConversationTags(_:)":{"type":"topic","abstract":[{"type":"text","text":"Provide an array of custom fields."}],"navigatorTitle":[{"kind":"identifier","text":"setConversationTags:"}],"required":true,"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)","defaultImplementations":1,"title":"setConversationTags(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConversationTags"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","title":"ConversationKitShared","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitShared","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/setConversationTags(_:)-6c0gj":{"title":"setConversationTags(_:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/setConversationTags(_:)-6c0gj","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/setconversationtags(_:)-6c0gj","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConversationTags","kind":"identifier"},{"text":"([","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setConversationTags:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setConversationTags:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setConversationTags:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tags"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"tags","content":[{"type":"paragraph","inlineContent":[{"text":"The dictionary of custom tags to be provided.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"setConversationTags:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationTags(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setConversationTags:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationTags(_:)\/fragments"},{"op":"replace","value":"ConversationKitShared","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ConversationKitShared"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ConversationKitShared"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/navigatorTitle"}]}]}