{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"abstract":[{"type":"text","text":"Call to stop polling for updates to conversation wait time."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopFetchingWaitTime"},{"kind":"text","text":"()"}]}]}],"defaultImplementationsSections":[{"title":"ConversationKitShared Implementations","anchor":"ConversationKitShared-Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/stopFetchingWaitTime()-2ovyu"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/stopfetchingwaittime()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/stopfetchingwaittime()"]}],"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"stopFetchingWaitTime","kind":"identifier"}],"roleHeading":"Instance Method","required":true,"title":"stopFetchingWaitTime()","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)stopFetchingWaitTime","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopFetchingWaitTime","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"ZendeskSDKConversationKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/stopFetchingWaitTime()"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","title":"ConversationKitShared","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitShared","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/stopFetchingWaitTime()-2ovyu":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/stopFetchingWaitTime()-2ovyu","title":"stopFetchingWaitTime()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopFetchingWaitTime"},{"kind":"text","text":"()"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/stopfetchingwaittime()-2ovyu","role":"symbol","type":"topic","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/stopFetchingWaitTime()":{"role":"symbol","title":"stopFetchingWaitTime()","navigatorTitle":[{"text":"stopFetchingWaitTime","kind":"identifier"}],"abstract":[{"text":"Call to stop polling for updates to conversation wait time.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/stopFetchingWaitTime()","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/stopfetchingwaittime()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopFetchingWaitTime","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","defaultImplementations":1}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"stopFetchingWaitTime"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopFetchingWaitTime","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopFetchingWaitTime"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","op":"replace","value":"ConversationKitShared"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","op":"replace","value":[{"text":"ConversationKitShared","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/navigatorTitle","op":"replace","value":[{"text":"ConversationKitShared","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1stopFetchingWaitTime()\/title","op":"replace","value":"stopFetchingWaitTime"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1stopFetchingWaitTime()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopFetchingWaitTime","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}