{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/postback","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An action to send a postback to the server."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"postback"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType@ZDKActionTypePostback","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postback","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKActionTypePostback","kind":"identifier"}],"role":"symbol","title":"ActionType.postback"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/actiontype\/postback"]},{"paths":["\/documentation\/zendesksdkconversationkit\/actiontype\/postback"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/postback":{"url":"\/documentation\/zendesksdkconversationkit\/actiontype\/postback","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"postback"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/postback","title":"ActionType.postback","navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypePostback"}],"abstract":[{"type":"text","text":"An action to send a postback to the server."}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType":{"role":"symbol","title":"ActionType","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ActionType"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","url":"\/documentation\/zendesksdkconversationkit\/actiontype"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKActionTypePostback","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"ZDKActionTypePostback","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKActionTypePostback"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1postback\/title","value":"ZDKActionTypePostback"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1postback\/fragments","value":[{"text":"ZDKActionTypePostback","kind":"identifier"}],"op":"replace"},{"value":"ZDKActionType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/fragments","value":[{"kind":"identifier","text":"ZDKActionType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}