{"metadata":{"symbolKind":"property","title":"subroles","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subroles","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"subroles"}],"role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthor(py)subroles","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"subroles","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkauthor\/subroles"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkauthor\/subroles"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKAuthor\/subroles","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"List of subroles associated with an author. Initially added to indicate if the message was generated by A.I."},{"text":" ","type":"text"},{"type":"text","text":"Note: The use of [String] instead of [Subroles] is for compatibility with Objective-C."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Author"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Author":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Author","url":"\/documentation\/zendesksdkconversationkit\/author","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Author","kind":"identifier"}],"title":"Author","navigatorTitle":[{"text":"Author","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKAuthor/subroles":{"url":"\/documentation\/zendesksdkconversationkit\/zdkauthor\/subroles","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKAuthor\/subroles","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"List of subroles associated with an author. Initially added to indicate if the message was generated by A.I."},{"text":" ","type":"text"},{"type":"text","text":"Note: The use of [String] instead of [Subroles] is for compatibility with Objective-C."}],"title":"subroles","navigatorTitle":[{"text":"subroles","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subroles"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"subroles"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"subroles","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"subroles"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKAuthor","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Author\/title","op":"replace"},{"value":[{"text":"ZDKAuthor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Author\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKAuthor~1subroles\/title","value":"subroles","op":"replace"},{"value":[{"kind":"identifier","text":"subroles"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKAuthor~1subroles\/fragments"}]}]}