{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent"]]},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdktextmessagecontent\/text"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdktextmessagecontent\/text"]}],"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKTextMessageContent(py)text","modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"text","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property","title":"text"},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/text","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The text of the "},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKTextMessageContent/text":{"role":"symbol","abstract":[{"type":"text","text":"The text of the "},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/text","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdktextmessagecontent\/text","navigatorTitle":[{"text":"text","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"text","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","title":"text"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent":{"role":"symbol","abstract":[{"type":"text","text":"Text related "},{"code":"MessageContent","type":"codeVoice"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent","url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent","navigatorTitle":[{"text":"TextMessageContent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextMessageContent","kind":"identifier"}],"type":"topic","title":"TextMessageContent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"text"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"text"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"text","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1text\/title","value":"text"},{"value":[{"text":"text","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1text\/fragments"},{"op":"replace","value":"ZDKTextMessageContent","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKTextMessageContent"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/fragments"}]}]}