{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationroutingstatus\/cleared"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationroutingstatus\/cleared"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus\/cleared"},"metadata":{"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cleared","kind":"identifier"}],"title":"ConversationRoutingStatus.cleared","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationRoutingStatusCleared"}],"roleHeading":"Case","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationRoutingStatus@ZDKConversationRoutingStatusCleared"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cleared","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationRoutingStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRoutingStatus"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus","title":"ConversationRoutingStatus","abstract":[{"text":"Represents the possible types of ","type":"text"},{"type":"codeVoice","code":"routingStatus"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationRoutingStatus"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationroutingstatus"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationRoutingStatus/cleared":{"url":"\/documentation\/zendesksdkconversationkit\/conversationroutingstatus\/cleared","title":"ConversationRoutingStatus.cleared","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationRoutingStatusCleared"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus\/cleared","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cleared","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKConversationRoutingStatusCleared"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKConversationRoutingStatusCleared","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKConversationRoutingStatusCleared"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus\/title","value":"ZDKConversationRoutingStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus\/fragments","value":[{"text":"ZDKConversationRoutingStatus","kind":"identifier"}]},{"value":"ZDKConversationRoutingStatusCleared","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus~1cleared\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus~1cleared\/fragments","value":[{"text":"ZDKConversationRoutingStatusCleared","kind":"identifier"}],"op":"replace"}]}]}