{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKSelectFormField\/select","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkselectformfield\/select"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkselectformfield\/select"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"select","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Option","text":"Option","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKOption"},{"kind":"text","text":"]?"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"select"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKSelectFormField(py)select","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"select"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKOption","kind":"typeIdentifier","text":"Option"},{"kind":"text","text":"]?"}],"symbolKind":"property","title":"select"},"abstract":[{"type":"text","text":"The subset of "},{"type":"codeVoice","code":"options"},{"type":"text","text":" that were chosen by the user"}],"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SelectFormField":{"url":"\/documentation\/zendesksdkconversationkit\/selectformfield","navigatorTitle":[{"text":"SelectFormField","kind":"identifier"}],"title":"SelectFormField","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Form Field that takes in generic user input","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SelectFormField"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKSelectFormField/select":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"select","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKOption","text":"Option","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"title":"select","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkselectformfield\/select","navigatorTitle":[{"text":"select","kind":"identifier"}],"abstract":[{"type":"text","text":"The subset of "},{"type":"codeVoice","code":"options"},{"type":"text","text":" that were chosen by the user"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKSelectFormField\/select"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Option":{"title":"Option","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Option","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/option","navigatorTitle":[{"text":"Option","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"Option"},{"type":"text","text":" model used for"},{"code":"Form","type":"codeVoice"},{"type":"text","text":" "},{"type":"codeVoice","code":"Message"},{"type":"text","text":" types, when the input "},{"type":"codeVoice","code":"type"},{"type":"text","text":" is "},{"type":"codeVoice","code":"select"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Option"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"select","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"select"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSArray<ZDKOption *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"select","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"ZDKSelectFormField","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/title"},{"value":[{"kind":"identifier","text":"ZDKSelectFormField"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKSelectFormField~1select\/title","value":"select"},{"value":[{"text":"select","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKSelectFormField~1select\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Option\/title","value":"ZDKOption","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKOption"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Option\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}