{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType","kind":"typeIdentifier","text":"FieldType"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"type","kind":"identifier"}],"symbolKind":"property","title":"type","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKSelectFormField(py)type","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}]},"sections":[],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkselectformfield\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkselectformfield\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKSelectFormField\/type","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"text":"FieldType","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"The field type."}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FieldType":{"role":"symbol","title":"FieldType","navigatorTitle":[{"kind":"identifier","text":"FieldType"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","url":"\/documentation\/zendesksdkconversationkit\/fieldtype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FieldType"}],"type":"topic","abstract":[{"text":"Form field type. ","type":"text"},{"code":"text","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"email"},{"type":"text","text":", "},{"code":"select","type":"codeVoice"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKSelectFormField/type":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FieldType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType"}],"abstract":[{"type":"text","text":"The field type."}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkselectformfield\/type","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKSelectFormField\/type","kind":"symbol","title":"type","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SelectFormField":{"url":"\/documentation\/zendesksdkconversationkit\/selectformfield","navigatorTitle":[{"text":"SelectFormField","kind":"identifier"}],"title":"SelectFormField","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Form Field that takes in generic user input","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SelectFormField"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"type"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","text":"ZDKFieldType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"ZDKFieldType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/fragments","value":[{"text":"ZDKFieldType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKSelectFormField~1type\/title","value":"type"},{"value":[{"kind":"identifier","text":"type"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKSelectFormField~1type\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/title","value":"ZDKSelectFormField","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/fragments","value":[{"text":"ZDKSelectFormField","kind":"identifier"}],"op":"replace"}]}]}