{"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"kind":"identifier","text":"MessageStatus"}],"roleHeading":"Enumeration","title":"MessageStatus","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageStatus","kind":"identifier"}],"symbolKind":"enum"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/exceedsMaxFileSize","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/failed","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/failedAttachmentNotSupported","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/pending","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/sent"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/isFailed"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/Equatable-Implementations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH","doc:\/\/com.zendesk.ConversationKit\/SY"],"kind":"relationships"}],"abstract":[{"text":"Represents the status of the ","type":"text"},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKMessageStatus) "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageStatus"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/messagestatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/messagestatus"]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/sent":{"type":"topic","role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"Message"},{"text":" has been sent to the server successfully.","type":"text"}],"title":"MessageStatus.sent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/sent","url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/sent","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sent"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKMessageStatusSent"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/failedAttachmentNotSupported":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedAttachmentNotSupported"}],"url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/failedattachmentnotsupported","abstract":[{"text":"An attempt was made to send the ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":" to the server but it failed because it is an unsupported file type.","type":"text"}],"title":"MessageStatus.failedAttachmentNotSupported","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/failedAttachmentNotSupported","navigatorTitle":[{"kind":"identifier","text":"ZDKMessageStatusFailedAttachmentNotSupported"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/pending":{"type":"topic","role":"symbol","title":"MessageStatus.pending","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Message"},{"text":" has not yet been sent to the server.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/pending","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/pending","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pending"}],"kind":"symbol","navigatorTitle":[{"text":"ZDKMessageStatusPending","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/rawrepresentable-implementations","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/failed":{"type":"topic","role":"symbol","abstract":[{"text":"An attempt was made to send the ","type":"text"},{"type":"codeVoice","code":"Message"},{"text":" to the server but it failed.","type":"text"}],"title":"MessageStatus.failed","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/failed","url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/failed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKMessageStatusFailed"}]},"doc://com.zendesk.ConversationKit/Se":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","title":"Swift.Decodable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/init(rawValue:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/init(rawvalue:)","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/Equatable-Implementations":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/Equatable-Implementations","abstract":[],"type":"topic","title":"Equatable Implementations","url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/equatable-implementations","role":"collectionGroup","kind":"article"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/exceedsMaxFileSize":{"title":"MessageStatus.exceedsMaxFileSize","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/exceedsMaxFileSize","navigatorTitle":[{"text":"ZDKMessageStatusExceedsMaxFileSize","kind":"identifier"}],"abstract":[{"type":"text","text":"An attempt was made to send the "},{"type":"codeVoice","code":"Message"},{"text":" to the server but it failed because the file size exceeds the max file size.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"exceedsMaxFileSize","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/exceedsmaxfilesize","kind":"symbol"},"doc://com.zendesk.ConversationKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus":{"url":"\/documentation\/zendesksdkconversationkit\/messagestatus","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageStatus"}],"role":"symbol","title":"MessageStatus","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus","abstract":[{"text":"Represents the status of the ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"MessageStatus","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/SE":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE","title":"Swift.Encodable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/description":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/description","title":"description","abstract":[{"type":"text","text":"String representation of the associated "},{"code":"MessageStatus","type":"codeVoice"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/description","kind":"symbol"},"doc://com.zendesk.ConversationKit/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SY","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/isFailed":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFailed","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/isFailed","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/isfailed","title":"isFailed","abstract":[{"text":"Returns a boolean indicating if the status is one of the failed types","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"i.e. "},{"code":"failed","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"failedAttachmentNotSupported"},{"text":" or ","type":"text"},{"code":"exceedsMaxFileSize","type":"codeVoice"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKMessageStatus"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKMessageStatus"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKMessageStatus"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/exceedsMaxFileSize","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/failed","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/failedAttachmentNotSupported","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/pending","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/sent"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKMessageStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"ZDKMessageStatusSent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1sent\/title"},{"value":[{"text":"ZDKMessageStatusSent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1sent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1failedAttachmentNotSupported\/title","value":"ZDKMessageStatusFailedAttachmentNotSupported"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1failedAttachmentNotSupported\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKMessageStatusFailedAttachmentNotSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1pending\/title","value":"ZDKMessageStatusPending"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1pending\/fragments","value":[{"kind":"identifier","text":"ZDKMessageStatusPending"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1failed\/title","value":"ZDKMessageStatusFailed","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1failed\/fragments","op":"replace","value":[{"text":"ZDKMessageStatusFailed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1exceedsMaxFileSize\/title","value":"ZDKMessageStatusExceedsMaxFileSize"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1exceedsMaxFileSize\/fragments","value":[{"text":"ZDKMessageStatusExceedsMaxFileSize","kind":"identifier"}]},{"op":"replace","value":"ZDKMessageStatus","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus\/fragments","value":[{"kind":"identifier","text":"ZDKMessageStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}