{"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH","doc:\/\/com.zendesk.ConversationKit\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/conversationHasBeenRepliedTo","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationHasBeenClicked","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationHasBeenDisplayed","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationWillDisplay"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/Equatable-Implementations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKProactiveMessageStatus) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProactiveMessageStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus"},"metadata":{"roleHeading":"Enumeration","title":"ProactiveMessageStatus","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProactiveMessageStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ProactiveMessageStatus"}],"role":"symbol"},"abstract":[{"text":"Status that compliments a ","type":"text"},{"type":"codeVoice","code":"ProactiveMessageStatusChanged"},{"text":" event in ","type":"text"},{"type":"codeVoice","code":"ConversationKitEvent"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/proactivemessagestatus"]},{"paths":["\/documentation\/zendesksdkconversationkit\/proactivemessagestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus/notificationHasBeenClicked":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationHasBeenClicked","type":"topic","navigatorTitle":[{"text":"ZDKProactiveMessageStatusNotificationHasBeenClicked","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/notificationhasbeenclicked","title":"ProactiveMessageStatus.notificationHasBeenClicked","abstract":[{"text":"Invoked when a proactive message has been clicked on.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notificationHasBeenClicked"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus/init(rawValue:)":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/init(rawValue:)","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/init(rawvalue:)","title":"init(rawValue:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus":{"title":"ProactiveMessageStatus","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ProactiveMessageStatus","kind":"identifier"}],"navigatorTitle":[{"text":"ProactiveMessageStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Status that compliments a "},{"type":"codeVoice","code":"ProactiveMessageStatusChanged"},{"text":" event in ","type":"text"},{"type":"codeVoice","code":"ConversationKitEvent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","kind":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus/notificationHasBeenDisplayed":{"title":"ProactiveMessageStatus.notificationHasBeenDisplayed","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/notificationhasbeendisplayed","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notificationHasBeenDisplayed"}],"navigatorTitle":[{"text":"ZDKProactiveMessageStatusNotificationHasBeenDisplayed","kind":"identifier"}],"abstract":[{"text":"Invoked when a proactive message has been displayed as a local notification.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationHasBeenDisplayed","kind":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/equatable-implementations","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/Equatable-Implementations","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus/conversationHasBeenRepliedTo":{"title":"ProactiveMessageStatus.conversationHasBeenRepliedTo","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKProactiveMessageStatusConversationHasBeenRepliedTo","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/conversationhasbeenrepliedto","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"conversationHasBeenRepliedTo","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/conversationHasBeenRepliedTo","abstract":[{"type":"text","text":"Invoked when the first reply has been sent in a conversation opened through a proactive message."}]},"doc://com.zendesk.ConversationKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ"},"doc://com.zendesk.ConversationKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SY"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus/notificationWillDisplay":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationWillDisplay","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/notificationwilldisplay","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationWillDisplay"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Invoked when a proactive message will be displayed as a local notification.","type":"text"}],"navigatorTitle":[{"text":"ZDKProactiveMessageStatusNotificationWillDisplay","kind":"identifier"}],"title":"ProactiveMessageStatus.notificationWillDisplay"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/RawRepresentable-Implementations"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"ZDKProactiveMessageStatus","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKProactiveMessageStatus","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKProactiveMessageStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/conversationHasBeenRepliedTo","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationHasBeenClicked","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationHasBeenDisplayed","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/notificationWillDisplay"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKProactiveMessageStatus"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"ZDKProactiveMessageStatusNotificationHasBeenClicked","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1notificationHasBeenClicked\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatusNotificationHasBeenClicked"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1notificationHasBeenClicked\/fragments"},{"value":"ZDKProactiveMessageStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1notificationHasBeenDisplayed\/title","value":"ZDKProactiveMessageStatusNotificationHasBeenDisplayed"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1notificationHasBeenDisplayed\/fragments","op":"replace","value":[{"text":"ZDKProactiveMessageStatusNotificationHasBeenDisplayed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1conversationHasBeenRepliedTo\/title","op":"replace","value":"ZDKProactiveMessageStatusConversationHasBeenRepliedTo"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1conversationHasBeenRepliedTo\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatusConversationHasBeenRepliedTo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1notificationWillDisplay\/title","value":"ZDKProactiveMessageStatusNotificationWillDisplay"},{"op":"replace","value":[{"text":"ZDKProactiveMessageStatusNotificationWillDisplay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1notificationWillDisplay\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}