{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"init(appId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:)","role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"baseURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"integrationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"region"},{"kind":"text","text":": "},{"preciseIdentifier":"s:25ZendeskSDKConversationKit6ConfigC6RegionO","text":"Region","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"restRetryPolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RestRetryPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKRestRetryPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"waitTimeConfig"},{"text":": ","kind":"text"},{"text":"WaitTimeConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig"},{"kind":"text","text":")"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"init","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig(im)initWithAppId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:","navigatorTitle":[{"kind":"identifier","text":"initWithAppId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"baseURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"integrationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"region","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit6ConfigC6RegionO","text":"Region","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/Region-swift.enum"},{"kind":"text","text":" = .us, "},{"text":"restRetryPolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKRestRetryPolicy","text":"RestRetryPolicy","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RestRetryPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"waitTimeConfig"},{"text":": ","kind":"text"},{"text":"WaitTimeConfig","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique resource identifier for the app."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The server base url."}]}],"name":"baseURL"},{"name":"integrationId","content":[{"type":"paragraph","inlineContent":[{"text":"The iOS integration id for this SDK.","type":"text"}]}]},{"name":"region","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The region to connect to."}]}]},{"name":"restRetryPolicy","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"RestRetryPolicy"},{"text":" for requests made to Sunshine Conversations.","type":"text"}]}]},{"name":"waitTimeConfig","content":[{"type":"paragraph","inlineContent":[{"text":"The admin settings for queue position and wait time behaviour.","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/init(appId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/config\/init(appid:baseurl:integrationid:region:restretrypolicy:waittimeconfig:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/config\/init(appid:baseurl:integrationid:region:restretrypolicy:waittimeconfig:)"]}],"abstract":[{"text":"Initialize a ","type":"text"},{"type":"codeVoice","code":"Config"},{"text":" instance.","type":"text"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config/init(appId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:)":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithAppId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/config\/init(appid:baseurl:integrationid:region:restretrypolicy:waittimeconfig:)","title":"init(appId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:)","abstract":[{"type":"text","text":"Initialize a "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" instance."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"baseURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"integrationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"region"},{"kind":"text","text":": "},{"text":"Region","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit6ConfigC6RegionO"},{"text":", ","kind":"text"},{"text":"restRetryPolicy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RestRetryPolicy","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKRestRetryPolicy"},{"text":", ","kind":"text"},{"text":"waitTimeConfig","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig","kind":"typeIdentifier","text":"WaitTimeConfig"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/init(appId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:)","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config":{"url":"\/documentation\/zendesksdkconversationkit\/config","abstract":[],"kind":"symbol","title":"Config","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Config","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Config","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/RestRetryPolicy":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RestRetryPolicy"}],"url":"\/documentation\/zendesksdkconversationkit\/restretrypolicy","title":"RestRetryPolicy","abstract":[{"type":"text","text":"The retry policy used when making REST requests."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RestRetryPolicy"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RestRetryPolicy"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config/Region-swift.enum":{"title":"Config.Region","abstract":[{"type":"text","text":"The region used to connect to the server."}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/config\/region-swift.enum","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/Region-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Region","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Region"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKRegion":{"fragments":[{"text":"ZDKRegion","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkregion","kind":"symbol","title":"ZDKRegion","type":"topic","abstract":[{"text":"The region used to connect to the server.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKRegion"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeConfig":{"kind":"symbol","type":"topic","title":"WaitTimeConfig","role":"symbol","abstract":[{"text":"The wait time configuration. Contains config related to queue position and wait time behaviour.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig","url":"\/documentation\/zendesksdkconversationkit\/waittimeconfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WaitTimeConfig","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"WaitTimeConfig"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","role":"collection","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithAppId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAppId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"baseURL:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"baseURL","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"integrationId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"integrationId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"region:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKRegion","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKRegion","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKRegion"},{"kind":"text","text":") "},{"text":"region","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"restRetryPolicy:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKRestRetryPolicy","text":"ZDKRestRetryPolicy","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RestRetryPolicy"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"restRetryPolicy"},{"kind":"text","text":" "},{"text":"waitTimeConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig","text":"ZDKWaitTimeConfig","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"waitTimeConfig"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config~1init(appId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:)\/title","value":"initWithAppId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config~1init(appId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAppId:baseURL:integrationId:region:restRetryPolicy:waitTimeConfig:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/title","value":"ZDKConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/fragments","value":[{"text":"ZDKConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1RestRetryPolicy\/title","value":"ZDKRestRetryPolicy"},{"value":[{"text":"ZDKRestRetryPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1RestRetryPolicy\/fragments"},{"value":"ZDKWaitTimeConfig","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKWaitTimeConfig"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}