{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaURL"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageActionItem\/mediaURL","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem"]]},"metadata":{"symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessageActionItem(py)mediaURL","navigatorTitle":[{"text":"mediaURL","kind":"identifier"}],"roleHeading":"Instance Property","title":"mediaURL","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"sections":[],"abstract":[{"text":"The URL of the media to be displayed with this item.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkmessageactionitem\/mediaurl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkmessageactionitem\/mediaurl"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionItem":{"type":"topic","role":"symbol","title":"MessageActionItem","abstract":[{"type":"text","text":"An item in a list type message, such as list or carousel."}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionitem","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageActionItem","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageActionItem"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKMessageActionItem/mediaURL":{"kind":"symbol","title":"mediaURL","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageActionItem\/mediaURL","url":"\/documentation\/zendesksdkconversationkit\/zdkmessageactionitem\/mediaurl","abstract":[{"type":"text","text":"The URL of the media to be displayed with this item."}],"navigatorTitle":[{"text":"mediaURL","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"mediaURL"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"mediaURL","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mediaURL"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/title","op":"replace","value":"ZDKMessageActionItem"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/fragments","op":"replace","value":[{"text":"ZDKMessageActionItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessageActionItem~1mediaURL\/title","value":"mediaURL","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessageActionItem~1mediaURL\/fragments","op":"replace","value":[{"kind":"identifier","text":"mediaURL"}]}]}]}