{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/actiontype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/actiontype"]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Enumeration","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType","symbolKind":"enum","title":"ActionType","navigatorTitle":[{"kind":"identifier","text":"ActionType"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionType"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKActionType) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionType","kind":"identifier"}]}]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/buy","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/link","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/locationRequest","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/postback","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/reply","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/share","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/webview"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/Equatable-Implementations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH","doc:\/\/com.zendesk.ConversationKit\/SY"],"title":"Conforms To"}],"references":{"doc://com.zendesk.ConversationKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/webview":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/webview","abstract":[{"type":"text","text":"An action to open the associated URI in a WebView."}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"webview","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypeWebview"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype\/webview","title":"ActionType.webview","role":"symbol"},"doc://com.zendesk.ConversationKit/SY":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/link":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/link","abstract":[{"text":"An action with an associated URI.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"link","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKActionTypeLink","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype\/link","title":"ActionType.link","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/actiontype\/rawrepresentable-implementations","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/Equatable-Implementations":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/Equatable-Implementations","abstract":[],"kind":"article","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/actiontype\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/share":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/share","abstract":[{"type":"text","text":"An action to share."}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"share","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypeShare"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype\/share","title":"ActionType.share","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/buy":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/buy","abstract":[{"text":"An action to buy the ","type":"text"},{"code":"MessageActionItem","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buy","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypeBuy"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype\/buy","title":"ActionType.buy","role":"symbol"},"doc://com.zendesk.ConversationKit/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/reply":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/reply","abstract":[{"type":"text","text":"An action to send a quick reply to the conversation."}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reply","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypeReply"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype\/reply","title":"ActionType.reply","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType":{"navigatorTitle":[{"text":"ActionType","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ActionType","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","type":"topic","title":"ActionType"},"doc://com.zendesk.ConversationKit/SE":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE","title":"Swift.Encodable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/locationRequest":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/locationRequest","abstract":[{"type":"text","text":"An action to request a location."}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationRequest","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypeLocationRequest"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype\/locationrequest","title":"ActionType.locationRequest","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/postback":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/postback","abstract":[{"type":"text","text":"An action to send a postback to the server."}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypePostback"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype\/postback","title":"ActionType.postback","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/init(rawValue:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/init(rawValue:)","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol"},"doc://com.zendesk.ConversationKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"ZDKActionType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKActionType"}]},{"op":"replace","value":[{"text":"ZDKActionType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/buy","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/link","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/locationRequest","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/postback","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/reply","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/share","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/webview"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKActionType"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1webview\/title","value":"ZDKActionTypeWebview"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKActionTypeWebview"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1webview\/fragments"},{"value":"ZDKActionTypeLink","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1link\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1link\/fragments","value":[{"text":"ZDKActionTypeLink","kind":"identifier"}]},{"op":"replace","value":"ZDKActionTypeShare","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1share\/title"},{"value":[{"text":"ZDKActionTypeShare","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1share\/fragments"},{"op":"replace","value":"ZDKActionTypeBuy","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1buy\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1buy\/fragments","value":[{"kind":"identifier","text":"ZDKActionTypeBuy"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1reply\/title","op":"replace","value":"ZDKActionTypeReply"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1reply\/fragments","op":"replace","value":[{"text":"ZDKActionTypeReply","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/title","value":"ZDKActionType"},{"op":"replace","value":[{"text":"ZDKActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1locationRequest\/title","value":"ZDKActionTypeLocationRequest","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKActionTypeLocationRequest"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1locationRequest\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1postback\/title","value":"ZDKActionTypePostback"},{"value":[{"kind":"identifier","text":"ZDKActionTypePostback"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1postback\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}