{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/message"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/message"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Class","modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","title":"Message","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Message"}],"navigatorTitle":[{"text":"Message","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKMessage) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Message"}]}],"kind":"declarations"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(from:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(id:content:createdAt:receivedAt:status:author:sourceId:localId:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(mediaURL:text:metadata:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(text:payload:metadata:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/actions","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/author","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/content","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/createdAt","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/id","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/localId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageActions","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/receivedAt","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/sourceId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/status","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/timestamp"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/isAuthoredBy(_:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/isEqual(_:)"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/sourceId":{"navigatorTitle":[{"text":"sourceId","kind":"identifier"}],"abstract":[{"text":"The id of the client that the ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":" originated from."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/sourceId","role":"symbol","title":"sourceId","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/sourceid","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/isAuthoredBy(_:)":{"navigatorTitle":[{"kind":"identifier","text":"isAuthoredBy:"}],"abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if the message originated from given ","type":"text"},{"type":"codeVoice","code":"Participant"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/isAuthoredBy(_:)","role":"symbol","title":"isAuthoredBy(_:)","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/isauthoredby(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isAuthoredBy","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","text":"Participant","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/id":{"navigatorTitle":[{"kind":"identifier","text":"id"}],"abstract":[{"text":"The id of the ","type":"text"},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/id","role":"symbol","title":"id","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/receivedAt":{"navigatorTitle":[{"text":"receivedAt","kind":"identifier"}],"abstract":[{"type":"text","text":"The timestamp of when the "},{"code":"Message","type":"codeVoice"},{"text":" was received from the server.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/receivedAt","role":"symbol","title":"receivedAt","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/receivedat","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"receivedAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/hash","role":"symbol","title":"hash","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/hash","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/messageType":{"navigatorTitle":[{"text":"messageType","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of the "},{"code":"Message","type":"codeVoice"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageType","role":"symbol","title":"messageType","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/messagetype","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/status":{"navigatorTitle":[{"kind":"identifier","text":"status"}],"abstract":[{"type":"text","text":"The status of the "},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/status","role":"symbol","title":"status","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/status","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageStatus","text":"MessageStatus"}]},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/init(from:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(from:)","role":"symbol","title":"init(from:)","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/isEqual(_:)","role":"symbol","title":"isEqual(_:)","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"navigatorTitle":[{"kind":"identifier","text":"Message"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","role":"symbol","title":"Message","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Message","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/init(id:content:createdAt:receivedAt:status:author:sourceId:localId:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(id:content:createdAt:receivedAt:status:author:sourceId:localId:)","role":"symbol","title":"init(id:content:createdAt:receivedAt:status:author:sourceId:localId:)","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/init(id:content:createdat:receivedat:status:author:sourceid:localid:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:25ZendeskSDKConversationKit14MessageContentO","kind":"typeIdentifier","text":"MessageContent"},{"text":", ","kind":"text"},{"text":"createdAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"receivedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageStatus","text":"MessageStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"author"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthor","text":"Author","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sourceId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"localId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/actions":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/actions","role":"symbol","title":"actions","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/actions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actions","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO","text":"MessageActionModel"},{"text":"]?","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/localId":{"navigatorTitle":[{"text":"localId","kind":"identifier"}],"abstract":[{"text":"The locally generated id of the ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":", defaults to id.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/localId","role":"symbol","title":"localId","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/localid","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/createdAt":{"navigatorTitle":[{"text":"createdAt","kind":"identifier"}],"abstract":[{"text":"The timestamp of when the ","type":"text"},{"type":"codeVoice","code":"Message"},{"type":"text","text":" was first created."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/createdAt","role":"symbol","title":"createdAt","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/createdat","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createdAt"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/init(mediaURL:text:metadata:)":{"navigatorTitle":[{"text":"initWithMediaURL:text:metadata:","kind":"identifier"}],"abstract":[{"text":"Failable init for sending a ","type":"text"},{"type":"codeVoice","code":"Message"},{"text":" that can be sent as an attachment. The type of this message may be either ","type":"text"},{"type":"codeVoice","code":".file"},{"text":", or ","type":"text"},{"code":".image","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(mediaURL:text:metadata:)","role":"symbol","title":"init(mediaURL:text:metadata:)","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/init(mediaurl:text:metadata:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"mediaURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":"]?)","kind":"text"}]},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/content":{"abstract":[{"text":"The content of the ","type":"text"},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/content","role":"symbol","title":"content","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/content","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"text":"MessageContent","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit14MessageContentO"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/description":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/description","role":"symbol","title":"description","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE"},"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH"},"doc://com.zendesk.ConversationKit/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/Se"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/author":{"navigatorTitle":[{"text":"author","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"type":"text","text":" who authored the "},{"code":"Message","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/author","role":"symbol","title":"author","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/author","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"author"},{"kind":"text","text":": "},{"text":"Author","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthor"}]},"doc://com.zendesk.ConversationKit/SQ":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/messageContent":{"navigatorTitle":[{"kind":"identifier","text":"messageContent"}],"abstract":[{"text":"The content of the ","type":"text"},{"type":"codeVoice","code":"Message"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageContent","role":"symbol","title":"messageContent","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/messagecontent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageContent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageContent","text":"Content","kind":"typeIdentifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/init(text:payload:metadata:)":{"navigatorTitle":[{"text":"initWithText:payload:metadata:","kind":"identifier"}],"abstract":[{"type":"text","text":"Init for sending a text "},{"code":"Message","type":"codeVoice"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(text:payload:metadata:)","role":"symbol","title":"init(text:payload:metadata:)","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message\/init(text:payload:metadata:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"payload","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":"]?)","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/timestamp":{"type":"topic","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/message\/timestamp","abstract":[{"type":"text","text":"The current valid timestamp for the "},{"type":"codeVoice","code":"Message"},{"text":".","type":"text"}],"title":"timestamp","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/timestamp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/messageActions":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageActions"}],"url":"\/documentation\/zendesksdkconversationkit\/message\/messageactions","title":"messageActions","abstract":[{"type":"text","text":"Any actions associated with the message"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageActions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"messageActions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction","kind":"typeIdentifier","text":"MessageAction"},{"text":"]?","kind":"text"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ZDKMessage","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKMessage","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKMessage","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/author","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/createdAt","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/id","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/localId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageActions","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageContent","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/receivedAt","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/sourceId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/status","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/timestamp"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(mediaURL:text:metadata:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(text:payload:metadata:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/isAuthoredBy(_:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/isEqual(_:)"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKMessage"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1sourceId\/title","op":"replace","value":"sourceId"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1sourceId\/fragments","value":[{"kind":"identifier","text":"sourceId"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1isAuthoredBy(_:)\/title","op":"replace","value":"isAuthoredBy:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isAuthoredBy:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1isAuthoredBy(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1id\/title","op":"replace","value":"id"},{"value":[{"text":"id","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1id\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1receivedAt\/title","value":"receivedAt","op":"replace"},{"value":[{"text":"receivedAt","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1receivedAt\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"value":"messageType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1messageType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1messageType\/fragments","value":[{"text":"messageType","kind":"identifier"}],"op":"replace"},{"value":"status","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1status\/title"},{"op":"replace","value":[{"text":"status","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1status\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1isEqual(_:)\/title","value":"isEqual:"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1isEqual(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title","value":"ZDKMessage"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","value":[{"text":"ZDKMessage","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1localId\/title","value":"localId"},{"value":[{"kind":"identifier","text":"localId"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1localId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1createdAt\/title","value":"createdAt"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1createdAt\/fragments","op":"replace","value":[{"text":"createdAt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1init(mediaURL:text:metadata:)\/title","value":"initWithMediaURL:text:metadata:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1init(mediaURL:text:metadata:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMediaURL:text:metadata:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1description\/title","op":"replace","value":"description"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1description\/fragments"},{"op":"replace","value":"author","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1author\/title"},{"value":[{"kind":"identifier","text":"author"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1author\/fragments"},{"op":"replace","value":"messageContent","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1messageContent\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1messageContent\/fragments","op":"replace","value":[{"kind":"identifier","text":"messageContent"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1init(text:payload:metadata:)\/title","op":"replace","value":"initWithText:payload:metadata:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithText:payload:metadata:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1init(text:payload:metadata:)\/fragments"},{"value":"timestamp","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1timestamp\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}]},{"value":"messageActions","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1messageActions\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1messageActions\/fragments","op":"replace","value":[{"kind":"identifier","text":"messageActions"}]}]}]}