{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent\/activity","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent\/conversationId"]}],"abstract":[{"text":"Wrapper object for Obj-C to return the associated types of the ","type":"text"},{"code":"newActivity","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"activityReceived","type":"codeVoice"},{"type":"text","text":" events."}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKActivityEvent","kind":"identifier"}],"title":"ZDKActivityEvent","role":"symbol","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"ZDKActivityEvent","kind":"identifier"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivityEvent","modules":[{"name":"ZendeskSDKConversationKit"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKActivityEvent"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkactivityevent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkactivityevent"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKActivityEvent":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent","abstract":[{"text":"Wrapper object for Obj-C to return the associated types of the ","type":"text"},{"type":"codeVoice","code":"newActivity"},{"text":" and ","type":"text"},{"code":"activityReceived","type":"codeVoice"},{"type":"text","text":" events."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKActivityEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkactivityevent","navigatorTitle":[{"text":"ZDKActivityEvent","kind":"identifier"}],"title":"ZDKActivityEvent","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKActivityEvent/activity":{"type":"topic","title":"activity","url":"\/documentation\/zendesksdkconversationkit\/zdkactivityevent\/activity","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activity","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"Activity"}],"navigatorTitle":[{"kind":"identifier","text":"activity"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent\/activity","abstract":[{"type":"text","text":"The received\/updated "},{"code":"Activity","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKActivityEvent/conversationId":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkactivityevent\/conversationid","abstract":[{"type":"text","text":"The identifier of the "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" that the messages belong to."}],"title":"conversationId","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent\/conversationId","navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"conversationId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","type":"unresolvable"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.ConversationKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKActivityEvent"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKActivityEvent"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKActivityEvent","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent\/activity","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent\/conversationId"],"title":"Instance Properties"}]},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKActivityEvent","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKActivityEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent\/title"},{"value":[{"text":"ZDKActivityEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent\/fragments"},{"value":"activity","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent~1activity\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent~1activity\/fragments","value":[{"text":"activity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent~1conversationId\/title","op":"replace","value":"conversationId"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent~1conversationId\/fragments","op":"replace","value":[{"kind":"identifier","text":"conversationId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}