{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKWaitTimeDataResult"}],"symbolKind":"class","navigatorTitle":[{"text":"ZDKWaitTimeDataResult","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeDataResult","role":"symbol","roleHeading":"Class","title":"ZDKWaitTimeDataResult"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/conversationId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/error","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/waitTimeData"]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkwaittimedataresult"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkwaittimedataresult"]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKWaitTimeDataResult"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"The event that gets emitted when the wait time data was fetched","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKWaitTimeDataResult":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult","abstract":[{"type":"text","text":"The event that gets emitted when the wait time data was fetched"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKWaitTimeDataResult"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkwaittimedataresult","navigatorTitle":[{"text":"ZDKWaitTimeDataResult","kind":"identifier"}],"title":"ZDKWaitTimeDataResult","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKWaitTimeDataResult/conversationId":{"url":"\/documentation\/zendesksdkconversationkit\/zdkwaittimedataresult\/conversationid","type":"topic","kind":"symbol","abstract":[],"role":"symbol","title":"conversationId","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/conversationId"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKWaitTimeDataResult/error":{"url":"\/documentation\/zendesksdkconversationkit\/zdkwaittimedataresult\/error","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/error","kind":"symbol","type":"topic","navigatorTitle":[{"text":"error","kind":"identifier"}],"role":"symbol","title":"error"},"doc://com.zendesk.ConversationKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKWaitTimeDataResult/waitTimeData":{"url":"\/documentation\/zendesksdkconversationkit\/zdkwaittimedataresult\/waittimedata","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitTimeData","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData","text":"WaitTimeData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/waitTimeData","type":"topic","kind":"symbol","navigatorTitle":[{"text":"waitTimeData","kind":"identifier"}],"role":"symbol","title":"waitTimeData"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKWaitTimeDataResult"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKWaitTimeDataResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKWaitTimeDataResult"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/conversationId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/error","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/waitTimeData"],"title":"Instance Properties"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKWaitTimeDataResult","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult\/title","value":"ZDKWaitTimeDataResult"},{"value":[{"text":"ZDKWaitTimeDataResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult\/fragments"},{"value":"conversationId","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult~1conversationId\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult~1conversationId\/fragments","value":[{"kind":"identifier","text":"conversationId"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult~1error\/title","value":"error"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult~1error\/fragments","value":[{"kind":"identifier","text":"error"}],"op":"replace"},{"value":"waitTimeData","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult~1waitTimeData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult~1waitTimeData\/fragments","value":[{"text":"waitTimeData","kind":"identifier"}]}]}]}