{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Initializer","title":"init(id:type:authorType:name:avatarURL:appUserId:lastRead:isInitialRouting:queuePosition:responseTime:startAt:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ActivityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"kind":"text","text":", "},{"text":"authorType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthorType","text":"AuthorType"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"avatarURL"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"appUserId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"lastRead","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?, "},{"text":"isInitialRouting","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queuePosition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"?, "},{"text":"responseTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:25ZendeskSDKConversationKit12ResponseTimeV","text":"ResponseTime","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"startAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"?)","kind":"text"}],"symbolKind":"init","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"s:25ZendeskSDKConversationKit8ActivityC2id4type10authorType4name9avatarURL9appUserId8lastRead16isInitialRouting13queuePosition12responseTime7startAtACSS_AA0dH0OAA06AuthorH0OSSSgA2S10Foundation4DateVSgSbSiSgAA08ResponseW0VSgAXtcfc"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/activity\/init(id:type:authortype:name:avatarurl:appuserid:lastread:isinitialrouting:queueposition:responsetime:startat:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/init(id:type:authorType:name:avatarURL:appUserId:lastRead:isInitialRouting:queuePosition:responseTime:startAt:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = UUID().uuidString, ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","text":"ActivityType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"authorType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AuthorType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthorType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthorType"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"avatarURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"appUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"lastRead"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":"? = nil, ","kind":"text"},{"text":"isInitialRouting","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"queuePosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"? = nil, "},{"text":"responseTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:25ZendeskSDKConversationKit12ResponseTimeV","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ResponseTime","text":"ResponseTime","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"startAt"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/init(id:type:authorType:name:avatarURL:appUserId:lastRead:isInitialRouting:queuePosition:responseTime:startAt:)":{"type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"ActivityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"authorType"},{"kind":"text","text":": "},{"text":"AuthorType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthorType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"avatarURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"appUserId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lastRead"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isInitialRouting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queuePosition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"responseTime"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ResponseTime","preciseIdentifier":"s:25ZendeskSDKConversationKit12ResponseTimeV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"startAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(id:type:authorType:name:avatarURL:appUserId:lastRead:isInitialRouting:queuePosition:responseTime:startAt:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/init(id:type:authorType:name:avatarURL:appUserId:lastRead:isInitialRouting:queuePosition:responseTime:startAt:)","abstract":[],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/activity\/init(id:type:authortype:name:avatarurl:appuserid:lastread:isinitialrouting:queueposition:responsetime:startat:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"url":"\/documentation\/zendesksdkconversationkit\/activitytype","title":"ActivityType","navigatorTitle":[{"text":"ActivityType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ActivityType","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/AuthorType":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthorType","abstract":[{"type":"text","text":"Represents the role of the user on the "},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/zendesksdkconversationkit\/authortype","title":"AuthorType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthorType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AuthorType","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ResponseTime":{"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/responsetime","title":"ResponseTime","navigatorTitle":[{"kind":"identifier","text":"ResponseTime"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResponseTime"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ResponseTime"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Activity","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Activity"}],"url":"\/documentation\/zendesksdkconversationkit\/activity","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","title":"Activity","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title","value":"ZDKActivityType"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKActivityType"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments"},{"value":"ZDKAuthorType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthorType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthorType\/fragments","op":"replace","value":[{"text":"ZDKAuthorType","kind":"identifier"}]},{"value":"ZDKActivity","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKActivity"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}