{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendConversationActivity(activity:conversationId:completion:)","interfaceLanguage":"swift"},"abstract":[{"text":"Call to send an activity ","type":"text"},{"type":"codeVoice","code":"ActivityType"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendConversationActivity"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"activity"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType","text":"ActivityType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"activity","content":[{"type":"paragraph","inlineContent":[{"text":"the ","type":"text"},{"type":"codeVoice","code":"ActivityType"},{"text":" that is to be sent","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the "},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":" that the "},{"code":"Activity","type":"codeVoice"},{"text":" will be sent","type":"text"}]}],"name":"conversationId"}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Available Activity Types are"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"conversationRead"}]}]},{"content":[{"inlineContent":[{"code":"typingStart","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"typingStop","type":"codeVoice"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendconversationactivity(activity:conversationid:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendconversationactivity(activity:conversationid:completion:)"]}],"sections":[],"kind":"symbol","metadata":{"symbolKind":"method","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit(im)sendConversationActivityWithActivity:conversationId:completion:","title":"sendConversationActivity(activity:conversationId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendConversationActivity"},{"kind":"text","text":"("},{"text":"activity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ActivityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"required":true,"modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"text":"sendConversationActivityWithActivity:conversationId:completion:","kind":"identifier"}],"role":"symbol","platforms":[],"roleHeading":"Instance Method"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/sendConversationActivity(activity:conversationId:completion:)":{"abstract":[{"type":"text","text":"Call to send an activity "},{"type":"codeVoice","code":"ActivityType"}],"required":true,"title":"sendConversationActivity(activity:conversationId:completion:)","type":"topic","navigatorTitle":[{"text":"sendConversationActivityWithActivity:conversationId:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendConversationActivity","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"activity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType","text":"ActivityType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendConversationActivity(activity:conversationId:completion:)","kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendconversationactivity(activity:conversationid:completion:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"type":"topic","role":"symbol","title":"ConversationKitObjC","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitObjC","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationKitObjC","kind":"identifier"}],"abstract":[{"code":"ConversationKitObjC","type":"codeVoice"},{"text":" needs to be configured  with a ","type":"text"},{"type":"codeVoice","code":"ConversationKitSettings"},{"type":"text","text":" "},{"text":"that includes the necessary ","type":"text"},{"type":"codeVoice","code":"integrationId"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"integrationId"},{"type":"text","text":" can be retrieved from the Native Messaging dashboard."}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivityType"}],"navigatorTitle":[{"kind":"identifier","text":"ActivityType"}],"type":"topic","title":"ActivityType","kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/activitytype","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"sendConversationActivityWithActivity:conversationId:completion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sendConversationActivityWithActivity:conversationId:completion:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"sendConversationActivityWithActivity:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKActivityType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"activity"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversationId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"sendConversationActivityWithActivity:conversationId:completion:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendConversationActivity(activity:conversationId:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendConversationActivityWithActivity:conversationId:completion:"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendConversationActivity(activity:conversationId:completion:)\/fragments","op":"replace"},{"value":"ZDKConversationKit","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments","value":[{"text":"ZDKConversationKit","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title","value":"ZDKActivityType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments","value":[{"kind":"identifier","text":"ZDKActivityType"}]}]}]}