{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/UnsupportedMessageContent"]]},"abstract":[{"type":"text","text":"The type of the "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType"}],"symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUnsupportedMessageContent(py)type","role":"symbol","title":"type","navigatorTitle":[{"text":"type","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKUnsupportedMessageContent\/type","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","text":"MessageType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkunsupportedmessagecontent\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkunsupportedmessagecontent\/type"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/UnsupportedMessageContent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UnsupportedMessageContent"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/UnsupportedMessageContent","title":"UnsupportedMessageContent","url":"\/documentation\/zendesksdkconversationkit\/unsupportedmessagecontent","role":"symbol","navigatorTitle":[{"text":"UnsupportedMessageContent","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKUnsupportedMessageContent/type":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"text":"MessageType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The type of the "},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKUnsupportedMessageContent\/type","title":"type","url":"\/documentation\/zendesksdkconversationkit\/zdkunsupportedmessagecontent\/type","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType":{"title":"MessageType","abstract":[{"type":"text","text":"Represents the different "},{"code":"Message","type":"codeVoice"},{"text":" types in a ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MessageType","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/messagetype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageType"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"type","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","text":"ZDKMessageType"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"ZDKUnsupportedMessageContent","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1UnsupportedMessageContent\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1UnsupportedMessageContent\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKUnsupportedMessageContent"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKUnsupportedMessageContent~1type\/title","op":"replace","value":"type"},{"value":[{"kind":"identifier","text":"type"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKUnsupportedMessageContent~1type\/fragments"},{"value":"ZDKMessageType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/fragments","op":"replace","value":[{"text":"ZDKMessageType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}