{"sections":[],"metadata":{"roleHeading":"Global Variable","symbolKind":"var","role":"symbol","title":"ConversationKitVersionString","navigatorTitle":[{"kind":"identifier","text":"ConversationKitVersionString"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"externalID":"c:@ConversationKitVersionString","modules":[{"name":"ZendeskSDKConversationKit"}]},"abstract":[{"type":"text","text":"Project version string for ConversationKit."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitVersionString","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitversionstring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitversionstring"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitVersionString":{"title":"ConversationKitVersionString","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"abstract":[{"text":"Project version string for ConversationKit.","type":"text"}],"navigatorTitle":[{"text":"ConversationKitVersionString","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitversionstring","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitVersionString","type":"topic","kind":"symbol","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"ConversationKitVersionString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ConversationKitVersionString","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"unsigned char","preciseIdentifier":"c:c"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitVersionString"},{"kind":"text","text":"[];"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitVersionString\/title","value":"ConversationKitVersionString"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitVersionString\/fragments","value":[{"text":"ConversationKitVersionString","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}