{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"sections":[],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"ProactiveMessage"},{"text":" event has occurred","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged\/proactiveMessage","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged\/status"],"title":"Instance Properties"}],"metadata":{"role":"symbol","symbolKind":"class","roleHeading":"Class","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessageStatusChanged","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKProactiveMessageStatusChanged"}],"navigatorTitle":[{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}],"title":"ZDKProactiveMessageStatusChanged"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged"},"references":{"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"},"doc://com.zendesk.ConversationKit/SQ":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKProactiveMessageStatusChanged/status":{"abstract":[{"text":"The status of the ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged\/status","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"status"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged\/status","kind":"symbol","title":"status","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"text":": ","kind":"text"},{"text":"ProactiveMessageStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","kind":"typeIdentifier"}]},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKProactiveMessageStatusChanged/proactiveMessage":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged\/proactiveMessage","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"proactiveMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProactiveMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"}],"type":"topic","abstract":[{"text":"The content of the ","type":"text"},{"type":"codeVoice","code":"ProactiveMessage"},{"text":".","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged\/proactivemessage","navigatorTitle":[{"text":"proactiveMessage","kind":"identifier"}],"title":"proactiveMessage","role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKProactiveMessageStatusChanged":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}],"type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":" event has occurred"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged","navigatorTitle":[{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}],"title":"ZDKProactiveMessageStatusChanged","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKProactiveMessageStatusChanged","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatusChanged"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged\/proactiveMessage","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged\/status"]}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged~1status\/title","value":"status"},{"value":[{"text":"status","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged~1status\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged~1proactiveMessage\/title","op":"replace","value":"proactiveMessage"},{"value":[{"kind":"identifier","text":"proactiveMessage"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged~1proactiveMessage\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged\/title","op":"replace","value":"ZDKProactiveMessageStatusChanged"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatusChanged"}]}]}]}