{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFileMessageContent\/hash","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkfilemessagecontent\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkfilemessagecontent\/hash"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKFileMessageContent(py)hash","title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent"]]},"kind":"symbol","sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FileMessageContent":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/filemessagecontent","navigatorTitle":[{"text":"FileMessageContent","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileMessageContent"}],"title":"FileMessageContent","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FileMessageContent","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKFileMessageContent/hash":{"url":"\/documentation\/zendesksdkconversationkit\/zdkfilemessagecontent\/hash","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFileMessageContent\/hash","title":"hash","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"hash"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent\/title","op":"replace","value":"ZDKFileMessageContent"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKFileMessageContent"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FileMessageContent\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFileMessageContent~1hash\/title","op":"replace","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFileMessageContent~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}