{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config"]]},"abstract":[{"text":"Contains admin settings for queue position and wait time behaviour.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitTimeConfig","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig","text":"WaitTimeConfig","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/waitTimeConfig"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/config\/waittimeconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/config\/waittimeconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig(py)waitTimeConfig","navigatorTitle":[{"text":"waitTimeConfig","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitTimeConfig","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WaitTimeConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig"}],"title":"waitTimeConfig","symbolKind":"property"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config/waitTimeConfig":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/config\/waittimeconfig","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitTimeConfig","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WaitTimeConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig"}],"type":"topic","navigatorTitle":[{"text":"waitTimeConfig","kind":"identifier"}],"abstract":[{"text":"Contains admin settings for queue position and wait time behaviour.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/waitTimeConfig","role":"symbol","title":"waitTimeConfig"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Config","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/config","title":"Config","kind":"symbol","navigatorTitle":[{"text":"Config","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeConfig":{"navigatorTitle":[{"kind":"identifier","text":"WaitTimeConfig"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WaitTimeConfig"}],"role":"symbol","title":"WaitTimeConfig","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/waittimeconfig","type":"topic","abstract":[{"text":"The wait time configuration. Contains config related to queue position and wait time behaviour.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"waitTimeConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"waitTimeConfig"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig","kind":"typeIdentifier","text":"ZDKWaitTimeConfig"},{"kind":"text","text":" * "},{"kind":"identifier","text":"waitTimeConfig"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config~1waitTimeConfig\/title","value":"waitTimeConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config~1waitTimeConfig\/fragments","value":[{"kind":"identifier","text":"waitTimeConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/title","value":"ZDKConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/fragments","value":[{"kind":"identifier","text":"ZDKConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/title","value":"ZDKWaitTimeConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/fragments","value":[{"kind":"identifier","text":"ZDKWaitTimeConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/navigatorTitle","value":[{"text":"ZDKWaitTimeConfig","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}