{"sections":[],"abstract":[{"text":"Initialize a ","type":"text"},{"type":"codeVoice","code":"ConversationKitSettings"},{"type":"text","text":" instance."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"integrationId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"region"},{"text":": ","kind":"text"},{"text":"Region","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings\/Region-swift.enum","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC8SettingsC6RegionO","kind":"typeIdentifier"},{"kind":"text","text":" = .us, "},{"text":"baseURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"integrationId","content":[{"type":"paragraph","inlineContent":[{"text":"The iOS integration id for this SDK.","type":"text"}]}]},{"name":"region","content":[{"type":"paragraph","inlineContent":[{"text":"The region to connect to.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The server base url."}]}],"name":"baseURL"}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings"]]},"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"integrationId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"region"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC8SettingsC6RegionO","text":"Region"},{"text":", ","kind":"text"},{"text":"baseURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationKitSettings(im)initWithIntegrationId:region:baseURL:","title":"init(integrationId:region:baseURL:)","symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithIntegrationId:region:baseURL:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitsettings\/init(integrationid:region:baseurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitsettings\/init(integrationid:region:baseurl:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings\/init(integrationId:region:baseURL:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKRegion":{"fragments":[{"text":"ZDKRegion","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkregion","title":"ZDKRegion","role":"symbol","abstract":[{"text":"The region used to connect to the server.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKRegion","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitSettings":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationKitSettings"}],"type":"topic","title":"ConversationKitSettings","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitsettings","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitSettings"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitSettings/init(integrationId:region:baseURL:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"integrationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"region","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC8SettingsC6RegionO","text":"Region"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"baseURL"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings\/init(integrationId:region:baseURL:)","title":"init(integrationId:region:baseURL:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithIntegrationId:region:baseURL:"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitsettings\/init(integrationid:region:baseurl:)","abstract":[{"type":"text","text":"Initialize a "},{"type":"codeVoice","code":"ConversationKitSettings"},{"text":" instance.","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitSettings/Region-swift.enum":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Region"}],"type":"topic","title":"ConversationKitSettings.Region","abstract":[{"text":"The region used to connect to the server.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitsettings\/region-swift.enum","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings\/Region-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Region"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithIntegrationId:region:baseURL:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithIntegrationId:region:baseURL:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithIntegrationId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"integrationId"},{"kind":"text","text":" "},{"text":"region:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKRegion","text":"ZDKRegion","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKRegion"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"region"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseURL:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"baseURL"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitSettings\/title","value":"ZDKConversationKitSettings","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitSettings\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitSettings"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitSettings~1init(integrationId:region:baseURL:)\/title","value":"initWithIntegrationId:region:baseURL:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitSettings~1init(integrationId:region:baseURL:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithIntegrationId:region:baseURL:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}