{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/messagetype\/formresponse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/messagetype\/formresponse"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formResponse"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"formResponse","kind":"identifier"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType@ZDKMessageTypeFormResponse","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ZDKMessageTypeFormResponse"}],"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"MessageType.formResponse","roleHeading":"Case"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType\/formResponse","interfaceLanguage":"swift"},"abstract":[{"text":"The response to a ","type":"text"},{"code":"form","type":"codeVoice"},{"text":" that was previously sent in a ","type":"text"},{"code":"Conversation","type":"codeVoice"}],"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType/formResponse":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType\/formResponse","title":"MessageType.formResponse","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formResponse"}],"navigatorTitle":[{"text":"ZDKMessageTypeFormResponse","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The response to a "},{"code":"form","type":"codeVoice"},{"text":" that was previously sent in a ","type":"text"},{"type":"codeVoice","code":"Conversation"}],"url":"\/documentation\/zendesksdkconversationkit\/messagetype\/formresponse"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","title":"MessageType","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messagetype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageType"}],"navigatorTitle":[{"text":"MessageType","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the different "},{"type":"codeVoice","code":"Message"},{"type":"text","text":" types in a "},{"type":"codeVoice","code":"Conversation"},{"text":".","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKMessageTypeFormResponse"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKMessageTypeFormResponse"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKMessageTypeFormResponse","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"ZDKMessageTypeFormResponse","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType~1formResponse\/title"},{"op":"replace","value":[{"text":"ZDKMessageTypeFormResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType~1formResponse\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/title","value":"ZDKMessageType","op":"replace"},{"value":[{"text":"ZDKMessageType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/fragments"}]}]}