{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Processes a "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":" status change."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)-4ctcc"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)-4ctcc"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"defaultImplementationsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-80ytw"],"title":"ConversationKitShared Implementations"}],"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageStatusChanged"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","text":"ProactiveMessageStatus","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"proactiveMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ProactiveMessage","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jwt"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"title":"proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)proactiveMessageStatusChanged:proactiveMessage:jwt:","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"proactiveMessageStatusChanged:proactiveMessage:jwt:"}],"symbolKind":"method","required":true},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageStatusChanged"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"status","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","text":"ProactiveMessageStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"proactiveMessage"},{"kind":"text","text":": "},{"text":"ProactiveMessage","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"jwt"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}]},{"kind":"parameters","parameters":[{"name":"status","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current status of a "},{"code":"ProactiveMessage","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The current ","type":"text"},{"type":"codeVoice","code":"ProactiveMessage"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"proactiveMessage"},{"name":"jwt","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"jwt"},{"type":"text","text":" that represents the content of a "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":"."}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","abstract":[{"text":"Status that compliments a ","type":"text"},{"type":"codeVoice","code":"ProactiveMessageStatusChanged"},{"text":" event in ","type":"text"},{"type":"codeVoice","code":"ConversationKitEvent"}],"url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus","role":"symbol","navigatorTitle":[{"text":"ProactiveMessageStatus","kind":"identifier"}],"kind":"symbol","title":"ProactiveMessageStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProactiveMessageStatus"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)-4ctcc","navigatorTitle":[{"text":"proactiveMessageStatusChanged:proactiveMessage:jwt:","kind":"identifier"}],"abstract":[{"type":"text","text":"Processes a "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":" status change."}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageStatusChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ProactiveMessageStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus"},{"kind":"text","text":", "},{"text":"proactiveMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ProactiveMessage","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jwt"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc","required":true,"title":"proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","role":"symbol","defaultImplementations":1},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessage":{"title":"ProactiveMessage","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProactiveMessage"}],"navigatorTitle":[{"text":"ProactiveMessage","kind":"identifier"}],"abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/proactivemessage"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-80ytw":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)-80ytw","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"proactiveMessageStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ProactiveMessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"proactiveMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProactiveMessage","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"jwt"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-80ytw","abstract":[{"text":"Processes a ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"type":"text","text":" status change."}],"role":"symbol","kind":"symbol","title":"proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitShared"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","kind":"symbol","title":"ConversationKitShared","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","kind":"symbol","role":"collection","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"proactiveMessageStatusChanged:proactiveMessage:jwt:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"proactiveMessageStatusChanged:proactiveMessage:jwt:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"proactiveMessageStatusChanged:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKProactiveMessageStatus","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"text":"proactiveMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","text":"ZDKProactiveMessage"},{"kind":"text","text":" *) "},{"text":"proactiveMessage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"jwt:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"jwt","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"ZDKProactiveMessageStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/fragments","value":[{"text":"ZDKProactiveMessageStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc\/title","value":"proactiveMessageStatusChanged:proactiveMessage:jwt:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"proactiveMessageStatusChanged:proactiveMessage:jwt:"}]},{"value":"ZDKProactiveMessage","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessage"}]},{"value":"ConversationKitShared","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","op":"replace","value":[{"text":"ConversationKitShared","kind":"identifier"}]}]}]}