{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateUserConversations:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateUserConversations","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"method","title":"updateUserConversations(_:)","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)updateUserConversations:","roleHeading":"Instance Method","required":true},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Update the user’s conversations.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserConversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"conversations"},{"text":": [","kind":"text"},{"text":"Conversation","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"conversations","content":[{"type":"paragraph","inlineContent":[{"text":"A list of ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"text":" objects.","type":"text"}]}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/updateUserConversations(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/updateuserconversations(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/updateuserconversations(_:)"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"type":"topic","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/conversation","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"kind":"symbol","title":"Conversation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitShared"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","kind":"symbol","title":"ConversationKitShared","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/updateUserConversations(_:)":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/updateuserconversations(_:)","abstract":[{"type":"text","text":"Update the user’s conversations."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/updateUserConversations(_:)","title":"updateUserConversations(_:)","role":"symbol","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserConversations"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation"},{"text":"])","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"updateUserConversations:","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","kind":"symbol","role":"collection","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"updateUserConversations:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"updateUserConversations:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"updateUserConversations:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<ZDKConversation *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"conversations","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","value":"ZDKConversation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments","value":[{"kind":"identifier","text":"ZDKConversation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","value":[{"text":"ConversationKitShared","kind":"identifier"}],"op":"replace"},{"value":"updateUserConversations:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1updateUserConversations(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1updateUserConversations(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"updateUserConversations:","kind":"identifier"}]}]}]}