{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"The field type."}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType","text":"FieldType","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"type","modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKTextFormField(py)type","symbolKind":"property","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType","text":"FieldType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextFormField\/type","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdktextformfield\/type"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdktextformfield\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField":{"url":"\/documentation\/zendesksdkconversationkit\/textformfield","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField","abstract":[{"text":"Form Field that takes in generic user input","type":"text"}],"type":"topic","title":"TextFormField","navigatorTitle":[{"text":"TextFormField","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TextFormField","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKTextFormField/type":{"abstract":[{"text":"The field type.","type":"text"}],"kind":"symbol","title":"type","navigatorTitle":[{"text":"type","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType","kind":"typeIdentifier","text":"FieldType"}],"url":"\/documentation\/zendesksdkconversationkit\/zdktextformfield\/type","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextFormField\/type","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FieldType":{"role":"symbol","title":"FieldType","navigatorTitle":[{"kind":"identifier","text":"FieldType"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","url":"\/documentation\/zendesksdkconversationkit\/fieldtype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FieldType"}],"type":"topic","abstract":[{"text":"Form field type. ","type":"text"},{"code":"text","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"email"},{"type":"text","text":", "},{"code":"select","type":"codeVoice"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType","kind":"typeIdentifier","text":"ZDKFieldType"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKTextFormField","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField\/fragments","value":[{"text":"ZDKTextFormField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextFormField~1type\/title","value":"type"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextFormField~1type\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"value":"ZDKFieldType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/fragments","value":[{"kind":"identifier","text":"ZDKFieldType"}]}]}]}