{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"An array of business ids contributing to the ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"business"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"business","symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"business","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"business"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation(py)business"},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/business","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/business"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/business"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"]]},"kind":"symbol","references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation/business":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"business"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"abstract":[{"text":"An array of business ids contributing to the ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"business","kind":"identifier"}],"title":"business","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversation\/business","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/business"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Conversation","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation","type":"topic","title":"Conversation","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"business","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"business","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"business","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1business\/title","op":"replace","value":"business"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1business\/fragments","value":[{"kind":"identifier","text":"business"}],"op":"replace"},{"value":"ZDKConversation","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKConversation"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}