{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/participants"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"participants","kind":"identifier"},{"kind":"text","text":": ["},{"text":"Participant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"An array of all the ","type":"text"},{"type":"codeVoice","code":"Participant"},{"text":"s in the ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"]]},"metadata":{"title":"participants","symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"participants","kind":"identifier"},{"kind":"text","text":": ["},{"text":"Participant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"participants","kind":"identifier"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation(py)participants"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/participants"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/participants"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Conversation","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation","type":"topic","title":"Conversation","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Participant":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/participant","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Participant","kind":"identifier"}],"navigatorTitle":[{"text":"Participant","kind":"identifier"}],"title":"Participant"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation/participants":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/participants","role":"symbol","abstract":[{"type":"text","text":"An array of all the "},{"type":"codeVoice","code":"Participant"},{"text":"s in the ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversation\/participants","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"participants","kind":"identifier"},{"kind":"text","text":": ["},{"text":"Participant","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"participants","kind":"identifier"}],"title":"participants"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"participants"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"participants","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<ZDKParticipant *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"participants"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","op":"replace","value":"ZDKConversation"},{"op":"replace","value":[{"text":"ZDKConversation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments"},{"op":"replace","value":"ZDKParticipant","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/fragments","op":"replace","value":[{"text":"ZDKParticipant","kind":"identifier"}]},{"value":"participants","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1participants\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1participants\/fragments","value":[{"kind":"identifier","text":"participants"}]}]}]}