{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(id:content:createdAt:receivedAt:status:author:sourceId:localId:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/message\/init(id:content:createdat:receivedat:status:author:sourceid:localid:)"]}],"metadata":{"externalID":"s:25ZendeskSDKConversationKit7MessageC2id7content9createdAt08receivedH06status6author8sourceId05localM0ACSS_AA0D7ContentO10Foundation4DateVSgAqA0D6StatusOAA6AuthorCSSSgAVtcfc","role":"symbol","symbolKind":"init","title":"init(id:content:createdAt:receivedAt:status:author:sourceId:localId:)","roleHeading":"Initializer","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageContent","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit14MessageContentO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createdAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?, ","kind":"text"},{"text":"receivedAt","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"author"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthor","text":"Author"},{"text":", ","kind":"text"},{"text":"sourceId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"localId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = UUID().uuidString, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit14MessageContentO","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageContent","text":"MessageContent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createdAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"? = Date(), ","kind":"text"},{"text":"receivedAt","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageStatus","text":"MessageStatus"},{"text":" = .pending, ","kind":"text"},{"text":"author","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Author","text":"Author","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthor","kind":"typeIdentifier"},{"text":" = .init(id: UUID().uuidString, type: .user), ","kind":"text"},{"text":"sourceId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"localId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageContent":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageContent","kind":"identifier"}],"navigatorTitle":[{"text":"MessageContent","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum that encapsulates all the different message types and their content"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messagecontent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageContent","kind":"symbol","title":"MessageContent","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"navigatorTitle":[{"text":"Message","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Message","kind":"identifier"}],"title":"Message","kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/message"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus":{"title":"MessageStatus","navigatorTitle":[{"text":"MessageStatus","kind":"identifier"}],"abstract":[{"text":"Represents the status of the ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageStatus","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/messagestatus","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus","type":"topic","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/init(id:content:createdAt:receivedAt:status:author:sourceId:localId:)":{"type":"topic","abstract":[],"role":"symbol","title":"init(id:content:createdAt:receivedAt:status:author:sourceId:localId:)","url":"\/documentation\/zendesksdkconversationkit\/message\/init(id:content:createdat:receivedat:status:author:sourceid:localid:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(id:content:createdAt:receivedAt:status:author:sourceId:localId:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageContent","preciseIdentifier":"s:25ZendeskSDKConversationKit14MessageContentO"},{"text":", ","kind":"text"},{"text":"createdAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"receivedAt","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageStatus","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"author"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthor","text":"Author"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"localId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Author":{"navigatorTitle":[{"text":"Author","kind":"identifier"}],"type":"topic","title":"Author","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Author","kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/author","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Author","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title","value":"ZDKMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","value":[{"kind":"identifier","text":"ZDKMessage"}],"op":"replace"},{"value":"ZDKMessageStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus\/title"},{"value":[{"text":"ZDKMessageStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Author\/title","value":"ZDKAuthor"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Author\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKAuthor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}