{"abstract":[{"text":"The content of the ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageContent"},"metadata":{"navigatorTitle":[{"text":"messageContent","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage(py)messageContent","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageContent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Content","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageContent"}],"title":"messageContent"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/message\/messagecontent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/message\/messagecontent"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"messageContent","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageContent","text":"Content"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Content":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Content"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","title":"Content","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"Content","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/content"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/messageContent":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageContent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Content","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageContent"}],"navigatorTitle":[{"kind":"identifier","text":"messageContent"}],"abstract":[{"type":"text","text":"The content of the "},{"type":"codeVoice","code":"Message"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/message\/messagecontent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageContent","kind":"symbol","title":"messageContent","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"navigatorTitle":[{"text":"Message","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Message","kind":"identifier"}],"title":"Message","kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/message"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"messageContent","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"messageContent","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageContent","text":"id<ZDKMessageContent>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"messageContent"}],"languages":["occ"]}]}},{"value":"ZDKMessageContent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Content\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Content\/fragments","value":[{"text":"ZDKMessageContent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1messageContent\/title","value":"messageContent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1messageContent\/fragments","value":[{"kind":"identifier","text":"messageContent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title","value":"ZDKMessage"},{"value":[{"kind":"identifier","text":"ZDKMessage"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}