{"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageItemSize@ZDKMessageItemSizeCompact","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"compact","kind":"identifier"}],"role":"symbol","title":"ActionItemSize.compact","symbolKind":"case","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Case","navigatorTitle":[{"text":"ZDKMessageItemSizeCompact","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Images are meant to be displayed with a large layout."}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/actionitemsize\/compact"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/actionitemsize\/compact"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/compact"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"compact","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize/compact":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compact"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/compact","title":"ActionItemSize.compact","abstract":[{"type":"text","text":"Images are meant to be displayed with a large layout."}],"url":"\/documentation\/zendesksdkconversationkit\/actionitemsize\/compact","navigatorTitle":[{"kind":"identifier","text":"ZDKMessageItemSizeCompact"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize":{"title":"ActionItemSize","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize","kind":"symbol","navigatorTitle":[{"text":"ActionItemSize","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The display size of "},{"code":"MessageActionItem","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionItemSize","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/actionitemsize"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKMessageItemSizeCompact","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKMessageItemSizeCompact"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKMessageItemSizeCompact","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKMessageItemSizeCompact","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize~1compact\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize~1compact\/fragments","value":[{"kind":"identifier","text":"ZDKMessageItemSizeCompact"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/title","value":"ZDKMessageItemSize","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/fragments","value":[{"text":"ZDKMessageItemSize","kind":"identifier"}]}]}]}