{"sections":[],"metadata":{"symbolKind":"case","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Case","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthenticationType@ZDKAuthenticationTypeJwt","title":"AuthenticationType.jwt","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jwt","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationTypeJwt"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType\/jwt"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/authenticationtype\/jwt"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/authenticationtype\/jwt"]}],"abstract":[{"text":"JWT authentication","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jwt","kind":"identifier"}]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/AuthenticationType":{"abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationType","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticationType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType","kind":"symbol","title":"AuthenticationType","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/authenticationtype"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/AuthenticationType/jwt":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jwt","kind":"identifier"}],"title":"AuthenticationType.jwt","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/authenticationtype\/jwt","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ZDKAuthenticationTypeJwt","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType\/jwt","abstract":[{"text":"JWT authentication","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKAuthenticationTypeJwt","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ZDKAuthenticationTypeJwt","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"ZDKAuthenticationTypeJwt","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKAuthenticationType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKAuthenticationType"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKAuthenticationType"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/navigatorTitle","op":"replace"},{"value":"ZDKAuthenticationTypeJwt","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType~1jwt\/title","op":"replace"},{"value":[{"text":"ZDKAuthenticationTypeJwt","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType~1jwt\/fragments","op":"replace"}]}]}