{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionToken"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationTypeSessionToken"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"AuthenticationType.sessionToken","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthenticationType@ZDKAuthenticationTypeSessionToken"},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType\/sessionToken","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionToken","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/authenticationtype\/sessiontoken"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/authenticationtype\/sessiontoken"]}],"abstract":[{"type":"text","text":"Anonymous session"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/AuthenticationType/sessionToken":{"url":"\/documentation\/zendesksdkconversationkit\/authenticationtype\/sessiontoken","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionToken","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Anonymous session","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType\/sessionToken","title":"AuthenticationType.sessionToken","type":"topic","navigatorTitle":[{"text":"ZDKAuthenticationTypeSessionToken","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/AuthenticationType":{"abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationType","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticationType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType","kind":"symbol","title":"AuthenticationType","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/authenticationtype"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKAuthenticationTypeSessionToken","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAuthenticationTypeSessionToken"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ZDKAuthenticationTypeSessionToken"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKAuthenticationTypeSessionToken","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType~1sessionToken\/title"},{"op":"replace","value":[{"text":"ZDKAuthenticationTypeSessionToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType~1sessionToken\/fragments"},{"op":"replace","value":"ZDKAuthenticationType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAuthenticationType"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/fragments"},{"op":"replace","value":[{"text":"ZDKAuthenticationType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}