{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKActivity) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Activity","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/init(from:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/init(id:type:authorType:name:avatarURL:appUserId:lastRead:isInitialRouting:queuePosition:responseTime:startAt:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/appUserId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/authorType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/avatarURL","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/id","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/isInitialRouting","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/lastRead","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/name","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/queuePosition","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/responseTime","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/startAt","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/isEqual(_:)"]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/activity"]},{"paths":["\/documentation\/zendesksdkconversationkit\/activity"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"Activity","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"Activity","symbolKind":"class","roleHeading":"Class","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Activity","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/id":{"role":"symbol","title":"id","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/id","url":"\/documentation\/zendesksdkconversationkit\/activity\/id","abstract":[],"navigatorTitle":[{"text":"id","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/lastRead":{"role":"symbol","title":"lastRead","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/lastRead","url":"\/documentation\/zendesksdkconversationkit\/activity\/lastread","abstract":[],"navigatorTitle":[{"text":"lastRead","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lastRead"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/responseTime":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/responseTime","url":"\/documentation\/zendesksdkconversationkit\/activity\/responsetime","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"responseTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"ResponseTime","preciseIdentifier":"s:25ZendeskSDKConversationKit12ResponseTimeV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol","title":"responseTime"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/isInitialRouting":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/isInitialRouting","url":"\/documentation\/zendesksdkconversationkit\/activity\/isinitialrouting","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isInitialRouting"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"kind":"symbol","role":"symbol","title":"isInitialRouting"},"doc://com.zendesk.ConversationKit/SQ":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/startAt":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/startAt","url":"\/documentation\/zendesksdkconversationkit\/activity\/startat","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startAt"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"?","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol","title":"startAt"},"doc://com.zendesk.ConversationKit/SE":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE","title":"Swift.Encodable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/init(id:type:authorType:name:avatarURL:appUserId:lastRead:isInitialRouting:queuePosition:responseTime:startAt:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/init(id:type:authorType:name:avatarURL:appUserId:lastRead:isInitialRouting:queuePosition:responseTime:startAt:)","url":"\/documentation\/zendesksdkconversationkit\/activity\/init(id:type:authortype:name:avatarurl:appuserid:lastread:isinitialrouting:queueposition:responsetime:startat:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ActivityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"kind":"text","text":", "},{"text":"authorType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthorType","text":"AuthorType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"avatarURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"appUserId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lastRead"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"isInitialRouting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"queuePosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"?, "},{"text":"responseTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ResponseTime","preciseIdentifier":"s:25ZendeskSDKConversationKit12ResponseTimeV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"startAt"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"?)","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol","title":"init(id:type:authorType:name:avatarURL:appUserId:lastRead:isInitialRouting:queuePosition:responseTime:startAt:)"},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/authorType":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/authorType","url":"\/documentation\/zendesksdkconversationkit\/activity\/authortype","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"authorType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthorType","text":"AuthorType"}],"navigatorTitle":[{"text":"authorType","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","title":"authorType"},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"},"doc://com.zendesk.ConversationKit/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.zendesk.ConversationKit\/Se"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/activity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Activity"}],"title":"Activity","role":"symbol","navigatorTitle":[{"text":"Activity","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/isEqual(_:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/isEqual(_:)","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/activity\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/init(from:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/init(from:)","url":"\/documentation\/zendesksdkconversationkit\/activity\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[],"kind":"symbol","role":"symbol","title":"init(from:)"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/name":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/name","url":"\/documentation\/zendesksdkconversationkit\/activity\/name","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"name"}],"abstract":[],"kind":"symbol","role":"symbol","title":"name"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/appUserId":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/appUserId","url":"\/documentation\/zendesksdkconversationkit\/activity\/appuserid","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appUserId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"appUserId","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","title":"appUserId"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/type":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/type","url":"\/documentation\/zendesksdkconversationkit\/activity\/type","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"text":"ActivityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","title":"type"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/queuePosition":{"title":"queuePosition","url":"\/documentation\/zendesksdkconversationkit\/activity\/queueposition","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/queuePosition","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queuePosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"?","kind":"text"}],"abstract":[],"kind":"symbol"},"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity/avatarURL":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/avatarURL","url":"\/documentation\/zendesksdkconversationkit\/activity\/avatarurl","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avatarURL"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"avatarURL"}],"abstract":[],"kind":"symbol","role":"symbol","title":"avatarURL"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKActivity","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKActivity","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKActivity"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/appUserId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/authorType","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/avatarURL","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/id","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/lastRead","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/name","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity\/isEqual(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKActivity","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1id\/title","value":"id"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1id\/fragments","value":[{"text":"id","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1lastRead\/title","op":"replace","value":"lastRead"},{"value":[{"text":"lastRead","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1lastRead\/fragments"},{"op":"replace","value":"authorType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1authorType\/title"},{"value":[{"text":"authorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1authorType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/title","value":"ZDKActivity","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/fragments","value":[{"text":"ZDKActivity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1isEqual(_:)\/fragments"},{"value":"name","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1name\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1name\/fragments","op":"replace","value":[{"kind":"identifier","text":"name"}]},{"value":"appUserId","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1appUserId\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1appUserId\/fragments","value":[{"text":"appUserId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1type\/title","value":"type","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1avatarURL\/title","value":"avatarURL","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity~1avatarURL\/fragments","value":[{"kind":"identifier","text":"avatarURL"}]}]}]}