{"metadata":{"symbolKind":"init","title":"init(settings:config:featureFlagManager:)","roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"settings"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationKitSettings","text":"ConversationKitSettings","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Config","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig"},{"kind":"text","text":", "},{"text":"featureFlagManager","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager","text":"FeatureFlagManager"},{"text":")","kind":"text"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"s:25ZendeskSDKConversationKit18SettingsParametersV8settings6config18featureFlagManagerAcA012ConversationcD0C_AA6ConfigC0A16SDKCoreUtilities07FeatureiJ0Ctcfc"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SettingsParameters"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SettingsParameters\/init(settings:config:featureFlagManager:)"},"abstract":[{"code":"SettingsParameters","type":"codeVoice"},{"text":" struct that is used to provide different settings","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"settings","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings","text":"ConversationKitSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationKitSettings"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","text":"Config","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig"},{"text":", ","kind":"text"},{"text":"featureFlagManager","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager","text":"FeatureFlagManager","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"settings","content":[{"type":"paragraph","inlineContent":[{"text":"Instance of ","type":"text"},{"type":"codeVoice","code":"ConversationKitSettings"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Instance of "},{"type":"codeVoice","code":"Config"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"config"},{"content":[{"inlineContent":[{"text":"Instance of ","type":"text"},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"featureFlagManager"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/settingsparameters\/init(settings:config:featureflagmanager:)"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitSettings":{"navigatorTitle":[{"text":"ConversationKitSettings","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings","url":"\/documentation\/zendesksdkconversationkit\/conversationkitsettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationKitSettings","kind":"identifier"}],"kind":"symbol","title":"ConversationKitSettings","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config":{"navigatorTitle":[{"kind":"identifier","text":"Config"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","url":"\/documentation\/zendesksdkconversationkit\/config","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Config","kind":"identifier"}],"kind":"symbol","title":"Config","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SettingsParameters/init(settings:config:featureFlagManager:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SettingsParameters\/init(settings:config:featureFlagManager:)","url":"\/documentation\/zendesksdkconversationkit\/settingsparameters\/init(settings:config:featureflagmanager:)","abstract":[{"type":"codeVoice","code":"SettingsParameters"},{"text":" struct that is used to provide different settings","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","title":"init(settings:config:featureFlagManager:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"settings","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationKitSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationKitSettings"},{"kind":"text","text":", "},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig","text":"Config"},{"kind":"text","text":", "},{"text":"featureFlagManager","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager","text":"FeatureFlagManager","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SettingsParameters":{"navigatorTitle":[{"text":"SettingsParameters","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SettingsParameters","abstract":[{"text":"Groups together a set of parameters","type":"text"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/settingsparameters","type":"topic","role":"symbol","title":"SettingsParameters","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsParameters"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKConversationKitSettings","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitSettings\/title","op":"replace"},{"op":"replace","value":[{"text":"ZDKConversationKitSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitSettings\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/title","value":"ZDKConfig","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/fragments","op":"replace","value":[{"text":"ZDKConfig","kind":"identifier"}]}]}]}