{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged\/status"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged\/status"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged\/status"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The status of the ","type":"text"},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":"."}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessageStatusChanged(py)status","title":"status","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","kind":"typeIdentifier","text":"ProactiveMessageStatus"}],"roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","text":"ProactiveMessageStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKProactiveMessageStatusChanged":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged","navigatorTitle":[{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}],"title":"ZDKProactiveMessageStatusChanged","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged","kind":"symbol","abstract":[{"type":"text","text":"A "},{"code":"ProactiveMessage","type":"codeVoice"},{"text":" event has occurred","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus":{"type":"topic","role":"symbol","title":"ProactiveMessageStatus","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ProactiveMessageStatus","kind":"identifier"}],"navigatorTitle":[{"text":"ProactiveMessageStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Status that compliments a "},{"type":"codeVoice","code":"ProactiveMessageStatusChanged"},{"text":" event in ","type":"text"},{"code":"ConversationKitEvent","type":"codeVoice"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKProactiveMessageStatusChanged/status":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProactiveMessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged\/status","navigatorTitle":[{"kind":"identifier","text":"status"}],"title":"status","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged\/status","kind":"symbol","type":"topic","abstract":[{"text":"The status of the ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"status"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"status","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","text":"ZDKProactiveMessageStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKProactiveMessageStatusChanged","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatusChanged"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/title","value":"ZDKProactiveMessageStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatus"}]},{"value":"status","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged~1status\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged~1status\/fragments","op":"replace","value":[{"kind":"identifier","text":"status"}]}]}]}