{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authentication"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthentication","text":"Authentication","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Authentication","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"authentication"},{"text":" of the ","type":"text"},{"type":"codeVoice","code":"User"}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKUser\/authentication","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkuser\/authentication"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkuser\/authentication"]}],"kind":"symbol","sections":[],"metadata":{"title":"authentication","symbolKind":"property","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser(py)authentication","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authentication"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthentication","kind":"typeIdentifier","text":"Authentication"}],"roleHeading":"Instance Property","modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"text":"authentication","kind":"identifier"}]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User":{"abstract":[],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","title":"User","navigatorTitle":[{"kind":"identifier","text":"User"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Authentication":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Authentication","url":"\/documentation\/zendesksdkconversationkit\/authentication","title":"Authentication","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Authentication","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Authentication"}],"abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKUser/authentication":{"url":"\/documentation\/zendesksdkconversationkit\/zdkuser\/authentication","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authentication","kind":"identifier"},{"kind":"text","text":": "},{"text":"Authentication","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthentication","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKUser\/authentication","navigatorTitle":[{"kind":"identifier","text":"authentication"}],"title":"authentication","role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"authentication","type":"codeVoice"},{"type":"text","text":" of the "},{"code":"User","type":"codeVoice"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"authentication"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"authentication","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthentication","text":"ZDKAuthentication","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Authentication"},{"kind":"text","text":" * "},{"text":"authentication","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKUser","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/fragments","op":"replace","value":[{"text":"ZDKUser","kind":"identifier"}]},{"op":"replace","value":"ZDKAuthentication","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Authentication\/title"},{"value":[{"kind":"identifier","text":"ZDKAuthentication"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Authentication\/fragments","op":"replace"},{"value":"authentication","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKUser~1authentication\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKUser~1authentication\/fragments","value":[{"text":"authentication","kind":"identifier"}],"op":"replace"}]}]}