{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastRead","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkparticipant\/lastread"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkparticipant\/lastread"]}],"abstract":[{"text":"The timestamp of the last read message","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant"]]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKParticipant\/lastRead","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"lastRead"}],"title":"lastRead","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant(py)lastRead","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastRead"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?","kind":"text"}]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Participant":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Participant"}],"abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/participant","title":"Participant","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","type":"topic","navigatorTitle":[{"text":"Participant","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKParticipant/lastRead":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKParticipant\/lastRead","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkparticipant\/lastread","title":"lastRead","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lastRead"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"The timestamp of the last read message"}],"navigatorTitle":[{"kind":"identifier","text":"lastRead"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"lastRead","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"lastRead"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"lastRead"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/title","value":"ZDKParticipant","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/fragments","value":[{"text":"ZDKParticipant","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKParticipant~1lastRead\/title","op":"replace","value":"lastRead"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKParticipant~1lastRead\/fragments","op":"replace","value":[{"text":"lastRead","kind":"identifier"}]}]}]}