{"defaultImplementationsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/stopFetchingWaitTime()-2ovyu"],"title":"ConversationKitShared Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"abstract":[{"type":"text","text":"Call to stop polling for updates to conversation wait time."}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/stopFetchingWaitTime()-7rnux","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"stopFetchingWaitTime"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"stopFetchingWaitTime()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopFetchingWaitTime","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","required":true,"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)stopFetchingWaitTime","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/stopfetchingwaittime()-7rnux"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/stopfetchingwaittime()-7rnux"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopFetchingWaitTime","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/stopFetchingWaitTime()-2ovyu":{"title":"stopFetchingWaitTime()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopFetchingWaitTime"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/stopFetchingWaitTime()-2ovyu","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/stopfetchingwaittime()-2ovyu","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/stopFetchingWaitTime()-7rnux":{"title":"stopFetchingWaitTime()","required":true,"kind":"symbol","navigatorTitle":[{"text":"stopFetchingWaitTime","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopFetchingWaitTime"},{"kind":"text","text":"()"}],"abstract":[{"text":"Call to stop polling for updates to conversation wait time.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/stopFetchingWaitTime()-7rnux","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/stopfetchingwaittime()-7rnux","defaultImplementations":1,"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConversationKitShared","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}],"title":"ConversationKitShared","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"stopFetchingWaitTime"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopFetchingWaitTime"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"stopFetchingWaitTime","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"stopFetchingWaitTime","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1stopFetchingWaitTime()-7rnux\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1stopFetchingWaitTime()-7rnux\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopFetchingWaitTime"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared"},{"value":[{"text":"ConversationKitShared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}