{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/webviewaction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/webviewaction"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction","doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKWebViewAction) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WebViewAction","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"WebViewAction"}],"role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWebViewAction","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"WebViewAction","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewAction"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/init(from:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/init(id:text:uri:default:fallback:metadata:openOnReceive:size:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/default","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/fallback","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/id","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/metadata","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/openOnReceive","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/size","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/text","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/type","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/uri"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/isEqual(_:)"]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/isEqual(_:)":{"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/isequal(_:)","title":"isEqual(_:)","type":"topic"},"doc://com.zendesk.ConversationKit/SE":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/text":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/text","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/text","title":"text","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"The action text to display."}],"navigatorTitle":[{"kind":"identifier","text":"text"}]},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/id":{"abstract":[{"text":"The resource id of this action.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/id","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"id","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/id","title":"id","type":"topic"},"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH"},"doc://com.zendesk.ConversationKit/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/Se"},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/init(id:text:uri:default:fallback:metadata:openOnReceive:size:)":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/init(id:text:uri:default:fallback:metadata:openOnReceive:size:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"uri","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"default"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"fallback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"openOnReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"text":"WebViewActionSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKWebViewActionSize"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/init(id:text:uri:default:fallback:metadata:openonreceive:size:)","title":"init(id:text:uri:default:fallback:metadata:openOnReceive:size:)","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/hash":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/hash","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/hash","title":"hash","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/description":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/description","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","title":"description","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/uri":{"navigatorTitle":[{"kind":"identifier","text":"uri"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/uri","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"uri","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","title":"uri","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/uri","abstract":[{"type":"text","text":"The action uri for when the action is selected."}]},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/init(from:)":{"abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"init(from:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/init(from:)"},"doc://com.zendesk.ConversationKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction":{"abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/webviewaction","navigatorTitle":[{"text":"WebViewAction","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WebViewAction"}],"title":"WebViewAction","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/fallback":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fallback"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"fallback","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/fallback","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/fallback","abstract":[{"type":"text","text":"The action fallback uri."}],"navigatorTitle":[{"text":"fallback","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKWebViewAction/default_":{"abstract":[{"text":"A flag indicating if this action is the default.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWebViewAction\/default_","fragments":[{"kind":"identifier","text":"default_"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkwebviewaction\/default_","title":"default_","type":"topic"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/metadata":{"abstract":[{"type":"text","text":"The metadata of this action"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/metadata","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"metadata"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":"]?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"metadata","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/metadata","title":"metadata","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/size":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/size","abstract":[{"type":"text","text":"The size of the webview"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WebViewActionSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKWebViewActionSize"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"size"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/size","title":"size","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageAction":{"title":"MessageAction","url":"\/documentation\/zendesksdkconversationkit\/messageaction","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageAction"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction","navigatorTitle":[{"text":"MessageAction","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/default":{"abstract":[{"type":"text","text":"A flag indicating if this action is the default."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/default","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/default","title":"default","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/type":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/type","url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/type","title":"type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType","text":"ActionType","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"ActionType","type":"codeVoice"},{"text":" of this action.","type":"text"}],"navigatorTitle":[{"text":"type","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction/openOnReceive":{"kind":"symbol","title":"openOnReceive","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/openOnReceive","role":"symbol","abstract":[{"text":"A flag indicating if the ","type":"text"},{"type":"codeVoice","code":"webview"},{"type":"text","text":" should open on receive"}],"navigatorTitle":[{"kind":"identifier","text":"openOnReceive"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openOnReceive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/zendesksdkconversationkit\/webviewaction\/openonreceive"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKWebViewAction","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"ZDKWebViewAction"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKWebViewAction","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/fallback","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/id","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/metadata","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/openOnReceive","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/size","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/text","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/type","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/uri","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWebViewAction\/default_"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction\/isEqual(_:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKWebViewAction"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1isEqual(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1text\/title","op":"replace","value":"text"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1text\/fragments","op":"replace","value":[{"text":"text","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1id\/title","op":"replace","value":"id"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1id\/fragments","value":[{"text":"id","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1hash\/title","value":"hash","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1hash\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1description\/title","value":"description","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1uri\/title","op":"replace","value":"uri"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1uri\/fragments","value":[{"text":"uri","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction\/title","op":"replace","value":"ZDKWebViewAction"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction\/fragments","value":[{"text":"ZDKWebViewAction","kind":"identifier"}]},{"op":"replace","value":"fallback","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1fallback\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1fallback\/fragments","value":[{"kind":"identifier","text":"fallback"}],"op":"replace"},{"value":"metadata","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1metadata\/title","op":"replace"},{"value":[{"text":"metadata","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1metadata\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1size\/title","value":"size","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1size\/fragments","value":[{"text":"size","kind":"identifier"}]},{"value":"ZDKMessageAction","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/title"},{"value":[{"kind":"identifier","text":"ZDKMessageAction"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1type\/title","value":"type"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1type\/fragments","op":"replace"},{"op":"replace","value":"openOnReceive","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1openOnReceive\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction~1openOnReceive\/fragments","value":[{"kind":"identifier","text":"openOnReceive"}]}]}]}