{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent"]},{"paths":["\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/init(from:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/init(quotedMessageId:formFields:metadata:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/formFields","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/fields","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/metadata","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/quotedMessageId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/isEqual(_:)"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"]}],"metadata":{"navigatorTitle":[{"text":"FormResponseMessageContent","kind":"identifier"}],"title":"FormResponseMessageContent","roleHeading":"Class","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKFormResponseMessageContent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FormResponseMessageContent","kind":"identifier"}],"symbolKind":"class","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKFormResponseMessageContent) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FormResponseMessageContent","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"codeVoice","code":"FormResponse"},{"type":"text","text":" related "},{"code":"MessageContent","type":"codeVoice"},{"type":"text","text":". Used to display a submitted form."}],"references":{"doc://com.zendesk.ConversationKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKFormResponseMessageContent/description":{"abstract":[],"kind":"symbol","title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/description","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/description","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent":{"abstract":[{"type":"codeVoice","code":"FormResponse"},{"text":" related ","type":"text"},{"code":"MessageContent","type":"codeVoice"},{"text":". Used to display a submitted form.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent","navigatorTitle":[{"text":"FormResponseMessageContent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseMessageContent","kind":"identifier"}],"role":"symbol","title":"FormResponseMessageContent","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent","kind":"symbol"},"doc://com.zendesk.ConversationKit/SE":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE","title":"Swift.Encodable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent/init(from:)":{"abstract":[],"kind":"symbol","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent\/init(from:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/init(from:)","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKFormResponseMessageContent/metadata":{"kind":"symbol","abstract":[{"text":"The metadata of the ","type":"text"},{"code":"Message","type":"codeVoice"}],"title":"metadata","navigatorTitle":[{"text":"metadata","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/metadata","url":"\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/metadata","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKFormResponseMessageContent/type":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The type  of the "},{"code":"Message","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","type":"topic","title":"type","url":"\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/type"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent/init(quotedMessageId:formFields:metadata:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/init(quotedMessageId:formFields:metadata:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"quotedMessageId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"formFields"},{"text":": [","kind":"text"},{"text":"FormField","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit9FormFieldO"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":"]?)"}],"abstract":[],"title":"init(quotedMessageId:formFields:metadata:)","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent\/init(quotedmessageid:formfields:metadata:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Content":{"role":"symbol","title":"Content","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Content"}],"navigatorTitle":[{"text":"Content","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/content","type":"topic","abstract":[]},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent/formFields":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The form fields for this form"}],"title":"formFields","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formFields"},{"kind":"text","text":": ["},{"text":"FormField","preciseIdentifier":"s:25ZendeskSDKConversationKit9FormFieldO","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/formFields","url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent\/formfields"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.ConversationKit/Se":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://com.zendesk.ConversationKit/SH":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKFormResponseMessageContent/fields":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/fields","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Field","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKField"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The form fields for this form"}],"title":"fields","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/fields","navigatorTitle":[{"kind":"identifier","text":"fields"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKFormResponseMessageContent/quotedMessageId":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/quotedMessageId","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"quotedMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"quotedMessageId","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/quotedmessageid","abstract":[{"type":"text","text":"The message id of the form to which this form response is responding."}],"navigatorTitle":[{"kind":"identifier","text":"quotedMessageId"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKFormResponseMessageContent/hash":{"kind":"symbol","type":"topic","title":"hash","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/hash","url":"\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"navigatorTitle":[{"text":"hash","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent/isEqual(_:)":{"kind":"symbol","abstract":[{"text":"Returns a Boolean value that indicates whether the receiver and a given object are equal.","type":"text"}],"title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/isEqual(_:)","url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent\/isequal(_:)","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ZDKFormResponseMessageContent","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKFormResponseMessageContent"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKFormResponseMessageContent","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/fields","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/metadata","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/quotedMessageId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/type"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/isEqual(_:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ZDKFormResponseMessageContent","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"value":"ZDKFormResponseMessageContent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/fragments","value":[{"text":"ZDKFormResponseMessageContent","kind":"identifier"}]},{"value":"metadata","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1metadata\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1metadata\/fragments","value":[{"text":"metadata","kind":"identifier"}]},{"value":"type","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1type\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1type\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"value":"ZDKMessageContent","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Content\/title","op":"replace"},{"value":[{"text":"ZDKMessageContent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Content\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1fields\/title","op":"replace","value":"fields"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1fields\/fragments","value":[{"text":"fields","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1quotedMessageId\/title","value":"quotedMessageId","op":"replace"},{"op":"replace","value":[{"text":"quotedMessageId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1quotedMessageId\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1hash\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent~1isEqual(_:)\/fragments"}]}]}