{"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","required":true,"modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property","title":"value","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKField(py)value","navigatorTitle":[{"kind":"identifier","text":"value"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field"]]},"abstract":[{"text":"The value of the field. Maps to the appropriate field that is related to the ","type":"text"},{"type":"codeVoice","code":"type"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkfield\/value"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkfield\/value"]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKField\/value","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"text"},{"text":" - the value is the ","type":"text"},{"type":"codeVoice","code":"text"},{"type":"text","text":" field."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"email"},{"text":" - the value is the ","type":"text"},{"type":"codeVoice","code":"email"},{"text":" field","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"select"},{"type":"text","text":" - the value is the "},{"code":"label","type":"codeVoice"},{"text":" property of the ","type":"text"},{"type":"codeVoice","code":"select"},{"text":" field","type":"text"}]}]}]},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Where "},{"code":"type","type":"codeVoice"},{"text":" is","type":"text"}]}],"style":"note","type":"aside"}],"kind":"content"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKField/value":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKField\/value","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","required":true,"abstract":[{"text":"The value of the field. Maps to the appropriate field that is related to the ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"value"}],"title":"value","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkfield\/value"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","role":"collection","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Field":{"navigatorTitle":[{"text":"Field","kind":"identifier"}],"title":"Field","abstract":[{"type":"text","text":"Objective-C representation of the fields in a "},{"code":"Form","type":"codeVoice"},{"type":"text","text":" message"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/field","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Field","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"value","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"value","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"value"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKField~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKField~1value\/fragments","value":[{"text":"value","kind":"identifier"}]},{"value":"ZDKField","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field\/fragments","value":[{"kind":"identifier","text":"ZDKField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}