{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageType"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/message\/messagetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/message\/messagetype"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message"]]},"abstract":[{"type":"text","text":"The type of the "},{"type":"codeVoice","code":"Message"}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","kind":"typeIdentifier","text":"MessageType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"messageType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"messageType"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage(py)messageType","title":"messageType"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/messageType":{"type":"topic","title":"messageType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/messageType","navigatorTitle":[{"text":"messageType","kind":"identifier"}],"abstract":[{"text":"The type of the ","type":"text"},{"type":"codeVoice","code":"Message"}],"role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/message\/messagetype"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the different "},{"code":"Message","type":"codeVoice"},{"text":" types in a ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"text":".","type":"text"}],"title":"MessageType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","navigatorTitle":[{"text":"MessageType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageType","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/messagetype"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Message"}],"navigatorTitle":[{"text":"Message","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","type":"topic","title":"Message","abstract":[],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/message"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"messageType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"messageType"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","kind":"typeIdentifier","text":"ZDKMessageType"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageType"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1messageType\/title","value":"messageType"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1messageType\/fragments","value":[{"text":"messageType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/title","value":"ZDKMessageType","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/fragments","value":[{"kind":"identifier","text":"ZDKMessageType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title","value":"ZDKMessage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","value":[{"kind":"identifier","text":"ZDKMessage"}]}]}]}