{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionDelay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}]}]}],"kind":"symbol","abstract":[{"text":"A delay for when the connect should be called.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/realtimesettings\/connectiondelay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/realtimesettings\/connectiondelay"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"connectionDelay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"symbolKind":"property","title":"connectionDelay","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"connectionDelay","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKRealtimeSettings(py)connectionDelay"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RealtimeSettings\/connectionDelay"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RealtimeSettings"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/RealtimeSettings/connectionDelay":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RealtimeSettings\/connectionDelay","title":"connectionDelay","abstract":[{"type":"text","text":"A delay for when the connect should be called."}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/realtimesettings\/connectiondelay","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"connectionDelay","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"connectionDelay","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/RealtimeSettings":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/RealtimeSettings","title":"RealtimeSettings","abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/realtimesettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RealtimeSettings","kind":"identifier"}],"navigatorTitle":[{"text":"RealtimeSettings","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"connectionDelay"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"connectionDelay"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"connectionDelay","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1RealtimeSettings~1connectionDelay\/title","value":"connectionDelay","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1RealtimeSettings~1connectionDelay\/fragments","value":[{"kind":"identifier","text":"connectionDelay"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1RealtimeSettings\/title","op":"replace","value":"ZDKRealtimeSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1RealtimeSettings\/fragments","value":[{"text":"ZDKRealtimeSettings","kind":"identifier"}]}]}]}