{"metadata":{"navigatorTitle":[{"text":"buildWith:config:featureFlagManager:callbackQueue:","kind":"identifier"}],"roleHeading":"Instance Method","title":"build(with:config:featureFlagManager:callbackQueue:)","externalID":"c:@CM@ZendeskSDKConversationKit@objc(cs)ZDKDefaultConversationKitBuilder(im)buildWith:config:featureFlagManager:callbackQueue:","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationKitSettings","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationKitSettings"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Config","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureFlagManager"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager","text":"FeatureFlagManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callbackQueue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier","text":"DispatchQueue"},{"text":") -> ","kind":"text"},{"text":"ConversationKitObjC","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit"}],"platforms":[]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"settings","kind":"internalParam"},{"kind":"text","text":": "},{"text":"ConversationKitSettings","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationKitSettings","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Config","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureFlagManager"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager","text":"FeatureFlagManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callbackQueue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue"},{"kind":"text","text":" = .main) -> "},{"text":"ConversationKitObjC","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder\/build(with:config:featureFlagManager:callbackQueue:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/defaultconversationkitbuilder\/build(with:config:featureflagmanager:callbackqueue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/defaultconversationkitbuilder\/build(with:config:featureflagmanager:callbackqueue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/DefaultConversationKitBuilder":{"title":"DefaultConversationKitBuilder","navigatorTitle":[{"kind":"identifier","text":"DefaultConversationKitBuilder"}],"url":"\/documentation\/zendesksdkconversationkit\/defaultconversationkitbuilder","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DefaultConversationKitBuilder","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitSettings":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings","navigatorTitle":[{"text":"ConversationKitSettings","kind":"identifier"}],"title":"ConversationKitSettings","url":"\/documentation\/zendesksdkconversationkit\/conversationkitsettings","type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitSettings"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config":{"url":"\/documentation\/zendesksdkconversationkit\/config","kind":"symbol","abstract":[],"title":"Config","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Config"}],"navigatorTitle":[{"text":"Config","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationKitObjC","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","type":"topic","title":"ConversationKitObjC","role":"symbol","abstract":[{"code":"ConversationKitObjC","type":"codeVoice"},{"text":" needs to be configured  with a ","type":"text"},{"code":"ConversationKitSettings","type":"codeVoice"},{"type":"text","text":" "},{"text":"that includes the necessary ","type":"text"},{"type":"codeVoice","code":"integrationId"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"integrationId"},{"type":"text","text":" can be retrieved from the Native Messaging dashboard."}],"navigatorTitle":[{"kind":"identifier","text":"ConversationKitObjC"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/DefaultConversationKitBuilder/build(with:config:featureFlagManager:callbackQueue:)":{"url":"\/documentation\/zendesksdkconversationkit\/defaultconversationkitbuilder\/build(with:config:featureflagmanager:callbackqueue:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationKitSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationKitSettings"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Config","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureFlagManager"},{"kind":"text","text":": "},{"text":"FeatureFlagManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callbackQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier","text":"DispatchQueue"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit","text":"ConversationKitObjC"}],"role":"symbol","kind":"symbol","title":"build(with:config:featureFlagManager:callbackQueue:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildWith:config:featureFlagManager:callbackQueue:"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder\/build(with:config:featureFlagManager:callbackQueue:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"buildWith:config:featureFlagManager:callbackQueue:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"buildWith:config:featureFlagManager:callbackQueue:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Qo@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit","text":"id<ZDKConversationKit>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"buildWith:"},{"text":"(","kind":"text"},{"text":"ZDKConversationKitSettings","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitSettings","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationKitSettings"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"settings"},{"kind":"text","text":" "},{"kind":"identifier","text":"config:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKConfig","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"kind":"text","text":" "},{"text":"featureFlagManager:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ZDKFeatureFlagManager","preciseIdentifier":"c:objc(cs)ZDKFeatureFlagManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"featureFlagManager"},{"kind":"text","text":" "},{"text":"callbackQueue:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSObject<OS_dispatch_queue>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue"},{"text":" *) ","kind":"text"},{"text":"callbackQueue","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKDefaultConversationKitBuilder","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder\/fragments","value":[{"text":"ZDKDefaultConversationKitBuilder","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKConversationKitSettings","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitSettings\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitSettings\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitSettings"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/title","value":"ZDKConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/fragments","value":[{"kind":"identifier","text":"ZDKConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title","value":"ZDKConversationKit"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments","value":[{"text":"ZDKConversationKit","kind":"identifier"}],"op":"replace"},{"value":"buildWith:config:featureFlagManager:callbackQueue:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder~1build(with:config:featureFlagManager:callbackQueue:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder~1build(with:config:featureFlagManager:callbackQueue:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"buildWith:config:featureFlagManager:callbackQueue:"}],"op":"replace"}]}]}