{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWebViewAction\/description"},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"property","role":"symbol","title":"description","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWebViewAction(py)description"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkwebviewaction\/description"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkwebviewaction\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewAction":{"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/webviewaction","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WebViewAction"}],"title":"WebViewAction","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WebViewAction"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewAction"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKWebViewAction/description":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWebViewAction\/description","role":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/zdkwebviewaction\/description","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"description","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction\/title","op":"replace","value":"ZDKWebViewAction"},{"value":[{"text":"ZDKWebViewAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewAction\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWebViewAction~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWebViewAction~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}