{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reply","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/reply","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypeReply"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"ActionType.reply","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"reply","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType@ZDKActionTypeReply"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/actiontype\/reply"]},{"paths":["\/documentation\/zendesksdkconversationkit\/actiontype\/reply"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"An action to send a quick reply to the conversation.","type":"text"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType/reply":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType\/reply","abstract":[{"type":"text","text":"An action to send a quick reply to the conversation."}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reply","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKActionTypeReply"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype\/reply","title":"ActionType.reply","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType":{"navigatorTitle":[{"text":"ActionType","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ActionType","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/actiontype","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","type":"topic","title":"ActionType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"ZDKActionTypeReply","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"ZDKActionTypeReply"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"ZDKActionTypeReply","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1reply\/title","value":"ZDKActionTypeReply"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType~1reply\/fragments","op":"replace","value":[{"text":"ZDKActionTypeReply","kind":"identifier"}]},{"value":"ZDKActionType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/title"},{"value":[{"text":"ZDKActionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/fragments"}]}]}