{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message"]]},"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage(im)initWithMediaURL:text:metadata:","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithMediaURL:text:metadata:"}],"roleHeading":"Initializer","title":"init(mediaURL:text:metadata:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"mediaURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":"]?)"}]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(mediaURL:text:metadata:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Failable init for sending a "},{"code":"Message","type":"codeVoice"},{"text":" that can be sent as an attachment. The type of this message may be either ","type":"text"},{"code":".file","type":"codeVoice"},{"text":", or ","type":"text"},{"code":".image","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/message\/init(mediaurl:text:metadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/message\/init(mediaurl:text:metadata:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"mediaURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":"]? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Local "},{"type":"codeVoice","code":"URL"},{"text":" of the file to be sent. This property also determines the type of the message.","type":"text"}]}],"name":"mediaURL"},{"name":"text","content":[{"type":"paragraph","inlineContent":[{"text":"Accompanying text to be sent with the attachment.","type":"text"}]}]},{"name":"metadata","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Dictionary"},{"text":" representing the message metadata","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Message","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Message"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","title":"Message"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/init(mediaURL:text:metadata:)":{"abstract":[{"text":"Failable init for sending a ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":" that can be sent as an attachment. The type of this message may be either ","type":"text"},{"code":".file","type":"codeVoice"},{"type":"text","text":", or "},{"type":"codeVoice","code":".image"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/init(mediaURL:text:metadata:)","type":"topic","title":"init(mediaURL:text:metadata:)","navigatorTitle":[{"kind":"identifier","text":"initWithMediaURL:text:metadata:"}],"url":"\/documentation\/zendesksdkconversationkit\/message\/init(mediaurl:text:metadata:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"mediaURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":"]?)"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithMediaURL:text:metadata:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMediaURL:text:metadata:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithMediaURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mediaURL"},{"kind":"text","text":" "},{"text":"text:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"text","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"metadata:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSObject *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"metadata"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title","op":"replace","value":"ZDKMessage"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","value":[{"text":"ZDKMessage","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1init(mediaURL:text:metadata:)\/title","value":"initWithMediaURL:text:metadata:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithMediaURL:text:metadata:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1init(mediaURL:text:metadata:)\/fragments"}]}]}