{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/hasactiveconversationinlatestten"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/hasactiveconversationinlatestten"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasActiveConversationInLatestTen","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"hasActiveConversationInLatestTen","kind":"identifier"}],"required":true,"roleHeading":"Instance Property","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(py)hasActiveConversationInLatestTen","role":"symbol","title":"hasActiveConversationInLatestTen"},"abstract":[{"type":"text","text":"Bool indicating if an active conversation was found within the first ten most recently updated conversations"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasActiveConversationInLatestTen","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/hasActiveConversationInLatestTen"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitShared","kind":"identifier"}],"abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationKitShared"}],"type":"topic","title":"ConversationKitShared"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/hasActiveConversationInLatestTen":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasActiveConversationInLatestTen"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/hasactiveconversationinlatestten","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/hasActiveConversationInLatestTen","required":true,"navigatorTitle":[{"text":"hasActiveConversationInLatestTen","kind":"identifier"}],"type":"topic","role":"symbol","title":"hasActiveConversationInLatestTen","abstract":[{"type":"text","text":"Bool indicating if an active conversation was found within the first ten most recently updated conversations"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"hasActiveConversationInLatestTen"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"hasActiveConversationInLatestTen","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"hasActiveConversationInLatestTen","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared"},{"value":[{"kind":"identifier","text":"ConversationKitShared"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1hasActiveConversationInLatestTen\/title","value":"hasActiveConversationInLatestTen"},{"op":"replace","value":[{"kind":"identifier","text":"hasActiveConversationInLatestTen"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1hasActiveConversationInLatestTen\/fragments"}]}]}