{"sections":[],"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKOpenWebViewMessageReceived","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKOpenWebViewMessageReceived","kind":"identifier"}],"role":"symbol","title":"ZDKOpenWebViewMessageReceived","symbolKind":"class","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"ZDKOpenWebViewMessageReceived"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKOpenWebViewMessageReceived","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived"]}],"abstract":[{"text":"A new message with a webview action ","type":"text"},{"type":"codeVoice","code":"openOnReceive"},{"type":"text","text":" has occurred"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/conversationId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/size","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/url"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"references":{"doc://com.zendesk.ConversationKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKOpenWebViewMessageReceived/size":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKWebViewActionSize","text":"WebViewActionSize","kind":"typeIdentifier"}],"title":"size","navigatorTitle":[{"text":"size","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived\/size","role":"symbol","abstract":[{"type":"text","text":"The size of the webview"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/size","kind":"symbol"},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKOpenWebViewMessageReceived/conversationId":{"type":"topic","abstract":[{"text":"The identifier of the ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" that the messages belong to."}],"url":"\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived\/conversationid","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"conversationId"}],"title":"conversationId","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/conversationId","role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKOpenWebViewMessageReceived/url":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/url","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"url"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived\/url","abstract":[{"type":"text","text":"The url "},{"type":"codeVoice","code":"String"},{"text":" of the Conversation Extension that needs to be opened.","type":"text"}],"title":"url"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKOpenWebViewMessageReceived":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKOpenWebViewMessageReceived","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKOpenWebViewMessageReceived","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkopenwebviewmessagereceived","abstract":[{"text":"A new message with a webview action ","type":"text"},{"type":"codeVoice","code":"openOnReceive"},{"type":"text","text":" has occurred"}],"title":"ZDKOpenWebViewMessageReceived"},"doc://com.zendesk.ConversationKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ConversationKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKOpenWebViewMessageReceived"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKOpenWebViewMessageReceived"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKOpenWebViewMessageReceived"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/conversationId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/size","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKOpenWebViewMessageReceived\/url"],"title":"Instance Properties"}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKOpenWebViewMessageReceived"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"size","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived~1size\/title"},{"value":[{"text":"size","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived~1size\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived~1conversationId\/title","value":"conversationId"},{"value":[{"text":"conversationId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived~1conversationId\/fragments"},{"op":"replace","value":"url","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived~1url\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived~1url\/fragments","value":[{"text":"url","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived\/title","op":"replace","value":"ZDKOpenWebViewMessageReceived"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKOpenWebViewMessageReceived\/fragments","value":[{"kind":"identifier","text":"ZDKOpenWebViewMessageReceived"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}