{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/activitytype\/conversationroutingcleared"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/activitytype\/conversationroutingcleared"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRoutingCleared"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationRoutingCleared","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"ActivityType.conversationRoutingCleared","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationRoutingCleared","kind":"identifier"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType@ZDKActivityTypeConversationRoutingCleared","navigatorTitle":[{"text":"ZDKActivityTypeConversationRoutingCleared","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Case"},"abstract":[{"text":"Receiving ‘conversation:routing:cleared’ clears the routing queue for a conversation.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"url":"\/documentation\/zendesksdkconversationkit\/activitytype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivityType","kind":"identifier"}],"kind":"symbol","type":"topic","title":"ActivityType","abstract":[],"navigatorTitle":[{"text":"ActivityType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/conversationRoutingCleared":{"kind":"symbol","title":"ActivityType.conversationRoutingCleared","abstract":[{"text":"Receiving ‘conversation:routing:cleared’ clears the routing queue for a conversation.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/activitytype\/conversationroutingcleared","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRoutingCleared","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationRoutingCleared","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKActivityTypeConversationRoutingCleared","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ZDKActivityTypeConversationRoutingCleared","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKActivityTypeConversationRoutingCleared"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ZDKActivityTypeConversationRoutingCleared"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title","value":"ZDKActivityType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments","value":[{"text":"ZDKActivityType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/navigatorTitle","value":[{"text":"ZDKActivityType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1conversationRoutingCleared\/title","value":"ZDKActivityTypeConversationRoutingCleared"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1conversationRoutingCleared\/fragments","value":[{"kind":"identifier","text":"ZDKActivityTypeConversationRoutingCleared"}]}]}]}