{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Existing ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":" updated for ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" with identifier."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"messageUpdated","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/messageUpdated"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/messageupdated"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/messageupdated"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventMessageUpdated","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"messageUpdated","kind":"identifier"}],"title":"ZDKConversationKitEvent.messageUpdated","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventMessageUpdated"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKConversationKitEvent","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","role":"symbol","navigatorTitle":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"abstract":[{"type":"text","text":"List of events that covers all events that could come from "},{"code":"ConversationKit","type":"codeVoice"},{"type":"text","text":"."}],"title":"ZDKConversationKitEvent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/messageUpdated":{"abstract":[{"text":"Existing ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":" updated for ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"text":" with identifier.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/messageUpdated","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageUpdated"}],"navigatorTitle":[{"text":"ZDKConversationKitEventMessageUpdated","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/messageupdated","title":"ZDKConversationKitEvent.messageUpdated"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"ZDKConversationKitEventMessageUpdated","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKConversationKitEventMessageUpdated"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ZDKConversationKitEventMessageUpdated"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKConversationKitEvent","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments","value":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKConversationKitEventMessageUpdated","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1messageUpdated\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1messageUpdated\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitEventMessageUpdated"}]}]}]}