{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType\/select","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"select"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Case","symbolKind":"case","title":"FieldType.select","navigatorTitle":[{"text":"ZDKFieldTypeSelect","kind":"identifier"}],"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"select","kind":"identifier"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType@ZDKFieldTypeSelect"},"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/fieldtype\/select"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/fieldtype\/select"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FieldType/select":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType\/select","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"select","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFieldTypeSelect"}],"type":"topic","title":"FieldType.select","url":"\/documentation\/zendesksdkconversationkit\/fieldtype\/select","abstract":[],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FieldType":{"type":"topic","title":"FieldType","url":"\/documentation\/zendesksdkconversationkit\/fieldtype","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FieldType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FieldType","kind":"identifier"}],"abstract":[{"type":"text","text":"Form field type. "},{"type":"codeVoice","code":"text"},{"type":"text","text":", "},{"type":"codeVoice","code":"email"},{"type":"text","text":", "},{"type":"codeVoice","code":"select"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKFieldTypeSelect","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ZDKFieldTypeSelect","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKFieldTypeSelect","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKFieldTypeSelect","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType~1select\/title"},{"value":[{"text":"ZDKFieldTypeSelect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType~1select\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/title","op":"replace","value":"ZDKFieldType"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/fragments","value":[{"kind":"identifier","text":"ZDKFieldType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}