{"kind":"symbol","abstract":[{"text":"A stop typing activity","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"typingStop"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/activitytype\/typingstop"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/activitytype\/typingstop"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/typingStop","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"case","title":"ActivityType.typingStop","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType@ZDKActivityTypeTypingStop","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"typingStop","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKActivityTypeTypingStop","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/typingStop":{"abstract":[{"text":"A stop typing activity","type":"text"}],"navigatorTitle":[{"text":"ZDKActivityTypeTypingStop","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/activitytype\/typingstop","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typingStop"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/typingStop","role":"symbol","title":"ActivityType.typingStop","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"title":"ActivityType","url":"\/documentation\/zendesksdkconversationkit\/activitytype","navigatorTitle":[{"text":"ActivityType","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivityType"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKActivityTypeTypingStop"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKActivityTypeTypingStop","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKActivityTypeTypingStop"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKActivityTypeTypingStop","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1typingStop\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1typingStop\/fragments","value":[{"text":"ZDKActivityTypeTypingStop","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title","value":"ZDKActivityType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments","value":[{"kind":"identifier","text":"ZDKActivityType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}