{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createAnonymousUser(with:surname:proactiveMessageId:)"},"metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAnonymousUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"surname","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"User","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"method","title":"createAnonymousUser(with:surname:proactiveMessageId:)","roleHeading":"Instance Method","platforms":[{"introducedAt":"13.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"13.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"13.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}],"externalID":"s:25ZendeskSDKConversationKit012ConversationC0P19createAnonymousUser4with7surname18proactiveMessageIdAA0G0CSSSg_A2JtYaKF","role":"symbol"},"abstract":[{"text":"Call to create an Anonymous ","type":"text"},{"code":"User","type":"codeVoice"},{"text":". This call will trigger a network request.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/createanonymoususer(with:surname:proactivemessageid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"defaultImplementationsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createAnonymousUser(with:surname:proactiveMessageId:)-44ik0"],"anchor":"ConversationKit-Implementations","title":"ConversationKit Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAnonymousUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"givenName","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"surname","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"User","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"givenName"},{"type":"text","text":" the user will be identified by."}]}],"name":"givenName"},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"surname"},{"type":"text","text":" the user will be identified by."}],"type":"paragraph"}],"name":"surname"},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"id","type":"codeVoice"},{"text":" of the Proactive Message.","type":"text"}]}],"name":"proactiveMessageId"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"Anonymous ","type":"text"},{"type":"codeVoice","code":"User"},{"text":" for the app.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"name":"Note","type":"aside","content":[{"inlineContent":[{"text":"If the ","type":"text"},{"code":"givenName","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"surname","type":"codeVoice"},{"text":" are empty, an anonymous user with a random name will be created.","type":"text"}],"type":"paragraph"}],"style":"note"},{"name":"Throws","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This will throw an error of type "},{"code":"ConversationKitError","type":"codeVoice"},{"type":"text","text":" in case of failure."}]}],"style":"note"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/createAnonymousUser(with:surname:proactiveMessageId:)-44ik0":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAnonymousUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"surname","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"User","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"Call to create an Anonymous "},{"type":"codeVoice","code":"User"},{"type":"text","text":". This call will trigger a network request."}],"type":"topic","title":"createAnonymousUser(with:surname:proactiveMessageId:)","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/createanonymoususer(with:surname:proactivemessageid:)-44ik0","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createAnonymousUser(with:surname:proactiveMessageId:)-44ik0"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/createAnonymousUser(with:surname:proactiveMessageId:)":{"type":"topic","title":"createAnonymousUser(with:surname:proactiveMessageId:)","defaultImplementations":1,"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/createanonymoususer(with:surname:proactivemessageid:)","abstract":[{"type":"text","text":"Call to create an Anonymous "},{"type":"codeVoice","code":"User"},{"type":"text","text":". This call will trigger a network request."}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnonymousUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"surname"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"proactiveMessageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createAnonymousUser(with:surname:proactiveMessageId:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"navigatorTitle":[{"kind":"identifier","text":"ConversationKit"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKit"}],"title":"ConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"type":"codeVoice","code":"SettingsParameters"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"type":"codeVoice","code":"AccessLevel"},{"type":"text","text":" and will check for a persisted user."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User":{"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"title":"User","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","navigatorTitle":[{"text":"User","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/title","value":"ZDKUser","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/fragments","value":[{"kind":"identifier","text":"ZDKUser"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/navigatorTitle","value":[{"text":"ZDKUser","kind":"identifier"}],"op":"replace"}]}]}