{"abstract":[{"text":"Call to create an Anonymous ","type":"text"},{"type":"codeVoice","code":"User"},{"text":". This call will trigger a network request.","type":"text"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAnonymousUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"surname","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"User","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"roleHeading":"Instance Method","required":true,"modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"s:25ZendeskSDKConversationKit012ConversationC0P19createAnonymousUser4with7surname18proactiveMessageId6resultySSSg_A2Iys6ResultOyAA0G0CAA0dC5ErrorOGcSgtF","role":"symbol","symbolKind":"method","title":"createAnonymousUser(with:surname:proactiveMessageId:result:)"},"defaultImplementationsSections":[{"title":"ConversationKit Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createAnonymousUser(with:surname:proactiveMessageId:result:)-3wbpr"],"anchor":"ConversationKit-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnonymousUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"givenName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"surname"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"proactiveMessageId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","kind":"typeIdentifier","text":"User"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","kind":"typeIdentifier","text":"ConversationKitError"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}]}]},{"kind":"parameters","parameters":[{"name":"givenName","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"givenName"},{"text":" the user will be identified by.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"surname","type":"codeVoice"},{"text":" the user will be identified by.","type":"text"}],"type":"paragraph"}],"name":"surname"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"id"},{"text":" of the Proactive Message.","type":"text"}],"type":"paragraph"}],"name":"proactiveMessageId"},{"content":[{"inlineContent":[{"text":"Anonymous ","type":"text"},{"type":"codeVoice","code":"User"},{"text":" for the app if successful, ","type":"text"},{"type":"codeVoice","code":"ConversationKitError"},{"text":" if not.","type":"text"}],"type":"paragraph"}],"name":"result"}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","name":"Note","style":"note","content":[{"inlineContent":[{"text":"If the ","type":"text"},{"code":"givenName","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"surname","type":"codeVoice"},{"text":" are empty, an anonymous user with a random name will be created.","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/createanonymoususer(with:surname:proactivemessageid:result:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createAnonymousUser(with:surname:proactiveMessageId:result:)"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/createAnonymousUser(with:surname:proactiveMessageId:result:)":{"abstract":[{"text":"Call to create an Anonymous ","type":"text"},{"code":"User","type":"codeVoice"},{"text":". This call will trigger a network request.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAnonymousUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"surname","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"User","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"title":"createAnonymousUser(with:surname:proactiveMessageId:result:)","role":"symbol","required":true,"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/createanonymoususer(with:surname:proactivemessageid:result:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createAnonymousUser(with:surname:proactiveMessageId:result:)","defaultImplementations":1},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User":{"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"title":"User","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","navigatorTitle":[{"text":"User","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitError":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkiterror","navigatorTitle":[{"text":"ConversationKitError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitError","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","type":"topic","title":"ConversationKitError","abstract":[{"type":"text","text":"Errors that could be returned from "},{"type":"codeVoice","code":"ConversationKit"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"navigatorTitle":[{"kind":"identifier","text":"ConversationKit"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKit"}],"title":"ConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"type":"codeVoice","code":"SettingsParameters"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"type":"codeVoice","code":"AccessLevel"},{"type":"text","text":" and will check for a persisted user."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/createAnonymousUser(with:surname:proactiveMessageId:result:)-3wbpr":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/createanonymoususer(with:surname:proactivemessageid:result:)-3wbpr","abstract":[{"type":"text","text":"Call to create an Anonymous "},{"type":"codeVoice","code":"User"},{"type":"text","text":". This call will trigger a network request."}],"title":"createAnonymousUser(with:surname:proactiveMessageId:result:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAnonymousUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"surname","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"User","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ConversationKitError","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createAnonymousUser(with:surname:proactiveMessageId:result:)-3wbpr","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKUser","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/title"},{"value":[{"text":"ZDKUser","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/fragments"},{"value":[{"kind":"identifier","text":"ZDKUser"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/navigatorTitle"}]}]}