{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createConversation(proactiveMessageId:result:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"metadata":{"externalID":"s:25ZendeskSDKConversationKit012ConversationC0P06createD018proactiveMessageId6resultySSSg_ys6ResultOyAA0D0CAA0dC5ErrorOGcSgtF","required":true,"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"createConversation(proactiveMessageId:result:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","text":"ConversationKitError","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/createconversation(proactivemessageid:result:)"]}],"abstract":[{"type":"text","text":"Call to create a "},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":" for the current "},{"code":"User","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","text":"ConversationKitError","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"proactiveMessageId","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"id"},{"text":" of the Proactive Message.","type":"text"}],"type":"paragraph"}]},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" if successful, "},{"type":"codeVoice","code":"ConversationKitError"},{"type":"text","text":" if not."}]}]}],"kind":"parameters"}],"defaultImplementationsSections":[{"title":"ConversationKit Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createConversation(proactiveMessageId:result:)-8ns7r"],"anchor":"ConversationKit-Implementations"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/createConversation(proactiveMessageId:result:)-8ns7r":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Conversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ConversationKitError","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","title":"createConversation(proactiveMessageId:result:)","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createConversation(proactiveMessageId:result:)-8ns7r","abstract":[{"type":"text","text":"Call to create a "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" for the current "},{"type":"codeVoice","code":"User"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/createconversation(proactivemessageid:result:)-8ns7r"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/createConversation(proactiveMessageId:result:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","text":"ConversationKitError","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/createconversation(proactivemessageid:result:)","required":true,"defaultImplementations":1,"abstract":[{"type":"text","text":"Call to create a "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" for the current "},{"type":"codeVoice","code":"User"},{"type":"text","text":"."}],"title":"createConversation(proactiveMessageId:result:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/createConversation(proactiveMessageId:result:)","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"navigatorTitle":[{"kind":"identifier","text":"ConversationKit"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKit"}],"title":"ConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"type":"codeVoice","code":"SettingsParameters"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"type":"codeVoice","code":"AccessLevel"},{"type":"text","text":" and will check for a persisted user."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitError":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkiterror","navigatorTitle":[{"text":"ConversationKitError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitError","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","type":"topic","title":"ConversationKitError","abstract":[{"type":"text","text":"Errors that could be returned from "},{"type":"codeVoice","code":"ConversationKit"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"title":"Conversation","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","value":"ZDKConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments","value":[{"kind":"identifier","text":"ZDKConversation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/navigatorTitle","value":[{"text":"ZDKConversation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}