{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"metadata":{"title":"fetchWaitTimeForConversation(conversationId:)","symbolKind":"method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchWaitTimeForConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"WaitTimeData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">","kind":"text"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS","introducedAt":"13.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"13.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.0"}],"role":"symbol","roleHeading":"Instance Method","externalID":"s:25ZendeskSDKConversationKit012ConversationC0P016fetchWaitTimeForD014conversationId7Combine12AnyPublisherVyAA0fG4DataCAA0dC5ErrorOGSS_tF","modules":[{"name":"ZendeskSDKConversationKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchWaitTimeForConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"WaitTimeData","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"text":", ","kind":"text"},{"text":"ConversationKitError","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"conversationId","content":[{"type":"paragraph","inlineContent":[{"text":"The Id of the conversation to fetch the wait time for.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"code":"AnyPublisher","type":"codeVoice"},{"type":"text","text":" that passes through "},{"code":"WaitTimeData","type":"codeVoice"},{"type":"text","text":" and "},{"code":"ConversationKitError","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"containing the wait time data associated with the conversation if successful, "},{"code":"ConversationKitError","type":"codeVoice"},{"type":"text","text":" if not."}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/fetchWaitTimeForConversation(conversationId:)","interfaceLanguage":"swift"},"defaultImplementationsSections":[{"title":"ConversationKit Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/fetchWaitTimeForConversation(conversationId:)-8u02m"],"anchor":"ConversationKit-Implementations"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/fetchwaittimeforconversation(conversationid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Fetches the current wait time for a specific conversation.","type":"text"},{"text":" ","type":"text"},{"text":"If polling is enabled, this call will initiate polling for updates to wait time.","type":"text"},{"text":" ","type":"text"},{"text":"Results received from polling or polling retries will be received on the publisher and also will be emitted as ","type":"text"},{"type":"codeVoice","code":"ConversationKitEvent"},{"text":"s.","type":"text"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"WaitTimeData"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WaitTimeData"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","type":"topic","kind":"symbol","title":"WaitTimeData","url":"\/documentation\/zendesksdkconversationkit\/waittimedata"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/fetchWaitTimeForConversation(conversationId:)":{"abstract":[{"text":"Fetches the current wait time for a specific conversation.","type":"text"},{"text":" ","type":"text"},{"text":"If polling is enabled, this call will initiate polling for updates to wait time.","type":"text"},{"text":" ","type":"text"},{"text":"Results received from polling or polling retries will be received on the publisher and also will be emitted as ","type":"text"},{"type":"codeVoice","code":"ConversationKitEvent"},{"text":"s.","type":"text"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchWaitTimeForConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"WaitTimeData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">","kind":"text"}],"role":"symbol","defaultImplementations":1,"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/fetchWaitTimeForConversation(conversationId:)","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/fetchwaittimeforconversation(conversationid:)","kind":"symbol","title":"fetchWaitTimeForConversation(conversationId:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"navigatorTitle":[{"kind":"identifier","text":"ConversationKit"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKit"}],"title":"ConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"type":"codeVoice","code":"SettingsParameters"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"type":"codeVoice","code":"AccessLevel"},{"type":"text","text":" and will check for a persisted user."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitError":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkiterror","navigatorTitle":[{"text":"ConversationKitError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitError","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","type":"topic","title":"ConversationKitError","abstract":[{"type":"text","text":"Errors that could be returned from "},{"type":"codeVoice","code":"ConversationKit"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/fetchWaitTimeForConversation(conversationId:)-8u02m":{"abstract":[{"text":"Fetches the current wait time for a specific conversation.","type":"text"},{"text":" ","type":"text"},{"text":"If polling is enabled, this call will initiate polling for updates to wait time.","type":"text"},{"text":" ","type":"text"},{"text":"Results received from polling or polling retries will be received on the publisher and also will be emitted as ","type":"text"},{"type":"codeVoice","code":"ConversationKitEvent"},{"text":"s.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/fetchwaittimeforconversation(conversationid:)-8u02m","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/fetchWaitTimeForConversation(conversationId:)-8u02m","title":"fetchWaitTimeForConversation(conversationId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchWaitTimeForConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"WaitTimeData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"text":">","kind":"text"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/title","value":"ZDKWaitTimeData","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/fragments","value":[{"kind":"identifier","text":"ZDKWaitTimeData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/navigatorTitle","value":[{"text":"ZDKWaitTimeData","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}