{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getConversations(offset:)-7ekxg","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Call to fetch the user’s list of conversations. This call will fetch the conversations list from storage,"},{"type":"text","text":" "},{"type":"text","text":"and will trigger a network request if no conversation has been previously persisted."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"s:25ZendeskSDKConversationKit012ConversationC0PAAE16getConversations6offsetAA0D4ListCSi_tYaKF","extendedModule":"ZendeskSDKConversationKit","roleHeading":"Instance Method","title":"getConversations(offset:)","modules":[{"name":"ZendeskSDKConversationKit"}],"platforms":[{"introducedAt":"13.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"introducedAt":"13.0","deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false}],"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationList","text":"ConversationList","kind":"typeIdentifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/getconversations(offset:)-7ekxg"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList","text":"ConversationList","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationList"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The number of items to skip before starting to collect the result set.","type":"text"}],"type":"paragraph"}],"name":"offset"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"A list of ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"text":" objects.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"name":"Throws","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This will throw an error of type "},{"type":"codeVoice","code":"ConversationKitError"},{"type":"text","text":" in case of failure."}]}],"style":"note","type":"aside"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"navigatorTitle":[{"kind":"identifier","text":"ConversationKit"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKit"}],"title":"ConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"type":"codeVoice","code":"SettingsParameters"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"type":"codeVoice","code":"AccessLevel"},{"type":"text","text":" and will check for a persisted user."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationList":{"title":"ConversationList","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationList"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationList"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList","url":"\/documentation\/zendesksdkconversationkit\/conversationlist"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/getConversations(offset:)-7ekxg":{"kind":"symbol","title":"getConversations(offset:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getConversations(offset:)-7ekxg","url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/getconversations(offset:)-7ekxg","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"ConversationList","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationList"}],"abstract":[{"type":"text","text":"Call to fetch the user’s list of conversations. This call will fetch the conversations list from storage,"},{"type":"text","text":" "},{"type":"text","text":"and will trigger a network request if no conversation has been previously persisted."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/title","value":"ZDKConversationList"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/fragments","value":[{"kind":"identifier","text":"ZDKConversationList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConversationList"}]}]}]}