{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"getVisitType()","platforms":[{"beta":false,"introducedAt":"13.0","deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"introducedAt":"13.0","deprecated":false,"name":"iPadOS","unavailable":false},{"beta":false,"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst","unavailable":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVisitType"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"VisitType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKVisitType"}],"required":true,"externalID":"s:25ZendeskSDKConversationKit012ConversationC0P12getVisitTypeAA0fG0OyYaKF"},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getVisitType()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/getvisittype()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"kind":"symbol","defaultImplementationsSections":[{"anchor":"ConversationKit-Implementations","title":"ConversationKit Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getVisitType()-4xmkx"]}],"abstract":[{"type":"text","text":"Call to get the "},{"type":"codeVoice","code":"VisitType"},{"type":"text","text":" for the current visitor."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getVisitType","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/VisitType","text":"VisitType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKVisitType"}]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"VisitType","type":"codeVoice"},{"text":" object.","type":"text"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"name":"Throws","content":[{"inlineContent":[{"text":"This will throw an error of type ","type":"text"},{"type":"codeVoice","code":"ConversationKitError"},{"text":" in case of failure.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/getVisitType()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVisitType"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"VisitType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKVisitType"}],"required":true,"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/getvisittype()","title":"getVisitType()","abstract":[{"type":"text","text":"Call to get the "},{"type":"codeVoice","code":"VisitType"},{"type":"text","text":" for the current visitor."}],"defaultImplementations":1,"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getVisitType()","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"navigatorTitle":[{"kind":"identifier","text":"ConversationKit"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKit"}],"title":"ConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"type":"codeVoice","code":"SettingsParameters"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"type":"codeVoice","code":"AccessLevel"},{"type":"text","text":" and will check for a persisted user."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/VisitType":{"title":"VisitType","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/visittype","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/VisitType","abstract":[{"type":"text","text":"Represents the possible visit types for the SDK."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VisitType"}],"navigatorTitle":[{"kind":"identifier","text":"VisitType"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/getVisitType()-4xmkx":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getVisitType()-4xmkx","type":"topic","title":"getVisitType()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVisitType"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"VisitType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKVisitType"}],"kind":"symbol","abstract":[{"type":"text","text":"Call to get the "},{"type":"codeVoice","code":"VisitType"},{"type":"text","text":" for the current visitor."}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/getvisittype()-4xmkx"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1VisitType\/title","value":"ZDKVisitType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1VisitType\/fragments","value":[{"kind":"identifier","text":"ZDKVisitType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1VisitType\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKVisitType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}