{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getVisitType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKVisitType","text":"VisitType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/VisitType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","text":"ConversationKitError","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}]}],"kind":"declarations"},{"parameters":[{"name":"result","content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"VisitType"},{"type":"text","text":" if successful, "},{"type":"codeVoice","code":"ConversationKitError"},{"type":"text","text":" if not."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/getvisittype(result:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"abstract":[{"text":"Call to get the ","type":"text"},{"code":"VisitType","type":"codeVoice"},{"text":" for the current visitor.","type":"text"}],"defaultImplementationsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getVisitType(result:)-77y4k"],"title":"ConversationKit Implementations","anchor":"ConversationKit-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getVisitType(result:)"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVisitType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"result"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKVisitType","text":"VisitType"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO","text":"ConversationKitError"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"required":true,"symbolKind":"method","modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","externalID":"s:25ZendeskSDKConversationKit012ConversationC0P12getVisitType6resultyys6ResultOyAA0fG0OAA0dC5ErrorOGcSg_tF","roleHeading":"Instance Method","title":"getVisitType(result:)"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/getVisitType(result:)-77y4k":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getVisitType(result:)-77y4k","title":"getVisitType(result:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getVisitType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"VisitType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKVisitType"},{"text":", ","kind":"text"},{"text":"ConversationKitError","kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Call to get the ","type":"text"},{"type":"codeVoice","code":"VisitType"},{"type":"text","text":" for the current visitor."}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/getvisittype(result:)-77y4k"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/getVisitType(result:)":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/getvisittype(result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVisitType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"result"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"VisitType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKVisitType"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ConversationKitError","preciseIdentifier":"s:25ZendeskSDKConversationKit012ConversationC5ErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Call to get the "},{"type":"codeVoice","code":"VisitType"},{"type":"text","text":" for the current visitor."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/getVisitType(result:)","required":true,"role":"symbol","title":"getVisitType(result:)","defaultImplementations":1},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"navigatorTitle":[{"kind":"identifier","text":"ConversationKit"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKit"}],"title":"ConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"type":"codeVoice","code":"SettingsParameters"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"type":"codeVoice","code":"AccessLevel"},{"type":"text","text":" and will check for a persisted user."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/VisitType":{"title":"VisitType","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/visittype","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/VisitType","abstract":[{"type":"text","text":"Represents the possible visit types for the SDK."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VisitType"}],"navigatorTitle":[{"kind":"identifier","text":"VisitType"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitError":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkiterror","navigatorTitle":[{"text":"ConversationKitError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitError","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitError","type":"topic","title":"ConversationKitError","abstract":[{"type":"text","text":"Errors that could be returned from "},{"type":"codeVoice","code":"ConversationKit"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1VisitType\/title","value":"ZDKVisitType","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKVisitType"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1VisitType\/fragments"},{"value":[{"text":"ZDKVisitType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1VisitType\/navigatorTitle"}]}]}