{"abstract":[{"type":"text","text":"Call to send an activity "},{"code":"ActivityType","type":"codeVoice"}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendConversationActivity(activity:conversationId:)","interfaceLanguage":"swift"},"defaultImplementationsSections":[{"anchor":"ConversationKit-Implementations","title":"ConversationKit Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendConversationActivity(activity:conversationId:)-4hbrj"]}],"metadata":{"title":"sendConversationActivity(activity:conversationId:)","required":true,"symbolKind":"method","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS","introducedAt":"13.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"13.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.0"}],"roleHeading":"Instance Method","modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendConversationActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"activity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType","text":"ActivityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"externalID":"s:25ZendeskSDKConversationKit012ConversationC0P04sendD8Activity8activity14conversationIdyAA0F4TypeO_SStYaKF"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkit\/sendconversationactivity(activity:conversationid:)"]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendConversationActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"activity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActivityType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ActivityType"},{"text":" that is to be sent","type":"text"}],"type":"paragraph"}],"name":"activity"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":"that the "},{"type":"codeVoice","code":"Activity"},{"type":"text","text":" will be sent"}]}],"name":"conversationId"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Available Activity Types are:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"conversationRead"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"typingStart"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"typingStop","type":"codeVoice"}]}]}]},{"type":"aside","style":"note","name":"Throws","content":[{"inlineContent":[{"type":"text","text":"This will throw an error of type "},{"type":"codeVoice","code":"ConversationKitError"},{"type":"text","text":" in case of failure."}],"type":"paragraph"}]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/sendConversationActivity(activity:conversationId:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendConversationActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"activity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ActivityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"defaultImplementations":1,"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/sendconversationactivity(activity:conversationid:)","title":"sendConversationActivity(activity:conversationId:)","required":true,"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendConversationActivity(activity:conversationId:)","kind":"symbol","abstract":[{"type":"text","text":"Call to send an activity "},{"type":"codeVoice","code":"ActivityType"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"navigatorTitle":[{"kind":"identifier","text":"ConversationKit"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkit","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKit"}],"title":"ConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"type":"codeVoice","code":"SettingsParameters"},{"type":"text","text":" (that contains "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"type":"codeVoice","code":"AccessLevel"},{"type":"text","text":" and will check for a persisted user."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"title":"ActivityType","url":"\/documentation\/zendesksdkconversationkit\/activitytype","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityType"}],"navigatorTitle":[{"kind":"identifier","text":"ActivityType"}],"role":"symbol","abstract":[],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit/sendConversationActivity(activity:conversationId:)-4hbrj":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendConversationActivity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"activity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ActivityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkit\/sendconversationactivity(activity:conversationid:)-4hbrj","title":"sendConversationActivity(activity:conversationId:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit\/sendConversationActivity(activity:conversationId:)-4hbrj","kind":"symbol","abstract":[{"type":"text","text":"Call to send an activity "},{"type":"codeVoice","code":"ActivityType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title","value":"ZDKActivityType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments","value":[{"kind":"identifier","text":"ZDKActivityType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/navigatorTitle","value":[{"text":"ZDKActivityType","kind":"identifier"}]}]}]}