{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRead","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A conversationRead activity"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/activitytype\/conversationread"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/activitytype\/conversationread"]}],"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType@ZDKActivityTypeConversationRead","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationRead","kind":"identifier"}],"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"ActivityType.conversationRead","navigatorTitle":[{"text":"ZDKActivityTypeConversationRead","kind":"identifier"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationRead"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"navigatorTitle":[{"text":"ActivityType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityType"}],"url":"\/documentation\/zendesksdkconversationkit\/activitytype","abstract":[],"role":"symbol","type":"topic","kind":"symbol","title":"ActivityType"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/conversationRead":{"navigatorTitle":[{"kind":"identifier","text":"ZDKActivityTypeConversationRead"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRead","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"conversationRead","kind":"identifier"}],"abstract":[{"text":"A conversationRead activity","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/activitytype\/conversationread","role":"symbol","type":"topic","kind":"symbol","title":"ActivityType.conversationRead"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"ZDKActivityTypeConversationRead","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKActivityTypeConversationRead","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ZDKActivityTypeConversationRead","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title","value":"ZDKActivityType","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments","op":"replace","value":[{"text":"ZDKActivityType","kind":"identifier"}]},{"op":"replace","value":"ZDKActivityTypeConversationRead","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1conversationRead\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1conversationRead\/fragments","op":"replace","value":[{"text":"ZDKActivityTypeConversationRead","kind":"identifier"}]}]}]}