{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthenticationType","text":"AuthenticationType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"roleHeading":"Instance Property","title":"type","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthentication(py)type","symbolKind":"property"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthenticationType","kind":"typeIdentifier","text":"AuthenticationType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKAuthentication\/type"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkauthentication\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkauthentication\/type"]}],"abstract":[{"text":"The type of authentication that the current ","type":"text"},{"type":"codeVoice","code":"User"},{"text":" has","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Authentication"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/AuthenticationType":{"navigatorTitle":[{"text":"AuthenticationType","kind":"identifier"}],"title":"AuthenticationType","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/authenticationtype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthenticationType","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Authentication":{"navigatorTitle":[{"text":"Authentication","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/authentication","title":"Authentication","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Authentication","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Authentication"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKAuthentication/type":{"kind":"symbol","abstract":[{"type":"text","text":"The type of authentication that the current "},{"type":"codeVoice","code":"User"},{"text":" has","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkauthentication\/type","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKAuthentication\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthenticationType","text":"AuthenticationType","kind":"typeIdentifier"}],"title":"type"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"type","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthenticationType","kind":"typeIdentifier","text":"ZDKAuthenticationType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/title","op":"replace","value":"ZDKAuthenticationType"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAuthenticationType"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Authentication\/title","op":"replace","value":"ZDKAuthentication"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Authentication\/fragments","op":"replace","value":[{"text":"ZDKAuthentication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKAuthentication~1type\/title","value":"type"},{"op":"replace","value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKAuthentication~1type\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}