{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem\/init(title:itemDescription:mediaURL:size:mediaType:actions:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"itemDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"mediaURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageItemSize","text":"ActionItemSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"actions","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO","text":"MessageActionModel"},{"text":"])","kind":"text"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Initializer","role":"symbol","externalID":"s:25ZendeskSDKConversationKit17MessageActionItemC5title15itemDescription8mediaURL4size0J4Type7actionsACSS_S2SAA0eF4SizeOSSSayAA0dE5ModelOGtcfc","symbolKind":"init","title":"init(title:itemDescription:mediaURL:size:mediaType:actions:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"itemDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mediaURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageItemSize","kind":"typeIdentifier","text":"ActionItemSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"actions","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionModel","kind":"typeIdentifier","text":"MessageActionModel","preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/messageactionitem\/init(title:itemdescription:mediaurl:size:mediatype:actions:)"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionItem/init(title:itemDescription:mediaURL:size:mediaType:actions:)":{"role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"itemDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaURL"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionItemSize","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageItemSize"},{"kind":"text","text":", "},{"text":"mediaType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"actions","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO","text":"MessageActionModel","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionitem\/init(title:itemdescription:mediaurl:size:mediatype:actions:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem\/init(title:itemDescription:mediaURL:size:mediaType:actions:)","kind":"symbol","title":"init(title:itemDescription:mediaURL:size:mediaType:actions:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","role":"collection","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionItem":{"url":"\/documentation\/zendesksdkconversationkit\/messageactionitem","type":"topic","abstract":[{"text":"An item in a list type message, such as list or carousel.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageActionItem"}],"kind":"symbol","title":"MessageActionItem","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","navigatorTitle":[{"kind":"identifier","text":"MessageActionItem"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionModel":{"kind":"symbol","title":"MessageActionModel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessageActionModel","kind":"identifier"}],"navigatorTitle":[{"text":"MessageActionModel","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionmodel","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionModel","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize","kind":"symbol","abstract":[{"text":"The display size of ","type":"text"},{"type":"codeVoice","code":"MessageActionItem"},{"type":"text","text":"."}],"title":"ActionItemSize","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/actionitemsize","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionItemSize"}],"navigatorTitle":[{"kind":"identifier","text":"ActionItemSize"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/title","op":"replace","value":"ZDKMessageActionItem"},{"value":[{"kind":"identifier","text":"ZDKMessageActionItem"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/title","op":"replace","value":"ZDKMessageItemSize"},{"op":"replace","value":[{"text":"ZDKMessageItemSize","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/fragments"}]}]}