{"sections":[],"abstract":[{"type":"text","text":"This property exists for backwards-compatability only, and will be removed in an upcoming ConversationKit version."},{"text":" ","type":"text"},{"type":"text","text":"Use the other init method that includes metadata."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","text":"ConversationType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isDefault","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"displayName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"displayDescription","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"iconURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"business"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"businessLastRead"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"text":"lastUpdatedAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? = nil, "},{"text":"participants","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","text":"Participant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","kind":"typeIdentifier"},{"kind":"text","text":"] = [], "},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Message","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","kind":"typeIdentifier"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"hasPrevious"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"myself"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Participant","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"activity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","kind":"typeIdentifier","text":"Activity"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"text":"ConversationStatus","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationStatus"},{"text":" = .unknown)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/init(id:type:isdefault:displayname:displaydescription:iconurl:business:businesslastread:lastupdatedat:participants:messages:hasprevious:myself:activity:status:)"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/init(id:type:isdefault:displayname:displaydescription:iconurl:business:businesslastread:lastupdatedat:participants:messages:hasprevious:myself:activity:status:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"]]},"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:)","role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationType","text":"ConversationType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDefault"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"displayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"displayDescription","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"iconURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"business"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"businessLastRead","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"lastUpdatedAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"participants","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","kind":"typeIdentifier","text":"Participant"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"messages"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Message","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage"},{"kind":"text","text":"], "},{"text":"hasPrevious","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"myself"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","kind":"typeIdentifier","text":"Participant"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"activity"},{"text":": ","kind":"text"},{"text":"Activity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationStatus"},{"kind":"text","text":")"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation(im)initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity":{"abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/activity","title":"Activity","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","navigatorTitle":[{"text":"Activity","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Activity"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation/init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:)":{"title":"init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:)","navigatorTitle":[{"text":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation\/init(id:type:isdefault:displayname:displaydescription:iconurl:business:businesslastread:lastupdatedat:participants:messages:hasprevious:myself:activity:status:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This property exists for backwards-compatability only, and will be removed in an upcoming ConversationKit version."},{"text":" ","type":"text"},{"type":"text","text":"Use the other init method that includes metadata."}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"ConversationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isDefault"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"displayName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"displayDescription","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"business","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"businessLastRead","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"lastUpdatedAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"text":"?, ","kind":"text"},{"text":"participants","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Participant","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant"},{"kind":"text","text":"], "},{"text":"messages","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Message","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hasPrevious"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"myself"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Participant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"activity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"Activity","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationStatus","text":"ConversationStatus"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationStatus":{"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationstatus","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationStatus"}],"title":"ConversationStatus","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus","abstract":[{"type":"text","text":"Represents the status of the "},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","title":"Conversation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversation"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"navigatorTitle":[{"text":"Message","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Message","kind":"identifier"}],"title":"Message","kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/message"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType":{"navigatorTitle":[{"text":"ConversationType","kind":"identifier"}],"abstract":[{"text":"Represents the possible types of a ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConversationType","kind":"identifier"}],"role":"symbol","title":"ConversationType","url":"\/documentation\/zendesksdkconversationkit\/conversationtype","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Participant":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","title":"Participant","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Participant","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Participant"}],"abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/participant"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"id","kind":"internalParam"},{"kind":"text","text":" "},{"text":"type:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ZDKConversationType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isDefault:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isDefault","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"displayName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"displayName"},{"kind":"text","text":" "},{"text":"displayDescription:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"displayDescription","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconURL:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"iconURL","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"business:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"business","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"businessLastRead:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"businessLastRead"},{"text":" ","kind":"text"},{"text":"lastUpdatedAt:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"text":" *) ","kind":"text"},{"text":"lastUpdatedAt","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"participants:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<ZDKParticipant *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"participants","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messages:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKMessage *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"messages"},{"kind":"text","text":" "},{"text":"hasPrevious:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"hasPrevious"},{"kind":"text","text":" "},{"kind":"identifier","text":"myself:"},{"kind":"text","text":"("},{"text":"ZDKParticipant","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant"},{"kind":"text","text":" *) "},{"text":"myself","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activity:"},{"kind":"text","text":"("},{"text":"ZDKActivity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"activity"},{"kind":"text","text":" "},{"text":"status:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationStatus","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus","kind":"typeIdentifier","text":"ZDKConversationStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/title","value":"ZDKActivity","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/fragments","value":[{"text":"ZDKActivity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:)\/title","op":"replace","value":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:participants:messages:hasPrevious:myself:activity:status:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus\/title","value":"ZDKConversationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus\/fragments","value":[{"text":"ZDKConversationStatus","kind":"identifier"}]},{"value":"ZDKConversation","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title"},{"value":[{"text":"ZDKConversation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title","value":"ZDKMessage"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","value":[{"text":"ZDKMessage","kind":"identifier"}],"op":"replace"},{"value":"ZDKConversationType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType\/fragments","value":[{"text":"ZDKConversationType","kind":"identifier"}],"op":"replace"},{"value":"ZDKParticipant","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/fragments","value":[{"kind":"identifier","text":"ZDKParticipant"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}