{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus\/idle","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Conversation"},{"text":" is inactive","type":"text"}],"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationStatus@ZDKConversationStatusIdle","role":"symbol","navigatorTitle":[{"text":"ZDKConversationStatusIdle","kind":"identifier"}],"symbolKind":"case","title":"ConversationStatus.idle","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}]},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationstatus\/idle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationstatus\/idle"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationStatus/idle":{"title":"ConversationStatus.idle","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus\/idle","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Conversation"},{"text":" is inactive","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationstatus\/idle","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationStatusIdle"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationStatus":{"title":"ConversationStatus","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus","type":"topic","abstract":[{"text":"Represents the status of the ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationStatus"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationstatus","navigatorTitle":[{"text":"ConversationStatus","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKConversationStatusIdle"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKConversationStatusIdle","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKConversationStatusIdle"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKConversationStatusIdle","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus~1idle\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus~1idle\/fragments","value":[{"text":"ZDKConversationStatusIdle","kind":"identifier"}]},{"value":"ZDKConversationStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus\/fragments","op":"replace","value":[{"text":"ZDKConversationStatus","kind":"identifier"}]}]}]}