{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/selectformfield\/label"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/selectformfield\/label"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"label","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"label"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKSelectFormField(py)label"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField\/label"},"kind":"symbol","abstract":[{"type":"text","text":"The label of the field. Must be unique per "},{"type":"codeVoice","code":"form"},{"type":"text","text":" or "},{"code":"formResponse","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"label"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","role":"collection","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SelectFormField/label":{"abstract":[{"type":"text","text":"The label of the field. Must be unique per "},{"type":"codeVoice","code":"form"},{"text":" or ","type":"text"},{"code":"formResponse","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"label","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/selectformfield\/label","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"label","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField\/label","role":"symbol","title":"label","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SelectFormField":{"kind":"symbol","title":"SelectFormField","abstract":[{"type":"text","text":"Form Field that takes in generic user input"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SelectFormField"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/selectformfield","navigatorTitle":[{"text":"SelectFormField","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"label","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"label","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"label","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField~1label\/title","op":"replace","value":"label"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField~1label\/fragments","value":[{"text":"label","kind":"identifier"}],"op":"replace"},{"value":"ZDKSelectFormField","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/fragments","value":[{"text":"ZDKSelectFormField","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}