{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType","kind":"typeIdentifier","text":"FieldType"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKSelectFormField(py)type","title":"type","role":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField\/type"},"sections":[],"kind":"symbol","abstract":[{"text":"The field type.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType","kind":"typeIdentifier","text":"FieldType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/selectformfield\/type"]},{"paths":["\/documentation\/zendesksdkconversationkit\/selectformfield\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FieldType":{"abstract":[{"type":"text","text":"Form field type. "},{"code":"text","type":"codeVoice"},{"type":"text","text":", "},{"code":"email","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"select"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FieldType"}],"navigatorTitle":[{"text":"FieldType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType","title":"FieldType","url":"\/documentation\/zendesksdkconversationkit\/fieldtype","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","role":"collection","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SelectFormField/type":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"title":"type","abstract":[{"type":"text","text":"The field type."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField\/type","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/selectformfield\/type","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType","text":"FieldType"}],"role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SelectFormField":{"kind":"symbol","title":"SelectFormField","abstract":[{"type":"text","text":"Form Field that takes in generic user input"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SelectFormField"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/selectformfield","navigatorTitle":[{"text":"SelectFormField","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"type","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKFieldType","text":"ZDKFieldType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FieldType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/title","value":"ZDKFieldType"},{"value":[{"kind":"identifier","text":"ZDKFieldType"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FieldType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField~1type\/title","value":"type"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField~1type\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/title","value":"ZDKSelectFormField"},{"value":[{"text":"ZDKSelectFormField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/fragments"}]}]}