{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"The last updated timestamp of the ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"lastUpdatedAt","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Represents when the last message was received in the "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Or, the creation time of the "},{"code":"Conversation","type":"codeVoice"},{"text":" if no messages have been received yet.","type":"text"}]}]}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversation\/lastUpdatedAt"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"]]},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lastUpdatedAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"lastUpdatedAt"}],"symbolKind":"property","title":"lastUpdatedAt","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation(py)lastUpdatedAt","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversation\/lastupdatedat"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversation\/lastupdatedat"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Conversation"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"abstract":[],"title":"Conversation","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversation/lastUpdatedAt":{"title":"lastUpdatedAt","abstract":[{"type":"text","text":"The last updated timestamp of the "},{"code":"Conversation","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"lastUpdatedAt"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversation\/lastUpdatedAt","url":"\/documentation\/zendesksdkconversationkit\/zdkconversation\/lastupdatedat","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lastUpdatedAt"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"lastUpdatedAt"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"lastUpdatedAt"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"lastUpdatedAt","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKConversation","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments","value":[{"text":"ZDKConversation","kind":"identifier"}],"op":"replace"},{"value":"lastUpdatedAt","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversation~1lastUpdatedAt\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversation~1lastUpdatedAt\/fragments","value":[{"text":"lastUpdatedAt","kind":"identifier"}],"op":"replace"}]}]}