{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextFormField\/minSizeObjc","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minSizeObjc"}],"externalID":"c:@CM@ZendeskSDKConversationKit@objc(cs)ZDKTextFormField(py)minSizeObjc","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minSizeObjc","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"symbolKind":"property","platforms":[],"title":"minSizeObjc","extendedModule":"ZendeskSDKConversationKit","roleHeading":"Instance Property","modules":[{"name":"ZendeskSDKConversationKit"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minSizeObjc"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdktextformfield\/minsizeobjc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdktextformfield\/minsizeobjc"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The minimum allowed length for the response for a field of type text.","type":"text"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKTextFormField/minSizeObjc":{"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdktextformfield\/minsizeobjc","navigatorTitle":[{"kind":"identifier","text":"minSizeObjc"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minSizeObjc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","kind":"symbol","abstract":[{"text":"The minimum allowed length for the response for a field of type text.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextFormField\/minSizeObjc","title":"minSizeObjc"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","role":"collection","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField":{"url":"\/documentation\/zendesksdkconversationkit\/textformfield","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextFormField"}],"title":"TextFormField","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFormField"}],"role":"symbol","abstract":[{"type":"text","text":"Form Field that takes in generic user input"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"minSizeObjc","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"minSizeObjc"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minSizeObjc"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextFormField~1minSizeObjc\/title","value":"minSizeObjc","op":"replace"},{"value":[{"text":"minSizeObjc","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextFormField~1minSizeObjc\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField\/title","value":"ZDKTextFormField","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField\/fragments","value":[{"text":"ZDKTextFormField","kind":"identifier"}]}]}]}