{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKEmailFormField\/label","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The label of the field. Must be unique per "},{"type":"codeVoice","code":"form"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"formResponse"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkemailformfield\/label"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkemailformfield\/label"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/EmailFormField"]]},"metadata":{"title":"label","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"label","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKEmailFormField(py)label","symbolKind":"property"},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/EmailFormField":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/EmailFormField","navigatorTitle":[{"text":"EmailFormField","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"EmailFormField","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EmailFormField","kind":"identifier"}],"abstract":[{"text":"Form Field used for email input","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/emailformfield"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKEmailFormField/label":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKEmailFormField\/label","type":"topic","title":"label","navigatorTitle":[{"text":"label","kind":"identifier"}],"abstract":[{"type":"text","text":"The label of the field. Must be unique per "},{"code":"form","type":"codeVoice"},{"type":"text","text":" or "},{"code":"formResponse","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkemailformfield\/label","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"label","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"label"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"label"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"label"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1EmailFormField\/title","op":"replace","value":"ZDKEmailFormField"},{"value":[{"text":"ZDKEmailFormField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1EmailFormField\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKEmailFormField~1label\/title","value":"label","op":"replace"},{"op":"replace","value":[{"text":"label","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKEmailFormField~1label\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}