{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"disconnected","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/connectionstatus\/disconnected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/connectionstatus\/disconnected"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"case","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConnectionStatus@ZDKConnectionStatusDisconnected","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusDisconnected"}],"roleHeading":"Case","title":"ConnectionStatus.disconnected"},"abstract":[{"type":"text","text":"Client is disconnected, this is the inital state."},{"text":" ","type":"text"},{"text":"It could also be that all connection atempts have failed.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus\/disconnected"},"kind":"symbol","sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConnectionStatus/disconnected":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus\/disconnected","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusDisconnected"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/connectionstatus\/disconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"abstract":[{"type":"text","text":"Client is disconnected, this is the inital state."},{"text":" ","type":"text"},{"text":"It could also be that all connection atempts have failed.","type":"text"}],"title":"ConnectionStatus.disconnected"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConnectionStatus":{"role":"symbol","navigatorTitle":[{"text":"ConnectionStatus","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/connectionstatus","type":"topic","abstract":[{"type":"text","text":"Represents the current connection state of the client."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConnectionStatus","kind":"identifier"}],"title":"ConnectionStatus","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKConnectionStatusDisconnected","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConnectionStatusDisconnected"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKConnectionStatusDisconnected","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus~1disconnected\/title","value":"ZDKConnectionStatusDisconnected","op":"replace"},{"value":[{"text":"ZDKConnectionStatusDisconnected","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus~1disconnected\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus\/title","value":"ZDKConnectionStatus"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus\/fragments","value":[{"text":"ZDKConnectionStatus","kind":"identifier"}],"op":"replace"}]}]}