{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType","text":"ActivityType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ActivityType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity(py)type","title":"type","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivity\/type","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkactivity\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkactivity\/type"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Activity"}],"type":"topic","title":"Activity","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/activity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Activity"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKActivity/type":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ActivityType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"}],"type":"topic","abstract":[],"title":"type","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivity\/type","url":"\/documentation\/zendesksdkconversationkit\/zdkactivity\/type","navigatorTitle":[{"text":"type","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/activitytype","title":"ActivityType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActivityType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ActivityType"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"type","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","text":"ZDKActivityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"ZDKActivity","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/fragments","value":[{"kind":"identifier","text":"ZDKActivity"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivity~1type\/title","op":"replace","value":"type"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivity~1type\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title","value":"ZDKActivityType"},{"value":[{"kind":"identifier","text":"ZDKActivityType"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}