{"metadata":{"title":"isEqual(_:)","symbolKind":"method","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKTextFormField(im)isEqual:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField"]]},"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/textformfield\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/textformfield\/isequal(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"object"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"the object to compare against"}],"type":"paragraph"}],"name":"object"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/isEqual(_:)"},"kind":"symbol","references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField\/isEqual(_:)","title":"isEqual(_:)","url":"\/documentation\/zendesksdkconversationkit\/textformfield\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextFormField":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextFormField"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextFormField","abstract":[{"type":"text","text":"Form Field that takes in generic user input"}],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/textformfield","title":"TextFormField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextFormField","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"isEqual:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"isEqual:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1isEqual(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField~1isEqual(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField\/title","op":"replace","value":"ZDKTextFormField"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextFormField\/fragments","value":[{"text":"ZDKTextFormField","kind":"identifier"}]}]}]}