{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendMessage(message:conversationId:completion:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendMessage"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","text":"Message","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"Message","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"Message"},{"type":"text","text":" that will be sent."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The id of the ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"text":" that the ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":" will be appended to."}]}],"name":"conversationId"},{"content":[{"inlineContent":[{"text":"The sent ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":" if successful, "},{"type":"codeVoice","code":"Error"},{"text":" if not.","type":"text"}],"type":"paragraph"}],"name":"completion"}]}],"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit(im)sendMessageWithMessage:conversationId:completion:","modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"Message","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Message","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"title":"sendMessage(message:conversationId:completion:)","platforms":[],"required":true,"navigatorTitle":[{"kind":"identifier","text":"sendMessageWithMessage:conversationId:completion:"}]},"abstract":[{"type":"text","text":"Call to send a "},{"type":"codeVoice","code":"Message"},{"type":"text","text":". This call will trigger a network request."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendmessage(message:conversationid:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendmessage(message:conversationid:completion:)"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/sendMessage(message:conversationId:completion:)":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"sendMessageWithMessage:conversationId:completion:"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendMessage(message:conversationId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"Message","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","text":"Message"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"title":"sendMessage(message:conversationId:completion:)","url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendmessage(message:conversationid:completion:)","abstract":[{"text":"Call to send a ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":". This call will trigger a network request."}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"navigatorTitle":[{"text":"Message","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Message","kind":"identifier"}],"title":"Message","kind":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/message"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationKitObjC","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","type":"topic","title":"ConversationKitObjC","role":"symbol","abstract":[{"code":"ConversationKitObjC","type":"codeVoice"},{"text":" needs to be configured  with a ","type":"text"},{"code":"ConversationKitSettings","type":"codeVoice"},{"type":"text","text":" "},{"text":"that includes the necessary ","type":"text"},{"type":"codeVoice","code":"integrationId"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"integrationId"},{"type":"text","text":" can be retrieved from the Native Messaging dashboard."}],"navigatorTitle":[{"kind":"identifier","text":"ConversationKitObjC"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"sendMessageWithMessage:conversationId:completion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"sendMessageWithMessage:conversationId:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"sendMessageWithMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ZDKMessage","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversationId"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(ZDKMessage *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"sendMessageWithMessage:conversationId:completion:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendMessage(message:conversationId:completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendMessage(message:conversationId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendMessageWithMessage:conversationId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title","value":"ZDKMessage"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","value":[{"text":"ZDKMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title","op":"replace","value":"ZDKConversationKit"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}