{"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventOpenWebViewMessageReceived","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openWebViewMessageReceived"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventOpenWebViewMessageReceived"}],"role":"symbol","title":"ZDKConversationKitEvent.openWebViewMessageReceived","symbolKind":"case","modules":[{"name":"ZendeskSDKConversationKit"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"A new message with a webview action "},{"type":"codeVoice","code":"openOnReceive"},{"text":" has occurred","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openWebViewMessageReceived"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/openwebviewmessagereceived"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/openwebviewmessagereceived"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/openWebViewMessageReceived","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/openWebViewMessageReceived":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openWebViewMessageReceived"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/openwebviewmessagereceived","navigatorTitle":[{"text":"ZDKConversationKitEventOpenWebViewMessageReceived","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/openWebViewMessageReceived","kind":"symbol","title":"ZDKConversationKitEvent.openWebViewMessageReceived","abstract":[{"type":"text","text":"A new message with a webview action "},{"code":"openOnReceive","type":"codeVoice"},{"type":"text","text":" has occurred"}],"type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","abstract":[{"text":"List of events that covers all events that could come from ","type":"text"},{"type":"codeVoice","code":"ConversationKit"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKConversationKitEvent"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","navigatorTitle":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"title":"ZDKConversationKitEvent","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"ZDKConversationKitEventOpenWebViewMessageReceived","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKConversationKitEventOpenWebViewMessageReceived","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKConversationKitEventOpenWebViewMessageReceived","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1openWebViewMessageReceived\/title","value":"ZDKConversationKitEventOpenWebViewMessageReceived"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1openWebViewMessageReceived\/fragments","value":[{"text":"ZDKConversationKitEventOpenWebViewMessageReceived","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","value":"ZDKConversationKitEvent","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKConversationKitEvent"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}