{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/proactivemessagestatuschanged"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/proactivemessagestatuschanged"]}],"metadata":{"title":"ZDKConversationKitEvent.proactiveMessageStatusChanged","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventProactiveMessageStatusChanged"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventProactiveMessageStatusChanged","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"proactiveMessageStatusChanged","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/proactiveMessageStatusChanged","interfaceLanguage":"swift"},"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"ProactiveMessage"},{"text":" event has occurred.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"proactiveMessageStatusChanged"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/proactiveMessageStatusChanged":{"kind":"symbol","type":"topic","title":"ZDKConversationKitEvent.proactiveMessageStatusChanged","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":" event has occurred."}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/proactiveMessageStatusChanged","navigatorTitle":[{"text":"ZDKConversationKitEventProactiveMessageStatusChanged","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/proactivemessagestatuschanged","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"proactiveMessageStatusChanged"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","abstract":[{"text":"List of events that covers all events that could come from ","type":"text"},{"type":"codeVoice","code":"ConversationKit"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKConversationKitEvent"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","navigatorTitle":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"title":"ZDKConversationKitEvent","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKConversationKitEventProactiveMessageStatusChanged","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"ZDKConversationKitEventProactiveMessageStatusChanged"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKConversationKitEventProactiveMessageStatusChanged","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"ZDKConversationKitEventProactiveMessageStatusChanged","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1proactiveMessageStatusChanged\/title"},{"value":[{"text":"ZDKConversationKitEventProactiveMessageStatusChanged","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1proactiveMessageStatusChanged\/fragments"},{"value":"ZDKConversationKitEvent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title"},{"value":[{"text":"ZDKConversationKitEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}