{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationRoutingQueued"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A conversation queued activity"}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRoutingQueued","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType@ZDKActivityTypeConversationRoutingQueued","role":"symbol","roleHeading":"Case","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"case","title":"ActivityType.conversationRoutingQueued","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationRoutingQueued"}],"navigatorTitle":[{"text":"ZDKActivityTypeConversationRoutingQueued","kind":"identifier"}]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/activitytype\/conversationroutingqueued"]},{"paths":["\/documentation\/zendesksdkconversationkit\/activitytype\/conversationroutingqueued"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType":{"url":"\/documentation\/zendesksdkconversationkit\/activitytype","title":"ActivityType","navigatorTitle":[{"text":"ActivityType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ActivityType","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActivityType/conversationRoutingQueued":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActivityType\/conversationRoutingQueued","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/activitytype\/conversationroutingqueued","abstract":[{"type":"text","text":"A conversation queued activity"}],"title":"ActivityType.conversationRoutingQueued","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationRoutingQueued","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKActivityTypeConversationRoutingQueued"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKActivityTypeConversationRoutingQueued"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKActivityTypeConversationRoutingQueued","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKActivityTypeConversationRoutingQueued","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/title","value":"ZDKActivityType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKActivityType"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType\/fragments"},{"value":"ZDKActivityTypeConversationRoutingQueued","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1conversationRoutingQueued\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActivityType~1conversationRoutingQueued\/fragments","value":[{"kind":"identifier","text":"ZDKActivityTypeConversationRoutingQueued"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}