{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getWaitTimeForConversation","kind":"identifier"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"WaitTimeData","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"conversationId","content":[{"inlineContent":[{"text":"The Id of the conversation to fetch the wait time for.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"Return the wait time data associated with the conversation if successful, ","type":"text"},{"type":"codeVoice","code":"Error"},{"text":" if not.","type":"text"}],"type":"paragraph"}]}]}],"kind":"symbol","abstract":[{"text":"Fetches the current wait time for a specific conversation","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/getwaittimeforconversation(conversationid:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/getwaittimeforconversation(conversationid:completion:)"]}],"metadata":{"role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit(im)getWaitTimeForConversationWithConversationId:completion:","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getWaitTimeForConversation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData","text":"WaitTimeData","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"platforms":[],"modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"getWaitTimeForConversationWithConversationId:completion:"}],"title":"getWaitTimeForConversation(conversationId:completion:)","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getWaitTimeForConversation(conversationId:completion:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"kind":"symbol","type":"topic","title":"ConversationKitObjC","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","role":"symbol","abstract":[{"type":"codeVoice","code":"ConversationKitObjC"},{"text":" needs to be configured  with a ","type":"text"},{"code":"Config","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"that includes the necessary "},{"type":"codeVoice","code":"integrationId"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"integrationId"},{"text":" can be retrieved from the Native Messaging dashboard.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitObjC"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","navigatorTitle":[{"text":"ConversationKitObjC","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/getWaitTimeForConversation(conversationId:completion:)":{"required":true,"kind":"symbol","abstract":[{"text":"Fetches the current wait time for a specific conversation","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/getwaittimeforconversation(conversationid:completion:)","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getWaitTimeForConversation(conversationId:completion:)","type":"topic","navigatorTitle":[{"text":"getWaitTimeForConversationWithConversationId:completion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getWaitTimeForConversation"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"WaitTimeData","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"getWaitTimeForConversation(conversationId:completion:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WaitTimeData","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WaitTimeData"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","url":"\/documentation\/zendesksdkconversationkit\/waittimedata","title":"WaitTimeData","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getWaitTimeForConversationWithConversationId:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"getWaitTimeForConversationWithConversationId:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getWaitTimeForConversationWithConversationId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"conversationId"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData#*$objc(cs)NSError)","text":"void (^)(ZDKWaitTimeData *, NSError *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title","op":"replace","value":"ZDKConversationKit"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments","op":"replace","value":[{"text":"ZDKConversationKit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getWaitTimeForConversation(conversationId:completion:)\/title","value":"getWaitTimeForConversationWithConversationId:completion:"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getWaitTimeForConversation(conversationId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getWaitTimeForConversationWithConversationId:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/title","value":"ZDKWaitTimeData","op":"replace"},{"value":[{"text":"ZDKWaitTimeData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}