{"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH","doc:\/\/com.zendesk.ConversationKit\/SY"]}],"kind":"symbol","abstract":[{"text":"The display size of ","type":"text"},{"type":"codeVoice","code":"MessageActionItem"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKMessageItemSize) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionItemSize","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionItemSize"}],"symbolKind":"enum","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageItemSize","modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ActionItemSize"}],"title":"ActionItemSize"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/actionitemsize"]},{"paths":["\/documentation\/zendesksdkconversationkit\/actionitemsize"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/compact","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/large","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/none"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/Equatable-Implementations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/RawRepresentable-Implementations"]}],"references":{"doc://com.zendesk.ConversationKit/Se":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/SE":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/SQ":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/Equatable-Implementations","type":"topic","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/zendesksdkconversationkit\/actionitemsize\/equatable-implementations"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize/init(rawValue:)":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/zendesksdkconversationkit\/actionitemsize\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize":{"navigatorTitle":[{"kind":"identifier","text":"ActionItemSize"}],"role":"symbol","title":"ActionItemSize","abstract":[{"text":"The display size of ","type":"text"},{"type":"codeVoice","code":"MessageActionItem"},{"text":".","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionItemSize","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/actionitemsize"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize/large":{"abstract":[{"text":"Images are meant to be displayed with a compact layout.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/large","title":"ActionItemSize.large","navigatorTitle":[{"kind":"identifier","text":"ZDKMessageItemSizeLarge"}],"url":"\/documentation\/zendesksdkconversationkit\/actionitemsize\/large","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"large"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/actionitemsize\/rawrepresentable-implementations"},"doc://com.zendesk.ConversationKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize/none":{"abstract":[{"type":"text","text":"Images are meant to be displayed with no specified layout."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/none","title":"ActionItemSize.none","navigatorTitle":[{"text":"ZDKMessageItemSizeNone","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/actionitemsize\/none","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}]},"doc://com.zendesk.ConversationKit/SY":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize/compact":{"abstract":[{"text":"Images are meant to be displayed with a large layout.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/compact","title":"ActionItemSize.compact","navigatorTitle":[{"kind":"identifier","text":"ZDKMessageItemSizeCompact"}],"url":"\/documentation\/zendesksdkconversationkit\/actionitemsize\/compact","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"compact","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKMessageItemSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"ZDKMessageItemSize","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKMessageItemSize"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/compact","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/large","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/none"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKMessageItemSize"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/title","value":"ZDKMessageItemSize","op":"replace"},{"value":[{"text":"ZDKMessageItemSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/fragments"},{"value":"ZDKMessageItemSizeLarge","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize~1large\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize~1large\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKMessageItemSizeLarge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize~1none\/title","value":"ZDKMessageItemSizeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize~1none\/fragments","value":[{"kind":"identifier","text":"ZDKMessageItemSizeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize~1compact\/title","value":"ZDKMessageItemSizeCompact"},{"op":"replace","value":[{"text":"ZDKMessageItemSizeCompact","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize~1compact\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}