{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"User"}],"roleHeading":"Class","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","symbolKind":"class","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"User","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"User","kind":"identifier"}]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/init(from:)"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/authentication","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/conversations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/externalId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/givenName","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/id","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/isLatestConversationActive","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/locale","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/realtimeSettings","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/surname"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/isEqual(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKUser) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"User"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/user"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/user"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"kind":"relationships"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/description":{"type":"topic","title":"description","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/description","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/user\/description","navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User":{"title":"User","navigatorTitle":[{"text":"User","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"User","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/realtimeSettings":{"type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"realtimeSettings","type":"codeVoice"},{"type":"text","text":" of the "},{"type":"codeVoice","code":"User"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user\/realtimesettings","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/realtimeSettings","title":"realtimeSettings","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"realtimeSettings","kind":"identifier"},{"kind":"text","text":": "},{"text":"RealtimeSettings","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKRealtimeSettings","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"realtimeSettings"}]},"doc://com.zendesk.ConversationKit/Se":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/externalId":{"title":"externalId","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/externalId","url":"\/documentation\/zendesksdkconversationkit\/user\/externalid","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"externalId"},{"type":"text","text":" of the "},{"code":"User","type":"codeVoice"}],"navigatorTitle":[{"kind":"identifier","text":"externalId"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/id":{"type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"id"},{"type":"text","text":" of the "},{"type":"codeVoice","code":"User"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user\/id","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/id","title":"id","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"id"}]},"doc://com.zendesk.ConversationKit/SH":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/surname":{"type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"surName","type":"codeVoice"},{"type":"text","text":" of the "},{"type":"codeVoice","code":"User"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user\/surname","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/surname","title":"surname","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"surname","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"surname"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/init(from:)":{"type":"topic","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user\/init(from:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/init(from:)","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/locale":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":"The ","type":"text"},{"code":"locale","type":"codeVoice"},{"type":"text","text":" of the "},{"code":"User","type":"codeVoice"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user\/locale","navigatorTitle":[{"kind":"identifier","text":"locale"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/locale","title":"locale","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE"},"doc://com.zendesk.ConversationKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/givenName":{"title":"givenName","url":"\/documentation\/zendesksdkconversationkit\/user\/givenname","navigatorTitle":[{"kind":"identifier","text":"givenName"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"givenName"},{"text":" of the ","type":"text"},{"code":"User","type":"codeVoice"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/givenName"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/isEqual(_:)":{"type":"topic","abstract":[{"text":"Returns a Boolean value that indicates whether the receiver and a given object are equal.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user\/isequal(_:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/isEqual(_:)","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP"},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/isLatestConversationActive":{"type":"topic","abstract":[{"type":"text","text":"Computed variable to detect if the latest "},{"code":"User","type":"codeVoice"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" is active"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user\/islatestconversationactive","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/isLatestConversationActive","title":"isLatestConversationActive","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isLatestConversationActive"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isLatestConversationActive","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/conversations":{"type":"topic","abstract":[{"type":"text","text":"The "},{"code":"conversations","type":"codeVoice"},{"text":" of the ","type":"text"},{"type":"codeVoice","code":"User"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user\/conversations","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/conversations","title":"conversations","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversations"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"conversations","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User/authentication":{"type":"topic","abstract":[{"type":"text","text":"The "},{"code":"authentication","type":"codeVoice"},{"type":"text","text":" of the "},{"type":"codeVoice","code":"User"}],"kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/user\/authentication","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/authentication","title":"authentication","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"authentication","kind":"identifier"},{"kind":"text","text":": "},{"text":"Authentication","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthentication"}],"navigatorTitle":[{"kind":"identifier","text":"authentication"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKUser","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKUser"}]},{"op":"replace","value":[{"kind":"identifier","text":"ZDKUser"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/authentication","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/conversations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/externalId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/givenName","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/id","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/isLatestConversationActive","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/locale","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/realtimeSettings","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/surname"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User\/isEqual(_:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUser"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1description\/title","value":"description"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1description\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/title","value":"ZDKUser","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/fragments","value":[{"kind":"identifier","text":"ZDKUser"}],"op":"replace"},{"op":"replace","value":"realtimeSettings","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1realtimeSettings\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1realtimeSettings\/fragments","value":[{"text":"realtimeSettings","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1externalId\/title","value":"externalId"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1externalId\/fragments","op":"replace","value":[{"text":"externalId","kind":"identifier"}]},{"op":"replace","value":"id","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1id\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1id\/fragments","value":[{"text":"id","kind":"identifier"}]},{"value":"surname","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1surname\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1surname\/fragments","value":[{"kind":"identifier","text":"surname"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1locale\/title","value":"locale"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1locale\/fragments","op":"replace","value":[{"kind":"identifier","text":"locale"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1givenName\/title","value":"givenName","op":"replace"},{"value":[{"text":"givenName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1givenName\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1isEqual(_:)\/title","value":"isEqual:"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"value":"isLatestConversationActive","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1isLatestConversationActive\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1isLatestConversationActive\/fragments","op":"replace","value":[{"text":"isLatestConversationActive","kind":"identifier"}]},{"op":"replace","value":"conversations","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1conversations\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1conversations\/fragments","value":[{"kind":"identifier","text":"conversations"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1authentication\/title","value":"authentication","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User~1authentication\/fragments","value":[{"text":"authentication","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}