{"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"messageActions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction","kind":"typeIdentifier","text":"MessageAction"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"messageActions","kind":"identifier"}],"title":"messageActions","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessageActionItem(py)messageActions"},"abstract":[{"type":"text","text":"An array of "},{"code":"MessageAction","type":"codeVoice"},{"type":"text","text":" to be displayed with this item."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageActions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MessageAction","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction"},{"text":"] { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem"]]},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkmessageactionitem\/messageactions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkmessageactionitem\/messageactions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageActionItem\/messageActions"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageAction":{"title":"MessageAction","role":"symbol","navigatorTitle":[{"text":"MessageAction","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageAction"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/messageaction"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKMessageActionItem/messageActions":{"title":"messageActions","role":"symbol","navigatorTitle":[{"text":"messageActions","kind":"identifier"}],"abstract":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"MessageAction"},{"type":"text","text":" to be displayed with this item."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageActions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction","text":"MessageAction"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageActionItem\/messageActions","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkmessageactionitem\/messageactions"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionItem":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageActionItem"}],"abstract":[{"text":"An item in a list type message, such as list or carousel.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionitem","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","kind":"symbol","role":"symbol","title":"MessageActionItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageActionItem","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"messageActions"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"messageActions","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<id<ZDKMessageAction>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"messageActions"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKMessageAction","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/fragments","op":"replace","value":[{"text":"ZDKMessageAction","kind":"identifier"}]},{"value":"messageActions","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessageActionItem~1messageActions\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessageActionItem~1messageActions\/fragments","op":"replace","value":[{"text":"messageActions","kind":"identifier"}]},{"value":"ZDKMessageActionItem","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/fragments","value":[{"text":"ZDKMessageActionItem","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}