{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"ActionType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ActionType"},{"text":" of this action.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType","text":"ActionType"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"type","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKLinkAction(py)type"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLinkAction\/type"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LinkAction"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdklinkaction\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdklinkaction\/type"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKLinkAction/type":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/zendesksdkconversationkit\/zdklinkaction\/type","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType","text":"ActionType","kind":"typeIdentifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ActionType"},{"type":"text","text":" of this action."}],"type":"topic","title":"type","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLinkAction\/type","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/LinkAction":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/LinkAction","url":"\/documentation\/zendesksdkconversationkit\/linkaction","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"LinkAction"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LinkAction","kind":"identifier"}],"title":"LinkAction","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType":{"url":"\/documentation\/zendesksdkconversationkit\/actiontype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionType","kind":"identifier"}],"type":"topic","title":"ActionType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","navigatorTitle":[{"text":"ActionType","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"type","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"type","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLinkAction~1type\/title"},{"value":[{"kind":"identifier","text":"type"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLinkAction~1type\/fragments"},{"op":"replace","value":"ZDKLinkAction","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LinkAction\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1LinkAction\/fragments","value":[{"text":"ZDKLinkAction","kind":"identifier"}]},{"value":"ZDKActionType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/title"},{"value":[{"kind":"identifier","text":"ZDKActionType"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}