{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Any actions associated with the message","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"messageActions","kind":"identifier"}],"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage(py)messageActions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"messageActions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MessageAction","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction"},{"kind":"text","text":"]?"}],"symbolKind":"property","roleHeading":"Instance Property","title":"messageActions"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageActions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction","kind":"typeIdentifier","text":"MessageAction"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkmessage\/messageactions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkmessage\/messageactions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessage\/messageActions","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKMessage/messageActions":{"title":"messageActions","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkmessage\/messageactions","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessage\/messageActions","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageActions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction","text":"MessageAction","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"abstract":[{"type":"text","text":"Any actions associated with the message"}],"navigatorTitle":[{"text":"messageActions","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageAction":{"url":"\/documentation\/zendesksdkconversationkit\/messageaction","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageAction","kind":"identifier"}],"type":"topic","title":"MessageAction","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction","navigatorTitle":[{"kind":"identifier","text":"MessageAction"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Message","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/message","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Message"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","title":"Message"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"messageActions"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"messageActions"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<ZDKMessageAction>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"messageActions","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"messageActions","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessage~1messageActions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"messageActions"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessage~1messageActions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/title","value":"ZDKMessageAction"},{"value":[{"kind":"identifier","text":"ZDKMessageAction"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/fragments"},{"value":"ZDKMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","value":[{"text":"ZDKMessage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}