{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/createconversation(proactivemessageid:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/createconversation(proactivemessageid:completion:)"]}],"kind":"symbol","metadata":{"platforms":[],"navigatorTitle":[{"text":"createConversationWithProactiveMessageId:completion:","kind":"identifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"required":true,"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit(im)createConversationWithProactiveMessageId:completion:","symbolKind":"method","title":"createConversation(proactiveMessageId:completion:)","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createConversation"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"proactiveMessageId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"id"},{"text":" of the Proactive Message.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Conversation"},{"text":" if successful, ","type":"text"},{"type":"codeVoice","code":"Error"},{"text":" if not.","type":"text"}]}],"name":"completion"}]}],"abstract":[{"text":"Call to create a ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"text":" for the current ","type":"text"},{"code":"User","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/createConversation(proactiveMessageId:completion:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/createConversation(proactiveMessageId:completion:)":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/createconversation(proactivemessageid:completion:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/createConversation(proactiveMessageId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createConversation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"proactiveMessageId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"createConversationWithProactiveMessageId:completion:","kind":"identifier"}],"required":true,"type":"topic","abstract":[{"type":"text","text":"Call to create a "},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":" for the current "},{"code":"User","type":"codeVoice"},{"type":"text","text":"."}],"title":"createConversation(proactiveMessageId:completion:)","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitObjC"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationKitObjC"}],"type":"topic","abstract":[{"code":"ConversationKitObjC","type":"codeVoice"},{"type":"text","text":" needs to be configured  with a "},{"type":"codeVoice","code":"ConversationKitSettings"},{"type":"text","text":" "},{"type":"text","text":"that includes the necessary "},{"type":"codeVoice","code":"integrationId"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"integrationId"},{"type":"text","text":" can be retrieved from the Native Messaging dashboard."}],"title":"ConversationKitObjC","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"kind":"symbol","title":"Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","url":"\/documentation\/zendesksdkconversationkit\/conversation","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Conversation"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"createConversationWithProactiveMessageId:completion:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"createConversationWithProactiveMessageId:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"createConversationWithProactiveMessageId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"proactiveMessageId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(ZDKConversation *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation#*$objc(cs)NSError)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1createConversation(proactiveMessageId:completion:)\/title","value":"createConversationWithProactiveMessageId:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createConversationWithProactiveMessageId:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1createConversation(proactiveMessageId:completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title","op":"replace","value":"ZDKConversationKit"},{"op":"replace","value":[{"text":"ZDKConversationKit","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","value":"ZDKConversation","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKConversation"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments"}]}]}