{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"compact","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/compact"},"sections":[],"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKWebViewActionSize@ZDKWebViewActionSizeCompact","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compact"}],"title":"WebViewActionSize.compact","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ZDKWebViewActionSizeCompact"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/webviewactionsize\/compact"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/webviewactionsize\/compact"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize/compact":{"url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize\/compact","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compact"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKWebViewActionSizeCompact"}],"title":"WebViewActionSize.compact","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/compact"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"WebViewActionSize","kind":"identifier"}],"title":"WebViewActionSize","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize","abstract":[],"navigatorTitle":[{"text":"WebViewActionSize","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKWebViewActionSizeCompact"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKWebViewActionSizeCompact"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ZDKWebViewActionSizeCompact"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKWebViewActionSizeCompact","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize~1compact\/title"},{"value":[{"kind":"identifier","text":"ZDKWebViewActionSizeCompact"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize~1compact\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize\/title","value":"ZDKWebViewActionSize"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKWebViewActionSize"}]}]}]}