{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType","kind":"typeIdentifier","text":"ActionType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkmessageaction\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkmessageaction\/type"]}],"abstract":[{"text":"The ","type":"text"},{"code":"ActionType","type":"codeVoice"},{"type":"text","text":" of this action."}],"metadata":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"title":"type","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction(py)type","symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"required":true,"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"text":"ActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType"}]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageAction\/type","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionType":{"url":"\/documentation\/zendesksdkconversationkit\/actiontype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionType","kind":"identifier"}],"type":"topic","title":"ActionType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","navigatorTitle":[{"text":"ActionType","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageAction":{"url":"\/documentation\/zendesksdkconversationkit\/messageaction","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageAction","kind":"identifier"}],"type":"topic","title":"MessageAction","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageAction","navigatorTitle":[{"kind":"identifier","text":"MessageAction"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKMessageAction/type":{"title":"type","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKMessageAction\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkmessageaction\/type","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ActionType"},{"type":"text","text":" of this action."}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType","text":"ActionType","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"type"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActionType","text":"ZDKActionType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionType","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"ZDKActionType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/title","op":"replace"},{"value":[{"text":"ZDKActionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/title","value":"ZDKMessageAction"},{"value":[{"text":"ZDKMessageAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageAction\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessageAction~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKMessageAction~1type\/fragments","value":[{"kind":"identifier","text":"type"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}