{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent"]]},"kind":"symbol","abstract":[{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" has been updated."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationUpdated","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/conversationupdated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/conversationupdated"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent@ZDKConversationKitEventConversationUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationUpdated"}],"role":"symbol","title":"ZDKConversationKitEvent.conversationUpdated","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEventConversationUpdated"}],"roleHeading":"Case","modules":[{"name":"ZendeskSDKConversationKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationUpdated"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"type":"topic","abstract":[{"type":"text","text":"List of events that covers all events that could come from "},{"code":"ConversationKit","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationKitEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEvent"}],"title":"ZDKConversationKitEvent","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent/conversationUpdated":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationUpdated","kind":"identifier"}],"kind":"symbol","title":"ZDKConversationKitEvent.conversationUpdated","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent\/conversationUpdated","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent\/conversationupdated","navigatorTitle":[{"text":"ZDKConversationKitEventConversationUpdated","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" has been updated."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKConversationKitEventConversationUpdated"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationKitEventConversationUpdated"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKConversationKitEventConversationUpdated"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","op":"replace","value":"ZDKConversationKitEvent"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments","op":"replace","value":[{"text":"ZDKConversationKitEvent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/navigatorTitle","op":"replace","value":[{"text":"ZDKConversationKitEvent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1conversationUpdated\/title","op":"replace","value":"ZDKConversationKitEventConversationUpdated"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent~1conversationUpdated\/fragments","op":"replace","value":[{"text":"ZDKConversationKitEventConversationUpdated","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}