{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationType","kind":"typeIdentifier","text":"ConversationType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType"},{"text":", ","kind":"text"},{"text":"isDefault","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"displayName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"displayDescription","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? = nil, ","kind":"text"},{"text":"iconURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"business"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"businessLastRead"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"lastUpdatedAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":"]? = nil, ","kind":"text"},{"text":"participants","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","text":"Participant","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"messages"},{"text":": [","kind":"text"},{"text":"Message","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage"},{"kind":"text","text":"] = [], "},{"text":"hasPrevious","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"myself","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","text":"Participant","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant"},{"text":"?, ","kind":"text"},{"text":"activity","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"Activity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationStatus","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus","kind":"typeIdentifier"},{"text":" = .unknown)","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"ConversationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationType"},{"kind":"text","text":", "},{"text":"isDefault","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"displayName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"displayDescription","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"iconURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"business"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"businessLastRead","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"lastUpdatedAt"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"participants","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Participant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"messages","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","text":"Message"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hasPrevious"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"myself","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Participant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant"},{"kind":"text","text":"?, "},{"text":"activity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"Activity"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"text":"ConversationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationStatus"},{"text":")","kind":"text"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation(im)initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:","roleHeading":"Initializer","title":"init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/init(id:type:isdefault:displayname:displaydescription:iconurl:business:businesslastread:lastupdatedat:metadata:participants:messages:hasprevious:myself:activity:status:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/init(id:type:isdefault:displayname:displaydescription:iconurl:business:businesslastread:lastupdatedat:metadata:participants:messages:hasprevious:myself:activity:status:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"]]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType":{"title":"ConversationType","role":"symbol","navigatorTitle":[{"text":"ConversationType","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Represents the possible types of a ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","url":"\/documentation\/zendesksdkconversationkit\/conversationtype"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation/init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:)":{"title":"init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:"}],"type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationType","text":"ConversationType"},{"text":", ","kind":"text"},{"text":"isDefault","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"displayName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"displayDescription","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"iconURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"business","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"businessLastRead","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"lastUpdatedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":"]?, ","kind":"text"},{"text":"participants","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","kind":"typeIdentifier","text":"Participant"},{"text":"], ","kind":"text"},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Message","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"hasPrevious"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"myself","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","kind":"typeIdentifier","text":"Participant"},{"kind":"text","text":"?, "},{"text":"activity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"Activity"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"text":"ConversationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationStatus"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:)","url":"\/documentation\/zendesksdkconversationkit\/conversation\/init(id:type:isdefault:displayname:displaydescription:iconurl:business:businesslastread:lastupdatedat:metadata:participants:messages:hasprevious:myself:activity:status:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"kind":"symbol","title":"Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","url":"\/documentation\/zendesksdkconversationkit\/conversation","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Conversation"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Participant":{"title":"Participant","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Participant"}],"navigatorTitle":[{"text":"Participant","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/participant"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Message","kind":"identifier"}],"title":"Message","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","url":"\/documentation\/zendesksdkconversationkit\/message","abstract":[],"navigatorTitle":[{"text":"Message","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationStatus":{"title":"ConversationStatus","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationStatus"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the status of the "},{"code":"Conversation","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationStatus"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus","url":"\/documentation\/zendesksdkconversationkit\/conversationstatus"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity":{"title":"Activity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Activity","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","navigatorTitle":[{"text":"Activity","kind":"identifier"}],"abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/activity","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"id","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"type:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationType","text":"ZDKConversationType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDefault:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDefault"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"displayName","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"displayDescription:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"displayDescription","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"iconURL:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"iconURL","kind":"internalParam"},{"kind":"text","text":" "},{"text":"business:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"business","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"businessLastRead:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"text":" *) ","kind":"text"},{"text":"businessLastRead","kind":"internalParam"},{"kind":"text","text":" "},{"text":"lastUpdatedAt:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"lastUpdatedAt","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSObject *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"metadata","kind":"internalParam"},{"kind":"text","text":" "},{"text":"participants:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<ZDKParticipant *>"},{"text":" *) ","kind":"text"},{"text":"participants","kind":"internalParam"},{"kind":"text","text":" "},{"text":"messages:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKMessage *>"},{"kind":"text","text":" *) "},{"text":"messages","kind":"internalParam"},{"kind":"text","text":" "},{"text":"hasPrevious:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"hasPrevious","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"myself:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ZDKParticipant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"myself"},{"text":" ","kind":"text"},{"text":"activity:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"ZDKActivity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"activity","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"status:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus","kind":"typeIdentifier","text":"ZDKConversationStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationStatus"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"ZDKConversationType","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType\/title","op":"replace"},{"value":[{"text":"ZDKConversationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:)\/title","op":"replace","value":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithId:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1init(id:type:isDefault:displayName:displayDescription:iconURL:business:businessLastRead:lastUpdatedAt:metadata:participants:messages:hasPrevious:myself:activity:status:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","op":"replace","value":"ZDKConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments","value":[{"text":"ZDKConversation","kind":"identifier"}]},{"op":"replace","value":"ZDKParticipant","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/title"},{"op":"replace","value":[{"text":"ZDKParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title","op":"replace","value":"ZDKMessage"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments","value":[{"text":"ZDKMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus\/title","value":"ZDKConversationStatus","op":"replace"},{"value":[{"text":"ZDKConversationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus\/fragments","op":"replace"},{"value":"ZDKActivity","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/title","op":"replace"},{"value":[{"text":"ZDKActivity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/fragments"}]}]}