{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"myself","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Participant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"]]},"metadata":{"title":"myself","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"myself"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Participant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"myself"}],"symbolKind":"property","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation(py)myself"},"abstract":[{"text":"Currently signed user","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/myself"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/myself"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/myself","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"type":"topic","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/conversation","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"kind":"symbol","title":"Conversation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Participant":{"title":"Participant","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Participant"}],"navigatorTitle":[{"text":"Participant","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/participant","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","kind":"symbol","role":"collection","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation/myself":{"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversation\/myself","title":"myself","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/myself","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"myself","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Participant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Currently signed user"}],"navigatorTitle":[{"text":"myself","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"myself","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"myself"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"ZDKParticipant","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKParticipant","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Participant"},{"kind":"text","text":" * "},{"kind":"identifier","text":"myself"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","value":"ZDKConversation"},{"op":"replace","value":[{"text":"ZDKConversation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments"},{"value":"ZDKParticipant","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Participant\/fragments","op":"replace","value":[{"text":"ZDKParticipant","kind":"identifier"}]},{"value":"myself","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1myself\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1myself\/fragments","value":[{"text":"myself","kind":"identifier"}]}]}]}