{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/routingStatus","interfaceLanguage":"swift"},"abstract":[{"text":"The end user expectation status of the ","type":"text"},{"code":"Conversation","type":"codeVoice"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/routingstatus"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/routingstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"]]},"kind":"symbol","metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"routingStatus"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation(py)routingStatus","roleHeading":"Instance Property","role":"symbol","title":"routingStatus","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"routingStatus","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationRoutingStatus","text":"ConversationRoutingStatus"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"routingStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationRoutingStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus","text":"ConversationRoutingStatus"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation/routingStatus":{"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversation\/routingstatus","title":"routingStatus","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/routingStatus","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"routingStatus"},{"text":": ","kind":"text"},{"text":"ConversationRoutingStatus","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationRoutingStatus","kind":"typeIdentifier"}],"abstract":[{"text":"The end user expectation status of the ","type":"text"},{"code":"Conversation","type":"codeVoice"}],"navigatorTitle":[{"kind":"identifier","text":"routingStatus"}],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"type":"topic","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/conversation","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"kind":"symbol","title":"Conversation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","kind":"symbol","role":"collection","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationRoutingStatus":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus","url":"\/documentation\/zendesksdkconversationkit\/conversationroutingstatus","abstract":[{"text":"Represents the possible types of ","type":"text"},{"code":"routingStatus","type":"codeVoice"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationRoutingStatus"}],"kind":"symbol","title":"ConversationRoutingStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRoutingStatus"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"routingStatus","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"routingStatus","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationRoutingStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus","text":"ZDKConversationRoutingStatus"},{"text":" ","kind":"text"},{"text":"routingStatus","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1routingStatus\/title","value":"routingStatus","op":"replace"},{"value":[{"kind":"identifier","text":"routingStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1routingStatus\/fragments"},{"value":"ZDKConversation","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title","op":"replace"},{"value":[{"text":"ZDKConversation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus\/title","value":"ZDKConversationRoutingStatus"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationRoutingStatus"}]}]}]}