{"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig(im)initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"waitTimeEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"queuePositionEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"onlyDecreasingQueue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"waitTimeOverride"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"queuePollingInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:","kind":"identifier"}],"role":"symbol","title":"init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:)","symbolKind":"init","modules":[{"name":"ZendeskSDKConversationKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig\/init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"waitTimeEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"queuePositionEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onlyDecreasingQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"waitTimeOverride"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"queuePollingInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/waittimeconfig\/init(waittimeenabled:queuepositionenabled:onlydecreasingqueue:waittimeoverride:queuepollinginterval:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/waittimeconfig\/init(waittimeenabled:queuepositionenabled:onlydecreasingqueue:waittimeoverride:queuepollinginterval:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeConfig":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig","abstract":[{"text":"The wait time configuration. Contains config related to queue position and wait time behaviour.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WaitTimeConfig","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/waittimeconfig","navigatorTitle":[{"kind":"identifier","text":"WaitTimeConfig"}],"title":"WaitTimeConfig","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeConfig/init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"waitTimeEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"queuePositionEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"onlyDecreasingQueue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"waitTimeOverride"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"queuePollingInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/waittimeconfig\/init(waittimeenabled:queuepositionenabled:onlydecreasingqueue:waittimeoverride:queuepollinginterval:)","navigatorTitle":[{"kind":"identifier","text":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig\/init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:)","kind":"symbol","abstract":[],"title":"init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:)","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithWaitTimeEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"waitTimeEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"queuePositionEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"queuePositionEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"onlyDecreasingQueue:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onlyDecreasingQueue","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waitTimeOverride:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"waitTimeOverride","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queuePollingInterval:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"queuePollingInterval","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/title","value":"ZDKWaitTimeConfig","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKWaitTimeConfig"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig~1init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:)\/title","value":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig~1init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:queuePollingInterval:)\/fragments","op":"replace"}]}]}