{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"title":"ActionItemSize.none","modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKMessageItemSizeNone"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageItemSize@ZDKMessageItemSizeNone"},"abstract":[{"type":"text","text":"Images are meant to be displayed with no specified layout."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/none","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/actionitemsize\/none"]},{"paths":["\/documentation\/zendesksdkconversationkit\/actionitemsize\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize/none":{"title":"ActionItemSize.none","type":"topic","abstract":[{"type":"text","text":"Images are meant to be displayed with no specified layout."}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize\/none","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/actionitemsize\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKMessageItemSizeNone"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize":{"title":"ActionItemSize","type":"topic","abstract":[{"text":"The display size of ","type":"text"},{"type":"codeVoice","code":"MessageActionItem"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/actionitemsize","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionItemSize","kind":"identifier"}],"navigatorTitle":[{"text":"ActionItemSize","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"ZDKMessageItemSizeNone","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ZDKMessageItemSizeNone","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKMessageItemSizeNone"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize~1none\/title","op":"replace","value":"ZDKMessageItemSizeNone"},{"op":"replace","value":[{"text":"ZDKMessageItemSizeNone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize~1none\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/title","value":"ZDKMessageItemSize"},{"op":"replace","value":[{"text":"ZDKMessageItemSize","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/fragments"}]}]}