{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKWebViewActionSize) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewActionSize"}]}]}],"sections":[],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH","doc:\/\/com.zendesk.ConversationKit\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/compact","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/full","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/tall"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/Equatable-Implementations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/RawRepresentable-Implementations"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKWebViewActionSize","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"WebViewActionSize"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"WebViewActionSize","kind":"identifier"}],"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"WebViewActionSize"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/webviewactionsize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/webviewactionsize"]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebViewActionSize"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WebViewActionSize","kind":"identifier"}],"abstract":[],"title":"WebViewActionSize","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize","url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize/full":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKWebViewActionSizeFull","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize\/full","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/full","title":"WebViewActionSize.full"},"doc://com.zendesk.ConversationKit/SY":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize/Equatable-Implementations":{"kind":"article","url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize\/equatable-implementations","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize/RawRepresentable-Implementations":{"type":"topic","role":"collectionGroup","kind":"article","url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize/tall":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKWebViewActionSizeTall"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tall","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/tall","title":"WebViewActionSize.tall","url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize\/tall"},"doc://com.zendesk.ConversationKit/Se":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://com.zendesk.ConversationKit/SE":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize/compact":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKWebViewActionSizeCompact","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compact","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize\/compact","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/compact","title":"WebViewActionSize.compact"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WebViewActionSize/init(rawValue:)":{"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/webviewactionsize\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/init(rawValue:)","title":"init(rawValue:)"},"doc://com.zendesk.ConversationKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ"},"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"ZDKWebViewActionSize","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKWebViewActionSize","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKWebViewActionSize","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/compact","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/full","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WebViewActionSize\/tall"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKWebViewActionSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize\/title","value":"ZDKWebViewActionSize","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize\/fragments","value":[{"kind":"identifier","text":"ZDKWebViewActionSize"}],"op":"replace"},{"value":"ZDKWebViewActionSizeFull","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize~1full\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize~1full\/fragments","value":[{"kind":"identifier","text":"ZDKWebViewActionSizeFull"}]},{"value":"ZDKWebViewActionSizeTall","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize~1tall\/title"},{"op":"replace","value":[{"text":"ZDKWebViewActionSizeTall","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize~1tall\/fragments"},{"value":"ZDKWebViewActionSizeCompact","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize~1compact\/title"},{"value":[{"text":"ZDKWebViewActionSizeCompact","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WebViewActionSize~1compact\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}