{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addEventObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"closure","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"ZDKConversationKitEvent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Object to observe the events."}]}]},{"name":"closure","content":[{"type":"paragraph","inlineContent":[{"text":"Closure to receive events on.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"This does not cause a retain cycle.","type":"text"},{"text":" ","type":"text"},{"text":"If the passed observer is deinitialized it will be automatically removed from the list.","type":"text"}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/addEventObserver(_:closure:)"},"metadata":{"symbolKind":"method","required":true,"role":"symbol","roleHeading":"Instance Method","title":"addEventObserver(_:closure:)","navigatorTitle":[{"kind":"identifier","text":"addEventObserver:closure:"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit(im)addEventObserver:closure:","modules":[{"name":"ZendeskSDKConversationKit"}],"platforms":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ZDKConversationKitEvent","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Add a type of "},{"type":"codeVoice","code":"AnyObject"},{"type":"text","text":" to listen for "},{"type":"codeVoice","code":"ZDKConversationKitEvent"},{"type":"text","text":" updates."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/addeventobserver(_:closure:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/addeventobserver(_:closure:)"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/addEventObserver(_:closure:)":{"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addEventObserver:closure:"}],"title":"addEventObserver(_:closure:)","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/addeventobserver(_:closure:)","deprecated":true,"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/addEventObserver(_:closure:)","abstract":[{"type":"text","text":"Add a type of "},{"code":"AnyObject","type":"codeVoice"},{"type":"text","text":" to listen for "},{"code":"ZDKConversationKitEvent","type":"codeVoice"},{"type":"text","text":" updates."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ZDKConversationKitEvent","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitObjC","kind":"identifier"}],"abstract":[{"code":"ConversationKitObjC","type":"codeVoice"},{"text":" needs to be configured  with a ","type":"text"},{"code":"Config","type":"codeVoice"},{"text":" ","type":"text"},{"text":"that includes the necessary ","type":"text"},{"code":"integrationId","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"integrationId","type":"codeVoice"},{"text":" can be retrieved from the Native Messaging dashboard.","type":"text"}],"navigatorTitle":[{"text":"ConversationKitObjC","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","title":"ConversationKitObjC","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationKitEvent":{"type":"topic","abstract":[{"type":"text","text":"List of events that covers all events that could come from "},{"code":"ConversationKit","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKConversationKitEvent"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationKitEvent"}],"title":"ZDKConversationKitEvent","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationkitevent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"addEventObserver:closure:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addEventObserver:closure:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"addEventObserver:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"observer"},{"kind":"text","text":" "},{"kind":"identifier","text":"closure:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationKitEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent","text":"ZDKConversationKitEvent"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"keyword","text":"id"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"closure"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"observer","content":[{"inlineContent":[{"text":"Object to observe the events.","type":"text"}],"type":"paragraph"}]},{"name":"closure","content":[{"type":"paragraph","inlineContent":[{"text":"Closure to receive events on.","type":"text"}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1addEventObserver(_:closure:)\/title","op":"replace","value":"addEventObserver:closure:"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1addEventObserver(_:closure:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addEventObserver:closure:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title","op":"replace","value":"ZDKConversationKit"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments","op":"replace","value":[{"text":"ZDKConversationKit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/navigatorTitle","op":"replace","value":[{"text":"ZDKConversationKit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/title","op":"replace","value":"ZDKConversationKitEvent"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationKitEvent"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationKitEvent\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationKitEvent"}]}]}]}