{"metadata":{"required":true,"modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKField(py)id","title":"id","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"id"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/field\/id"]},{"paths":["\/documentation\/zendesksdkconversationkit\/field\/id"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field\/id"},"kind":"symbol","abstract":[{"type":"text","text":"The id of the "},{"code":"Field","type":"codeVoice"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Field/id":{"required":true,"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field\/id","title":"id","abstract":[{"type":"text","text":"The id of the "},{"code":"Field","type":"codeVoice"}],"url":"\/documentation\/zendesksdkconversationkit\/field\/id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"id"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Field":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field","url":"\/documentation\/zendesksdkconversationkit\/field","abstract":[{"type":"text","text":"Objective-C representation of the fields in a "},{"type":"codeVoice","code":"Form"},{"text":" message","type":"text"}],"title":"Field","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Field","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Field"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"id","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"id","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field~1id\/title","value":"id","op":"replace"},{"value":[{"kind":"identifier","text":"id"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field~1id\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field\/title","value":"ZDKField"},{"value":[{"text":"ZDKField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}