{"abstract":[{"type":"text","text":"Invoked when the first reply has been sent in a conversation opened through a proactive message."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/conversationhasbeenrepliedto"]},{"paths":["\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/conversationhasbeenrepliedto"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"ProactiveMessageStatus.conversationHasBeenRepliedTo","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus@ZDKProactiveMessageStatusConversationHasBeenRepliedTo","navigatorTitle":[{"kind":"identifier","text":"ZDKProactiveMessageStatusConversationHasBeenRepliedTo"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationHasBeenRepliedTo"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationHasBeenRepliedTo"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/conversationHasBeenRepliedTo","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus":{"url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus","title":"ProactiveMessageStatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ProactiveMessageStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ProactiveMessageStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","abstract":[{"text":"Status that compliments a ","type":"text"},{"type":"codeVoice","code":"ProactiveMessageStatusChanged"},{"type":"text","text":" event in "},{"code":"ConversationKitEvent","type":"codeVoice"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus/conversationHasBeenRepliedTo":{"url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus\/conversationhasbeenrepliedto","title":"ProactiveMessageStatus.conversationHasBeenRepliedTo","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversationHasBeenRepliedTo","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKProactiveMessageStatusConversationHasBeenRepliedTo"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus\/conversationHasBeenRepliedTo","abstract":[{"type":"text","text":"Invoked when the first reply has been sent in a conversation opened through a proactive message."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"ZDKProactiveMessageStatusConversationHasBeenRepliedTo","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"ZDKProactiveMessageStatusConversationHasBeenRepliedTo","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKProactiveMessageStatusConversationHasBeenRepliedTo"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/title","op":"replace","value":"ZDKProactiveMessageStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatus"}]},{"value":"ZDKProactiveMessageStatusConversationHasBeenRepliedTo","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1conversationHasBeenRepliedTo\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus~1conversationHasBeenRepliedTo\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatusConversationHasBeenRepliedTo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}