{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" wait time banner is set to null or has invalid status."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationroutingstatus\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationroutingstatus\/unknown"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus\/unknown"},"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConversationRoutingStatusUnknown"}],"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationRoutingStatus@ZDKConversationRoutingStatusUnknown","symbolKind":"case","role":"symbol","title":"ConversationRoutingStatus.unknown","modules":[{"name":"ZendeskSDKConversationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus"]]},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationRoutingStatus/unknown":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus\/unknown","type":"topic","abstract":[{"type":"text","text":"A "},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":" wait time banner is set to null or has invalid status."}],"title":"ConversationRoutingStatus.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationroutingstatus\/unknown","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKConversationRoutingStatusUnknown"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationRoutingStatus":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationRoutingStatus"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationRoutingStatus"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationRoutingStatus","url":"\/documentation\/zendesksdkconversationkit\/conversationroutingstatus","kind":"symbol","title":"ConversationRoutingStatus","abstract":[{"text":"Represents the possible types of ","type":"text"},{"code":"routingStatus","type":"codeVoice"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKConversationRoutingStatusUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKConversationRoutingStatusUnknown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKConversationRoutingStatusUnknown"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus~1unknown\/title","value":"ZDKConversationRoutingStatusUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus~1unknown\/fragments","value":[{"kind":"identifier","text":"ZDKConversationRoutingStatusUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus\/title","value":"ZDKConversationRoutingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus\/fragments","value":[{"text":"ZDKConversationRoutingStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationRoutingStatus\/navigatorTitle","value":[{"text":"ZDKConversationRoutingStatus","kind":"identifier"}]}]}]}