{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversations","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","kind":"typeIdentifier","text":"Conversation"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationlist\/conversations"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkconversationlist\/conversations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"A list of "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList"]]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationList\/conversations","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationList(py)conversations","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversations"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation"},{"kind":"text","text":"]"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"role":"symbol","symbolKind":"property","title":"conversations","roleHeading":"Instance Property","navigatorTitle":[{"text":"conversations","kind":"identifier"}]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Conversation"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"abstract":[],"title":"Conversation","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKConversationList/conversations":{"type":"topic","title":"conversations","role":"symbol","abstract":[{"type":"text","text":"A list of "},{"code":"Conversation","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"conversations","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"conversations","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKConversationList\/conversations","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdkconversationlist\/conversations"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","role":"collection","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationList":{"type":"topic","title":"ConversationList","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationList"}],"navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationList","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationlist"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"conversations","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"conversations","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<ZDKConversation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"conversations"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"ZDKConversation","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title"},{"value":[{"kind":"identifier","text":"ZDKConversation"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationList~1conversations\/title","op":"replace","value":"conversations"},{"op":"replace","value":[{"text":"conversations","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKConversationList~1conversations\/fragments"},{"value":"ZDKConversationList","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationList\/fragments","value":[{"text":"ZDKConversationList","kind":"identifier"}]}]}]}