{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/imagemessagecontent\/actions"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ImageMessageContent"]]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ImageMessageContent\/actions","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","title":"actions","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property","externalID":"s:25ZendeskSDKConversationKit19ImageMessageContentC7actionsSayAA0E11ActionModelOGSgvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO","text":"MessageActionModel","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO","text":"MessageActionModel","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionModel"},{"kind":"text","text":"]?"}]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ImageMessageContent/actions":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageActionModel","preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO"},{"kind":"text","text":"]?"}],"title":"actions","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/imagemessagecontent\/actions","abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ImageMessageContent\/actions","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionModel":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionModel","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageActionModel","kind":"identifier"}],"role":"symbol","title":"MessageActionModel","navigatorTitle":[{"text":"MessageActionModel","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionmodel","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ImageMessageContent":{"navigatorTitle":[{"kind":"identifier","text":"ImageMessageContent"}],"kind":"symbol","abstract":[],"title":"ImageMessageContent","url":"\/documentation\/zendesksdkconversationkit\/imagemessagecontent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ImageMessageContent","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageMessageContent"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ImageMessageContent\/title","value":"ZDKImageMessageContent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ImageMessageContent\/fragments","value":[{"text":"ZDKImageMessageContent","kind":"identifier"}]},{"value":[{"text":"ZDKImageMessageContent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ImageMessageContent\/navigatorTitle"}]}]}