{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"init","title":"init(quotedMessageId:formFields:metadata:)","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"quotedMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"formFields","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"FormField","preciseIdentifier":"s:25ZendeskSDKConversationKit9FormFieldO","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"role":"symbol","roleHeading":"Initializer","externalID":"s:25ZendeskSDKConversationKit26FormResponseMessageContentC06quotedF2Id10formFields8metadataACSS_SayAA0D5FieldOGSDySSs11AnyHashableVGSgtcfc"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent\/init(quotedmessageid:formfields:metadata:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/init(quotedMessageId:formFields:metadata:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"quotedMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"formFields","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"FormField","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormField","preciseIdentifier":"s:25ZendeskSDKConversationKit9FormFieldO"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent":{"kind":"symbol","abstract":[{"type":"codeVoice","code":"FormResponse"},{"type":"text","text":" related "},{"type":"codeVoice","code":"MessageContent"},{"type":"text","text":". Used to display a submitted form."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseMessageContent","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseMessageContent","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent","title":"FormResponseMessageContent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormField":{"abstract":[{"type":"text","text":"Enum representing the Field"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/formfield","kind":"symbol","title":"FormField","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormField","kind":"identifier"}],"navigatorTitle":[{"text":"FormField","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormField"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent/init(quotedMessageId:formFields:metadata:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"quotedMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"formFields","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:25ZendeskSDKConversationKit9FormFieldO","text":"FormField","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent\/init(quotedMessageId:formFields:metadata:)","url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent\/init(quotedmessageid:formfields:metadata:)","type":"topic","title":"init(quotedMessageId:formFields:metadata:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/title","op":"replace","value":"ZDKFormResponseMessageContent"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/fragments","op":"replace","value":[{"text":"ZDKFormResponseMessageContent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKFormResponseMessageContent"}]}]}]}