{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/Region-swift.enum"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/Region-swift.enum\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/config\/region-swift.enum\/equatable-implementations"]}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/Region-swift.enum\/!=(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"}],"metadata":{"title":"Equatable Implementations","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"API Collection","role":"collectionGroup"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config/Region-swift.enum/!=(_:_:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/Region-swift.enum\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/config\/region-swift.enum\/!=(_:_:)","title":"!=(_:_:)","type":"topic","role":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config/Region-swift.enum":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config\/Region-swift.enum","kind":"symbol","title":"Config.Region","role":"symbol","abstract":[{"type":"text","text":"The region used to connect to the server."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Region"}],"navigatorTitle":[{"kind":"identifier","text":"Region"}],"url":"\/documentation\/zendesksdkconversationkit\/config\/region-swift.enum"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Config":{"url":"\/documentation\/zendesksdkconversationkit\/config","abstract":[],"title":"Config","navigatorTitle":[{"kind":"identifier","text":"Config"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Config","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Config"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/title","op":"replace","value":"ZDKConfig"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/fragments","op":"replace","value":[{"text":"ZDKConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Config\/navigatorTitle","op":"replace","value":[{"text":"ZDKConfig","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}