{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitbuilderobjc\/build()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitbuilderobjc\/build()"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC\/build()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"build"}],"title":"build()","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKitBuilder(im)build","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ConversationKitObjC","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit"}],"platforms":[],"modules":[{"name":"ZendeskSDKConversationKit"}],"required":true,"role":"symbol"},"abstract":[{"type":"text","text":"Returns an initialized type conforming to the "},{"code":"ConversationKitObjC","type":"codeVoice"},{"type":"text","text":" protocol"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ConversationKitObjC","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitBuilderObjC/build()":{"required":true,"role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Returns an initialized type conforming to the "},{"type":"codeVoice","code":"ConversationKitObjC"},{"type":"text","text":" protocol"}],"navigatorTitle":[{"kind":"identifier","text":"build"}],"title":"build()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit","kind":"typeIdentifier","text":"ConversationKitObjC"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitbuilderobjc\/build()","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC\/build()"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitBuilderObjC":{"title":"ConversationKitBuilderObjC","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC","abstract":[{"type":"text","text":"Type conforming to "},{"type":"codeVoice","code":"ConversationKitBuilderObjC"},{"type":"text","text":" provide methods which vend concrete types of "},{"type":"codeVoice","code":"ConversationKitObjC"}],"navigatorTitle":[{"text":"ConversationKitBuilderObjC","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitbuilderobjc","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitBuilderObjC","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"abstract":[{"type":"codeVoice","code":"ConversationKitObjC"},{"text":" needs to be configured  with a ","type":"text"},{"type":"codeVoice","code":"Config"},{"text":" ","type":"text"},{"text":"that includes the necessary ","type":"text"},{"type":"codeVoice","code":"integrationId"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"integrationId"},{"text":" can be retrieved from the Native Messaging dashboard.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ConversationKitObjC","kind":"identifier"}],"title":"ConversationKitObjC","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitObjC","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"build"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id<ZDKConversationKit>","preciseIdentifier":"c:Qo@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"build","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC~1build()\/title","value":"build"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC~1build()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"build","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC\/title","value":"ZDKConversationKitBuilder"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC\/fragments","value":[{"text":"ZDKConversationKitBuilder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKConversationKitBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title","value":"ZDKConversationKit"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/navigatorTitle","value":[{"text":"ZDKConversationKit","kind":"identifier"}]}]}]}