{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessage"},{"kind":"text","text":": "},{"text":"ProactiveMessage","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged\/proactivemessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged\/proactivemessage"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"proactiveMessage","symbolKind":"property","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessageStatusChanged(py)proactiveMessage","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","kind":"typeIdentifier","text":"ProactiveMessage"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"text":"proactiveMessage","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged\/proactiveMessage"},"abstract":[{"type":"text","text":"The content of the "},{"type":"codeVoice","code":"ProactiveMessage"},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessage":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","url":"\/documentation\/zendesksdkconversationkit\/proactivemessage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProactiveMessage"}],"abstract":[],"title":"ProactiveMessage","type":"topic","navigatorTitle":[{"text":"ProactiveMessage","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKProactiveMessageStatusChanged":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKProactiveMessageStatusChanged","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKProactiveMessageStatusChanged"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged","url":"\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged","title":"ZDKProactiveMessageStatusChanged","role":"symbol","kind":"symbol","abstract":[{"text":"A ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"type":"text","text":" event has occurred"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKProactiveMessageStatusChanged/proactiveMessage":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proactiveMessage","kind":"identifier"},{"kind":"text","text":": "},{"text":"ProactiveMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"proactiveMessage"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKProactiveMessageStatusChanged\/proactiveMessage","title":"proactiveMessage","url":"\/documentation\/zendesksdkconversationkit\/zdkproactivemessagestatuschanged\/proactivemessage","role":"symbol","kind":"symbol","abstract":[{"text":"The content of the ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"proactiveMessage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"proactiveMessage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"ZDKProactiveMessage","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"proactiveMessage"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"ZDKProactiveMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/title"},{"value":[{"kind":"identifier","text":"ZDKProactiveMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged\/title","value":"ZDKProactiveMessageStatusChanged","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKProactiveMessageStatusChanged"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged\/fragments"},{"value":"proactiveMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged~1proactiveMessage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKProactiveMessageStatusChanged~1proactiveMessage\/fragments","value":[{"text":"proactiveMessage","kind":"identifier"}]}]}]}