{"metadata":{"externalID":"s:25ZendeskSDKConversationKit17MessageActionItemC5title15itemDescription8mediaURL12attachmentId4size0J4Type7actionsACSS_S3SSgAA0eF4SizeOSSSayAA0dE5ModelOGtcfc","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"itemDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mediaURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"attachmentId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"text":"ActionItemSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageItemSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"actions","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageActionModel","preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO"},{"text":"])","kind":"text"}],"role":"symbol","title":"init(title:itemDescription:mediaURL:attachmentId:size:mediaType:actions:)","symbolKind":"init","modules":[{"name":"ZendeskSDKConversationKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"itemDescription"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"mediaURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"attachmentId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageItemSize","text":"ActionItemSize","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaType"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"actions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MessageActionModel","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionModel","preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO"},{"text":"])","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/messageactionitem\/init(title:itemdescription:mediaurl:attachmentid:size:mediatype:actions:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem\/init(title:itemDescription:mediaURL:attachmentId:size:mediaType:actions:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionModel":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionModel","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageActionModel","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionmodel","navigatorTitle":[{"text":"MessageActionModel","kind":"identifier"}],"title":"MessageActionModel","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionItem/init(title:itemDescription:mediaURL:attachmentId:size:mediaType:actions:)":{"title":"init(title:itemDescription:mediaURL:attachmentId:size:mediaType:actions:)","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/messageactionitem\/init(title:itemdescription:mediaurl:attachmentid:size:mediatype:actions:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem\/init(title:itemDescription:mediaURL:attachmentId:size:mediaType:actions:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"itemDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mediaURL"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"attachmentId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"text":"ActionItemSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageItemSize"},{"text":", ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"actions","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO","kind":"typeIdentifier","text":"MessageActionModel"},{"text":"])","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ActionItemSize":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ActionItemSize","abstract":[{"text":"The display size of ","type":"text"},{"type":"codeVoice","code":"MessageActionItem"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionItemSize"}],"url":"\/documentation\/zendesksdkconversationkit\/actionitemsize","navigatorTitle":[{"text":"ActionItemSize","kind":"identifier"}],"title":"ActionItemSize","role":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageActionItem":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageActionItem","abstract":[{"type":"text","text":"An item in a list type message, such as list or carousel."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageActionItem","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/messageactionitem","navigatorTitle":[{"text":"MessageActionItem","kind":"identifier"}],"title":"MessageActionItem","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKMessageItemSize","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ActionItemSize\/fragments","value":[{"text":"ZDKMessageItemSize","kind":"identifier"}]},{"value":"ZDKMessageActionItem","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageActionItem\/fragments","value":[{"kind":"identifier","text":"ZDKMessageActionItem"}],"op":"replace"}]}]}