{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"waitTimeEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"queuePositionEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlyDecreasingQueue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"waitTimeOverride","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"text":"pollingInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/waittimeconfig\/init(waittimeenabled:queuepositionenabled:onlydecreasingqueue:waittimeoverride:pollinginterval:)"]},{"paths":["\/documentation\/zendesksdkconversationkit\/waittimeconfig\/init(waittimeenabled:queuepositionenabled:onlydecreasingqueue:waittimeoverride:pollinginterval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig\/init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:)","interfaceLanguage":"swift"},"metadata":{"title":"init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:)","symbolKind":"init","navigatorTitle":[{"text":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:","kind":"identifier"}],"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig(im)initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"waitTimeEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"queuePositionEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onlyDecreasingQueue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"waitTimeOverride"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pollingInterval"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"modules":[{"name":"ZendeskSDKConversationKit"}]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeConfig":{"kind":"symbol","type":"topic","title":"WaitTimeConfig","role":"symbol","abstract":[{"text":"The wait time configuration. Contains config related to queue position and wait time behaviour.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig","url":"\/documentation\/zendesksdkconversationkit\/waittimeconfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WaitTimeConfig","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"WaitTimeConfig"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeConfig/init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:)":{"url":"\/documentation\/zendesksdkconversationkit\/waittimeconfig\/init(waittimeenabled:queuepositionenabled:onlydecreasingqueue:waittimeoverride:pollinginterval:)","type":"topic","title":"init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"waitTimeEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"queuePositionEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlyDecreasingQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"waitTimeOverride","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"pollingInterval","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig\/init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:)","navigatorTitle":[{"text":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","role":"collection","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithWaitTimeEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"waitTimeEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"queuePositionEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"queuePositionEnabled"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onlyDecreasingQueue:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"onlyDecreasingQueue","kind":"internalParam"},{"kind":"text","text":" "},{"text":"waitTimeOverride:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"waitTimeOverride"},{"kind":"text","text":" "},{"text":"pollingInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pollingInterval","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/title","value":"ZDKWaitTimeConfig"},{"op":"replace","value":[{"text":"ZDKWaitTimeConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig~1init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:)\/title","value":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithWaitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig~1init(waitTimeEnabled:queuePositionEnabled:onlyDecreasingQueue:waitTimeOverride:pollingInterval:)\/fragments"}]}]}