{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig"]]},"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeConfig(py)pollingInterval","roleHeading":"Instance Property","title":"pollingInterval","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pollingInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"pollingInterval","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Interval in seconds at which the SDK should poll for updates from the backend.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pollingInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/waittimeconfig\/pollinginterval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/waittimeconfig\/pollinginterval"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig\/pollingInterval","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeConfig/pollingInterval":{"kind":"symbol","type":"topic","title":"pollingInterval","role":"symbol","abstract":[{"text":"Interval in seconds at which the SDK should poll for updates from the backend.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig\/pollingInterval","url":"\/documentation\/zendesksdkconversationkit\/waittimeconfig\/pollinginterval","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"pollingInterval","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"pollingInterval"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeConfig":{"kind":"symbol","type":"topic","title":"WaitTimeConfig","role":"symbol","abstract":[{"text":"The wait time configuration. Contains config related to queue position and wait time behaviour.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeConfig","url":"\/documentation\/zendesksdkconversationkit\/waittimeconfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WaitTimeConfig","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"WaitTimeConfig"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"pollingInterval","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"pollingInterval","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"pollingInterval"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig~1pollingInterval\/title","op":"replace","value":"pollingInterval"},{"value":[{"kind":"identifier","text":"pollingInterval"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig~1pollingInterval\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/title","value":"ZDKWaitTimeConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeConfig\/fragments","value":[{"text":"ZDKWaitTimeConfig","kind":"identifier"}]}]}]}