{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/waitTimeData"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkwaittimedataresult\/waittimedata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkwaittimedataresult\/waittimedata"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeDataResult(py)waitTimeData","symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"waitTimeData","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"waitTimeData","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData","text":"WaitTimeData","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"waitTimeData","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitTimeData","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","text":"WaitTimeData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"text":"?","kind":"text"}]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData":{"kind":"symbol","type":"topic","title":"WaitTimeData","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WaitTimeData"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","navigatorTitle":[{"text":"WaitTimeData","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/waittimedata"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKWaitTimeDataResult":{"title":"ZDKWaitTimeDataResult","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKWaitTimeDataResult","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKWaitTimeDataResult","kind":"identifier"}],"abstract":[{"text":"The event that gets emitted when the wait time data was fetched","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkwaittimedataresult"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKWaitTimeDataResult/waitTimeData":{"title":"waitTimeData","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKWaitTimeDataResult\/waitTimeData","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitTimeData","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData","text":"WaitTimeData"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"waitTimeData"}],"abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/zdkwaittimedataresult\/waittimedata"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","kind":"symbol","role":"collection","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"waitTimeData","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"waitTimeData","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ZDKWaitTimeData","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"waitTimeData"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/title","op":"replace","value":"ZDKWaitTimeData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/fragments","value":[{"text":"ZDKWaitTimeData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult\/title","value":"ZDKWaitTimeDataResult"},{"value":[{"text":"ZDKWaitTimeDataResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult~1waitTimeData\/title","op":"replace","value":"waitTimeData"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKWaitTimeDataResult~1waitTimeData\/fragments","op":"replace","value":[{"text":"waitTimeData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}