{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"title":"AuthenticationType.unauthenticated","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKAuthenticationType@ZDKAuthenticationTypeUnauthenticated","modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationTypeUnauthenticated"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unauthenticated","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType"]]},"abstract":[{"text":"Unauthenticated","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unauthenticated","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/authenticationtype\/unauthenticated"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/authenticationtype\/unauthenticated"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType\/unauthenticated"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/AuthenticationType/unauthenticated":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unauthenticated"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationTypeUnauthenticated"}],"url":"\/documentation\/zendesksdkconversationkit\/authenticationtype\/unauthenticated","role":"symbol","title":"AuthenticationType.unauthenticated","abstract":[{"text":"Unauthenticated","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType\/unauthenticated"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","type":"topic","title":"ZendeskSDKConversationKit","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/AuthenticationType":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/AuthenticationType","role":"symbol","title":"AuthenticationType","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationType"}],"url":"\/documentation\/zendesksdkconversationkit\/authenticationtype","kind":"symbol","navigatorTitle":[{"text":"AuthenticationType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ZDKAuthenticationTypeUnauthenticated"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"ZDKAuthenticationTypeUnauthenticated","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"ZDKAuthenticationTypeUnauthenticated","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKAuthenticationTypeUnauthenticated","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType~1unauthenticated\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType~1unauthenticated\/fragments","value":[{"text":"ZDKAuthenticationTypeUnauthenticated","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/title","value":"ZDKAuthenticationType"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1AuthenticationType\/fragments","op":"replace","value":[{"text":"ZDKAuthenticationType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}