{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"fields","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Field","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKField","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/fields"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/fields"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/fields","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKFormResponseMessageContent(py)fields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKField","kind":"typeIdentifier","text":"Field"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"fields","kind":"identifier"}],"title":"fields"},"abstract":[{"type":"text","text":"The form fields for this form"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKFormResponseMessageContent/fields":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fields"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKField","text":"Field","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/fields","abstract":[{"type":"text","text":"The form fields for this form"}],"navigatorTitle":[{"text":"fields","kind":"identifier"}],"title":"fields","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/fields"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent":{"url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FormResponseMessageContent","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormResponseMessageContent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent","kind":"symbol","abstract":[{"code":"FormResponse","type":"codeVoice"},{"text":" related ","type":"text"},{"type":"codeVoice","code":"MessageContent"},{"text":". Used to display a submitted form.","type":"text"}],"title":"FormResponseMessageContent","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Field":{"kind":"symbol","title":"Field","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Field"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Field"}],"url":"\/documentation\/zendesksdkconversationkit\/field","abstract":[{"text":"Objective-C representation of the fields in a ","type":"text"},{"code":"Form","type":"codeVoice"},{"type":"text","text":" message"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Field"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"fields","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fields"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<id<ZDKField>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"fields"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"fields","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1fields\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1fields\/fragments","op":"replace","value":[{"kind":"identifier","text":"fields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/title","value":"ZDKFormResponseMessageContent"},{"value":[{"text":"ZDKFormResponseMessageContent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field\/title","op":"replace","value":"ZDKField"},{"value":[{"kind":"identifier","text":"ZDKField"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Field\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}