{"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"kind":"identifier","text":"quotedMessageId"}],"role":"symbol","title":"quotedMessageId","roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKFormResponseMessageContent(py)quotedMessageId","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quotedMessageId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/quotedmessageid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/quotedmessageid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent"]]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/quotedMessageId","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The message id of the form to which this form response is responding."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quotedMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKFormResponseMessageContent/quotedMessageId":{"url":"\/documentation\/zendesksdkconversationkit\/zdkformresponsemessagecontent\/quotedmessageid","navigatorTitle":[{"text":"quotedMessageId","kind":"identifier"}],"abstract":[{"type":"text","text":"The message id of the form to which this form response is responding."}],"role":"symbol","title":"quotedMessageId","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"quotedMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKFormResponseMessageContent\/quotedMessageId"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/FormResponseMessageContent":{"url":"\/documentation\/zendesksdkconversationkit\/formresponsemessagecontent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FormResponseMessageContent","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormResponseMessageContent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/FormResponseMessageContent","kind":"symbol","abstract":[{"code":"FormResponse","type":"codeVoice"},{"text":" related ","type":"text"},{"type":"codeVoice","code":"MessageContent"},{"text":". Used to display a submitted form.","type":"text"}],"title":"FormResponseMessageContent","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"quotedMessageId","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"quotedMessageId","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"quotedMessageId"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1quotedMessageId\/title","op":"replace","value":"quotedMessageId"},{"value":[{"kind":"identifier","text":"quotedMessageId"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKFormResponseMessageContent~1quotedMessageId\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/title","value":"ZDKFormResponseMessageContent","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKFormResponseMessageContent"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1FormResponseMessageContent\/fragments","op":"replace"}]}]}