{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitobjc"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitObjC","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationKitObjC"}],"title":"ConversationKitObjC","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit","role":"symbol","symbolKind":"protocol","modules":[{"name":"ZendeskSDKConversationKit"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKConversationKit) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitObjC"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared","text":"ConversationKitShared"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"syntax":"objc","type":"codeListing","code":["id<ConversationKitObjC> conversationKit = [[[ZDKDefaultConversationKitBuilder alloc] init] build];","ZDKConversationKitSettings *settings = [[ZDKConversationKitSettings alloc] initWithIntegrationId:id];","[conversationKit setupWith:settings completion: nil];"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/addEventObserver(_:closure:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/createAnonymousUser(with:surname:proactiveMessageId:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/createConversation(proactiveMessageId:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getConversation(with:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getConversations(offset:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getMessages(before:conversationId:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getVisitType(completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/loginUser(with:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/logoutUser(completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendConversationActivity(activity:conversationId:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendConversationReferral(proactiveMessageId:conversationId:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendMessage(message:conversationId:completion:)"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"abstract":[{"code":"ConversationKitObjC","type":"codeVoice"},{"text":" needs to be configured  with a ","type":"text"},{"type":"codeVoice","code":"ConversationKitSettings"},{"type":"text","text":" "},{"type":"text","text":"that includes the necessary "},{"code":"integrationId","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"integrationId","type":"codeVoice"},{"type":"text","text":" can be retrieved from the Native Messaging dashboard."}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/sendMessage(message:conversationId:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Message","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage","text":"Message","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"sendMessageWithMessage:conversationId:completion:"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendmessage(message:conversationid:completion:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendMessage(message:conversationId:completion:)","title":"sendMessage(message:conversationId:completion:)","kind":"symbol","role":"symbol","abstract":[{"text":"Call to send a ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":". This call will trigger a network request.","type":"text"}],"required":true,"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/getMessages(before:conversationId:completion:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getMessages(before:conversationId:completion:)","title":"getMessages(before:conversationId:completion:)","type":"topic","required":true,"navigatorTitle":[{"text":"getMessagesBefore:conversationId:completion:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getMessages","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"before"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/getmessages(before:conversationid:completion:)","abstract":[{"type":"text","text":"Call to fetch a list of messages before a given record "},{"type":"codeVoice","code":"timestamp"},{"type":"text","text":" for a given "},{"type":"codeVoice","code":"conversation"},{"type":"text","text":". This call will trigger a network request."}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"title":"ConversationKitObjC","kind":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConversationKitObjC","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ConversationKitObjC"},{"type":"text","text":" needs to be configured  with a "},{"code":"ConversationKitSettings","type":"codeVoice"},{"text":" ","type":"text"},{"text":"that includes the necessary ","type":"text"},{"code":"integrationId","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"integrationId"},{"text":" can be retrieved from the Native Messaging dashboard.","type":"text"}],"navigatorTitle":[{"text":"ConversationKitObjC","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/getConversation(with:completion:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getConversation(with:completion:)","abstract":[{"type":"text","text":"Call to fetch a "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" object by its "},{"type":"codeVoice","code":"identifier"},{"type":"text","text":". This call will trigger a network request."}],"kind":"symbol","role":"symbol","title":"getConversation(with:completion:)","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"getConversationWith:completion:"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/getconversation(with:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getConversation"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/createAnonymousUser(with:surname:proactiveMessageId:completion:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/createAnonymousUser(with:surname:proactiveMessageId:completion:)","kind":"symbol","title":"createAnonymousUser(with:surname:proactiveMessageId:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createAnonymousUser"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"surname","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"proactiveMessageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","text":"User","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/createanonymoususer(with:surname:proactivemessageid:completion:)","navigatorTitle":[{"text":"createAnonymousUserWith:surname:proactiveMessageId:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Call to create an Anonymous "},{"code":"ZDKUser","type":"codeVoice"},{"type":"text","text":". This call will trigger a network."}],"required":true},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/getVisitType(completion:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getVisitType(completion:)","abstract":[{"type":"text","text":"Call to get the "},{"type":"codeVoice","code":"VisitType"},{"text":" for the current visitor.","type":"text"}],"kind":"symbol","role":"symbol","title":"getVisitType(completion:)","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"getVisitTypeWithCompletion:"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/getvisittype(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getVisitType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"VisitType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKVisitType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationKitShared"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationKitShared","kind":"identifier"}],"title":"ConversationKitShared","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/sendConversationActivity(activity:conversationId:completion:)":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendConversationActivity(activity:conversationId:completion:)","abstract":[{"type":"text","text":"Call to send an activity "},{"type":"codeVoice","code":"ActivityType"}],"kind":"symbol","role":"symbol","title":"sendConversationActivity(activity:conversationId:completion:)","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"sendConversationActivityWithActivity:conversationId:completion:"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendconversationactivity(activity:conversationid:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendConversationActivity"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"activity"},{"text":": ","kind":"text"},{"text":"ActivityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKActivityType"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/createConversation(proactiveMessageId:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createConversation"},{"text":"(","kind":"text"},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","text":"Conversation"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/createConversation(proactiveMessageId:completion:)","abstract":[{"type":"text","text":"Call to create a "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" for the current "},{"code":"User","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","title":"createConversation(proactiveMessageId:completion:)","type":"topic","required":true,"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/createconversation(proactivemessageid:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createConversationWithProactiveMessageId:completion:"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/getConversations(offset:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConversations"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"offset"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationList","text":"ConversationList"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getConversations(offset:completion:)","abstract":[{"type":"text","text":"Call to fetch the user’s list of conversations. This call will trigger a network request."}],"kind":"symbol","title":"getConversations(offset:completion:)","type":"topic","required":true,"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/getconversations(offset:completion:)","role":"symbol","navigatorTitle":[{"text":"getConversationsWithOffset:completion:","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/addEventObserver(_:closure:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addEventObserver"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s9AnyObjecta","kind":"typeIdentifier","text":"AnyObject"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closure"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationKitEvent","text":"ZDKConversationKitEvent"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s9AnyObjecta","text":"AnyObject"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/addEventObserver(_:closure:)","abstract":[{"text":"Add a type of ","type":"text"},{"type":"codeVoice","code":"AnyObject"},{"text":" to listen for ","type":"text"},{"code":"ZDKConversationKitEvent","type":"codeVoice"},{"text":" updates.","type":"text"}],"kind":"symbol","title":"addEventObserver(_:closure:)","type":"topic","required":true,"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/addeventobserver(_:closure:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addEventObserver:closure:"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/sendConversationReferral(proactiveMessageId:conversationId:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendConversationReferral","kind":"identifier"},{"kind":"text","text":"("},{"text":"proactiveMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation","kind":"typeIdentifier","text":"Conversation"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendConversationReferral(proactiveMessageId:conversationId:completion:)","abstract":[{"text":"Call to send a conversation referral. This call will fetch the updated conversation with the proactive message added.","type":"text"}],"kind":"symbol","title":"sendConversationReferral(proactiveMessageId:conversationId:completion:)","type":"topic","required":true,"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/sendconversationreferral(proactivemessageid:conversationid:completion:)","role":"symbol","navigatorTitle":[{"text":"sendConversationReferralWithProactiveMessageId:conversationId:completion:","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/loginUser(with:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loginUser"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","text":"User"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/loginUser(with:completion:)","abstract":[{"type":"text","text":"Call to authenticate a new user, or re-authenticate an existing user during a conversation."}],"kind":"symbol","title":"loginUser(with:completion:)","type":"topic","required":true,"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/loginuser(with:completion:)","role":"symbol","navigatorTitle":[{"text":"loginUserWith:completion:","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC/logoutUser(completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logoutUser"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/logoutUser(completion:)","abstract":[{"text":"Call to unauthenticate the current ","type":"text"},{"code":"User","type":"codeVoice"},{"text":" and remove their associated information from storage.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc\/logoutuser(completion:)","kind":"symbol","title":"logoutUser(completion:)","navigatorTitle":[{"text":"logoutUserWithCompletion:","kind":"identifier"}],"type":"topic","required":true}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"ZDKConversationKit","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"text":"ZDKConversationKit","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKConversationKit","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/addEventObserver(_:closure:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/createAnonymousUser(with:surname:proactiveMessageId:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/createConversation(proactiveMessageId:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getConversation(with:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getConversations(offset:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getMessages(before:conversationId:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/getVisitType(completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/loginUser(with:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/logoutUser(completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendConversationActivity(activity:conversationId:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendConversationReferral(proactiveMessageId:conversationId:completion:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC\/sendMessage(message:conversationId:completion:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKConversationKit","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","text":"ConversationKitShared","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendMessage(message:conversationId:completion:)\/title","value":"sendMessageWithMessage:conversationId:completion:"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendMessage(message:conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendMessageWithMessage:conversationId:completion:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getMessages(before:conversationId:completion:)\/title","value":"getMessagesBefore:conversationId:completion:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessagesBefore:conversationId:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getMessages(before:conversationId:completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title","op":"replace","value":"ZDKConversationKit"},{"value":[{"text":"ZDKConversationKit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getConversation(with:completion:)\/title","value":"getConversationWith:completion:"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getConversation(with:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"getConversationWith:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1createAnonymousUser(with:surname:proactiveMessageId:completion:)\/title","value":"createAnonymousUserWith:surname:proactiveMessageId:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1createAnonymousUser(with:surname:proactiveMessageId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createAnonymousUserWith:surname:proactiveMessageId:completion:"}],"op":"replace"},{"value":"getVisitTypeWithCompletion:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getVisitType(completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getVisitType(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVisitTypeWithCompletion:"}]},{"value":"ConversationKitShared","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title"},{"value":[{"kind":"identifier","text":"ConversationKitShared"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendConversationActivity(activity:conversationId:completion:)\/title","value":"sendConversationActivityWithActivity:conversationId:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendConversationActivity(activity:conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendConversationActivityWithActivity:conversationId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1createConversation(proactiveMessageId:completion:)\/title","value":"createConversationWithProactiveMessageId:completion:"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1createConversation(proactiveMessageId:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createConversationWithProactiveMessageId:completion:","kind":"identifier"}]},{"value":"getConversationsWithOffset:completion:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getConversations(offset:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1getConversations(offset:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getConversationsWithOffset:completion:"}],"op":"replace"},{"value":"addEventObserver:closure:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1addEventObserver(_:closure:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1addEventObserver(_:closure:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addEventObserver:closure:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"sendConversationReferralWithProactiveMessageId:conversationId:completion:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendConversationReferral(proactiveMessageId:conversationId:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1sendConversationReferral(proactiveMessageId:conversationId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sendConversationReferralWithProactiveMessageId:conversationId:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1loginUser(with:completion:)\/title","op":"replace","value":"loginUserWith:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1loginUser(with:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"loginUserWith:completion:","kind":"identifier"}]},{"value":"logoutUserWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1logoutUser(completion:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC~1logoutUser(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"logoutUserWithCompletion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}