{"metadata":{"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"ZendeskSDKConversationKit"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationKitShared"}],"title":"ConversationKitShared","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitShared"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationKitShared"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clientId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/config","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/currentUser","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/featureFlagManager","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/settings"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationFields()","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationTags()","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-7k823","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/pause()","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/removeEventObserver(_:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/resume()","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationFields(_:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setVisitType(_:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/updatePushNotificationToken(_:)"],"title":"Instance Methods"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearConversationFields()":{"type":"topic","required":true,"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationfields()","abstract":[{"type":"text","text":"Clears all fields from storage."}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationFields()","navigatorTitle":[{"text":"clearConversationFields","kind":"identifier"}],"title":"clearConversationFields()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearConversationFields"},{"kind":"text","text":"()"}],"kind":"symbol","defaultImplementations":1},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/setVisitType(_:)":{"abstract":[{"text":"Call to set the ","type":"text"},{"type":"codeVoice","code":"VisitType"},{"text":" for the current visitor.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setvisittype(_:)","type":"topic","role":"symbol","title":"setVisitType(_:)","navigatorTitle":[{"kind":"identifier","text":"setVisitType:"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setVisitType(_:)","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVisitType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VisitType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKVisitType"},{"text":")","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKit":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKit","title":"ConversationKit","navigatorTitle":[{"text":"ConversationKit","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationKit","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" needs to be configured  with "},{"type":"codeVoice","code":"SettingsParameters"},{"type":"text","text":" (that contains "},{"code":"ConversationKitSettings","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"Config"},{"type":"text","text":" and "},{"type":"codeVoice","code":"FeatureFlagManager"},{"text":")","type":"text"},{"text":" ","type":"text"},{"text":"and ","type":"text"},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"DefaultConversationKit"},{"type":"text","text":"’s initializer will create the App "},{"type":"codeVoice","code":"AccessLevel"},{"text":" and will check for a persisted user.","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clientId":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Current "},{"type":"codeVoice","code":"UUID"},{"text":" to identify the host app install","type":"text"}],"type":"topic","title":"clientId","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clientId","navigatorTitle":[{"kind":"identifier","text":"clientId"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clientid"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/currentUser":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/currentuser","abstract":[{"type":"text","text":"Current "},{"type":"codeVoice","code":"User"},{"type":"text","text":" if it exists."}],"required":true,"role":"symbol","navigatorTitle":[{"text":"currentUser","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentUser"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","kind":"typeIdentifier","text":"User"},{"text":"?","kind":"text"}],"title":"currentUser","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/currentUser","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/setConversationFields(_:)":{"title":"setConversationFields(_:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Provide a dictionary of custom fields."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationFields(_:)","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setConversationFields"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationfields(_:)","navigatorTitle":[{"text":"setConversationFields:","kind":"identifier"}],"defaultImplementations":1},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearConversationTags()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearConversationTags","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationTags()","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearconversationtags()","title":"clearConversationTags()","abstract":[{"text":"Clears all tags from storage.","type":"text"}],"defaultImplementations":1,"required":true,"role":"symbol","navigatorTitle":[{"text":"clearConversationTags","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/pause()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/pause()","title":"pause()","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/pause()","abstract":[{"text":"Call to pause the realtime connection that ","type":"text"},{"code":"ConversationKit","type":"codeVoice"},{"type":"text","text":" has with the backend."}],"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pause"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/setConversationTags(_:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setConversationTags","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}],"kind":"symbol","required":true,"abstract":[{"type":"text","text":"Provide an array of custom fields."}],"navigatorTitle":[{"text":"setConversationTags:","kind":"identifier"}],"defaultImplementations":1,"title":"setConversationTags(_:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/setconversationtags(_:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc":{"navigatorTitle":[{"kind":"identifier","text":"proactiveMessageStatusChanged:proactiveMessage:jwt:"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/proactivemessagestatuschanged(_:proactivemessage:jwt:)-4ctcc","defaultImplementations":1,"abstract":[{"text":"Processes a ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"text":" status change.","type":"text"}],"required":true,"role":"symbol","kind":"symbol","title":"proactiveMessageStatusChanged(_:proactiveMessage:jwt:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"proactiveMessageStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","text":"ProactiveMessageStatus"},{"text":", ","kind":"text"},{"text":"proactiveMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ProactiveMessage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"jwt"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/config":{"abstract":[{"type":"text","text":"Current "},{"type":"codeVoice","code":"Config"},{"text":" of ","type":"text"},{"code":"ConversationKit","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/config","type":"topic","role":"symbol","title":"config","navigatorTitle":[{"kind":"identifier","text":"config"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/config","required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"config","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConfig","text":"Config"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitObjC":{"title":"ConversationKitObjC","kind":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitobjc","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConversationKitObjC","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ConversationKitObjC"},{"type":"text","text":" needs to be configured  with a "},{"code":"ConversationKitSettings","type":"codeVoice"},{"text":" ","type":"text"},{"text":"that includes the necessary ","type":"text"},{"code":"integrationId","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"integrationId"},{"text":" can be retrieved from the Native Messaging dashboard.","type":"text"}],"navigatorTitle":[{"text":"ConversationKitObjC","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/removeEventObserver(_:)":{"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/removeeventobserver(_:)","kind":"symbol","title":"removeEventObserver(_:)","navigatorTitle":[{"kind":"identifier","text":"removeEventObserver:"}],"abstract":[{"text":"Remove a type of ","type":"text"},{"type":"codeVoice","code":"AnyObject"},{"type":"text","text":" from listening to "},{"code":"ConversationKitEvent","type":"codeVoice"},{"text":" updates.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeEventObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s9AnyObjecta","text":"AnyObject"},{"text":")","kind":"text"}],"required":true,"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/removeEventObserver(_:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/updatePushNotificationToken(_:)":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/updatePushNotificationToken(_:)","abstract":[{"type":"text","text":"Call to update a push notification token."}],"role":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/updatepushnotificationtoken(_:)","title":"updatePushNotificationToken(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updatePushNotificationToken","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"updatePushNotificationToken:","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/featureFlagManager":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/featureFlagManager","abstract":[{"type":"text","text":"Current "},{"type":"codeVoice","code":"FeatureFlagManager"},{"type":"text","text":"."}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/featureflagmanager","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"featureFlagManager"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"featureFlagManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FeatureFlagManager","preciseIdentifier":"c:@M@ZendeskSDKCoreUtilities@objc(cs)ZDKFeatureFlagManager"}],"title":"featureFlagManager","required":true},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationKitShared"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationKitShared","kind":"identifier"}],"title":"ConversationKitShared","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/resume()":{"navigatorTitle":[{"text":"resume","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/resume()","abstract":[{"type":"text","text":"Call to resume the realtime connection that "},{"type":"codeVoice","code":"ConversationKit"},{"type":"text","text":" has with the backend."}],"required":true,"role":"symbol","kind":"symbol","title":"resume()","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/resume()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resume","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/settings":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/settings","type":"topic","kind":"symbol","title":"settings","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"settings","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationKitSettings","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversationKitSettings"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/settings","navigatorTitle":[{"kind":"identifier","text":"settings"}],"abstract":[{"text":"Current ","type":"text"},{"type":"codeVoice","code":"ConversationKitSettings"},{"text":".","type":"text"}],"required":true},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearProactiveMessages(proactiveMessageIds:)-7k823":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearProactiveMessages","kind":"identifier"},{"kind":"text","text":"("},{"text":"proactiveMessageIds","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"])"}],"title":"clearProactiveMessages(proactiveMessageIds:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-7k823","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)-7k823","abstract":[{"text":"Call to delete proactive messages data from storage","type":"text"}],"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearProactiveMessagesWithProactiveMessageIds:"}],"defaultImplementations":1}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ConversationKitShared"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ConversationKitShared"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ConversationKitShared","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clientId","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/config","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/currentUser","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/featureFlagManager","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/settings"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationFields()","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearConversationTags()","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-7k823","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/pause()","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/removeEventObserver(_:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/resume()","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationFields(_:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setConversationTags(_:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/setVisitType(_:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/updatePushNotificationToken(_:)"]}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitObjC"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitShared"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearConversationFields()\/title","op":"replace","value":"clearConversationFields"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearConversationFields()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearConversationFields"}]},{"value":"setVisitType:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setVisitType(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setVisitType(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setVisitType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clientId\/title","op":"replace","value":"clientId"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clientId\/fragments","op":"replace","value":[{"text":"clientId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1currentUser\/title","value":"currentUser"},{"op":"replace","value":[{"text":"currentUser","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1currentUser\/fragments"},{"value":"setConversationFields:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationFields(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationFields(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConversationFields:"}]},{"op":"replace","value":"clearConversationTags","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearConversationTags()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearConversationTags()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"clearConversationTags","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1pause()\/title","value":"pause","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1pause()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pause"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationTags(_:)\/title","value":"setConversationTags:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1setConversationTags(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConversationTags:"}]},{"op":"replace","value":"proactiveMessageStatusChanged:proactiveMessage:jwt:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1proactiveMessageStatusChanged(_:proactiveMessage:jwt:)-4ctcc\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"proactiveMessageStatusChanged:proactiveMessage:jwt:"}]},{"value":"config","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1config\/title","op":"replace"},{"op":"replace","value":[{"text":"config","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1config\/fragments"},{"value":"ZDKConversationKit","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitObjC\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKit"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1removeEventObserver(_:)\/title","value":"removeEventObserver:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1removeEventObserver(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeEventObserver:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1updatePushNotificationToken(_:)\/title","value":"updatePushNotificationToken:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1updatePushNotificationToken(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updatePushNotificationToken:","kind":"identifier"}],"op":"replace"},{"value":"featureFlagManager","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1featureFlagManager\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1featureFlagManager\/fragments","value":[{"kind":"identifier","text":"featureFlagManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","value":[{"kind":"identifier","text":"ConversationKitShared"}],"op":"replace"},{"value":"resume","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1resume()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1resume()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resume"}]},{"value":"settings","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1settings\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1settings\/fragments","value":[{"kind":"identifier","text":"settings"}]},{"value":"clearProactiveMessagesWithProactiveMessageIds:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearProactiveMessages(proactiveMessageIds:)-7k823\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearProactiveMessagesWithProactiveMessageIds:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearProactiveMessages(proactiveMessageIds:)-7k823\/fragments"}]}]}