{"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH","doc:\/\/com.zendesk.ConversationKit\/SY"],"kind":"relationships","title":"Conforms To"}],"abstract":[{"type":"text","text":"Represents the possible types of a "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":"."}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKConversationType) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"metadata":{"role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationType"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"ConversationType","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"ConversationType"}],"symbolKind":"enum"},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/group","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/personal"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/Equatable-Implementations","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationtype"]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationtype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType/personal":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"personal","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationtype\/personal","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" between the "},{"type":"codeVoice","code":"User"},{"text":" and the service provider.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/personal","title":"ConversationType.personal","type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKConversationTypePersonal","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/SE":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/zendesksdkconversationkit\/conversationtype\/equatable-implementations","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/Equatable-Implementations","kind":"article","type":"topic"},"doc://com.zendesk.ConversationKit/SH":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationType","kind":"identifier"}],"title":"ConversationType","navigatorTitle":[{"text":"ConversationType","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationtype","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","abstract":[{"type":"text","text":"Represents the possible types of a "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":"."}]},"doc://com.zendesk.ConversationKit/SY":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/Se":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/SQ":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/zendesksdkconversationkit\/conversationtype\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType/group":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"group","kind":"identifier"}],"title":"ConversationType.group","navigatorTitle":[{"text":"ZDKConversationTypeGroup","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationtype\/group","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/group","type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" between multiple people, including the "},{"type":"codeVoice","code":"User"},{"type":"text","text":" and the service provider."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType/init(rawValue:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationtype\/init(rawvalue:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","value":"ZDKConversationType","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKConversationType"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKConversationType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/group","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/personal"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKConversationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType~1personal\/title","op":"replace","value":"ZDKConversationTypePersonal"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType~1personal\/fragments","op":"replace","value":[{"text":"ZDKConversationTypePersonal","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType\/title","value":"ZDKConversationType"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType\/fragments","op":"replace","value":[{"text":"ZDKConversationType","kind":"identifier"}]},{"value":"ZDKConversationTypeGroup","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType~1group\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType~1group\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConversationTypeGroup"}]}]}]}