{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"abstract":[{"text":"Text related ","type":"text"},{"type":"codeVoice","code":"MessageContent"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKTextMessageContent) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TextMessageContent","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKTextMessageContent","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"TextMessageContent","navigatorTitle":[{"text":"TextMessageContent","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextMessageContent"}]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/init(from:)","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/init(text:payload:actions:metadata:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/actions","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/messageActions","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/metadata","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/payload","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/text","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/type"]},{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/isEqual(_:)"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/textmessagecontent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/textmessagecontent"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/Se","doc:\/\/com.zendesk.ConversationKit\/SE","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.zendesk.ConversationKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKTextMessageContent/type":{"abstract":[{"text":"The type of the ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"role":"symbol","title":"type","url":"\/documentation\/zendesksdkconversationkit\/zdktextmessagecontent\/type","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/type"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent/actions":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO","text":"MessageActionModel"},{"kind":"text","text":"]?"}],"type":"topic","title":"actions","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/actions","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent\/actions","abstract":[]},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ConversationKit/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SE"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKTextMessageContent/text":{"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/zdktextmessagecontent\/text","abstract":[{"text":"The text of the ","type":"text"},{"type":"codeVoice","code":"Message"},{"text":".","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","title":"text","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/text","navigatorTitle":[{"kind":"identifier","text":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKTextMessageContent/payload":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/payload","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/zdktextmessagecontent\/payload","kind":"symbol","title":"payload","role":"symbol","abstract":[{"text":"The payload of the ","type":"text"},{"type":"codeVoice","code":"Message"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"payload","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"payload"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent/init(text:payload:actions:metadata:)":{"title":"init(text:payload:actions:metadata:)","url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent\/init(text:payload:actions:metadata:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/init(text:payload:actions:metadata:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"payload","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"actions"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:25ZendeskSDKConversationKit18MessageActionModelO","kind":"typeIdentifier","text":"MessageActionModel"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":"]?)","kind":"text"}],"role":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKTextMessageContent/metadata":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/metadata","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"metadata","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"metadata"}],"title":"metadata","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdktextmessagecontent\/metadata","abstract":[{"text":"The metadata of the ","type":"text"},{"code":"Message","type":"codeVoice"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKTextMessageContent/description":{"title":"description","url":"\/documentation\/zendesksdkconversationkit\/zdktextmessagecontent\/description","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/init(from:)","url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent\/init(from:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKTextMessageContent/hash":{"url":"\/documentation\/zendesksdkconversationkit\/zdktextmessagecontent\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/hash","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKTextMessageContent/messageActions":{"title":"messageActions","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/messageActions","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/zdktextmessagecontent\/messageactions","navigatorTitle":[{"kind":"identifier","text":"messageActions"}],"abstract":[{"text":"Any actions associated with the message","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageActions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKMessageAction","kind":"typeIdentifier","text":"MessageAction"},{"text":"]?","kind":"text"}]},"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent":{"title":"TextMessageContent","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Text related "},{"type":"codeVoice","code":"MessageContent"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextMessageContent"}],"navigatorTitle":[{"kind":"identifier","text":"TextMessageContent"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent"},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Content":{"role":"symbol","title":"Content","navigatorTitle":[{"kind":"identifier","text":"Content"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content","abstract":[],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/content","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"Content","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.ConversationKit/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/com.zendesk.ConversationKit\/Se","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/TextMessageContent/isEqual(_:)":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","title":"isEqual(_:)","abstract":[{"text":"Returns a Boolean value that indicates whether the receiver and a given object are equal.","type":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/textmessagecontent\/isequal(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKTextMessageContent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKTextMessageContent"}]},{"op":"replace","value":[{"kind":"identifier","text":"ZDKTextMessageContent"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/description","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/hash","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/messageActions","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/metadata","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/payload","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/text","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKTextMessageContent\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/TextMessageContent\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Content"],"type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ZDKTextMessageContent","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"type","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1type\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1type\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"value":"text","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1text\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1text\/fragments","op":"replace","value":[{"text":"text","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1payload\/title","op":"replace","value":"payload"},{"value":[{"text":"payload","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1payload\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1metadata\/title","value":"metadata"},{"value":[{"kind":"identifier","text":"metadata"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1metadata\/fragments","op":"replace"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1description\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]},{"value":"messageActions","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1messageActions\/title"},{"value":[{"kind":"identifier","text":"messageActions"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKTextMessageContent~1messageActions\/fragments","op":"replace"},{"value":"ZDKTextMessageContent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/title"},{"value":[{"kind":"identifier","text":"ZDKTextMessageContent"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Content\/title","value":"ZDKMessageContent"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Content\/fragments","op":"replace","value":[{"text":"ZDKMessageContent","kind":"identifier"}]},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent~1isEqual(_:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1TextMessageContent~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"}]}]}