{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sent"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Message"},{"type":"text","text":" has been sent to the server successfully."}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/sent","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKMessageStatusSent"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sent"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageStatus@ZDKMessageStatusSent","title":"MessageStatus.sent","modules":[{"name":"ZendeskSDKConversationKit"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/messagestatus\/sent"]},{"paths":["\/documentation\/zendesksdkconversationkit\/messagestatus\/sent"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus/sent":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sent"}],"url":"\/documentation\/zendesksdkconversationkit\/messagestatus\/sent","role":"symbol","type":"topic","title":"MessageStatus.sent","abstract":[{"type":"text","text":"The "},{"code":"Message","type":"codeVoice"},{"text":" has been sent to the server successfully.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus\/sent","navigatorTitle":[{"text":"ZDKMessageStatusSent","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageStatus":{"title":"MessageStatus","navigatorTitle":[{"text":"MessageStatus","kind":"identifier"}],"abstract":[{"text":"Represents the status of the ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageStatus","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/messagestatus","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageStatus","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ZDKMessageStatusSent","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKMessageStatusSent","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKMessageStatusSent"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1sent\/title","value":"ZDKMessageStatusSent"},{"value":[{"text":"ZDKMessageStatusSent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus~1sent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus\/title","value":"ZDKMessageStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageStatus\/fragments","value":[{"kind":"identifier","text":"ZDKMessageStatus"}]}]}]}