{"sections":[],"metadata":{"roleHeading":"Case","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationStatus@ZDKConversationStatusActive","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"case","title":"ConversationStatus.active","navigatorTitle":[{"text":"ZDKConversationStatusActive","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationstatus\/active"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationstatus\/active"]}],"abstract":[{"text":"The ","type":"text"},{"code":"Conversation","type":"codeVoice"},{"text":" is active","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus\/active","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","role":"collection","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationStatus"}],"kind":"symbol","navigatorTitle":[{"text":"ConversationStatus","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationstatus","title":"ConversationStatus","type":"topic","abstract":[{"type":"text","text":"Represents the status of the "},{"code":"Conversation","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationStatus/active":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"active","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKConversationStatusActive","kind":"identifier"}],"type":"topic","title":"ConversationStatus.active","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Conversation"},{"text":" is active","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationStatus\/active","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationstatus\/active","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKConversationStatusActive","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKConversationStatusActive"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKConversationStatusActive"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"ZDKConversationStatus","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus\/fragments","value":[{"text":"ZDKConversationStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus~1active\/title","value":"ZDKConversationStatusActive"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationStatus~1active\/fragments","value":[{"kind":"identifier","text":"ZDKConversationStatusActive"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}