{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectedRealtime"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/connectionstatus\/connectedrealtime"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/connectionstatus\/connectedrealtime"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus"]]},"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConnectionStatus@ZDKConnectionStatusConnectedRealtime","title":"ConnectionStatus.connectedRealtime","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"connectedRealtime","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"ZDKConnectionStatusConnectedRealtime","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus\/connectedRealtime","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The client is connected to the network and has a realtime connection with the server."}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","kind":"symbol","role":"collection","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConnectionStatus/connectedRealtime":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusConnectedRealtime"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus\/connectedRealtime","title":"ConnectionStatus.connectedRealtime","type":"topic","abstract":[{"type":"text","text":"The client is connected to the network and has a realtime connection with the server."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connectedRealtime","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/connectionstatus\/connectedrealtime"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConnectionStatus":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus","abstract":[{"type":"text","text":"Represents the current connection state of the client."}],"title":"ConnectionStatus","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionStatus"}],"navigatorTitle":[{"text":"ConnectionStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/connectionstatus"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKConnectionStatusConnectedRealtime","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKConnectionStatusConnectedRealtime","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKConnectionStatusConnectedRealtime","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"ZDKConnectionStatusConnectedRealtime","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus~1connectedRealtime\/title"},{"value":[{"text":"ZDKConnectionStatusConnectedRealtime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus~1connectedRealtime\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus\/title","value":"ZDKConnectionStatus"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus\/fragments","value":[{"text":"ZDKConnectionStatus","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}