{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ShareAction\/init(id:metadata:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ShareAction"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":"]?)"}],"roleHeading":"Initializer","role":"symbol","externalID":"s:25ZendeskSDKConversationKit11ShareActionC2id8metadataACSS_SDySSs11AnyHashableVGSgtcfc","symbolKind":"init","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"init(id:metadata:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":"]? = nil)","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/shareaction\/init(id:metadata:)"]}],"kind":"symbol","sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ShareAction/init(id:metadata:)":{"url":"\/documentation\/zendesksdkconversationkit\/shareaction\/init(id:metadata:)","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ShareAction\/init(id:metadata:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","title":"init(id:metadata:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":"]?)","kind":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ShareAction":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ShareAction","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ShareAction","kind":"identifier"}],"navigatorTitle":[{"text":"ShareAction","kind":"identifier"}],"title":"ShareAction","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/shareaction"}},"variantOverrides":[{"patch":[{"value":"ZDKShareAction","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ShareAction\/title"},{"value":[{"kind":"identifier","text":"ZDKShareAction"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ShareAction\/fragments"},{"value":[{"kind":"identifier","text":"ZDKShareAction"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ShareAction\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}