{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/connectionstatus\/connected"]},{"paths":["\/documentation\/zendesksdkconversationkit\/connectionstatus\/connected"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connected","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus\/connected","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The client is currently connected to the network.","type":"text"}],"metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConnectionStatus@ZDKConnectionStatusConnected","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Case","title":"ConnectionStatus.connected","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connected","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusConnected"}]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConnectionStatus":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ConnectionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"ConnectionStatus","kind":"identifier"}],"abstract":[{"text":"Represents the current connection state of the client.","type":"text"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/connectionstatus","title":"ConnectionStatus"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConnectionStatus/connected":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConnectionStatus\/connected","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusConnected"}],"url":"\/documentation\/zendesksdkconversationkit\/connectionstatus\/connected","abstract":[{"text":"The client is currently connected to the network.","type":"text"}],"type":"topic","title":"ConnectionStatus.connected"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKConnectionStatusConnected"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ZDKConnectionStatusConnected","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKConnectionStatusConnected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus\/title","value":"ZDKConnectionStatus","op":"replace"},{"value":[{"text":"ZDKConnectionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus\/fragments"},{"value":"ZDKConnectionStatusConnected","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus~1connected\/title"},{"value":[{"kind":"identifier","text":"ZDKConnectionStatusConnected"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConnectionStatus~1connected\/fragments","op":"replace"}]}]}