{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personal","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/personal","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType"]]},"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"Conversation"},{"text":" between the ","type":"text"},{"code":"User","type":"codeVoice"},{"text":" and the service provider.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationtype\/personal"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationtype\/personal"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"personal"}],"roleHeading":"Case","externalID":"c:@M@ZendeskSDKConversationKit@E@ZDKConversationType@ZDKConversationTypePersonal","role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"ConversationType.personal","symbolKind":"case","navigatorTitle":[{"text":"ZDKConversationTypePersonal","kind":"identifier"}]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationType","kind":"identifier"}],"title":"ConversationType","navigatorTitle":[{"text":"ConversationType","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationtype","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType","abstract":[{"type":"text","text":"Represents the possible types of a "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":"."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationType/personal":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"personal","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationtype\/personal","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"Conversation"},{"type":"text","text":" between the "},{"type":"codeVoice","code":"User"},{"text":" and the service provider.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationType\/personal","title":"ConversationType.personal","type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKConversationTypePersonal","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKConversationTypePersonal"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKConversationTypePersonal","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKConversationTypePersonal"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType\/title","value":"ZDKConversationType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType\/fragments","value":[{"text":"ZDKConversationType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType~1personal\/title","value":"ZDKConversationTypePersonal","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationType~1personal\/fragments","value":[{"kind":"identifier","text":"ZDKConversationTypePersonal"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}