{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"activity","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Activity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"activity","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"Activity","kind":"typeIdentifier"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivityEvent(py)activity","title":"activity","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"activity"}]},"abstract":[{"type":"text","text":"The received\/updated "},{"type":"codeVoice","code":"Activity"},{"text":".","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent"]]},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/zdkactivityevent\/activity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkactivityevent\/activity"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent\/activity","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity":{"title":"Activity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/activity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Activity","kind":"identifier"}],"navigatorTitle":[{"text":"Activity","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKActivityEvent":{"title":"ZDKActivityEvent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKActivityEvent","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent","url":"\/documentation\/zendesksdkconversationkit\/zdkactivityevent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKActivityEvent"}],"abstract":[{"type":"text","text":"Wrapper object for Obj-C to return the associated types of the "},{"code":"newActivity","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"activityReceived","type":"codeVoice"},{"text":" events.","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKActivityEvent/activity":{"title":"activity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKActivityEvent\/activity","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"Activity","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"activity","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkactivityevent\/activity","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"The received\/updated ","type":"text"},{"type":"codeVoice","code":"Activity"},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"activity","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"activity"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ZDKActivity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"activity"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/title","value":"ZDKActivity","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/fragments","value":[{"text":"ZDKActivity","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent\/title","value":"ZDKActivityEvent"},{"value":[{"text":"ZDKActivityEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent\/fragments"},{"op":"replace","value":"activity","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent~1activity\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKActivityEvent~1activity\/fragments","value":[{"kind":"identifier","text":"activity"}]}]}]}