{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"A ","type":"text"},{"code":"ProactiveMessage","type":"codeVoice"},{"text":" event has occurred.","type":"text"}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitevent\/proactivemessagestatuschanged(status:proactivemessage:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"proactiveMessageStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","text":"ProactiveMessageStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"proactiveMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","text":"ProactiveMessage","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitEvent\/proactiveMessageStatusChanged(status:proactiveMessage:)"},"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"s:25ZendeskSDKConversationKit012ConversationC5EventO29proactiveMessageStatusChangedyAcA09ProactivegH0O_AA0jG0CtcACmF","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"proactiveMessageStatusChanged"},{"kind":"text","text":"("},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","text":"ProactiveMessageStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"proactiveMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ProactiveMessage","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage"},{"kind":"text","text":")"}],"roleHeading":"Case","title":"ConversationKitEvent.proactiveMessageStatusChanged(status:proactiveMessage:)","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitEvent"]]},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","title":"ZendeskSDKConversationKit","kind":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessageStatus":{"url":"\/documentation\/zendesksdkconversationkit\/proactivemessagestatus","title":"ProactiveMessageStatus","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessageStatus","role":"symbol","abstract":[{"text":"Status that compliments a ","type":"text"},{"code":"ProactiveMessageStatusChanged","type":"codeVoice"},{"text":" event in ","type":"text"},{"type":"codeVoice","code":"ConversationKitEvent"}],"navigatorTitle":[{"text":"ProactiveMessageStatus","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ProactiveMessageStatus","kind":"identifier"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitEvent":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationKitEvent"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitEvent","kind":"symbol","abstract":[{"type":"text","text":"List of events that covers all events that could come from "},{"type":"codeVoice","code":"ConversationKit"}],"title":"ConversationKitEvent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitEvent","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/conversationkitevent"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitEvent/proactiveMessageStatusChanged(status:proactiveMessage:)":{"url":"\/documentation\/zendesksdkconversationkit\/conversationkitevent\/proactivemessagestatuschanged(status:proactivemessage:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"proactiveMessageStatusChanged"},{"kind":"text","text":"("},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKProactiveMessageStatus","kind":"typeIdentifier","text":"ProactiveMessageStatus"},{"kind":"text","text":", "},{"text":"proactiveMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKProactiveMessage","text":"ProactiveMessage"},{"kind":"text","text":")"}],"role":"symbol","title":"ConversationKitEvent.proactiveMessageStatusChanged(status:proactiveMessage:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A "},{"code":"ProactiveMessage","type":"codeVoice"},{"type":"text","text":" event has occurred."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitEvent\/proactiveMessageStatusChanged(status:proactiveMessage:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ProactiveMessage":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ProactiveMessage","kind":"identifier"}],"navigatorTitle":[{"text":"ProactiveMessage","kind":"identifier"}],"title":"ProactiveMessage","type":"topic","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/proactivemessage","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ProactiveMessage"}},"variantOverrides":[{"patch":[{"value":"ZDKProactiveMessageStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessageStatus\/fragments","value":[{"kind":"identifier","text":"ZDKProactiveMessageStatus"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/title","value":"ZDKProactiveMessage","op":"replace"},{"value":[{"text":"ZDKProactiveMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ProactiveMessage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}