{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"author","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Author","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Author","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthor"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/message\/author"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/message\/author"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKMessage(py)author","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"author"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthor","text":"Author"}],"title":"author","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"author"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property","role":"symbol"},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/author","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"type":"text","text":" who authored the "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message":{"navigatorTitle":[{"kind":"identifier","text":"Message"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/message","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Message"}],"title":"Message","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message","role":"symbol","abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Author":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Author","kind":"identifier"}],"navigatorTitle":[{"text":"Author","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Author","type":"topic","abstract":[],"url":"\/documentation\/zendesksdkconversationkit\/author","role":"symbol","title":"Author"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Message/author":{"url":"\/documentation\/zendesksdkconversationkit\/message\/author","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"author","kind":"identifier"}],"type":"topic","title":"author","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"author","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Author","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthor","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"User"},{"type":"text","text":" who authored the "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Message\/author"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"author","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"author","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKAuthor","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Author","text":"ZDKAuthor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"author"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKMessage","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKMessage"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKMessage"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message\/navigatorTitle"},{"op":"replace","value":"ZDKAuthor","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Author\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAuthor"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Author\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAuthor"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Author\/navigatorTitle"},{"op":"replace","value":"author","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1author\/title"},{"op":"replace","value":[{"text":"author","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Message~1author\/fragments"}]}]}