{"abstract":[{"text":"Call to delete proactive messages data from storage","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-7k823","interfaceLanguage":"swift"},"defaultImplementationsSections":[{"title":"ConversationKitShared Implementations","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-63emt"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearProactiveMessages","kind":"identifier"},{"text":"(","kind":"text"},{"text":"proactiveMessageIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ids of the proactive message concerned"}]}],"name":"proactiveMessageIds"}],"kind":"parameters"}],"sections":[],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"clearProactiveMessagesWithProactiveMessageIds:","kind":"identifier"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)clearProactiveMessagesWithProactiveMessageIds:","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearProactiveMessages"},{"kind":"text","text":"("},{"text":"proactiveMessageIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"title":"clearProactiveMessages(proactiveMessageIds:)","required":true,"modules":[{"name":"ZendeskSDKConversationKit"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)-7k823"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)-7k823"]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"kind":"symbol","navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitShared"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","role":"symbol","type":"topic","abstract":[],"title":"ConversationKitShared"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearProactiveMessages(proactiveMessageIds:)-63emt":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"clearProactiveMessages","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"proactiveMessageIds"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"title":"clearProactiveMessages(proactiveMessageIds:)","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)-63emt","role":"symbol","abstract":[{"text":"Call to delete proactive messages data from storage","type":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-63emt"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearProactiveMessages(proactiveMessageIds:)-7k823":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearProactiveMessages"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"proactiveMessageIds"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"type":"topic","abstract":[{"type":"text","text":"Call to delete proactive messages data from storage"}],"defaultImplementations":1,"required":true,"navigatorTitle":[{"text":"clearProactiveMessagesWithProactiveMessageIds:","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)-7k823","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-7k823","kind":"symbol","title":"clearProactiveMessages(proactiveMessageIds:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"clearProactiveMessagesWithProactiveMessageIds:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"clearProactiveMessagesWithProactiveMessageIds:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"clearProactiveMessagesWithProactiveMessageIds:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"proactiveMessageIds","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"ConversationKitShared","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","value":[{"text":"ConversationKitShared","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearProactiveMessages(proactiveMessageIds:)-7k823\/title","value":"clearProactiveMessagesWithProactiveMessageIds:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"clearProactiveMessagesWithProactiveMessageIds:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearProactiveMessages(proactiveMessageIds:)-7k823\/fragments"}]}]}