{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/removeEventObserver(_:)"},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/removeeventobserver(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/removeeventobserver(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeEventObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"observer"},{"kind":"text","text":": "},{"text":"AnyObject","kind":"typeIdentifier","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"observer","content":[{"inlineContent":[{"type":"text","text":"Object to remove from observing events."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"If the passed observer is not currently observing, nothing will happen.","type":"text"}]}],"name":"Note","type":"aside"}]}],"kind":"symbol","abstract":[{"text":"Remove a type of ","type":"text"},{"code":"AnyObject","type":"codeVoice"},{"text":" from listening to ","type":"text"},{"type":"codeVoice","code":"ConversationKitEvent"},{"text":" updates.","type":"text"}],"metadata":{"modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeEventObserver","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s9AnyObjecta","text":"AnyObject"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"removeEventObserver:","kind":"identifier"}],"roleHeading":"Instance Method","title":"removeEventObserver(_:)","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ConversationKitShared(im)removeEventObserver:"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"kind":"symbol","navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitShared"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","role":"symbol","type":"topic","abstract":[],"title":"ConversationKitShared"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/removeEventObserver(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeEventObserver"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s9AnyObjecta","text":"AnyObject","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Remove a type of ","type":"text"},{"code":"AnyObject","type":"codeVoice"},{"type":"text","text":" from listening to "},{"code":"ConversationKitEvent","type":"codeVoice"},{"text":" updates.","type":"text"}],"required":true,"navigatorTitle":[{"text":"removeEventObserver:","kind":"identifier"}],"title":"removeEventObserver(_:)","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/removeeventobserver(_:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/removeEventObserver(_:)"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","type":"topic","role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"removeEventObserver:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeEventObserver:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"removeEventObserver:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"observer","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","op":"replace","value":"ConversationKitShared"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments","op":"replace","value":[{"text":"ConversationKitShared","kind":"identifier"}]},{"value":"removeEventObserver:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1removeEventObserver(_:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1removeEventObserver(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeEventObserver:"}],"op":"replace"}]}]}