{"kind":"symbol","metadata":{"roleHeading":"Class","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKLoginResult","modules":[{"name":"ZendeskSDKConversationKit"}],"symbolKind":"class","title":"ZDKLoginResult","navigatorTitle":[{"kind":"identifier","text":"ZDKLoginResult"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKLoginResult"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKLoginResult","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkloginresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkloginresult"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult\/error","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult\/user"],"title":"Instance Properties"}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"type":"conformsTo","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","role":"collection","kind":"symbol"},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.ConversationKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKLoginResult":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult","kind":"symbol","navigatorTitle":[{"text":"ZDKLoginResult","kind":"identifier"}],"title":"ZDKLoginResult","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKLoginResult","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkloginresult","role":"symbol"},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKLoginResult/error":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult\/error","kind":"symbol","navigatorTitle":[{"text":"error","kind":"identifier"}],"title":"error","abstract":[{"text":"The error that occurred if there was a problem authenticating the ","type":"text"},{"type":"codeVoice","code":"User"},{"type":"text","text":"."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkloginresult\/error","role":"symbol"},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKLoginResult/user":{"url":"\/documentation\/zendesksdkconversationkit\/zdkloginresult\/user","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult\/user","navigatorTitle":[{"text":"user","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"user","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser","text":"User"},{"text":"?","kind":"text"}],"title":"user","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"User"},{"text":" object if authentication was successful.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.zendesk.ConversationKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"ZDKLoginResult","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKLoginResult"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKLoginResult","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult\/error","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKLoginResult\/user"],"title":"Instance Properties"}]},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKLoginResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult\/title","op":"replace","value":"ZDKLoginResult"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult\/fragments","value":[{"kind":"identifier","text":"ZDKLoginResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult~1error\/title","value":"error"},{"value":[{"text":"error","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult~1error\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult~1user\/title","value":"user","op":"replace"},{"value":[{"text":"user","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKLoginResult~1user\/fragments"}]}]}