{"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKUser\/givenName","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"givenName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"givenName","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ZendeskSDKConversationKit"}],"title":"givenName","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKUser(py)givenName"},"abstract":[{"type":"text","text":"The "},{"code":"givenName","type":"codeVoice"},{"text":" of the ","type":"text"},{"code":"User","type":"codeVoice"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkuser\/givenname"]},{"paths":["\/documentation\/zendesksdkconversationkit\/zdkuser\/givenname"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/User":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/User","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"User","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/user","title":"User","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"User","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKUser/givenName":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/zendesksdkconversationkit\/zdkuser\/givenname","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"givenName","kind":"identifier"}],"type":"topic","title":"givenName","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKUser\/givenName","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"givenName"},{"type":"text","text":" of the "},{"code":"User","type":"codeVoice"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"url":"\/documentation\/zendesksdkconversationkit","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","abstract":[],"title":"ZendeskSDKConversationKit","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"givenName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"givenName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"givenName"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/title","value":"ZDKUser"},{"value":[{"text":"ZDKUser","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1User\/fragments","op":"replace"},{"value":"givenName","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKUser~1givenName\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKUser~1givenName\/fragments","value":[{"kind":"identifier","text":"givenName"}]}]}]}