{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The type of the ","type":"text"},{"code":"Message","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent\/type","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","text":"MessageType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/carouselmessagecontent\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/carouselmessagecontent\/type"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent"]]},"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKCarouselMessageContent(py)type","navigatorTitle":[{"text":"type","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageType","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType"}],"modules":[{"name":"ZendeskSDKConversationKit"}],"title":"type","roleHeading":"Instance Property"},"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/CarouselMessageContent/type":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","text":"MessageType"}],"url":"\/documentation\/zendesksdkconversationkit\/carouselmessagecontent\/type","abstract":[{"type":"text","text":"The type of the "},{"type":"codeVoice","code":"Message"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent\/type","title":"type","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/CarouselMessageContent":{"title":"CarouselMessageContent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CarouselMessageContent"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/CarouselMessageContent","url":"\/documentation\/zendesksdkconversationkit\/carouselmessagecontent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CarouselMessageContent"}],"abstract":[]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/MessageType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageType"}],"role":"symbol","navigatorTitle":[{"text":"MessageType","kind":"identifier"}],"abstract":[{"text":"Represents the different ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":" types in a "},{"code":"Conversation","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType","url":"\/documentation\/zendesksdkconversationkit\/messagetype","title":"MessageType","kind":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","role":"collection","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"type","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKMessageType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@E@ZDKMessageType","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/MessageType"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1CarouselMessageContent~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1CarouselMessageContent~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1CarouselMessageContent\/title","value":"ZDKCarouselMessageContent"},{"value":[{"kind":"identifier","text":"ZDKCarouselMessageContent"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1CarouselMessageContent\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/title","op":"replace","value":"ZDKMessageType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1MessageType\/fragments","value":[{"kind":"identifier","text":"ZDKMessageType"}]}]}]}