{"relationshipsSections":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder"],"type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"ConversationKitBuilderObjC","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKitBuilder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationKitBuilderObjC","kind":"identifier"}],"title":"ConversationKitBuilderObjC","role":"symbol","roleHeading":"Protocol"},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Type conforming to "},{"type":"codeVoice","code":"ConversationKitBuilderObjC"},{"text":" provide methods which vend concrete types of ","type":"text"},{"type":"codeVoice","code":"ConversationKitObjC"}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC\/build()"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitbuilderobjc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitbuilderobjc"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKConversationKitBuilder) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationKitBuilderObjC"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitBuilderObjC/build()":{"title":"build()","abstract":[{"text":"Returns an initialized type conforming to the ","type":"text"},{"code":"ConversationKitObjC","type":"codeVoice"},{"type":"text","text":" protocol"}],"navigatorTitle":[{"text":"build","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitbuilderobjc\/build()","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC\/build()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"text":"() -> ","kind":"text"},{"text":"ConversationKitObjC","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(pl)ZDKConversationKit"}],"type":"topic","required":true,"kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/DefaultConversationKitBuilder":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DefaultConversationKitBuilder","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/defaultconversationkitbuilder","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultConversationKitBuilder"}],"title":"DefaultConversationKitBuilder","role":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitBuilderObjC":{"title":"ConversationKitBuilderObjC","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationKitBuilderObjC","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC","url":"\/documentation\/zendesksdkconversationkit\/conversationkitbuilderobjc","type":"topic","navigatorTitle":[{"text":"ConversationKitBuilderObjC","kind":"identifier"}],"abstract":[{"type":"text","text":"Type conforming to "},{"type":"codeVoice","code":"ConversationKitBuilderObjC"},{"text":" provide methods which vend concrete types of ","type":"text"},{"code":"ConversationKitObjC","type":"codeVoice"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","role":"collection","url":"\/documentation\/zendesksdkconversationkit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"ZDKConversationKitBuilder","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"ZDKConversationKitBuilder","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKConversationKitBuilder","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitBuilderObjC\/build()"],"title":"Instance Methods"}],"op":"replace"},{"op":"replace","value":[{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/DefaultConversationKitBuilder"],"type":"conformingTypes"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKConversationKitBuilder"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"build","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC~1build()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC~1build()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"build","kind":"identifier"}]},{"value":"ZDKDefaultConversationKitBuilder","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1DefaultConversationKitBuilder\/fragments","value":[{"text":"ZDKDefaultConversationKitBuilder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC\/title","value":"ZDKConversationKitBuilder","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitBuilderObjC\/fragments","value":[{"kind":"identifier","text":"ZDKConversationKitBuilder"}]}]}]}