{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/isInitialRouting","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/lowestQueuePosition","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/lowestQueuePositionNumber","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/queuePosition","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/queuePositionNumber","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/responseTime"],"title":"Instance Properties"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ConversationKit\/SQ","doc:\/\/com.zendesk.ConversationKit\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKWaitTimeData) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"WaitTimeData","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/waittimedata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/waittimedata"]}],"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WaitTimeData","kind":"identifier"}],"navigatorTitle":[{"text":"WaitTimeData","kind":"identifier"}],"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKWaitTimeData","title":"WaitTimeData","symbolKind":"class"},"references":{"doc://com.zendesk.ConversationKit/SQ":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","abstract":[],"title":"ZendeskSDKConversationKit","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","role":"collection","url":"\/documentation\/zendesksdkconversationkit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData/lowestQueuePositionNumber":{"abstract":[{"type":"text","text":"The lowest queue position the end user has reached since entering the queue. Used when “Only Decreasing Queue Position” setting is enabled."}],"title":"lowestQueuePositionNumber","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/lowestQueuePositionNumber","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"lowestQueuePositionNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/zendesksdkconversationkit\/waittimedata\/lowestqueuepositionnumber","navigatorTitle":[{"text":"lowestQueuePositionNumber","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WaitTimeData","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WaitTimeData"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData","url":"\/documentation\/zendesksdkconversationkit\/waittimedata","title":"WaitTimeData","kind":"symbol","type":"topic"},"doc://com.zendesk.ConversationKit/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData/isInitialRouting":{"title":"isInitialRouting","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInitialRouting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/isInitialRouting","url":"\/documentation\/zendesksdkconversationkit\/waittimedata\/isinitialrouting","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isInitialRouting"}],"abstract":[{"text":"Indicates whether this is the first time the ticket has been routed.","type":"text"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData/responseTime":{"title":"responseTime","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"responseTime","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKResponseTime","text":"ResponseTime"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/responseTime","url":"\/documentation\/zendesksdkconversationkit\/waittimedata\/responsetime","type":"topic","navigatorTitle":[{"text":"responseTime","kind":"identifier"}],"abstract":[{"type":"text","text":"Optional estimated response time range for when an agent might be assigned."}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData/queuePositionNumber":{"abstract":[{"type":"text","text":"The current position of the end user in the queue."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/queuePositionNumber","title":"queuePositionNumber","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queuePositionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"}],"url":"\/documentation\/zendesksdkconversationkit\/waittimedata\/queuepositionnumber","navigatorTitle":[{"kind":"identifier","text":"queuePositionNumber"}],"kind":"symbol"},"doc://com.zendesk.ConversationKit/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.ConversationKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.ConversationKit/SH":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData/lowestQueuePosition":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/lowestQueuePosition","role":"symbol","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/waittimedata\/lowestqueueposition","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lowestQueuePosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[],"title":"lowestQueuePosition","type":"topic"},"doc://com.zendesk.ConversationKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/WaitTimeData/queuePosition":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"queuePosition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/queuePosition","title":"queuePosition","url":"\/documentation\/zendesksdkconversationkit\/waittimedata\/queueposition","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKWaitTimeData"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKWaitTimeData"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKWaitTimeData","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/isInitialRouting","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/lowestQueuePositionNumber","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/queuePositionNumber","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/WaitTimeData\/responseTime"]}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ConversationKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKWaitTimeData","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData~1lowestQueuePositionNumber\/title","value":"lowestQueuePositionNumber","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"lowestQueuePositionNumber"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData~1lowestQueuePositionNumber\/fragments"},{"value":"ZDKWaitTimeData","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/title","op":"replace"},{"value":[{"text":"ZDKWaitTimeData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData~1isInitialRouting\/title","op":"replace","value":"isInitialRouting"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData~1isInitialRouting\/fragments","op":"replace","value":[{"text":"isInitialRouting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData~1responseTime\/title","value":"responseTime","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData~1responseTime\/fragments","value":[{"kind":"identifier","text":"responseTime"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData~1queuePositionNumber\/title","value":"queuePositionNumber","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1WaitTimeData~1queuePositionNumber\/fragments","value":[{"text":"queuePositionNumber","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}