{"metadata":{"title":"activity","externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKConversation(py)activity","role":"symbol","symbolKind":"property","modules":[{"name":"ZendeskSDKConversationKit"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"Activity","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"activity","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/activity"},"abstract":[{"text":"A most recent ","type":"text"},{"code":"Activity","type":"codeVoice"},{"text":" for the ","type":"text"},{"code":"Conversation","type":"codeVoice"}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"activity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","text":"Activity","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity"},{"kind":"text","text":"?"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/activity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkconversationkit\/conversation\/activity"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation/activity":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation\/activity","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Activity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"activity","kind":"identifier"}],"title":"activity","abstract":[{"text":"A most recent ","type":"text"},{"code":"Activity","type":"codeVoice"},{"text":" for the ","type":"text"},{"code":"Conversation","type":"codeVoice"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversation\/activity"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","title":"ZendeskSDKConversationKit","abstract":[],"role":"collection","url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Conversation":{"title":"Conversation","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversation"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Activity":{"role":"symbol","navigatorTitle":[{"text":"Activity","kind":"identifier"}],"kind":"symbol","title":"Activity","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Activity","kind":"identifier"}],"type":"topic","url":"\/documentation\/zendesksdkconversationkit\/activity"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"activity","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"activity"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKActivity","text":"ZDKActivity","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Activity"},{"text":" * ","kind":"text"},{"text":"activity","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"activity","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1activity\/title"},{"op":"replace","value":[{"kind":"identifier","text":"activity"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation~1activity\/fragments"},{"op":"replace","value":"ZDKConversation","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/title"},{"op":"replace","value":[{"text":"ZDKConversation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/fragments"},{"op":"replace","value":[{"text":"ZDKConversation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Conversation\/navigatorTitle"},{"op":"replace","value":"ZDKActivity","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/title"},{"op":"replace","value":[{"text":"ZDKActivity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/fragments"},{"op":"replace","value":[{"text":"ZDKActivity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Activity\/navigatorTitle"}]}]}