{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkselectformfield\/options"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkconversationkit\/zdkselectformfield\/options"]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Option","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKOption"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"options"}],"symbolKind":"property","title":"options","roleHeading":"Instance Property","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKSelectFormField(py)options"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField"]]},"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKSelectFormField\/options","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Array of objects representing the response for a field of type "},{"type":"codeVoice","code":"select"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"options","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Option","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKOption","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Option"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ZDKSelectFormField/options":{"role":"symbol","type":"topic","url":"\/documentation\/zendesksdkconversationkit\/zdkselectformfield\/options","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ZDKSelectFormField\/options","abstract":[{"type":"text","text":"Array of objects representing the response for a field of type "},{"type":"codeVoice","code":"select"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"options"},{"kind":"text","text":": ["},{"text":"Option","preciseIdentifier":"c:@M@ZendeskSDKConversationKit@objc(cs)ZDKOption","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"options","navigatorTitle":[{"kind":"identifier","text":"options"}]},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/SelectFormField":{"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/SelectFormField","kind":"symbol","abstract":[{"text":"Form Field that takes in generic user input","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SelectFormField"}],"url":"\/documentation\/zendesksdkconversationkit\/selectformfield","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelectFormField"}],"role":"symbol","title":"SelectFormField"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","kind":"symbol","title":"ZendeskSDKConversationKit","url":"\/documentation\/zendesksdkconversationkit","abstract":[],"role":"collection"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/Option":{"kind":"symbol","title":"Option","url":"\/documentation\/zendesksdkconversationkit\/option","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Option","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Option"}],"role":"symbol","abstract":[{"type":"codeVoice","code":"Option"},{"text":" model used for","type":"text"},{"code":"Form","type":"codeVoice"},{"text":" ","type":"text"},{"code":"Message","type":"codeVoice"},{"type":"text","text":" types, when the input "},{"type":"codeVoice","code":"type"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"select"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/Option"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"options","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"options","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<ZDKOption *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"options","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"options","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKSelectFormField~1options\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ZDKSelectFormField~1options\/fragments","op":"replace","value":[{"text":"options","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/title","value":"ZDKSelectFormField","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1SelectFormField\/fragments","value":[{"text":"ZDKSelectFormField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Option\/title","value":"ZDKOption","op":"replace"},{"value":[{"text":"ZDKOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1Option\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}