{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)-63emt"]}],"identifier":{"url":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-63emt","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearProactiveMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"proactiveMessageIds"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ids of the proactive message concerned"}]}],"name":"proactiveMessageIds"}],"kind":"parameters"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-7k823"]]},"metadata":{"role":"symbol","modules":[{"name":"ZendeskSDKConversationKit"}],"externalID":"s:25ZendeskSDKConversationKit012ConversationC0PAAE22clearProactiveMessages19proactiveMessageIdsySaySSG_tF","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearProactiveMessages"},{"kind":"text","text":"("},{"text":"proactiveMessageIds","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"extendedModule":"ZendeskSDKConversationKit","symbolKind":"method","roleHeading":"Instance Method","title":"clearProactiveMessages(proactiveMessageIds:)"},"sections":[],"abstract":[{"type":"text","text":"Call to delete proactive messages data from storage"}],"references":{"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit":{"role":"collection","title":"ZendeskSDKConversationKit","abstract":[],"url":"\/documentation\/zendesksdkconversationkit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearProactiveMessages(proactiveMessageIds:)-7k823":{"title":"clearProactiveMessages(proactiveMessageIds:)","role":"symbol","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)-7k823","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-7k823","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearProactiveMessages"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"proactiveMessageIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"Call to delete proactive messages data from storage"}],"required":true,"defaultImplementations":1,"navigatorTitle":[{"kind":"identifier","text":"clearProactiveMessagesWithProactiveMessageIds:"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared/clearProactiveMessages(proactiveMessageIds:)-63emt":{"title":"clearProactiveMessages(proactiveMessageIds:)","role":"symbol","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared\/clearProactiveMessages(proactiveMessageIds:)-63emt","url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared\/clearproactivemessages(proactivemessageids:)-63emt","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearProactiveMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"proactiveMessageIds"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"abstract":[{"text":"Call to delete proactive messages data from storage","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.ConversationKit/documentation/ZendeskSDKConversationKit/ConversationKitShared":{"type":"topic","identifier":"doc:\/\/com.zendesk.ConversationKit\/documentation\/ZendeskSDKConversationKit\/ConversationKitShared","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationKitShared","kind":"identifier"}],"url":"\/documentation\/zendesksdkconversationkit\/conversationkitshared","abstract":[],"kind":"symbol","title":"ConversationKitShared","navigatorTitle":[{"text":"ConversationKitShared","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"clearProactiveMessagesWithProactiveMessageIds:","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearProactiveMessages(proactiveMessageIds:)-7k823\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"clearProactiveMessagesWithProactiveMessageIds:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared~1clearProactiveMessages(proactiveMessageIds:)-7k823\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/title","value":"ConversationKitShared"},{"value":[{"text":"ConversationKitShared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ConversationKit~1documentation~1ZendeskSDKConversationKit~1ConversationKitShared\/fragments"}]}]}